### ISSUE TITLE
Settings display may be broken

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1003]
Settings display may be broken by some CSS resetor. 

![スクリーンショット 2020-01-08 13 28 33](https://user-images.githubusercontent.com/7702653/71950647-5d5b6d00-321b-11ea-8afd-aee9c3fe3eea.png)

Plaese add `box-sizing` to `.ce-settings`. 

```
.ce-settings {
  box-sizing: content-box;
}
```

**Comment by JustTSK** [comment]
I have the same issue, happens only when parent container have `box-sizing: border-box;` 
Which is the case for bootstrap 4 for instance.

**Comment by neSpecc** [comment]
@hata6502 Thanks for the report. You are welcome to improve this moment and open a Pull Request.
