### ISSUE TITLE
Block Tune MoveUp and MoveDown (Swap) trigger event or lifecycle hook

### ISSUE THREAD

**Issue by natterstefan** [codex-team/editor.js#1005]
## Current Situation

Currently, I am using editorjs in a [react environment](https://www.npmjs.com/package/@natterstefan/react-editor-js). That is why I came up with the two other issues and questions posted earlier.

_Problem:_ It looks like there's no event I can subscribe to when a block is moved either up or down (or swapped). This leaves me clueless when a block moved.

Maybe there's an API for that already, but I was not able to find it (neither [editorjs.io/base-concepts](https://editorjs.io/base-concepts), [master/docs](https://github.com/codex-team/editor.js/tree/master/docs) or [editorjs.io/making-a-block-settings](https://editorjs.io/making-a-block-settings)).

This is critical for me (and maybe others as well), as some parts of my react component break when the block is moved. For instance, tinymce renders it's content inside a selected `div`. When the block is moved its element (iframe) is reloaded and gone as a result.*

At this point, I do not now _when_ to re-init the 3rd party div as an example.

## Expected Solution

EditorJS allows subscribing to block tune's (eg. move ups, downs and swaps) by either providing an event or a lifecycle hook.

## References and Ideas

Currently, my time's limited to contribute. But I've checked out some parts of the code and came up with the following suggestion. Adding a new lifecycle (eg. `swapped`) could be used to do whatever is needed when a block was swapped.

```diff
  // https://github.com/codex-team/editor.js/blob/ac93017c706f091fd3014c3edb248db4e03f55dd/src/components/blocks.ts#L126-L144
  public swap(first: number, second: number): void {
	// ... existing code

+    /**
+     * trigger cycle hooks
+     */
+    this.blocks[first].call(BlockToolAPI.SWAPPED); // or ON_SWAPPED
+    this.blocks[second].call(BlockToolAPI.SWAPPED);
  }
```

### Links

- [src/components/block-tunes/block-tune-move-up.ts#L59-L106](https://github.com/codex-team/editor.js/blob/ac93017c706f091fd3014c3edb248db4e03f55dd/src/components/block-tunes/block-tune-move-up.ts#L59-L106)
- [src/components/block-tunes/block-tune-move-down.ts#L58-L98](https://github.com/codex-team/editor.js/blob/ac93017c706f091fd3014c3edb248db4e03f55dd/src/components/block-tunes/block-tune-move-down.ts#L58-L98)
- [src/components/block.ts#L31-L44](https://github.com/codex-team/editor.js/blob/ac93017c706f091fd3014c3edb248db4e03f55dd/src/components/block.ts#L31-L44)
- [src/components/blocks.ts#L126-L144](https://github.com/codex-team/editor.js/blob/ac93017c706f091fd3014c3edb248db4e03f55dd/src/components/blocks.ts#L126-L144)
- [src/components/block.ts#L418-L437](https://github.com/codex-team/editor.js/blob/ac93017c706f091fd3014c3edb248db4e03f55dd/src/components/block.ts#L418-L437)
- [src/components/dom.ts#L129-L149](https://github.com/codex-team/editor.js/blob/ac93017c706f091fd3014c3edb248db4e03f55dd/src/components/dom.ts#L129-L149)
- [editorjs.io/listeners](https://editorjs.io/listeners)

\* Context: the 3rd party tool renders its content inside an `iframe`, and according to [this post on stackoverflow](https://stackoverflow.com/a/8318401/1238150) `iframe`s update when they were moved in the dom. This was an issue mentioned in the [tinymce repo years ago](https://github.com/tinymce/tinymce/issues/1073).

**Comment by gohabereg** [comment]
Resolved by #1007
