### ISSUE TITLE
hide block background color

### ISSUE THREAD

**Issue by 61Q** [codex-team/editor.js#1006]
Hi there.
In editor.js, when click on a block, it will show a gray background.
How can we disable this background color changing?
Thanks!

**Comment by gohabereg** [comment]
Hi @61Q 
You can override css `.ce-block--focused` class

**Comment by 61Q** [comment]
> Hi @61Q
> You can override css `.ce-block--focused` class

Hi @gohabereg 
Thanks!! It works!
BTW, would you please let me know how do we track which block has changed?

**Comment by neSpecc** [comment]
In 2.17.0 focused blocks won't be highlighted. #1064

@61Q Please create a separate issue for the second question
