### ISSUE TITLE
Can't import EditorJs

### ISSUE THREAD

**Issue by gitsumcoffee** [codex-team/editor.js#1010]
I seem to have a problem when trying to use EditorJs, even in a simple web page.

After installing EditorJs with npm, I made two simple files : an HTML file and a Javascript file.

Here's my `index.html` page :
```html
<html>
<head>
</head>
<body>
    <h1>Hello World !</h1>
    <div id="editorjs"></div>
    <script src="./index.js"></script>
</body>
</html>
```

Here's my `index.js` file :
```javascript
import EditorJs from '@editorjs/editorjs';

const editor = new EditorJs({
    
});
```
I get the following error message on Firefox :
```
SyntaxError: import declarations may only appear at top level of a module
index.js:1
```

When importing the `index.js` file as a module :
```html
<script src="./index.js" type="module"></script>
```

I get the following :
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource (Reason: CORS request not http).
Module source URI is not allowed in this document
index.html:12:1
```

Any ideas ?
Thanks.

**Comment by hata6502** [comment]
I think it is not problem of EditorJS. 
I recommend to use WebPack, and so on.

**Comment by leorolland** [comment]
Remove the import statement and manually import in html
<script src="editor.js"></script>
