### ISSUE TITLE
Paste event is dispatched multiple times when multiple EditorJS are launched. 

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1011]
I'll write more detail soon. 😃

**Comment by hata6502** [comment]
When launched two EditorJS in same page: 

<img width="262" alt="スクリーンショット 2020-01-21 18 17 20" src="https://user-images.githubusercontent.com/7702653/72791237-4d5f7680-3c7a-11ea-89fd-979e5a5e5993.png">
(example-dev.html)

Paste event is dispatched multiple times when multiple EditorJS are launched: 
![スクリーンショット 2020-01-21 18 19 12](https://user-images.githubusercontent.com/7702653/72791358-8c8dc780-3c7a-11ea-985c-4fd9258739cc.png)

**Comment by gkshi** [comment]
I have the same problem. It may be related with the last update. I haven't get this bug before v2.16.1.

More details:
There are two editors on the page with unique **holder** options (every holder value matches to div with the same id value).

**Comment by DDroll** [comment]
Confirm and rolled back to previous version (npm install @editorjs/editorjs@2.15.1 --save), it solves problem)

**Comment by gkshi** [comment]
I've tried to return to v2.15.1 and It works fine, no double paste behavior on the page.
But it isn't a solution. Previous version has other critical bugs with inline toolbar and text selection.

**Comment by Teebo** [comment]
That works 😎

**Comment by ponnex** [comment]
Experienced the same hope this issue will be fixed soon 👍

**Comment by ponnex** [comment]
From what I've observed it will pasted multiple times based on how many instance of editorjs there is

**Comment by ponnex** [comment]
![Screenshot 2020-01-30 at 6 40 36 PM](https://user-images.githubusercontent.com/10062054/73442614-20a11280-4390-11ea-88c6-bec8bcc51866.png)

Does each editor has to have its own paste listener? handlePasteEvent is being called multiple times since there are multiple listeners thus the copied text is pasted multiple times

![Screenshot 2020-01-30 at 6 42 30 PM](https://user-images.githubusercontent.com/10062054/73442756-5a721900-4390-11ea-903b-9cee8814c8ce.png)

and alreadyExist seems to be null even if the listener is already added

**Comment by ponnex** [comment]
For the meantime I've published an editorjs with the assumed "fix" on the paste issue -> [@ponnex/editorjs](https://www.npmjs.com/package/@ponnex/editorjs) will delete this one when the pull request is accepted or when a fix is already available

**Comment by tasuku-s** [comment]
thanks to @ponnex, I could write this workarround.
I apply this until the PR is merged.

```typescript
class PatchedEditor extends EditorJS {
  constructor(configuration?: EditorConfig|string) {
    super(configuration);
  }

  public exportAPI(editor: any) {
    super['exportAPI'](editor);
    const Paste = editor.moduleInstances.Paste;
    const onPastes = Paste.Editor.Listeners.findAll(document, 'paste');
    Paste.Editor.Listeners.allListeners = (Paste.Editor.Listeners.allListeners as []).filter(l => !onPastes.includes(l));
    onPastes.forEach(paste => paste.element.removeEventListener(paste.eventType, paste.handler, paste.options));
    Paste.Editor.Listeners.on(Paste.Editor.UI.nodes.holder, 'paste', Paste.handlePasteEvent);
  }
}
```

**Comment by ponnex** [comment]
Hi all! 2.17 is already released with this I will be deleting [@ponnex/editorjs](https://www.npmjs.com/package/@ponnex/editorjs), those that are using the package kindly move to @editorjs/editorjs@2.17

**Comment by akash1201** [comment]
I'm still facing the issue, I'm on V2.26.5

<img width="270" alt="image" src="https://github.com/codex-team/editor.js/assets/63228493/373c3713-c281-48b0-b7d3-6af6e7407c82">

Update:- There are two instance of editor.js running in the page, hence it's being pasted twice. So I'm suspecting this maybe the issue. Any solution for the same?

**Comment by akash1201** [comment]
Hi All, 
The issue was resolved, I just changed the holder of one editor instance, that sort of did the trick.

Thanks.

**Comment by sergey-yarchuk-4ib** [comment]
> Hi All, The issue was resolved, I just changed the holder of one editor instance, that sort of did the trick.
> 
> Thanks.

Hi, can you write what exactly you did?

**Comment by akash1201** [comment]
Hi,

Earlier I was using two instance of editor.js.

```
<div id="editorjs"></div> // for title
<div id="editorjs"></div> //for body
```

It caused the above mentioned issue.

Then I changed it to
```
<div id="editorjs-title"></div> //title
<div id="editorjs"></div> //body
```

This solved the issue.

**Comment by sergey-yarchuk-4ib** [comment]
> Hi,
> 
> Earlier I was using two instance of editor.js.
> 
> ```
> <div id="editorjs"></div> // for title
> <div id="editorjs"></div> //for body
> ```
> 
> It caused the above mentioned issue.
> 
> Then I changed it to
> 
> ```
> <div id="editorjs-title"></div> //title
> <div id="editorjs"></div> //body
> ```
> 
> This solved the issue.

thx for answer.

**Comment by akash1201** [comment]
> > Hi,
> > Earlier I was using two instance of editor.js.
> > ```
> > <div id="editorjs"></div> // for title
> > <div id="editorjs"></div> //for body
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It caused the above mentioned issue.
> > Then I changed it to
> > ```
> > <div id="editorjs-title"></div> //title
> > <div id="editorjs"></div> //body
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This solved the issue.
> 
> thx for answer.

Please let me know if that solved your issue or you're facing a different issue.

**Comment by sergey-yarchuk-4ib** [comment]
> Please let me know if that solved your issue or you're facing a different issue.

Unfortunately, it didn't solve it. I think I have something different, thank you anyway.
