### ISSUE TITLE
Is there a reason that stop onClick propagation?

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1021]
Thank you for managing EditorJS :)

Probably, blocks can't listen onClick event because of ui's stopPropagation. 
Is there a reason that stop onClick propagation?

I send PR to propagate onclick event. 
But, this PR may causes other bugs. 
https://github.com/codex-team/editor.js/pull/1020

**Comment by hata6502** [comment]
I'm making my Image block. 
Image Block contains Upload Button to open file select dialog. 
But Button can't be clicked because onClick event is not propagated.

**Comment by leorolland** [comment]
You can catch mousedown event on EditorJs by using listeners api
define this once the editor instance is ready (couble be in onReady hook)
`editor.listeners.on(editorContainer, 'mousedown', (data)=>console.log(data)`

**Comment by hata6502** [comment]
https://github.com/codex-team/editor.js/pull/1020#issuecomment-597731973
