### ISSUE TITLE
Add create block button

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1023]
Currently, new block is created by pressing Enter key in the last block. 
This UI may be un-usefriendly for article editors. 

This problem is resolved by To displaying + button to create new block. 
Is this good idea?

![スクリーンショット 2020-01-29 15 19 11](https://user-images.githubusercontent.com/7702653/73332701-e14cc600-42aa-11ea-9ac6-8ed9b89266fb.png)

**Comment by christoph-kluge** [comment]
I've solved it by adding a new block and binding the click to create a new block within the editor.

```
<button data-editorjs-new-element>
New Element Text or <i class="wb-icon wb-blabla" />
</button>
```

```
class CreateNewElementBinder {
    constructor({data, api, config}) {
      document.querySelectorAll('[data-editorjs-new-element]').forEach(function (element) {
        element.addEventListener('click', function () {
          let block = 'paragraph',
            blockData = {},
            blockConfig = {},
            blockPosition = api.blocks.getBlocksCount(),
            blockFocus = true;

          api.blocks.insert(block, blockData, blockConfig, blockPosition, blockFocus);
          api.caret.setToLastBlock('start');
          api.toolbar.open();
        });
      });
    }
  }
```

**Comment by hata6502** [comment]
Thank you!
I'll make new block button in my fork repository.
