### ISSUE TITLE
Override default tools icon and tooltip text

### ISSUE THREAD

**Issue by rubenjimenez** [codex-team/editor.js#1024]
Hi,

Is there any way to modify the default icon and tooltip text when you load the tool in the editor config? Like the "placeholder" option or something like that. The main problem is the default editorjs language. Our clients need the editorjs to be in spanish and we don't want to modify each block by hand.

```
tools: {
    header: {
        class: Header,
        inlineToolbar: true,
        config: {
            placeholder: 'Write a header'
        }
    }
}
```

On the other hand, the icons used in all the available blocks, are they listed somewhere? We're developing some blocks and we'd like to keep the icons style but we don't find the public list or the palette to check if there're more to use in custom blocks.

Thanks!

**Comment by Farrien** [comment]
I think this is important and necessary ability.
Devs are russian like me but they forgot about localization to our lang.

**Comment by neSpecc** [comment]
You can override a title and icon throght the `toolbox` property
