### ISSUE TITLE
Отсутствует перевод строки

### ISSUE THREAD

**Issue by Farrien** [codex-team/editor.js#1030]
Уже давно принято, что при сочетании SHIFT+ENTER переводится строка. В разных редакторах по разному через \n или `<br>`.
В Editor.js это видимо не работает. В самом редакторе такой переход осуществляется, но при сохранении в выводе он отсутствует. В итоге получаешь текст в одной линии без переходов.

Может я что-то упустил?
Перевод строги новым параграфом не подходит - там отступы есть.

**Comment by shaburovpv** [comment]
В Google Chrome 79 перевод строки работает.
```js
{
    "blocks" : [
        {
            "type" : "paragraph",
            "data" : {
                "text" : "Hey. Meet the new Editor.<br>On this page you can see it in action — try to edit this text."
            }
        }
    ]
}
```
