### ISSUE TITLE
Is there some way to embed google slide inside this editor js?

### ISSUE THREAD

**Issue by sabit990928** [codex-team/editor.js#1033]

**Comment by hata6502** [comment]
https://github.com/editor-js/embed
https://github.com/editor-js/raw

**Comment by sabit990928** [comment]
@hata6502, sorry for the late answer, but I tried them both. Embed has a kind of solution, it's looked like just the bookmark while Google slide has embed functionality which gives you ability to show iframe in your platform

Actually I find another solution to solve this problem and it's without editor js
