### ISSUE TITLE
[Question] Is it possible to add file uploads in Text

### ISSUE THREAD

**Issue by ceesvanegmond** [codex-team/editor.js#1037]
Hi there,

I know it's possible to upload images using the image component. I noticed there is also a AttachTool component which allows us to add files to articles.

I was wondering, is there any possibility to upload PDF/Docs and add them in the header component? Add file links in text?

Could you give me advice on how to do it?

Thanks!

**Comment by gohabereg** [comment]
Hi @ceesvanegmond!

Each Editor.js plugin conceptually should implement just one functional block, so header is header and paragraph is paragraph. If you need the ability to add some files to text fragments, you can implement [InlineTool](https://editorjs.io/creating-an-inline-tool) for that. Also, we will have Block Tunes API added in the nearest future, it will allow you to attach files to blocks. However, I don't think we will implement these tools by ourselves.

As you noticed we have AttachTool, but it doesn't support second verstion of the Editor yet

**Comment by neSpecc** [comment]
Outdated
