### ISSUE TITLE
hi, how to use editor.js in nuxt.js, is there an example?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [codex-team/editor.js#1038]
How to use editor.js in nuxt.js, are there any related examples?

**Comment by neSpecc** [comment]
Related #1036

**Comment by zabavnikov** [comment]
Hi, @Yakumo-Yukari!  Try this.

```
<template>
  <div id="codex-editor"></div>
</template>

<script>
  let EditorJS = null;

  if (process.client) {
    EditorJS = require('@editorjs/editorjs')
  }

  export default {
    mounted() {
      const editor = new EditorJS({
        /**
         * Id of Element that should contain Editor instance
         */
        holderId: 'codex-editor'
      });
    }
  }
</script>
```

**Comment by Yakumo-Yukari** [comment]
> Hi @Yakumo-Yukari! Try this.
> 
> ```
> <template>
>   <div id="codex-editor"></div>
> </template>
> 
> <script>
>   let EditorJS = null;
> 
>   if (process.client) {
>     EditorJS = require('@editorjs/editorjs')
>   }
> 
>   export default {
>     mounted() {
>       const editor = new EditorJS({
>         /**
>          * Id of Element that should contain Editor instance
>          */
>         holder: 'codex-editor'
>       });
>     }
>   }
> </script>
> ```

Thanks for the example

**Comment by gbgb66** [comment]
> Hi @Yakumo-Yukari! Try this.
> 
> ```
> <template>
>   <div id="codex-editor"></div>
> </template>
> 
> <script>
>   let EditorJS = null;
> 
>   if (process.client) {
>     EditorJS = require('@editorjs/editorjs')
>   }
> 
>   export default {
>     mounted() {
>       const editor = new EditorJS({
>         /**
>          * Id of Element that should contain Editor instance
>          */
>         holder: 'codex-editor'
>       });
>     }
>   }
> </script>
> ```

it's works, but how import tools?

**Comment by Yakumo-Yukari** [comment]
> > Hi @Yakumo-Yukari! Try this.
> > ```
> > <template>
> >   <div id="codex-editor"></div>
> > </template>
> > 
> > <script>
> >   let EditorJS = null;
> > 
> >   if (process.client) {
> >     EditorJS = require('@editorjs/editorjs')
> >   }
> > 
> >   export default {
> >     mounted() {
> >       const editor = new EditorJS({
> >         /**
> >          * Id of Element that should contain Editor instance
> >          */
> >         holder: 'codex-editor'
> >       });
> >     }
> >   }
> > </script>
> > ```
> 
> it's works, but how import tools?

Thank you so much for your help.

**Comment by joffreyBerrier** [comment]
Hi, you can do better in Nuxt3 like that:

```vue
<script setup lang="ts">
  const uploadEditorJS = () => import('@editorjs/editorjs')
  let Editor = null

  onMounted(async () => {
    try {
      const editor = await uploadEditorJS()
      Editor = new editor.default({
        holder: 'editorjs',
      })
    } catch (err) {
      console.log(err)
    }
  })
</script>

<template>
  <div id="editorjs" />
</template>
```

🙏
