### ISSUE TITLE
Inline link tool not showing up

### ISSUE THREAD

**Issue by kayvanbree** [codex-team/editor.js#1042]
Hi, I'm trying to create a Strapi plugin that replaces the default editor with EditorJs. I'm using a React wrapper ("@natterstefan/react-editor-js": "^0.3.1") to add it to the admin area. The default inline tools bold and italic work out of the box but the link tool is not working:

![image](https://user-images.githubusercontent.com/11921540/74668213-05fad600-51a5-11ea-9bb7-f26925f06ee6.png)

Is there something extra I should do to enable the inline link tool? [According to the docs](https://editorjs.io/enable-inline-toolbar) link should be built-in just like bold and italic:

> Names of Tools in inlineToolbar is the keys of Inline Tools plugins that used in tools property of initial config. There are three build-in Inline Tools: link, bold, italic.

My config is as follows: 

```
        tools={{
          header: Header,
          quote: {
            class: Quote,
            inlineToolbar: true,
          },
          embed: {
            class: Embed,
            config: {
              services: {
                youtube: true
              }
            }
          },
          paragraph: {
            class: Paragraph,
            inlineToolbar: true
          },
          link: Link,
          marker: Marker,
          table: {
            class: Table,
            inlineToolbar: true,
          },
          list: {
            class: List,
            inlineToolbar: true,
          },
          delimiter: Delimiter,
          checklist: {
            class: Checklist,
            inlineToolbar: true,
          },
        }}
```

**Comment by neSpecc** [comment]
It looks like a custom `link` tool in your config conflicts with a built-in Link tool that is connected under the same key. Try to use a different name for your tool.

**Comment by neSpecc** [comment]
Related #637

**Comment by kayvanbree** [comment]
Ah indeed, I thought `link` was for https://github.com/editor-js/link and `linkTool` was for the inline linking tool! Thanks for your help!
