### ISSUE TITLE
Async loading data

### ISSUE THREAD

**Issue by artecoop** [codex-team/editor.js#1049]
Hello all!

is it possible to render data asynchronously? Either on subscription or promise?

**Comment by neSpecc** [comment]
You can use `api.blocks.render()` at any moment.

https://editorjs.io/blocks#render

**Comment by artecoop** [comment]
@neSpecc thanks for your response.
how do I get reference to api?

` const editor = new EditorJS({...}); `

I cant understand it from the docs.

**Comment by neSpecc** [comment]
You can access it from the instance as described [here](https://editorjs.io/api)

```js
const editor = EditorJS()

editor.blocks.clear()
```

**Comment by artecoop** [comment]
@neSpecc thanks a lot

with
```js
const editor = EditorJS();

const data = await fetchData();
editor.blocks.render(data);
```

all works fine. Thank you!

This code fails with:
