### ISSUE TITLE
Auto-removing rows when using table tool

### ISSUE THREAD

**Issue by bazexp** [codex-team/editor.js#1050]
Hi Codex Team,

First of all, great job on the editor it's really good.
Second, would you be so kind and rework the auto-removal of rows in the table tool ?
It is an ok feature but I think it can be better if it was configurable.
In my scenario, I need those empty rows when creating documents for users to use.

Thanks

**Comment by gohabereg** [comment]
Hi @bazexp!

This issue is related to [editor-js/table](https://github.com/editor-js/table) repository. Could you please raise one there
