### ISSUE TITLE
Other UI way to make new block

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1053]
I'll describe more detail soon! 😀

**Comment by 61Q** [comment]
Here is an abstract implementation:
1. origin blocks: [{}, {}, {}] 
2. UI interaction add a block: [{}, {}, {}, {}]
3.
```
editorInstance.render({ blocks: [{}, {}, {}, {}] });
```

**Comment by hata6502** [comment]
Currently, new empty blocks are inserted when Enter key pressed. 
This may be difficult to use. 

Example, to insert new block after Table block, user need to focus Table block and press Enter key. 

Therefore, it is useful to make Insert button in Settings menu. 

![Screenshot from 2020-03-11 01-53-55](https://user-images.githubusercontent.com/7702653/76337820-3e707880-633b-11ea-8030-b80c68649231.png)

**Comment by gohabereg** [comment]
Hi @hata6502 

With Block Tunes API (under development at the moment) this will be possible.

With the current version, you can use [`api.blocks.insert`](https://editorjs.io/blocks#insert) method to insert new block programmatically

**Comment by hata6502** [comment]
@gohabereg Thank you for your answer!
I wait for feature version with Block Tunes API.
