### ISSUE TITLE
inline toolbar order

### ISSUE THREAD

**Issue by flaming-cl** [codex-team/editor.js#1056]
Hi, if we hope to change the order of the inline tools, how can we implement it?

For example, if we want Marker to be placed before all the other tools:
![image](https://user-images.githubusercontent.com/51183663/76331514-3825d080-632a-11ea-8dd6-b2903ab75606.png)

Thanks!

**Comment by khaydarov** [comment]
reference #862

**Comment by neSpecc** [comment]
1. Add `inlineToolbar` option to the root of EditorConfig. This common option will allow removing some tools from all blocks. Or disable the Inline Toolbar for all blocks by passing `false`. Or specify a sorting of tools.

2. If there is no root `inlineToolbar` option passed, get the order of the inline tools by their order in the `tools` config option appended to the internal (link, bold, italic).

3. The `inlineToolbar` option of specific tool (got from `tools<tool>` sections) will override the root setting.

4. Inside the `show` method of the Inline Toolbar perform buttons ordering corresponding by the current (tool or root) setting.
