### ISSUE TITLE
Disabling the "I'm ready!" Log.

### ISSUE THREAD

**Issue by ALITHEALI** [codex-team/editor.js#1058]
Hi!
First of all, thanks a lot for this great project, it is an awesome editor and deserves a lot of respect but I'm using Jest to test my app and the initialization console log which says "Editor.js 2.16.1 I'm ready! (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧" shows multiple times during test. Is there anyway I can disable this log? 

I have also checked the types to see if there is a way to disable them from EditorJS class via `logLevel` but no luck because it throws typeerror at the runtime. Here are the relevant screenshots:

<img width="342" alt="Screenshot 2020-03-13 at 13 04 46" src="https://user-images.githubusercontent.com/44507581/76623456-6faf9b00-652b-11ea-886b-2424be4c9c16.png">
<img width="332" alt="Screenshot 2020-03-13 at 13 13 15" src="https://user-images.githubusercontent.com/44507581/76624020-6a9f1b80-652c-11ea-959a-4550074a2fd0.png">

Massive respect to the team behind this editor.
Many Thanks in Advance!
Ali

**Comment by neSpecc** [comment]
Hi, @ALITHEALI

Try to set: `logLevel: 'ERROR'`

**Comment by ALITHEALI** [comment]
Hi @neSpecc ! Thanks for getting back to me.
Yes! It works great and also I had to cast it as `any` which totally solves the issue and no further action is required.

Thanks a lot for your rapid response/help. I'll close the issue now. ❤️ 
Ali
