### ISSUE TITLE
Feat: expose more methods from SelectionUtils in api.selection.*

### ISSUE THREAD

**Issue by natterstefan** [codex-team/editor.js#1066]
## Current Situation

As of 2.16, guess also in 2.17, only two selection methods are exposed in the api:

```
selection: {findParentTag: ƒ, expandToTag: ƒ}
```

## Current Problem

In one of our apps, I need to extend and overwrite [inline-tool-link.ts](https://github.com/codex-team/editor.js/blob/737ba2abb423665257cf6ccc5e8472742433322f/src/components/inline-tools/inline-tool-link.ts), because our customer wants to be able to set a `target` and `title` attribute.

When I started creating my own inline-tool-link, based on your implementation, I saw it uses some really helpful functions from [selection.ts](https://github.com/codex-team/editor.js/blob/737ba2abb423665257cf6ccc5e8472742433322f/src/components/selection.ts).

_But not all of them are exposed_, so I had to copy & paste them into my app as well (so its 2 times in the bundle for instance).

## Example (snippet)

- https://gist.github.com/natterstefan/0e6c22ed7af59c221b8a80e68b5cdb22

## Suggestion

Can't we expose more methods of the utility in the block api? Especially:

- static get range()
- static get text()
- static get()
- removeFakeBackground()
- setFakeBackground()
- save()
- restore()
- clearSaved()
- collapseToEnd()

What speaks in favor, what speaks against?

I'm happy to contribute if you agree this is useful.

## Related Issues*

\* in terms of: can be useful for them

- https://github.com/codex-team/editor.js/issues/1057

**Comment by gohabereg** [comment]
Hi @natterstefan,

I think it would be really useful. Also, DOM utils from `dom.ts` might be used in plugins. 

There are some reasons we haven't done this yet:

1. We don't want any internal Editor's interfaces/types/objects to be exported.

2. Some utils should be tested on how they work outside. E.g. saved selection is managed by core now and we don't know how would it behave if plugins use it.

3. The most important point is conceptual (haha, classic). Should Editor.js API provide methods for DOM/Selection manipulations? We think it shouldn't. API (*application* programming interface) should export methods related to the application only.

So a solution I see now is to move these utils to separate NPM packages. They could be installed to core and plugins to avoid code duplicates. 

This way if you include @editorjs/* packages into your bundle, utils packages would be resolved by your bundle tool and wouldn't be duplicated. However, using CDN delivery would still duplicate (more than one time if several plugins include utils package) some code. So if there are any ways to resolve duplicates when using Editor through CDN, we can go with separate packages for utils.

**Comment by natterstefan** [comment]
Hi @neSpecc,

I hope you are doing great. Do you have any news regarding this feature?

**Comment by orlando-labs** [comment]
Hi, @neSpecc, first of all, thanks for your work!
These features clearly needs a bump! We've hit that several times.

**Comment by neSpecc** [comment]
> Hi, @neSpecc, first of all, thanks for your work! These features clearly needs a bump! We've hit that several times.

Hey. Describe your case. Which methods do you need?

**Comment by orlando-labs** [comment]
At least it is extremely useful to use methods for the saving/restoring the selection and for the fake background manipulating. I think the initial suggestion methods list is pretty fair and complete.

**Comment by neSpecc** [comment]
Resolved by #2718, released under 2.30. See a changelog: https://codex.so/editorjs-2-30 

If you need more methods, open a separate issue with detailed description of the usecase
