### ISSUE TITLE
React: User can't add new block (content) between two custom blocks

### ISSUE THREAD

**Issue by natterstefan** [codex-team/editor.js#1068]
## Current Situation

Based on the same situation and setup, described in https://github.com/codex-team/editor.js/issues/1067, I've got the following additional issue.

## Current Problem

When I add two custom react tools, there's no way for the editors to add a new paragraph (or any other block type) between these two. Editors must first create a new block below/above) and move it.

![Screen Capture on 2020-03-17 at 13-58-57](https://user-images.githubusercontent.com/1043668/76858357-8588cd00-6857-11ea-912d-d2fa1b8903ab.gif)

(see also https://d.pr/i/8c3nm4/fkYmOxtasj)

## What I've tried

Not sure if this is 100% an issue with editorjs or if I just need guidance to solve this. Nevertheless, I don't know how to resolve this.

If already tried:

- adding `contentEditable` to the rendered react containers. This helps selecting the block with the arrow keys, _but_ the editor should not be able to change the generated HTML of the react component. So this seems not to be the solution.
- when the outer container is `contentEditable={true}` and the inner one not `contentEditable={false}` the selection with the arrow keys does not work (see `// <<<<< HERE >>>>>>` comments in the example app).

## Expected Behaviour

Editor can

- select the custom blocks with the arrow keys (like any other block too)
- add new content between two custom blocks

## Example App

https://codesandbox.io/s/jolly-cherry-us2mv

---

As always, thank you very much for your help!

**Comment by alpharaoh** [comment]
How did you fix this? I am in need of this functionality urgently

**Comment by neSpecc** [comment]
1) You can click near your react component and press Enter
2) You can handle Enter internally in react component, check if caret is set at the end of text (for example using [isCaretAtEndOfInput](https://github.com/editor-js/utils/blob/main/packages/caret/src/isCaretAtEndOfInput/isCaretAtEndOfInput.ts#L18) of the [@editorjs/caret](https://github.com/editor-js/utils/tree/main/packages/caret) package), and then create a block below via API:

```ts
const newBlock = this.api.blocks.insert();

this.api.caret.setToBlock(newBlock)
```
