### ISSUE TITLE
How to edit an output JSON with EditorJS

### ISSUE THREAD

**Issue by FerJEP** [codex-team/editor.js#1070]
Do you provide a way to edit your own JSON with EditorJS?

**Comment by gohabereg** [comment]
Hi @FerJEP 
Could you please describe your use-case?

**Comment by FerJEP** [comment]
I'm using EditorJS in a custom blog to write the articles, but I was wondering How I could edit an existing article. Can I import the JSON in a new EditorJS instance to edit it?

**Comment by gohabereg** [comment]
No, you can't do it.
If you store your articles in HTML, you can use `api.blocks.renderFromHTML` method. If they are in JSON, you need to write some converter to convert them to EditorJs format.

**Comment by FerJEP** [comment]
But I have the EditJS JSON format of the articles, I render the HTML from those JSONs

**Comment by FerJEP** [comment]
Can't I pass that JSON back to EditorJS? They're the same that EditorJS gave me back then

**Comment by gohabereg** [comment]
Sure, you can pass it to `data` property of editor insurance config

**Comment by FerJEP** [comment]
Thanks!

**Comment by smostafad** [comment]
Hello , I want to change the json file dynamically, that is, the user fills in the information on the site and downloads the new json file. Can you help me?
