### ISSUE TITLE
Converting to .docx

### ISSUE THREAD

**Issue by eeriksp** [codex-team/editor.js#1076]
In my application the user can upload .docx files. I wonder if it would be possible to use editor.js to edit these documents online. Is it possible to convert a .docx file to something that editor.js can use and vice versa?

**Comment by gohabereg** [comment]
Hi @eeriksp,

It is possible. `.docx` uses `text/rtf` format to store data. You can parse it on your backend and then convert it to the Editor.js JSON format and vice-versa.

We don't provide such tools at the moment, so you need to implement it yourself

**Comment by neSpecc** [comment]
Answered
