### ISSUE TITLE
copy paste from word document convert text into image

### ISSUE THREAD

**Issue by harshalone** [codex-team/editor.js#1083]
Hi when i copy paste my content from a word document it converts it into image. Any solution for it

**Comment by stasyuk93** [comment]
I have this problem with Mac-Chrome

**Comment by gohabereg** [comment]
Hi there
AFAIK image is pasted if clipboard buffer includes some certain data like images/tables/etc

As MS Word uses RTF it is too expensive to parse it at the Editor's core. So it should be processed on the backend or maybe by a service worker. However, there is no way to plug in  any paste processing at the moment.

**Comment by neSpecc** [comment]
Related #729
