### ISSUE TITLE
custom toolbar placement

### ISSUE THREAD

**Issue by Tukizz** [codex-team/editor.js#1084]
i just wanna to ask a question
can i create custom toolbar placement like this :
![image](https://user-images.githubusercontent.com/22318828/77722862-72c58380-7021-11ea-811c-1d6233d19a3c.png)
i want to make the toolbar as bottom navigation so user with mobile version will easier to use

i just wanna make custom toolbar for matching with my frontend design
if it can, let me know with the example code thanks

**Comment by neSpecc** [comment]
In the current version, the Toolbar will be shown near the bottom of the block on mobile devices:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/3684889/79644825-1551cc00-81b4-11ea-9c17-74f082e6337f.png">

The Inline Toolbar will be shown separately 

<img width="846" alt="image" src="https://user-images.githubusercontent.com/3684889/79644840-2ac6f600-81b4-11ea-980d-3794f1844382.png">

There is no ability to put Inline Toolbar inside the main Toolbar. Maybe only with CSS overriding via `position: fixed` option

**Comment by neSpecc** [comment]
Also, there will be a problem with positioning the Toolbar at the bottom of the screen: T9 panel will overlay the toolbar on iOS devices.
