### ISSUE TITLE
How do you get all blocks onReady or onChange?

### ISSUE THREAD

**Issue by jeff-crosby** [codex-team/editor.js#1085]
I need to be able to scan all the blocks onReady and onChange for updates to the page outside the editor, but I'm not seeing a method in the Core API to get all blocks within the editor. All the examples I see in the repo and documentation just show simple console messages being output onChange or onReady.

In my particular use case, I'd like to update a table of contents (TOC) outside the editor with a linked title to every H2 (and maybe other levels) header currently within the editor, so I'd just want to rebuild that TOC onReady and onChange.

Any advice would be greatly appreciated.

**Comment by hagemann** [comment]
You can get all blocks this way:
```
import EditorJS from '@editorjs/editorjs'

var editor = new EditorJS({
  onChange: async () => {
    var data = await this.editor.save()
    // Update TOC by iterating through data.blocks
  }
})
```

**Comment by hagemann** [comment]
Just realized that the `onChange` callback passes a parameter since v2.17. Therefore, your code could look like this:

```
import EditorJS from '@editorjs/editorjs'

var editor = new EditorJS({
  onChange: async (data) => { // Parameter added.
    var { blocks } = await data.saver.save()
    // Update TOC by iterating through blocks.
  }
})
```

https://github.com/codex-team/editor.js/releases/tag/v2.17

**Comment by neSpecc** [comment]
Answered.

**Comment by findela** [comment]
The problem onChange method in react, I am facing is the data returning multiple times during change event for file upload like simpleImage plugin, how to get final data blocks that could give only one piece of block, any API or configuration for this? my code is like this

`onChange: async () => {
                    let data = await editor.save();
                    console.log(data)
                    // Update TOC by iterating through data.blocks
                },`

this above code returning multiple instance of the same block data but for editor while writing it returns only one.
