### ISSUE TITLE
Blocks#render doesn't work (API)

### ISSUE THREAD

**Issue by Paultje52** [codex-team/editor.js#1086]
Hello. I have a basic editorJS setup, with only the header tool and a testtool. I'm trying to use the blocks#render function in the API. This is my tool.
```js
class MyTool {
  constructor({data, api}){
    this.api = api;
    // ...
    setTimeout(() => {
      this.test();
    }, 1000);
  }

  test() {
    this.api.blocks.render(
      [
        {
          type: "header",
          data: {
             text: "New header",
             level: 2
          }
        }
      ]
    );
  }
}
```
_It's almost a direct copy from the docs._

When I load the page, everything is fine. After one second the function "test" is called and the editor is blank.

I get this error in my console.
```js
Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at e.<anonymous> (editorjs@latest:6)
    at c (editorjs@latest:6)
    at Generator._invoke (editorjs@latest:6)
    at Generator.forEach.t.<computed> [as next] (editorjs@latest:6)
    at c (editorjs@latest:6)
    at e (editorjs@latest:6)
    at editorjs@latest:6
    at new Promise (<anonymous>)
    at r (editorjs@latest:6)
    at S._invoke (editorjs@latest:6)
```

Am I doing something wrong or is this a bug?

**Comment by Paultje52** [comment]
I made this issue 5 days ago, I still don't have an answer. I did some more tests, and I found the solution! You need to use the direct output of editorJS. I only used the blocks, as an array. This works.
```js
class MyTool {
  constructor({data, api}) {
    this.api = api;
    // ...
    setTimeout(() => {
      this.test();
    }, 2000);
  }

  test() {
    this.api.blocks.render(
      {
      	time: Date.now(),
      	version: "2.17.0",
      	blocks: [
	    {
	      type: "header",
	      data: {
	         text: "New header",
	         level: 2
	      }
	     }
	  ]
	}
    );
  }
}
```

But the reason I didn't do it right, is because the documentation isn't correct. The example on this page needs to be changed: https://editorjs.io/blocks#render

**Comment by neSpecc** [comment]
@Paultje52 Thanks, I've fixed the example in docs.

**Comment by psdon** [comment]
I also encounter this, and @Paultje52 example doesn't work.

I tried
```
editor.blocks.render({
      	time: Date.now(),
      	version: "2.17.0",
      	blocks: [
	    {
	      type: "header",
	      data: {
	         text: "New header",
	         level: 2
	      }
	     }
	  ]
	}
)
```

It throws an error:
`jquery.js:4055 Uncaught TypeError: Cannot read property 'render' of undefined`

**Comment by Paultje52** [comment]
@psdon is editor.js ready before you try it?

**Comment by findela** [comment]
The documentation site of this plugin is limited, unclear, less example oriented, more worried and very poor in knowledge base. It's only super-heroic to ninja people or for those stupid folks who built this.
