### ISSUE TITLE
Feature Request (Tool-Setting): add option to not delete selected block on backspace or enter keydown

### ISSUE THREAD

**Issue by natterstefan** [codex-team/editor.js#1090]
## Scenario

A block's tool setting opens a modal (or any other new view outside of editorjs). Whenever the user hits backspace _or_ enter in the new view though, the block - which is still selected (`.ce-block--selected`) - gets deleted.

There is currently _no way_ to remove the selection from the block, when a tune was toggled/clicked.

## Example

![Screen Capture on 2020-04-01 at 16-40-17](https://user-images.githubusercontent.com/1043668/78150397-887ae480-7437-11ea-810f-d27563ea9b55.gif)

## Example Codepen

https://codepen.io/natterstefan/pen/PoqLVJr?editors=0110

## Research

There is a `enableLineBreaks` setting, managing how blocks behave when `enter` is pressed. In [the example](https://codepen.io/natterstefan/pen/PoqLVJr?editors=0110) it still looks like this is not working properly.

https://github.com/codex-team/editor.js/blob/be6f9b78f265c3d553c799c99e59c9916bf29e17/src/components/modules/blockEvents.ts#L257-L263

Same goes for `backspace`, but here we never reach this part of the code:

https://github.com/codex-team/editor.js/blob/be6f9b78f265c3d553c799c99e59c9916bf29e17/src/components/modules/blockEvents.ts#L353-L361

Because the block is still selected and [results to true in this if](https://github.com/codex-team/editor.js/blob/be6f9b78f265c3d553c799c99e59c9916bf29e17/src/components/modules/blockEvents.ts#L327-L338
).

## Feature request

Enable developers to unselect a block when a tune was toggled. Means, a new method is added to the blocks API (https://editorjs.io/api#blocks).

## Current Workaround (not 100% tested tough)

When the toggle is clicked, we remove the [selected class](https://github.com/codex-team/editor.js/blob/be6f9b78f265c3d553c799c99e59c9916bf29e17/src/components/block.ts#L67) from the block. This should help us to pass the if`s in the keydown handlers.

But this is kinda hacky IMHO.

## Additional questions

- is there really a global active `keydown` listener on the document ([here](https://github.com/codex-team/editor.js/blob/be6f9b78f265c3d553c799c99e59c9916bf29e17/src/components/modules/ui.ts#L310))? Because there is another [`backspacePressed` handler](https://github.com/codex-team/editor.js/blob/be6f9b78f265c3d553c799c99e59c9916bf29e17/src/components/modules/ui.ts#L390).

## (Possible) related Issues

- https://github.com/codex-team/editor.js/issues/810

**Comment by m-alzam** [comment]
Hi,

I'm having the same problem with an `input` element inside the block settings. I can't press the backspace key while editing it or the whole block get removed. As a proposal, there's not documentation available for how to manage other types of inputs (apart of buttons) in the block settings. Simple blocks doesn't require it, but more complex ones requires that type of settings.

This can be considered as a bug, because while block settings is opened we usually don't might want to remove the block.

Regards

**Comment by gohabereg** [comment]
Hi @m-alzam,
Wouldn't you mind if I assign you to this issue?
