### ISSUE TITLE
How to render json data with html tags on web view

### ISSUE THREAD

**Issue by chandresh-pancholi** [codex-team/editor.js#1091]
Hi,

I am new to front end technologies. I would like to know once we get the JSON output. How can I render this on react native based mobile app?

**Comment by hagemann** [comment]
You have to iterate through every block item and write your own HTML around it. The whole point of the blocks structure is that you are completely free to design your own layout (the drawback being that you have to do some more initial design work yourself).

**Comment by MurzNN** [comment]
I have same needs, not all users ready to write his own renderer for each block type. So will be good to implement build-in "default" renderer, that will write simple "default" HTML code that renders content like now in editor area, excluding edit instruments.

**Comment by hagemann** [comment]
I don’t think HTML output should be part of EditorJS because what you do with the generated blocks is out of its scope. Since I’ve already implemented it, I’ll make a start and welcome any feedback for enhancement: https://gist.github.com/hagemann/9e3d53b93ece55e77332d2594ffda43c

**Comment by gohabereg** [comment]
Hi there, I'm closing the thread

You can also see related issues: #676, #860, #1071
