### ISSUE TITLE
There is performance issue on $.isEmpty

### ISSUE THREAD

**Issue by tasuku-s** [codex-team/editor.js#1095]
In my usecase (Angular, many editor, long text in a block), copy, paste and click any line in block that has too long lines makes browser freezing.

I found that `isEmpty` method in `editor.js/src/components/dom.ts` has bad algorithm to traverse nodes.

When there are nodes like `A, B, C, D, E`, then this method traverse nodes as `A, B, C, D, E, B, C, D, E, C, D, E, D, E`.

**Comment by gohabereg** [comment]
Resolved by #1096
