### ISSUE TITLE
Jumpy contentEditable caption on Chrome and Firefox

### ISSUE THREAD

**Issue by hagemann** [codex-team/editor.js#1097]
Pull #981 seems to include a hack for Firefox, but it causes a jumpy behavior (two lines image caption field becomes one upon focus): https://github.com/codex-team/editor.js/blob/be6f9b78f265c3d553c799c99e59c9916bf29e17/src/styles/ui.css#L23

You can also observe it on the editorjs.io website.

How about giving `cdx-input` a `min-height: 46px;` style as suggested here: https://stackoverflow.com/questions/24793551/firefox-does-not-allow-blank-contenteditable-area

It resolves the jumpy behavior and it did not cause any issue on Firefox either.

**Comment by neSpecc** [comment]
Resolved by https://github.com/editor-js/image/pull/82
