### ISSUE TITLE
No Proper Documentation

### ISSUE THREAD

**Issue by Someskumarasamy** [codex-team/editor.js#1101]
Hi team, It would be more helpful if you had a proper documentation for react implementation too

**Comment by hagemann** [comment]
I implemented it with Vue and there was nothing particularly special about it. Implementation with React should be quite straightforward too, like how you use any other library.

**Comment by Someskumarasamy** [comment]
@hagemann  Is it possible to use the packages with next.js.

**Comment by hagemann** [comment]
If you make sure that the editor only loads on client-side (no SSR), then I assume so. I’ve never worked with React before, but the `componentDidMount` lifecycle seems not to execute on server and that’s where you could place your code in.

Rough guess:

```
import React from 'react'
import EditorJS from '@editorjs/editorjs'

class Editor extends React.Component {
  componentDidMount() {
    const editor = new EditorJS()
  }
  render() {
    return <div id="editorjs"></div>
  }
}

export default Editor
```

**Comment by crying2812** [comment]
> I implemented it with Vue and there was nothing particularly special about it. Implementation with React should be quite straightforward too, like how you use any other library.

Hi @hagemann , i'm a newbie who trying to add custom plugin for editor.js, can you give me an example for this? Thanks
