### ISSUE TITLE
Cannot read property 'holder' of undefined

### ISSUE THREAD

**Issue by nicolapagni** [codex-team/editor.js#1102]
Hi guys,

when i try to remove a block (my custom or simply a paragraph) I receive the error described in the issue title.

I've to specify that if I try to apply
`api.blocks.delete(blockPosition);` the in onChange listener It works fine...
Instead if I run the same outside of It I get this error.

It's very strange since other methons like move, getblock, render works as well.

Any suggestions?

Thanks in advance.

Regards,
  Nicola

**Comment by gohabereg** [comment]
Hi @nicolapagni 
In the current version `blocks.delete` doesn't accept block index, but there is already a PR #1108 

As for now, if you call `blocks.delete` without any block selected, it will throw an error. However, I'll add there a `warn` with details instead of the error

**Comment by nicolapagni** [comment]
Hi @gohabereg,

ok!
To avoid this error, is there a method that allows me to select a block and then use blocks.delete ?

Let me know :)

Thanks!

**Comment by gohabereg** [comment]
No, unfortunately.

I don't think its a good idea to set current block externally. We will release new version soon, you will be able to specify index when calling `delete`

**Comment by nicolapagni** [comment]
ok.
Currently I'm using the render method. So instead "update" a single block, refresh them all.

Tranks for the fast response :)
