### ISSUE TITLE
blocks[] strips html tags 

### ISSUE THREAD

**Issue by ninjavis** [codex-team/editor.js#1115]
Hi there! Thanks for this awesome plugin. I'm currently using it in Angular 9, however, when I add html to a code block, the object to be saved completely strips any html tags. Some other code tests like Typescript seem to work fine. Is this something your plugin does, or is it perhaps something Angular does? Any ideas how this can be resolved too, please? Many thanks!

this.editor.save().then((outputData) => {

      console.log('Article data: ', outputData))

}

this results in:

![image](https://user-images.githubusercontent.com/11474529/79856365-8e2b7080-83cc-11ea-87e7-7dfd1910d0cc.png)

**Comment by gohabereg** [comment]
Hi @ninjavis 
This issue is related to the plugin, not the core.
There is already a PR for that https://github.com/editor-js/code/pull/20. Should be merged soon

**Comment by sosie-js** [comment]
Maybe we can avoid this with a [tool-configurator](https://github.com/sosie-js/tool-configurator) based on the suggestion you made me on [#1280](https://github.com/codex-team/editor.js/issues/1280)

**Comment by neSpecc** [comment]
Solved on the plugin side
