### ISSUE TITLE
[Bug]Delete key

### ISSUE THREAD

**Issue by stasyuk93** [codex-team/editor.js#1125]
If you select several blocks and press the **delete key**, no action occurs (backspace works).

**Comment by gohabereg** [comment]
Hi @stasyuk93 
Could you please split the issue into each of the three problems?

And also provide some details for the second one (pasting with one selected Block). If I select Block through Cmd+A pressed once, it seems to work as expected. If I select one Block through Cross-Block selection, paste doesn't work at all, but it's related to the third problem you described.

**Comment by jeremyVignelles** [comment]
Duplicate of #1315 ?

**Comment by gohabereg** [comment]
Closing due to more descriptive duplicate #1315
