### ISSUE TITLE
How to change the <b> tag to <strong>

### ISSUE THREAD

**Issue by AmirArdakani** [codex-team/editor.js#1144]
Hello
How to change the `<b>` tag to `<strong>` in the **BoldInlineTool** class?

![issue_1](https://user-images.githubusercontent.com/31389761/80956151-e07d8000-8e15-11ea-9203-e06fdfba8740.JPG)

![issue_2](https://user-images.githubusercontent.com/31389761/80956156-e4a99d80-8e15-11ea-8513-c7b5cc61cef3.JPG)

**Comment by sis-dk** [comment]
In bold inline tool that comes with the core module uses a browser API. So it puts <b> in most browsers and <strong> in IE. If you always want <strong> then you'll probably have to write your own inline tool.

**Comment by AmirArdakani** [comment]
@sis-dk 
Yes. That's right
After reviewing, I finally created my own inline tool.

**Comment by Haraldson** [comment]
Who doesn’t want `strong`? This should be bundled and normalized.

Anyhow, how did you replace the default inline B tool with your Strong tool, @AmirArdakani?

**Comment by AmirArdakani** [comment]
@Haraldson Hello
Exactly, this should be possible by default.
But I created a plugin and used it, you can use Inline tools and apply changes.
like this :
`
this.tag = 'STRONG';
`
`
static get sanitize() {
    return {
      strong: {}
    };
  }
`
Then, using the build: prod command, I use the plugin and replace it with the default tool 
`
    var editor = new EditorJS({
      holder: 'editorjs',
      tools: { bold: InlineBold },
      data: {},
    });
`
