### ISSUE TITLE
Use css files instead of <style> blocks in DOM

### ISSUE THREAD

**Issue by CancerRaccon** [codex-team/editor.js#1149]
Hi all,

I am testing the plug in for my project and was wondering if i can avoid inline css and use the files instead.

thanks in advance.

**Comment by sis-dk** [comment]
Hi, what plugin are you using? Is it your own plugin? Didn't see inline css in any of the plugins that are available already. All of them use css the style modules way.

**Comment by CancerRaccon** [comment]
> 
> 
> Hi, what plugin are you using? Is it your own plugin? Didn't see inline css in any of the plugins that are available already. All of them use css the style modules way.

Release 2.18.
I just downloaded the project and included the editor.js and all the styles to my project.

My first problem was that the browser(chrome) wasn't able to recognize the way  CSS files are written (nested blocks mainly).

Then I noticed that the plug in appended some `<style>` blocks and for some different technical reasons I cannot have a feature that runs like that in my project.

Thanks for your time.

**Comment by sis-dk** [comment]
> My first problem was that the browser(chrome) wasn't able to recognize the way CSS files are written (nested blocks mainly).

I think you are including Editorjs wrong in your project. Could you show us how you have setup your project?

> Then I noticed that the plug in appended some <style> blocks and for some different technical reasons I cannot have a feature that runs like that in my project.

I don't think you would be able to include the EditorJS styles as an external CSS.

**Comment by CancerRaccon** [comment]
> 
> 
> I think you are including Editorjs wrong in your project. Could you show us how you have setup your project?
>
> I don't think you would be able to include the EditorJS styles as an external CSS (Unless you build it that way yourself)

In both cases you are 100% correct. I will try to understand better the project and if keep on facing problems i will come back with more accurate questions.

Thanks a lot.

**Comment by sis-dk** [comment]
> > I think you are including Editorjs wrong in your project. Could you show us how you have setup your project?
> > I don't think you would be able to include the EditorJS styles as an external CSS (Unless you build it that way yourself)
> 
> In both cases you are 100% correct. I will try to understand better the project and if keep on facing problems i will come back with more accurate questions.
> 
> Thanks a lot.

Sure. You can just fork the repo, comment out the loadStyles code that appends the style tag but leave the import of the main.css there and use something like mini-css-extract-plugin in the webpack config to extract out the css to another file and do a 'yarn build'. That would give you two separate files for JS and for CSS. But that is only for the editor core. The same will have to be done for all of the tools that you use such as paragraph (which is the default tool that comes with the editor) and other tools that you plug into the editor. There could be easier ways of doing it but this method will also work.

**Comment by AlexRMU** [comment]
Isn't it easier for developers, instead of embedding styles`!` in the head`!`, to encapsulate them, as all normal people do?
When initializing, the editor has an element id, so why shouldn't it use this id in styles?
