### ISSUE TITLE
[Bug] Lag with big text

### ISSUE THREAD

**Issue by ErriourRU** [codex-team/editor.js#1150]
Error with long text (or text carried over next line). Browser freezes after about 9-10 lines of this text.

Steps to reproduce:
1. Go to your site with editor [(https://editorjs.io/)](https://editorjs.io/)
2. Start typing something via Shift+Enter (like this: [https://i.imgur.com/pBXXhGf.png](https://i.imgur.com/pBXXhGf.png))
3. FUN!!!

Expected behavior: All works

Device, Browser, OS: PC, Chrome 81, Windows 10

Editor.js version: 2.17.0

Plugins you use with their versions: Anything

**Comment by sis-dk** [comment]
Was this reproducible in the place where you used EditorJS (In your project using EditorJS)?

**Comment by ErriourRU** [comment]
> Was this reproducible in the place where you used EditorJS (In your project using EditorJS)?

Yes of course. In another way I never asked this question...

**Comment by sis-dk** [comment]
> > Was this reproducible in the place where you used EditorJS (In your project using EditorJS)?
> 
> Yes of course. In another way I never asked this question...

I asked that question because you pointed to the editorjs.io site in the steps to reproduce and when I tried the same in a separate project the problem didn't occur. But then I noticed my project is using 2.18 and you mentioned the version as 2.17 (My mistake). Tried with 2.17 and the problem did indeed occur.

**Comment by ErriourRU** [comment]
> I asked that question because you pointed to the editorjs.io site in the steps to reproduce and when I tried the same in a separate project the problem didn't occur. But then I noticed my project is using 2.18 and you mentioned the version as 2.17 (My mistake). Tried with 2.17 and the problem did indeed occur.

Hmm... I didn't notice that 2.18 is appeared (it's still 2.17 on site and in NPM). I will try to manually update to 2.18 and check result.

**Comment by sis-dk** [comment]
> > I asked that question because you pointed to the editorjs.io site in the steps to reproduce and when I tried the same in a separate project the problem didn't occur. But then I noticed my project is using 2.18 and you mentioned the version as 2.17 (My mistake). Tried with 2.17 and the problem did indeed occur.
> 
> Hmm... I didn't notice that 2.18 is appeared (it's still 2.17 on site and in NPM). I will try to manually update to 2.18 and check result.

2.18 hasn't released yet. I'm building it from my 2.18 fork.

**Comment by ErriourRU** [comment]
> 2.18 hasn't released yet. I'm building it from my 2.18 fork.
Yep, no problems in 2.18. Thanks!
