### ISSUE TITLE
Hyperlink button not showing when select all the text of a paragraph

### ISSUE THREAD

**Issue by matheusslg** [codex-team/editor.js#1158]
Steps to reproduce:
1. Write some text in a normal paragraph and select all the text and then try to add a hyperlink to this text.

Expected behavior: 
Show the hyperlink button when select all the text.

Screenshots:
![image](https://user-images.githubusercontent.com/14168382/82284180-84f1eb80-99ec-11ea-8e2e-35ae44e620cf.png)

Device, Browser, OS:
Laptop, Chrome, Windows 10

Editor.js version:
2.15.1

Plugins you use with their versions:
"@editorjs/editorjs": "^2.15.1",
"@editorjs/paragraph": "^2.6.0",
"react-editor-js": "^1.4.1"
"@stfy/react-editor.js": "^0.1.5",

**Comment by gabrielmoterani** [comment]
Hey guys, can anybody help us here? What should we do to get it working?

**Comment by neSpecc** [comment]
This behaviour only related to the outdated version of editor.js. Update editor.js and plugins to the latest version to resolve this.

**Comment by gabrielmoterani** [comment]
@neSpecc thanks. We will try to update ;)
