### ISSUE TITLE
missing BaseToolConstructorOptions named interface export.

### ISSUE THREAD

**Issue by adrianpdm** [codex-team/editor.js#1167]
Branch: [`release/2.18`](https://github.com/codex-team/editor.js/tree/release/2.18)

This line [here](https://github.com/codex-team/editor.js/blob/2997ed00e8b5d7238fc1e987c0a71294b32b3779/types/tools/block-tool.d.ts#L3):
```javascript
// types/tools/block-tool.d.ts
import {BaseTool, BaseToolConstructable, BaseToolConstructorOptions} from './tool';
```

There is no export named `BaseToolConstructorOptions` in the imported module.

**Comment by khaydarov** [comment]
@adrianpdm this interface was removed in [v2.19](https://github.com/codex-team/editor.js/releases/tag/v2.19.0). I'll close this issue, but if it is still actual please report again so that we could re-open
