### ISSUE TITLE
Error when trying to integrate Editorjs with Angular

### ISSUE THREAD

**Issue by aleksadjukic** [codex-team/editor.js#1183]
This is the error I get: 
---------------------------------------------------------------------
ERROR in node_modules/@editorjs/editorjs/types/api/block.d.ts:2:25 - error TS2307: Cannot find module '../../src/types-internal/block-data'.

import {SavedData} from '../../src/types-internal/block-data';
---------------------------------------------------------------------

So basically it's trying to import from src folder, but there is no src folder in the @editorjs/editorjs when i use the 'npm install @editorjs/editorjs --save-dev'. 
I am aware that there is an ngx-editorjs package, but I'm really frustrated by this issue.
Any help would be highly appreciated.

**Comment by nikolassoares** [comment]
I also have the same bug
help

**Comment by gopumon** [comment]
Me too... My CI log ends with
```
ERROR in node_modules/@editorjs/editorjs/types/api/block.d.ts:2:25 - error TS2307: Cannot find module '../../src/types-internal/block-data'.
 2 import {SavedData} from '../../src/types-internal/block-data';
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running after_script
Uploading artifacts for failed job
ERROR: Job failed: exit code 1
```
This happened when I updated EditorJS today.

**Comment by juanmigonzalez** [comment]
Same here when I updated dependencies.

Install and force a previous version of editorjs (and plugins) with package.json worked for me until they will patch the error:
```
    "@editorjs/editorjs": "2.17.0",
```
and then:

`npm install`

**Comment by tommiv** [comment]
There's a slightly easier way, just ask npm to install an exact version:

```bash
npm install @editorjs/editorjs@2.17.0
```

Don't forget to install the latest version when the fix for this issue is available (`npm install @editorjs/editorjs@latest`)

**Comment by nikolassoares** [comment]
@tommiv, @juanmigonzalez thanks, works for me

**Comment by tiberiumihai** [comment]
I've investigated the issue and because `/src/` folder is not included in the library published to npm, the typing file `block-data.d.ts` does not exist.

I think it we can fix this by moving the type file from `/src/types-internal/block-data.d.ts` to `/types/api/block-data.d.ts` and refactoring all its import declarations.

Proof: Testing by simply adding `block-data.d.ts` to node_modules in my project works.

I can add a PR with the changes if I have the approval from you guys.

Thanks!

**Comment by minirobotdan** [comment]
Thanks for the workaround @tiberiumihai you saved me from stalling progress on an important feature!

Would be keen to see this PR'd and corrected quickly!

**Comment by Teebo** [comment]
Is this fixed with latest version?

**Comment by RicoBrase** [comment]
Getting the same error.

Seems like no type definitions files (`*.d.ts`) are generated for the files under `src`, but other type definitions (e.g. this `block.d.ts`) depend on them.

**Comment by Teebo** [comment]
@RicoBrase my workaround was to follow on what @tiberiumihai suggested:

> I think it we can fix this by moving the type file from /src/types-internal/block-data.d.ts to /types/api/block-data.d.ts and refactoring all its import declarations.

**Comment by RicoBrase** [comment]
@Teebo Currently working on an easy workaround PR by modifying the `.npmignore` file. That way, one doesn't have to move around any files.

**Comment by Teebo** [comment]
@RicoBrase Great!

**Comment by rantunokrek** [comment]
Thanks fixed
