### ISSUE TITLE
[Bug] Unable to move on from initial block when tabbing in from outside

### ISSUE THREAD

**Issue by lindelius** [codex-team/editor.js#1184]
I'm unable to move on from the initial block (without using the mouse) when tabbing in from outside the editor. For example, in my case I have separate title input and when I use TAB to move on from the title input to the editor I'm unable to then move on from the initial block. The ENTER key just creates a new line (like CTRL + ENTER otherwise does) and pressing TAB again gets me to the address bar of the browser.

Steps to reproduce:
1. Create an input field outside (just above) of the editor
2. Focus the input field and then press TAB to enter the editor
3. You are now unable to move on from the initial block (create new blocks) without using the mouse

Expected behavior:
The editor is expected to behave just like when you use the mouse to enter the editor, i.e. that ENTER creates a new block and TAB opens the block settings.

Device, Browser, OS:
Chrome 79.0.3945.117, Ubuntu 18.04

Editor.js version:
2.18

**Comment by ReedRodgers** [comment]
I'm seeing this too, it's a bit of an issue since when the data is saved the output doesn't include line breaks, so
```
three
line
text block
```
saves as 
```threelinetext block```

Chrome 85.0.4183.121
macOS 10.15.7
Editor.JS 2.19.0

**Comment by neSpecc** [comment]
Duplicate https://github.com/codex-team/editor.js/issues/927
