### ISSUE TITLE
[Bug] editor.js toolbar buttons don't fit on mobile

### ISSUE THREAD

**Issue by Daeren** [codex-team/editor.js#1186]
![[Bug] editor.js toolbar buttons don't fit on mobile device](https://user-images.githubusercontent.com/5007624/83811408-6bc28d80-a6c2-11ea-9652-fe87ba9e4f37.png)

**Comment by flydev-fr** [comment]
It could help the devs to know on which browser/device you are experiencing that because on my side, everything is fine on iOS / iPhone 6s / Chrome and Safari.

**Comment by Daeren** [comment]
Hm. You're right. I created a new project and everything is fine. But when i look at the main page of the site, everything breaks down like this (screenshot). 

Android 8.1 / FF or Opera dev tools and some other.

Then, basically, the issue can be considered closed. Because the problem concerns the site
