### ISSUE TITLE
💡 Color plugin

### ISSUE THREAD

**Issue by vincentdesmares** [codex-team/editor.js#1200]
1. Describe a problem.

Many of our users requested the ability to change the color of the text.

2. Describe the solution you'd like. Mockups are welcome.

A simple color picker that can be activated on hover. Like the twitter color picker: http://casesandberg.github.io/react-color/

3. Are there any alternatives?

Right now you can only highlight text or underline it (since two days!).

**Comment by flaming-cl** [comment]
Hi. I've made a simple color plugin. Maybe it could fit your demand. 
[editorjs-text-color-plugin](https://www.npmjs.com/package/editorjs-text-color-plugin)

**Comment by vincentdesmares** [comment]
@flaming-cl Really nice initiative! We don't need something more complex for now so we will use it. You should ask to add it to the list of plugins.

**Comment by ageddesi** [comment]
Thats ace @flaming-cl will be using that in my editor.

**Comment by Aarbel** [comment]
Sounds like a great plugin @neSpecc do you plan to put it inside editorjs ?

**Comment by neSpecc** [comment]
> Sounds like a great plugin @neSpecc do you plan to put it inside editorjs ?

No, plugins are not included in the core editor. They must remain separate packages. The editor's API allows for the implementation of such a plugin.

If you want to discuss the plugin implementation, it's better to create a Discussion

**Comment by Aarbel** [comment]
@neSpecc i mean, would it be possible to have this plugin officialy listed inside editorjs plugins ?

**Comment by neSpecc** [comment]
> @neSpecc i mean, would it be possible to have this plugin officialy listed inside editorjs plugins ?

Probably yes
