### ISSUE TITLE
Integrating editor.js in a react application 

### ISSUE THREAD

**Issue by Ajitesh13** [codex-team/editor.js#1202]
I was trying to use the react plugin [react-editor-js](https://github.com/Jungwoo-An/react-editor-js) of editor.js but couldn't access the data returned by the editor, in any way.I want to know can I directly integrate editor.js in a react application without using the react-editor-js ?

**Comment by flaming-cl** [comment]
if you don't mind to operate with both the real and virtual DOM, you can use React ref to integrate editor.js.
``` javascript
// 1. create a react ref
const editor = useRef();
// 2. set that ref to a jsx node
       <div ref={editor}></div>
// 3. set up configs and init editor.js
 useEffect(() => {
        initEditor();
    }, []);

const initEditor = () => {
    const configs = {};
    if (editor.current) {
            editor.current.id = "editorjs";
            const editorNode = new EditorJS(configs);
            editorConfig.onChange = () => {
                handleEditorTextChange(editorNode); // handle data change
            };
        }
}
```

**Comment by ysqsimon** [comment]
I'm not quite sure why you can't access the data, but if you have read the react version doc carefully, the second parameter of the "**onChange**" API, "**newData**", is the data returned by the editor. I've tried it and it works as expected.
However, you **CAN** just use the original editor.js in React app in three steps(I'm not 1000% sure but it works fine for me):

1. 
```jsx 
import EditorJS from '@editorjs/editorjs'
```
2. you need to create the instance somewhere before componentDidMount, maybe like
```jsx
constructor(props){
   super(props)
   this.editor = new EditorJS({
    /**
     * Id of Element that should contain Editor instance
     */
    holder: 'editorjs',
  })
}
```
3. connect the instance with a DOM element `<div id="editorjs" />`, note the id is the holder of the instance

More specific usage about the instance I recommend the html example as a starting point [https://github.com/codex-team/editor.js/blob/release/2.18/example/example.html](url)

**Comment by Ajitesh13** [comment]
Thanks @ysqsimon. Can you tell me how to render out the saved data in an uneditable format ?

**Comment by Ajitesh13** [comment]
> More specific usage about the instance I recommend the html example as a starting point [https://github.com/codex-team/editor.js/blob/release/2.18/example/example.html](url)

I am sorry, I couldn't find the html page you referred here.

**Comment by ysqsimon** [comment]
> Thanks @ysqsimon. Can you tell me how to render out the saved data in an uneditable format ?

If you mean to just display data definitely check out this post #609

**Comment by gohabereg** [comment]
Hi @lsbyerley,
There are several options for React made by community. You can find couple of them here — https://github.com/editor-js/awesome-editorjs#javascript

We'd like to focus on core development at the moment. As for ecosystem, we are relying on the community until we have enough resources to make it "official".

I close the thread
