### ISSUE TITLE
💡One For The Poets

### ISSUE THREAD

**Issue by cupcakedream** [codex-team/editor.js#1211]
Hey there - 

I'm using this javascript library for an app where users edit poems and lyrics - right now every-time you break a line it creates a new block which adds a bunch of padding between lines. I'm able to remove the padding, but I was just wondering if it's possible to have line breaks within a block, or if that could be added in?

![image](https://user-images.githubusercontent.com/1387911/85190575-9a766180-b287-11ea-96c3-85c0ad997226.png)

Thanks,

Mike

**Comment by ranemihir** [comment]
press SHIFT + ENTER for line breaks in the same block.
Closes #1211

**Comment by cupcakedream** [comment]
Perfect - thank you!
