### ISSUE TITLE
[Bug] Unable to access editor content

### ISSUE THREAD

**Issue by cupcakedream** [codex-team/editor.js#1213]
Hey All - 

I'm trying to access the data that's in the EditorJS instance and save it to my to database via an AJAX call. In the docs it goes over using the `.save()` method but that returns a Promise object with an internal object that's not accessible. Is that the best way to get the data? Is there a method i'm missing to get the data? 

```
window.editor = new EditorJS({
            holder : 'editor',
            data: {}
});

content = window.editor.save();
```

Thanks,

Mike

**Comment by ranemihir** [comment]
Currently there is no other way to get the saved data. You can just resolve the promise and make the AJAX request.

**Comment by cupcakedream** [comment]
Okay, thank you!
