### ISSUE TITLE
How can I import tool.js(ex: @editorjs/paragraph, image, ...) with NextJS

### ISSUE THREAD

**Issue by Kamez** [codex-team/editor.js#1223]
When I try to import tool.js it shows error like "window is not defined".

```
import dynamic from "next/dynamic";
import { EDITOR_JS_TOOLS } from '../utils/tool'

const EditorNoSSRWrapper = dynamic(import("react-editor-js"), {
  ssr: false,
  loading: () => <p>Loading ...</p>,
});

function Editor() {
    return (
      <>
        <EditorNoSSRWrapper 
            tools={EDITOR_JS_TOOLS}
        />
      </>
    );
  }
  
export default Editor;
```

Can someone help me ?

**Comment by stan900814** [comment]
I use nuxt.js also have this problem,the reason is only client has  'window', you can try it
`let Paragraph = null 
if(process.client){
Paragraph = required('@editorjs/paragraph')}
`

**Comment by ranemihir** [comment]
In server-side rendering, the modules which require **window** or **document** object i.e. which are client specific need to be required inside a **process.client** block so that the same code does not run on the server side.

**Comment by xjasonsong** [comment]
For anyone who is still trying to create their own react wrapper with NextJS. Do not use dynamic import as it works only for React components. To import js modules, use import instead, see the discussion here: https://github.com/vercel/next.js/discussions/13417

So you could do: 

```
        const EditorJS = (await import("@editorjs/editorjs")).default;
        const Header = (await import("@editorjs/header")).default;
```
