### ISSUE TITLE
💡onBlur event

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1225]
1. Describe a problem.
I use onChange event to save EditorJS automatically. 
But a performance problem is occured because onChange events are dispatched frequently. 

2. Describe the solution you'd like. Mockups are welcome.
Add onBlur event to EditorJS. 
It is dispatched when the EditorJS was blurred only. 

3. Are there any alternatives?
Improve onChange event. 
I think it should be dispatched when the OutputData will be changed.

**Comment by neSpecc** [comment]
I've answered [here](https://github.com/codex-team/editor.js/pull/1224#issuecomment-681104900) why the `onBlur` event is not a good solution for this problem.

> The onBlur does not resolve the attached issue because the content of the editor can be modified not only through the typing from the keyboard. All other changes like blocks moving, changing block tunes, and others won't fire the onBlur event. It means that you can't use it for triggering a saving.

Why not use debounce in your onChange callback?

**Comment by hata6502** [comment]
@neSpecc 
I'll use debounce on change event, and I think it'll be resolved! 
Thank you.
