### ISSUE TITLE
[Bug] Tune Block editor throws n.closest is not a function when clicking the control mutliple times

### ISSUE THREAD

**Issue by millenniumbrain** [codex-team/editor.js#1226]
When clicking on the tune button multiple times in Firefox, I'm getting a n.closest is not a function error which will duplicate the tune controls, they still work properly when moving or deleting block. It seems in Firefox the shadow DOM element will exist but without it's properties which will cause this UI error. I have fixed this by also checking if closest is a function however, this may not be the ideal solution. I could submit a PR with the check but I'm looking for guidance on how to approach this.

Steps to reproduce:
1. Create an element with the editor initialized in Firefox
2. Click on the tune button in the editor multiple times
3. n.closest error should show up in the console and this image below is what will happen:
![Editor JS Error](https://user-images.githubusercontent.com/8406358/86868949-a9407f00-c0a3-11ea-92d4-358bb48b6eb5.png)

Expected behavior:
It should not throw this error and create multiple tune controls

Screenshots:
Browser: Firefox
OS: Windows 10

Editor.js version: 2.18.0

Plugins you use with their versions:
Image v2.4.2
Header v2.5.0 
List v1.5.0
Paragraph v2.7.0

**Comment by jluini** [comment]
Same here. The error is thrown when clicking the _tune_ control multiple times but **also when deleting a block**.

I simply created an empty html file, imported the core editor.js manually, instantiated it and I'm getting the error in Firefox.

**Comment by neSpecc** [comment]
Duplicates #1273
