### ISSUE TITLE
Is there any python library convert html to block of editorjs, or convert block to html

### ISSUE THREAD

**Issue by qqqays** [codex-team/editor.js#1232]
i want to convert html to block (json structure of editorjs )

**Comment by gabrielmoterani** [comment]
Maybe I am wrong, but think if you start editorjs with html as initial payload it will convert for blocks for you. Block to html you can find samples of code online.

**Comment by qqqays** [comment]
@gabrielmoterani  Thank you for your reply.I have gotten some html pages with python spider from public website. Now I want to parse them to blocks of editorjs in backend, and then save these blocks to database.

**Comment by gabrielmoterani** [comment]
@qqqays Yeah, I need to convert HTML for EditorJs blocks too... What I am doing is using a nodejs lib to convert HTML to json and then iterating each item of this json, converting to blocks. But I dont think this is such a good ideia. HTML is very nested...
I think Editorjs has something inside that do this conversion, since you can paste html in Editor and he will convert to Editorjs Blocks. 

It would be better if EditorJs provide us that api. 

If anyone knows a better way to do that, please share with us :)

**Comment by qqqays** [comment]
@gabrielmoterani Hello, bro! How is the work of parsing html into editor.js blocks? 
I did this with jsdom that ran in nodejs，I created a entity of editorjs in jsdom,  then share this entity in jsdom and nodejs env. The entity as a factory converting html to blocks, then return the blocks.

**Comment by gabrielmoterani** [comment]
Well I am still struggling to make a good solution for my application. @qqqays can u share more details of your implementation? Can u share the code that converts jsdom to blocks?

I tried to use a lib that named Hymalaya that converts html to JSON, but HTML object became so nested, thats impossible to iterate over it. 

Does anyone nows how Editorjs convert pasted content to blocks?

**Comment by qqqays** [comment]
@gabrielmoterani I put the project to https://github.com/qqqays/server4parseEditorJs. You can try it ; )

**Comment by proflinksgh** [comment]
> 
How did you do it? Please show me

**Comment by Alchez** [comment]
@proflinksgh I was able to take a clue from @qqqays's library and I used the following code block to convert an HTML string to EditorJS blocks:

```js
const editor = new EditorJS({
  ...
  onReady: async () => {
    if (dataIsHtml) {
      await editor.blocks.renderFromHTML(data);
    }
  },
  ...
});
```

**Comment by sushant-78** [comment]
@Alchez Hello, I came across your reply as I am facing the same issue, did you change anything else except adding above code to the editorjs instance? Where can you get the outputted html string from?Also, if possible can I have a look at the code file?

**Comment by Alchez** [comment]
Hey @sushant-78, unfortunately the code is private on Github so I can't share it.

We were receiving an HTML string from our backend server that we wanted to output as EditorJS blocks, that was our source. By just adding that `onReady` function, we were able to convert the string to blocks.

Hope that helps.

**Comment by sushant-tce** [comment]
@Alchez Thanks, for quick reply, didn't need to try it out, worked out a solution,needed to migrate data, so wrote patch script for it

**Comment by ranjancse26** [comment]
@qqqays You are the savior. The solution works well with editorjs@2.19.1 but not the latest. Yet, you are the legend

`<script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.1/dist/editor.min.js"></script>`

**Comment by sumitkr2000** [comment]
Hello, I am struggling to dins a way to convert HTML files into EditorJS blocks. Can anyone please help me?

**Comment by dsp-pricesenz** [comment]
hi team, is there any defined solution r=to render html to editorjs. i have tried abve suggestion but i failed.

**Comment by GhostEarz** [comment]
hi team, is there any defined solution r=to render html to editorjs. i have tried above suggestion but i failed.

**Comment by cactis** [comment]
But it give [object HTMLPreElement] for pre tag, how to solve it? Thanks.
