### ISSUE TITLE
How to save editor.js  at all time and places 

### ISSUE THREAD

**Issue by stan900814** [codex-team/editor.js#1234]
i want to save the data all the times but there is no method  ，also not have the blur event 。has any ways to get it？

**Comment by neSpecc** [comment]
What do you mean "all the times"?

**Comment by neSpecc** [comment]
The `blur` event is implemented and waiting for the [code review](https://github.com/codex-team/editor.js/pull/1224)

**Comment by stan900814** [comment]
> What do you mean "all the times"?

just like i edit a block it can immediately save this data

**Comment by stan900814** [comment]
> The `blur` event is implemented and waiting for the [code review](https://github.com/codex-team/editor.js/pull/1224)

how  i can listening the keydown and keyup events in edtor.js

**Comment by neSpecc** [comment]
You can use the [`onChange`](https://editorjs.io/configuration#editor-modifications-callback) callback where simply call the `.save()`

**Comment by ranemihir** [comment]
`editor.save().then((outputData) => {
  // Get your output data here
  // you can save it on the client side using localStorage or Indexed DB.
  //Or you can store it on your custom backend.
}).catch((error) => {
  console.log('Saving failed: ', error)
});`

You can place the above method by implementing a way to save the data inside the `onChange` callback.

**Comment by neSpecc** [comment]
Answered

**Comment by ShadowMyst** [comment]
@neSpecc Could you give me an example of implementation with "onchange", since I can't find the way to use .save (), it gives me an error when I try it

**Comment by neSpecc** [comment]
@ShadowMyst See an [example](https://github.com/codex-team/codex/blob/master/www/public/app/js/modules/editorLanding.js#L161) from our landing page

**Comment by ShadowMyst** [comment]
thanks you. based on the link you passed me I did this.

```
const editor = new EditorJS({
    holder: 'editorjs',
    autofocus: true,
    tools:{
        header:{
            class: Header,
            config:{
                placeholder: "Escriba el titulo",
                levels: [2,3,4,5,6],
                defaultLevel:2
            },
            inlineToolbar: true
        },
        list: {
            class: List,
            inlineToolbar:true,
        }
    },
    data:{},
    onReady: ()=>{

    },
    onChange:() =>{
        saved();
    }
});
function saved(){
    editor.save().then((savedData) =>{
        console.log('salvado',savedData);
    }).catch((error) =>{
        console.log("fallo al guardar",error)
    })
}

```
