### ISSUE TITLE
Is there a reason why EditorJS has opinions about element styling? 

### ISSUE THREAD

**Issue by jnguyen32** [codex-team/editor.js#1239]
Is there a way to disable EditorJS' insertion of classes like `ce-header`? 

Some tools let you edit the styles outside of the editor itself, and it would make more sense to inherit them rather than force things like padding on headings. I understand that the response from the editor is JSON format and you're ultimately responsible for the styling, but it really messes with the user's ability to see their work how they intended to see it.

**Comment by CavalcanteLeo** [comment]
@jnguyen32 how did you solve?

**Comment by chisomgbata** [comment]
@CavalcanteLeo How did you solve it ???

**Comment by CavalcanteLeo** [comment]
yarn remove editorjs

Kidding but it's true, i have changed editorjs to ckeditor5

Too many bugs in here, too many features missing. Too closed for changes and no support at all

@chisomgbata

**Comment by chisomgbata** [comment]
I just removed it and I am using tiptap now
Ckeditor is just an overkill for my project, but i will really miss how editorjs gives me a json to work with
@CavalcanteLeo

**Comment by chisomgbata** [comment]
I am using prose mirror now, I dont like ckeditor
@CavalcanteLeo

**Comment by CavalcanteLeo** [comment]
Actually I'm using tinyMCE, i confused when I said ckeditor.
