### ISSUE TITLE
Can i use inline toolbar when i set contenteditable to false for all elements

### ISSUE THREAD

**Issue by umutbozdag** [codex-team/editor.js#1241]
When i set contenteditable to false for elements i can't use the inline toolbar tools. 

I mean when i select contenteditable="false" elements (e.g paragraph) inline toolbar should show up on the screen. 

I just saw that you guys disabled it in #542, so how can i enable it back by myself? @neSpecc

**Comment by gohabereg** [comment]
Hi there!
Tool's UI sometimes consists of non-editable elements, so we shouldn't show inline toolbar for them. Could you describe a use-case for behaviour you need?

**Comment by umutbozdag** [comment]
> Hi there!
> Tool's UI sometimes consists of non-editable elements, so we shouldn't show inline toolbar for them. Could you describe a use-case for behaviour you need?

Hi, for example i want to make editor read-only by setting all contenteditable elements to false and then i want to let users use the inline toolbar to make annotations with marker tool. @gohabereg

**Comment by gohabereg** [comment]
Readonly mode means you can't edit anything.

Great case though! We are going to introduce comments in the future (not near as it requires lots of other features to be implemented). So annotations are just like comments.

At the moment you can create an external tool to annotate content on the page I guess, don't see any other options.
