### ISSUE TITLE
Unexpected token on some Plugins

### ISSUE THREAD

**Issue by willard** [codex-team/editor.js#1242]
throwing some error on some plugin like code, list and image

Bundler : ParcelJS

Expected behavior:

Screenshots:

![Screen Shot 2020-07-20 at 3 19 20 PM](https://user-images.githubusercontent.com/544756/87977270-7d0e0080-ca9c-11ea-95df-098dcbc9f939.png)

Device, Browser, OS: MacOS, 

Editor.js version:2.18.0

Plugins you use with their versions: code, list and image

**Comment by neSpecc** [comment]
Looks like there is a List tool on your screen, so this issue would better to open in a List repo.

**Comment by neSpecc** [comment]
Also, you can use Webpack to build the sources

**Comment by harwee** [comment]
@willard were you able to solve this?

**Comment by willard** [comment]
> @willard were you able to solve this?

no.. i think i will try webpack or rollup instead of parcel

**Comment by jere-co** [comment]
Experiencing this as well with Parcel.

**Comment by Pitbi** [comment]
I had the same problem. It works with Parcel 2.0.0-nightly.475
