### ISSUE TITLE
Increase content block width

### ISSUE THREAD

**Issue by shreeharsha-factly** [codex-team/editor.js#1243]
How can I increase content block width?

**Comment by stephenrichard** [comment]
Hello,

The easiest / quickest way to increase the content block width is to override this default style with your custom CSS : 
```language:css
.ce-block__content {
    position: relative;
    max-width: 650px; // Default is 650px. Increase the max-width as it fit your needs
    margin: 0 auto;
    -webkit-transition: background-color .15s ease;
    transition: background-color .15s ease;
}
```

Hope it helps.

**Comment by shreeharsha-factly** [comment]
@stephenrichard thanks for your reply. It worked after overriding .ce-block__content and .ce-toolbar__content

**Comment by literakl** [comment]
I use:
```
    max-width: 98%;
```
