### ISSUE TITLE
File/Image Manager what is the best way in Editor.JS?

### ISSUE THREAD

**Issue by Karstenve** [codex-team/editor.js#1246]
Hi everyone! I'm currently working on a custom CMS and for the admin panel we are using EditorJS. It's an awesome editor but there is some stuff that's currently missing. We would like to incorporate that ourselves.

The main thing we want in EditorJS is have a image/file manager that makes it easy for a user to find an image they've used before and in turn means less images will be uploaded to the server. What I need to know is what the best way would be to go about this. Could I for example incorporate it as a plugin or maybe make a seperate file browser outside of the editor itself? We are currently using the image plugin. 

I'd also like to know if anyone has ever made a poll plugin. I've seen it mentioned on the website but couldn't find it on Github.

Thank you in advance!

**Comment by gohabereg** [comment]
Hi @Karstenve,

For the image manager you can extend image plugin functionality (or make it from scratch). So it is up to you how to implement it. I would suggest showing available images once block is rendered, or show images in popup.
You tool can add any UI you want inside it's block and outside as well (with direct appends to the document body or other elements).

As for poll plugins, we had some plans to implement it. However, it requires complex backend which each user should implement by his own.

**Comment by neSpecc** [comment]
Answered
