### ISSUE TITLE
Font and font color?

### ISSUE THREAD

**Issue by TechOverflow** [codex-team/editor.js#1247]
Hi all,
editor.js is a beautiful library, but I can't for the life of me find a way to enable changing the font or color of the selected text. Am I missing something? 

Thanks!

**Comment by gohabereg** [comment]
Hi @TechOverflow!
Core of the Editor.js provide only basic tools (bold, italic, link). If you want to be able to change font and color of the selected text you need to add custom Inline Tool that implements such behaviour.

There is a tool for changing text color by @RogierW — https://github.com/RogierW/editor-js-text-color
