### ISSUE TITLE
How to get rid of "I18n: section was not found in current dictionary" message in console

### ISSUE THREAD

**Issue by akash-mitra** [codex-team/editor.js#1269]
Is there a way I can get rid of "**I18n: section was not found in current dictionary**" message that is flooding my browser console?

**I do not need i18n support** and I am not sure if there is any way to stop these messages to come up.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/3336242/89757571-3bf79200-db18-11ea-9433-34a9f788ffae.png">

**Comment by gohabereg** [comment]
Hi @akash-mitra 
You can disable console output using log level property — https://editorjs.io/configuration#log-level

However, it doesn't seem ok, @neSpecc could you have a look please.

**Comment by neSpecc** [comment]
While implementing the I18n API I thought that this log will be useful, but it's not. I'll remove this log in the next release.
