### ISSUE TITLE
Linebreak in a table cell (custom table plugin)

### ISSUE THREAD

**Issue by yafim** [codex-team/editor.js#1271]
I've created my own table plugin, a simple html table.
When I'm in a specific table cell - I want to press 'Enter' and add a linebreak to this cell.

What actually happens is that it creates a new block under my table component.
BTW it works (new line break in a cell) when I'm pressing SHIFT+ENTER.

Tried to override the keydown event and prevent default behavior of the enter in a cell with no success.

any help would be appreciated,
Thanks

**Comment by BartekCK** [comment]
I have the same problem, Do you find solution ?

**Comment by yafim** [comment]
> I have the same problem, Do you find solution ?

No, still waiting though

**Comment by neSpecc** [comment]
You can specify the [enableLineBreaks](https://editorjs.io/tools-api#enablelinebreaks) as `true` for your tools.

```js
/**
 * Code Tool for the Editor.js allows to include code examples in your articles.
 */
class CodeTool {
  /**
   * Allow pressing Enter inside the CodeTool textarea
   *
   * @returns {boolean}
   * @public
   */
  static get enableLineBreaks() {
    return true;
  }

  // ... tool's code
}
```
