### ISSUE TITLE
is possible to add the editor as a overlay to PDF

### ISSUE THREAD

**Issue by Nilanth** [codex-team/editor.js#1276]
I need to add text to an existing PDF, so is possible to use editor.js as an overlay editor to the PDF and add text and other properties to it.

**Comment by gohabereg** [comment]
Hi @Nilanth 
You can render Editor.js JSON output to PDF and attach it to existing PDF file as new pages. It should be pretty simple for most cases.

However, if you need to edit existing PDF, it would be a challenge to convert it to Editor.js format.

**Comment by neSpecc** [comment]
Answered
