### ISSUE TITLE
Handle the fork complety from github with a fixed build script 💡

### ISSUE THREAD

**Issue by sos-productions** [codex-team/editor.js#1283]
Hello all,

I noticed that github fork is not complete , paragraph is empty and make the build crash this is a github issue
   TS2307: Cannot find module '../tools/paragraph/dist/bundle'.

I suggest either
 inform that is required because paragraph is the default tool and install it manually from editor.js source cloned tree
$ git clone https://github.com/editor-js/paragraph.git src/components/tools/paragraph
                          or 
or better update package.json to fech it if missing
                          or
include the sources with editor.js

**Comment by sos-productions** [comment]
I udated the build_dev and build help script adding:

#plugin Paragraph is mandantory
#
DIR="src/components/tools/paragraph"
if ! [ "$(ls -A $DIR)" ]; then
     git clone https://github.com/editor-js/paragraph.git src/components/tools/paragraph
fi

**Comment by hata6502** [comment]
https://www.chatwork.com/#!rid139624421

Editor.js uses git sub modules to `src/components/tools/paragraph` and more. 
It can be resolved by using `yarn`: 

```
yarn install
yarn pull_tools
```

**Comment by sos-productions** [comment]
hata-さん, ありがとう !

**Comment by neSpecc** [comment]
Resolved

**Comment by sos-productions** [comment]
> https://www.chatwork.com/#!rid139624421
> 
Aniki, it requires permissions to join the chat - I searched by id it fails. 
I created an account there https://chatwork.com/sos-productions

**Comment by hata6502** [comment]
@sos-productions 
Sorry! I mistaked url. 
correct: https://editorjs.io/core-development
