### ISSUE TITLE
Can't save data to an array with api.saver.save()❓

### ISSUE THREAD

**Issue by stejul** [codex-team/editor.js#1289]
**Question**

Is there a way to get the saved data into an array? when using the saver api it doesn't seem to work correctly?

```javascript
getContent() {
    const a = []
    const testContent = this.api.saver.save().then((savedData) => {
        a["content"] = savedData;
    });

    console.log(a["content"]);
} 
```
This is what I get in the console.
<img width="138" alt="image" src="https://user-images.githubusercontent.com/7622701/91598483-ac4e4200-e965-11ea-80eb-7a06bb242c4d.png">

**Context**
I'm trying to build a markdown plugin and i need the blocks data

**Comments**

Is there another way to retrieve the saved blocks?

**Comment by gohabereg** [comment]
Not sure I got the question.

In your example `console.log` is executed before data is saved as `save` method is async.

So the correct code is:
```
async getContent() {
  const a = {};

  const data = await this.api.saver.save();

  a['content'] = data;

  console.log(a.content);
}

```

Still not understand what do you mean "get saved data into an array". Save method returns an object which has `blocks` property. https://editorjs.io/saving-data#output-data-format

**Comment by stejul** [comment]
Actually that's what I was looking for. Thank you!
