### ISSUE TITLE
How to add borderline and static tool bar with content space

### ISSUE THREAD

**Issue by ajoysinha** [codex-team/editor.js#1294]
I am very new [ Started Only two days back ] to integrate editor.js [ Best Editor for it's unique features ] with my application. I am able to implement the basic editor with my angular 10 application, without issue. but I am looking to have a outline/ borderline on editor section [ where content will be edited ] and also like to have a static tool bar at the top of my content space. If anybody can help me with any sample of these two , that will be great help for a newbee.

1. Border line with content space
2. Static toolbar with content space.

**Comment by neSpecc** [comment]
You can add a border on your side as well as other styles overriding.

What about the second question — you can implement it by yourself using the API. It has been discussed [here](https://github.com/codex-team/editor.js/issues/1193)

**Comment by ajoysinha** [comment]
Hi, I am trying to add border to the content area only .. but seems it is tricky.  My expectation is in images as below

I am looking to put a border around content area only. But it seems border [ Black one ] applied to outer most area. 

Any suggestion is welcome 

![editor js](https://user-images.githubusercontent.com/3907209/92128913-84a52100-ee20-11ea-8e0c-163a1c53f200.png)
