### ISSUE TITLE
Odd padding-bottom: 300px; added with editor div. 

### ISSUE THREAD

**Issue by ajoysinha** [codex-team/editor.js#1300]
When implementing editor.js i have found that **padding-bottom: 300px;** added to a div and there is no way to override the same. Hence my editor space is unnecessary big. i need to reduce the height of the same.

If possible, let me know some way to reduce the padding-buttom area.  also surprised to see the same a inline style not in class.

Screenshot attachaed
![editorjs-error](https://user-images.githubusercontent.com/3907209/92236159-7c0d2300-eed2-11ea-95f2-8ec955be39e9.png)

**Comment by neSpecc** [comment]
This padding allows creating of a new block at any time by clicking at the bottom area, under all existed blocks.

You can disable it by specifying `minHeight: 0` at Editor Config.
