### ISSUE TITLE
Optional loader 💡

### ISSUE THREAD

**Issue by f1nality** [codex-team/editor.js#1305]
1. Describe a problem.

- When making editor turn on/off functionality editor block height is jumping when you add/remove editor to DOM element
- When page is initially loaded editor block height it jumping

2. Describe the solution you'd like. Mockups are welcome.

Add optional config parameter `loader: false` which will init editor synchronous without displaying loader

3. Are there any alternatives?

**Comment by xis** [comment]
are there any updates about this? editor height is still jumping.

**Comment by alexbrower** [comment]
I was able to work around the same issue (jumpy editor height) with this CSS:
```
.cdx-loader{
    display: none !important;
}
```

**Comment by nikita-ks** [comment]
```
  .cdxcodex-editor__loader {
    display: none !important;
  }
```

**Comment by nikita-ks** [comment]
**"@editorjs/editorjs": "^2.21.0",**

```
 .codex-editor__loader {
    display: none !important;
  }
```

**Comment by f1nality** [comment]
These are half-way solutions, DOM elements are jumping while text blocks are rendered.
Ability to render synchronously would be perfect
