### ISSUE TITLE
I18n API documentation example does not work

### ISSUE THREAD

**Issue by svenpl** [codex-team/editor.js#1327]
I followed the I18n example in the [I18n API section](https://editorjs.io/i18n-api) of the documention but I could not get it to work until I noticed the difference to the example of the [Base Concepts - Internationalization section](https://editorjs.io/i18n) which then works.

The difference is the missing `messages` key in the I18n API example.

The example should be:

```js
new Editorjs({
  // ...
  tools: {
    image: SimpleImage,
  },
  i18n: {
    messages: {
      tools: {
        image: {
          'Upload an image': 'Загрузить изображение',
        }
      }
    }
  }
})
```

**Comment by dsheyp** [comment]
I tried both above ways, with and without 'messages', and I couldn't make it work for me. Any ideas on this?

**Comment by dsheyp** [comment]
I found that in `/src/components/core.ts` on line 211 the i18n config is reset by doing this: `this.config.i18n = {};` commenting this line fixes the issues.

**Comment by ErriourMe** [comment]
Still doesn't work (2.22.0)...

**Comment by robonetphy** [comment]
Hey, guys sorry for the late reply,
it is due to the documentation error please use the below configuration as a reference example:


    i18n: {
          /**
           * @type {I18nDictionary}
           */
          messages: {
            /**
             * Other below: translation of different UI components of the editor.js core
             */
            ui: {
              "blockTunes": {
                "toggler": {
                  "Click to tune": "Нажмите, чтобы настроить",
                  "or drag to move": "или перетащите"
                },
              },
              "inlineToolbar": {
                "converter": {
                  "Convert to": "Конвертировать в"
                }
              },
              "toolbar": {
                "toolbox": {
                  "Add": "Добавить"
                }
              }
            },
  
            /**
             * Section for translation Tool Names: both block and inline tools
             */
            toolNames: {
              "Text": "Параграф",
              "Heading": "Заголовок",
              "List": "Список",
              "Warning": "Примечание",
              "Checklist": "Чеклист",
              "Quote": "Цитата",
              "Code": "Код",
              "Delimiter": "Разделитель",
              "Raw HTML": "HTML-фрагмент",
              "Table": "Таблица",
              "Link": "Ссылка",
              "Marker": "Маркер",
              "Bold": "Полужирный",
              "Italic": "Курсив",
              "InlineCode": "Моноширинный",
            },
  
            /**
             * Section for passing translations to the external tools classes
             */
            tools: {
              /**
               * Each subsection is the i18n dictionary that will be passed to the corresponded plugin
               * The name of a plugin should be equal the name you specify in the 'tool' section for that plugin
               */
              "warning": { // <-- 'Warning' tool will accept this dictionary section
                "Title": "Название",
                "Message": "Сообщение",
              },
  
              /**
               * Link is the internal Inline Tool
               */
              "link": {
                "Add a link": "Вставьте ссылку"
              },
              /**
               * The "stub" is an internal block tool, used to fit blocks that does not have the corresponded plugin
               */
              "stub": {
                'The block can not be displayed correctly.': 'Блок не может быть отображен'
              }
            },
  
            /**
             * Section allows to translate Block Tunes
             */
  
            blockTunes: {
              /**
               * Each subsection is the i18n dictionary that will be passed to the corresponded Block Tune plugin
               * The name of a plugin should be equal the name you specify in the 'tunes' section for that plugin
               *
               * Also, there are few internal block tunes: "delete", "moveUp" and "moveDown"
               */
              "deleteTune": {
                "Delete": "Удалить"
              },
              "moveUpTune": {
                "Move up": "Переместить вверх"
              },
              "moveDownTune": {
                "Move down": "Переместить вниз"
              }
            },
          }
        },
        
we will update soon same on editor.js.

**Comment by neSpecc** [comment]
Thanks @svenpl @robonetphy . I've updated the doc for I18n API. Please, check.

**Comment by ErriourMe** [comment]
@robonetphy It still doesn't work with "tools" section exactly.

**Comment by robonetphy** [comment]
@ErriourRU Please check this PR #1711 for fix
