### ISSUE TITLE
How to add ID for per block in OutputBlockData

### ISSUE THREAD

**Issue by dnstylish** [codex-team/editor.js#1331]
Hi i am try add id for block  in OutputBlockData like

`{
type: type,
data: data,
id: id here
}`
How to do that and when i update the content of the block, the id will not be lost

**Comment by hata6502** [comment]
https://github.com/codex-team/editor.js/pull/1333

**Comment by talyguryn** [comment]
resolved in [2.21.0](https://github.com/codex-team/editor.js/blob/next/docs/CHANGELOG.md#2210)
