### ISSUE TITLE
[Bug] onChange can't be dispatched after onChange callback throws an exception

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1339]
Describe a bug.

Steps to reproduce:
1. Implement onChange callback that throws an exception. 
```
onChange: () => {
  throw new Error();
}
```

2. Modify anywhere and dispatch onChange. 

3. Throws an exception. 

4. onChange can't be dispatched next time.  

Expected behavior:
onChange is dispatched after onChange callback throws an exception

Editor.js version: 2.18.0

It seems that modificationObserver is disabled after onChange callback throws an exception. 
It can be resolved by using try {} finally {} sentence.

**Comment by neSpecc** [comment]
I've followed these steps and couldn't reproduce a problem: error triggered in every changing 
<img width="812" alt="image" src="https://user-images.githubusercontent.com/3684889/95231117-6b223b00-080b-11eb-9001-d4609fecca5b.png">

**Comment by gohabereg** [comment]
Error should be the save method to reproduce
