### ISSUE TITLE
retrieve block and cursor position

### ISSUE THREAD

**Issue by CavalcanteLeo** [codex-team/editor.js#1346]
Hello guys,

I need help with editor.js

Imagine the following scenario, on my page I have the editor.js on the right and a bunch of buttons on the right side of the screen.

The buttons are a collection of phrases, and when click on it, the phrase must be inserted in the editor.js

However, it must be inserted where the cursor was before losing focus, considering it to be anywhere in the editor.js, Example, can be in the first, second or last block, and within a specific block, the cursor can be in the beginning, middle or end of the sentence.

How can I retrieve the block and cursor position to insert the new phrase?

**Comment by sosie-js** [comment]
To insert a text at the cursor position one way is
``js
//see http://stackoverflow.com/a/25943182
         function insertHTML(newElement) {
            var sel, range;
            if (window.getSelection && (sel = window.getSelection()).rangeCount) {
                range = sel.getRangeAt(0);
                range.collapse(true);
                range.insertNode(newElement);

                // Move the caret immediately after the inserted span
                range.setStartAfter(newElement);
                range.collapse(true);
                sel.removeAllRanges();
                sel.addRange(range);
            }
        }
        
        var bunny=document.createTextNode("Bunny")
        //inject "Bunny" at the position of the cursor
        insertHTML(bunny);
``

**Comment by neSpecc** [comment]
Answered

**Comment by Remixrty** [comment]
doesn't work in safari. 
window.getSelection().rangeCount returns 0, because it immediately loses caret position
