### ISSUE TITLE
Add Tweet embed feature in the editor💡

### ISSUE THREAD

**Issue by wayne9499** [codex-team/editor.js#1353]
1. By copying the URL of the tweet and pasting it to our tweet module will embed the tweet in the editor.

2. Using Twitter's api, i think this feature would be easy to implement.

❣ EditorJS

**Comment by neSpecc** [comment]
You can use the [Embed Tool](https://github.com/editor-js/embed) or create a Tool for Twitter

**Comment by kpnigalye** [comment]
@neSpecc how does embed work in the editor? I tried adding it to toolbar but still not working.
