### ISSUE TITLE
[Issue:Discussion] Read-only mode should give preview of how data is presented for every tool, not just disable all inputs.

### ISSUE THREAD

**Issue by ranemihir** [codex-team/editor.js#1354]
The newly introduced Read-only mode works perfectly fine. But when it comes to tools which accept user input through any html input tags, the inputs are only disabled instead of showing the data appropriately.

For example, the image tool provides the functionality to add a caption to the image. Right now, this caption is displayed as is inside the text input which looks a bit odd. My idea is that this caption should be displayed below the image without the text input. So, that it will look more like the preview of how the data will be displayed which will ultimately enhance the over all user experience.

This can be done every tool possible.

**Comment by Davidzhu001** [comment]
agree

**Comment by neSpecc** [comment]
I'm closing it since it is a nice recommendation for tools developers, not an editor.js issue
