### ISSUE TITLE
💡 Add clone interface to copy valid block data

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1357]
1. Describe a problem.
Currently, the copy & paste functions uses the block data by `save()` interfaces. 
This behavior makes the invalid data for some block tools. 

(ex. ) The block data having UUID
```
Original data
{
  "type": "example",
  "data": {
    "id": dd974408-7679-6e2c-d052-f343c90ea8a5
    "text": "The block data having UUID"
  }
}

↓

Pasted data
{
  "type": "example",
  "data": {
    "id": dd974408-7679-6e2c-d052-f343c90ea8a5  // This ID is duplicated
    "text": "The block data having UUID"
  }
}
```

2. Describe the solution you'd like. Mockups are welcome.
Copy & paste functions support any blocks by adding `clone()` interface. 
If `clone()` is not implemented to the block tool, uses `save()` by default. 
So this feature causes no breaking changes. 

```
Original data
{
  "type": "example",
  "data": {
    "id": dd974408-7679-6e2c-d052-f343c90ea8a5
    "text": "The block data having UUID"
  }
}

↓

Pasted data
{
  "type": "example",
  "data": {
    "id": a9374cf2-373b-83dd-749e-55f3947120bb  // This ID was generated by clone()
    "text": "The block data having UUID"
  }
}
```

**Comment by hata6502** [comment]
@neSpecc 
Hello!
Would you like this feature?
I think it is a common feature, and causes no breaking changes.

**Comment by hata6502** [comment]
Umm... the UUIDs are duplicated when paste block multiple times (even using `clone` interface). 
So, the UUIDs should be regenerated at paste process. 
The `clone()` idea is invalid to resolve UUID problem.

**Comment by hata6502** [comment]
To resolve UUID problem, 
`onBlockPasted` interface is needed like `onPasted`. 
https://editorjs.io/tools-api#onpaste

**Comment by natsumework** [comment]
How can I deal with this problem?
It seems like clone interface not released yet.

**Comment by natsumework** [comment]
@neSpecc Will this feature be released?
