### ISSUE TITLE
[Bug]Hitting backspace key merges / deletes block if block has no 'merge' method

### ISSUE THREAD

**Issue by dsheyp** [codex-team/editor.js#1361]
Steps to reproduce:
1. Add two blocks of the same type (of a block type which has no merge method)
2. edit second block, put caret in first input at position 0, hit backspace key
3. the second block disapears

Expected behavior:
nothing should happen and the second block should still be there

Screenshots:
none

Device, Browser, OS:
latest Chrome, Win 10

Editor.js version:
2.18.0

Plugins you use with their versions:
Custom tool (under development).

Suggested solution:

in `/src/components/block/index.ts` on line 361 add `get`

```
  public mergeable(): boolean {
    return typeof this.tool.merge === 'function';
  }
```
```
  public get mergeable(): boolean {
    return typeof this.tool.merge === 'function';
  }
```
this solution fixes the issue for me.

**Comment by neSpecc** [comment]
Duplicate https://github.com/codex-team/editor.js/issues/1415
Resolved by https://github.com/codex-team/editor.js/pull/1422
Will be shipped in 2.19.1
