### ISSUE TITLE
Editor.render is not working

### ISSUE THREAD

**Issue by apaly** [codex-team/editor.js#1362]
I want to reload editorjs with new data after initialisation but I got this error: "Uncaught (in promise) TypeError: Cannot read property 'map' of undefined javascript". The data I passed in is:
{
    "time" : 1550476186479,
    "blocks" : [
        {
            "type" : "paragraph",
            "data" : {
                "text" : "The example of text that was written in <b>one of popular</b> text editors."
            }
        },
        {
            "type" : "header",
            "data" : {
                "text" : "With the header of course"            }
        },
        {
            "type" : "paragraph",
            "data" : {
                "text" : "So what do we have?"
            }
        }
    ],
    "version" : "2.18.0"
}
Steps to reproduce:
1. Pass in the data above when editorjs is initialized: editor = new Editorjs
2. Paste the data in a textarea on the same page as Editorjs.
3. Get the data from the textarea : textarea.textContent
4. Pass the data into render(): editor.clear(); editor.render(data);

Expected behaviour:
Editorjs should be cleared and reloaded with the data passed into editor.render().

Device, Browser, OS:
PC, Windows 10, Chrome 86

Editor.js version:
2.18.0

Plugins you use with their versions:
- htmlblock - own extension of Raw Html
- header
- list
- checklist
- warning
- underline
- delimiter

I would appreciate help with this because this issue has stalled my work.
Thank you.

**Comment by paperbun** [comment]
Hi,

I am able to render the same data without any error.

editor = new EditorJS({
            holder: 'editorjs',
            onChange: autoSave,
            tools: {
                paragraph: {
                    config: { placeholder: 'Tell your story...' }
                },
                image: {
                    class: ImageTool,
                    config: {
                        endpoints: {
                            byFile: 'http://localhost:8008/uploadFile', // Your backend file uploader endpoint
                            byUrl: 'http://localhost:8008/fetchUrl', // Your endpoint that provides uploading by Url
                        }
                    }
                },
                header: {
                    class: Header,
                    inlineToolbar: true,
                    config: {
                        placeholder: 'Header name...',
                        levels: [2],
                        defaultLevel: 2
                    }
                },
                linkTool: {
                    class: LinkTool,
                    config: {
                        endpoint: 'http://localhost:8008/fetchUrl', // Your backend endpoint for url data fetching
                    }
                },
                list: {
                    class: List,
                    inlineToolbar: true,
                },
                gist: Gist
            },
        });
        editor.isReady
            .then(() => {
                console.log('Editor.js is ready to work!')
                //draftBody = json.stringify()
                editor.render({
                    "time" : 1550476186479,
                    "blocks" : [
                    {
                    "type" : "paragraph",
                    "data" : {
                    "text" : "The example of text that was written in one of popular text editors."
                    }
                    },
                    {
                    "type" : "header",
                    "data" : {
                    "text" : "With the header of course" }
                    },
                    {
                    "type" : "paragraph",
                    "data" : {
                    "text" : "So what do we have?"
                    }
                    }
                    ],
                    "version" : "2.18.0"
                    })

                /** Do anything you need after editor initialization */
            })
            .catch((reason) => {
                console.log(`Editor.js initialization failed because of ${reason}`)
            });

**Comment by paperbun** [comment]
If you are passing the JSON Object, pls try JSON.parse( ) as shown below.

editor.render(JSON.parse(draftBody))

**Comment by apaly** [comment]
Hi,
Thanks for your reply. I will try it out.
