### ISSUE TITLE
💡 can we add an option for dev/prod to hide the "I'm ready! .." and other unnecessary logs 

### ISSUE THREAD

**Issue by abdessamadelhamdany** [codex-team/editor.js#1379]
1. Describe a problem.
While I'm using the console to get any important feedback that affect my application, 
I need it to be clear, do its easy to read any important logs.

2. Describe the solution you'd like. Mockups are welcome.
I would love to have an option to disable the logs, that are not warnings/errors

3. Are there any alternatives?
I think the alternative correspond to deleting the comment from the source code, 
which is not good idea.

**Comment by hata6502** [comment]
Please use `logLevel` 🙏
https://editorjs.io/configuration#log-level
https://github.com/codex-team/editor.js/issues/962
