### ISSUE TITLE
Focus active item of Block Settings by opening it from keyboard

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#1383]
1. Describe the problem.

When I'm opening a Block Settings by Tab keydown, they are opening with the first item focused. 

<img width="813" alt="image" src="https://user-images.githubusercontent.com/3684889/96158445-33f30e80-0f1c-11eb-9425-e74191919041.png">

2. Describe the solution you'd like. Mockups are welcome.

It would be nice if the active item will be focused by default

**Comment by kaaaaaaaaaaai** [comment]
👍

**Comment by nbrown1337** [comment]
Hi! I'm one of the mentors for a nonprofit program called [CodeDay Init](https://labs.codeday.org/), and we partner with colleges to help CS students make their first open-source contribution.

We'll claim this issue for now and a group of students will be on it soon with mentorship! Thanks!

**Comment by gklake** [comment]
CodeDay Micro-Internship members [Wicaksa](https://github.com/wicaksa), [Hamzah](https://github.com/wv5246), and I collaborated on this pull request.
