### ISSUE TITLE
Prevent new block when user press Enter

### ISSUE THREAD

**Issue by CavalcanteLeo** [codex-team/editor.js#1387]
I have to prevent when the users press Enter, and instead of create a new paragraph, it should just return a break line `<br />`. But when the users type enter only

The enter key should be equal Shift+Enter

Here's my editor:
https://staging.leorad.com.br/laudador/63

There are a bunch of pre set sentences there. If the user wants to improve that, they can continue writing, but when the user types enter, it must continue in the same block, it can not create a new block.

How can I do that?

Something around this class

https://github.com/codex-team/editor.js/blob/43032ebaac6a8b9a67c9bf2ada5adc0f8592d546/src/components/modules/blockEvents.ts#L208

By using 
```js
  static get enableLineBreaks() {
    return true
  }
```
It continues in the same block, but it creates extra divs inside my current block, wrapping the sentence by divs, and i need to just add `<br />` 

`Press Enter Key` should work exactly like when `press Shift+Enter Keys`

**Comment by Gbuomprisco** [comment]
Following, have exactly the same need

**Comment by CavalcanteLeo** [comment]
please guys, @khaydarov @gohabereg @neSpecc @talyguryn

i really need it

**Comment by gohabereg** [comment]
Hey @CavalcanteLeo 
If you enable line breaks, this behaviour is handled by browser. As browsers are inconsistent you get different results. There is no way to handle this in the core at the moment, so you can add your own listeners on enter press in your tool and manage this behaviour on your own

**Comment by neSpecc** [comment]
Answered

**Comment by CavalcanteLeo** [comment]
actually, no, it's not answered. 
This behavior is not handled by browsers, shift+enter does not create extra DIV element.

I'm trying to get the same behavior of `static get enableLineBreaks() { return true }` with `shit + Enter`

**Comment by CavalcanteLeo** [comment]
@neSpecc could you please, reopen, since there is no answer?
Or should I create a new issue?

**Comment by tknappra** [comment]
@neSpecc @gohabereg I feel as tough the answer here is a bit open ended,
> you can add your own listeners on enter press in your tool and manage this behaviour on your own

Can you show, or at least guide in the right direction, how one might actually go about implementing that in the tool?

I think that anybody reading this can understand the logic/idea behind that as it seems to make a lot of sense, but I don't think anyone looking at this can easily connect the dots in order to implement it into editor.js like you guys can.

PS
Amazing library btw! I just found it today, and Editor.js looks really impressive so far!

Thanks!
Tom

**Comment by Oyshoboy** [comment]
kindly landed here for update
