### ISSUE TITLE
there are many plugins not supporting readoly💡

### ISSUE THREAD

**Issue by Davidzhu001** [codex-team/editor.js#1394]
1. if a plugin is not set read only, editorjs is not smart enough to do the ones which set read only part. 
can anyone make it support as many as it already supported?

**Comment by neSpecc** [comment]
Editor.js won't be initialised in Read-Only if some of Tools don't support it. That's because Editor ensures that user can't change anything while this mode is activated.

Ask to author of Tools to add the support of read-only or don't use this tools in the read-only mode.
