### ISSUE TITLE
Adding custom variable to block

### ISSUE THREAD

**Issue by jamesmcarthur115555** [codex-team/editor.js#1395]
Hi 

Love this project 

Question - I really want to be able to tag blocks with a source ID / version - basically some variable in the java script

I want to be able to determine if some content ( group of blocks ) was added by a person or a system from a source - a reference ID / version / hash

I cant work out how to add variables and they get stripped on save.   Does anyone have an idea how we might do it without modifying the project

**Comment by vujicP** [comment]
Could a base class be extended to achieve this feature? Any hint in this direction is appreciated.

**Comment by neSpecc** [comment]
Yes, it is a duplicate. Follow issues above.
