### ISSUE TITLE
[Bug] Pasted blocks are not sanitized, It may occurs XSS attack!

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1396]
Describe a bug.
Pasted blocks are not sanitized, It may occurs XSS attack!

Steps to reproduce:
1. Copy blocks includes `<b onclick="alert('XSS test')">Click me!</b>`
2. Paste blocks. 
3. Click it. 

Please see the following GIF animation. 

Expected behavior:
Pasted blocks should be sanitized. 

Screenshots:
![ezgif com-gif-maker (7)](https://user-images.githubusercontent.com/7702653/97069931-c4ada680-160e-11eb-8eb2-19768df923b6.gif)

Editor.js version: v2.19.0

**Comment by gurshafriri** [comment]
👋 @gohabereg @neSpecc did you have a chance to follow up on this issue? 
We (at [snyk](www.snyk.io)) would like to add it to our vulnerability db if it is valid.

**Comment by neSpecc** [comment]
Actually, it will be sanitised on saving, so this is not a real vulnerability. But we will think about it.

**Comment by hata6502** [comment]
@neSpecc Thank you! I'll fix it and send PR.
