### ISSUE TITLE
[Bug] Remove Shortcut listners and codex-tooltip when destroy()

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1398]
Since forget to release Shortcut listners and codex-tooltip when destroy(), 
they may occur performance issue with long time using in same browser window. 

Expected behavior:
Release Shortcut listners and codex-tooltip by destroy()

Editor.js version: v2.19.0

**Comment by UmangRobro** [comment]
@hata6502 So Can we close This issue?

**Comment by robonetphy** [comment]
@hata6502  So Can we close this issue?
