### ISSUE TITLE
[Bug] TypeError: Cannot read property 'deactivate' of null

### ISSUE THREAD

**Issue by mochicode** [codex-team/editor.js#1400]
I am trying to use editor.js with react hooks and every time I am trying to destroy the editor I get the following error:
`TypeError: Cannot read property 'deactivate' of null`

From what I can see, when you call the `destroy` method on the editor instance the `destroy` methods of `BlockSettings` and `Toolbox` are being called twice.
1.  `src/codex.ts`: the first call to destroy happens in here
2. `src/components/modules/toolbar/index.ts`: the second call to destroy happens here

Both `destroy` methods of `BlockSettings` and `Toolbox` are setting `this.flipper = null` after a calling `this.flipper.deactivate()` and thus the error message: `TypeError: Cannot read property 'deactivate' of null`

Steps to reproduce:
Demo App: [https://react-editor.vercel.app/](https://react-editor.vercel.app/)
Demo source code: [https://github.com/riezler-co/editorjs-demo](https://github.com/riezler-co/editorjs-demo)
The modified editorjs code: [https://github.com/riezler-co/editor.js](https://github.com/riezler-co/editor.js)

Expected behavior:
I can destroy the editor without throwing an exception

Screenshots:
[https://drive.google.com/file/d/1DMvTvP2MKnCPiOSW92tMKlGqTw1TBRHU/view?usp=sharing](https://drive.google.com/file/d/1DMvTvP2MKnCPiOSW92tMKlGqTw1TBRHU/view?usp=sharing)

Device, Browser, OS:
Version 86.0.4240.111 (Official Build) (64-bit)

Editor.js version:
2.19.0

Plugins you use with their versions:
none

**Comment by mochicode** [comment]
Related Issue: [https://github.com/codex-team/editor.js/issues/919#issuecomment-709234210](https://github.com/codex-team/editor.js/issues/919#issuecomment-709234210)

**Comment by StarAzure** [comment]
Please fix this bug - 

`Cannot read property 'deactivate' of null`

Happening here
      ```
              value: function() {
                        this.flipper.deactivate(), this.flipper = null, this.removeAllNodes()
                    }
```

**Comment by StarAzure** [comment]
Feel free to add https://dealete.com. Thanks.

**Comment by sis-dk** [comment]
Related: #1380

**Comment by sam26880** [comment]
Is there any update on this issue? I'm seeing this as well.

**Comment by lysyi3m** [comment]
Is there any updates here? it breaks core functionality, since it doesn't allow to properly destroy previously created editor instance.

**Comment by rakeshshubhu** [comment]
having the same problem here as well.
Any updates?

**Comment by rakeshshubhu** [comment]
Not sure if this is ideal but for the time being
I tried this in my react component
```js
if (instance) {
      document.querySelector(`#${holder} .codex-editor`).remove();
    }
```

**Comment by D1verGW** [comment]
Hello!
First of all - nice works! Amazing tool, I'm really like it!
But...
Any updates on this one?
I've tried to use editor with my ReactJS code, and by default I have an issue described in the topic head, it makes me suffer...

**Comment by neSpecc** [comment]
Duplicate https://github.com/codex-team/editor.js/issues/1380

**Comment by alxndr** [comment]
I see this error in v2.22.2, when testing a custom Tool in a headless environment (using [Cypress](https://www.cypress.io/)).

Using `.click({force:true})` allows the tests to pass.
