### ISSUE TITLE
ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by ratkorle** [codex-team/editor.js#1407]
Describe a bug.
In my Angular 10 Application when I run it **locally it works fine**. But when I start it on server, **SSR gives ReferenceError: Element is not defined**
I tried uninstalling and install it again (delete node modules , package-lock).
Also tried to get the HTML element via **ViewChild()** and also with **holderId**.

Steps to reproduce:
This is how EditorJS is initialized in my Application:

**blog-editor.component.html** 
`                           <div id="post-editor" #editorJs></div>
`

**blog-editor.component.ts**
```
import EditorJS from '@editorjs/editorjs';
import Header from '@editorjs/header';
import List from '@editorjs/list';
import Paragraph from '@editorjs/paragraph';
import ImageTool from '@editorjs/image';
import Embed from '@editorjs/embed';
import LinkTool from '@editorjs/link';
import CodeTool from '@editorjs/code';
import Table from '@editorjs/table';
```

```
@Component({
  selector: 'app-blog-editor',
  templateUrl: './blog-editor.component.html',
  styleUrls: ['./blog-editor.component.scss'],
})
export class BlogEditorComponent implements OnInit, OnDestroy, AfterViewInit {
 ngAfterViewInit() {
    this.SetEditor();
  }
SetEditor(): void {
    this.editor = new EditorJS({
      holder: this.el.nativeElement,
      tools: {
        header: {
          class: Header,
          config: {
            placeholder: 'Enter a header',
            levels: [2, 3, 4],
            defaultLevel: 3,
          },
        },
        paragraph: {
          class: Paragraph,
          inlineToolbar: true,
        },
        list: {
          class: List,
          inlineToolbar: true,
        },
        image: {
          class: ImageTool,
          config: {
            endpoints: {
              byFile: environment.USER_POST_SERVICE + 'post/upload/image', // Your backend file uploader endpoint
            },
          },
        },
        embed: {
          class: Embed,
          config: {
            services: {
              youtube: true,
              coub: true,
            },
          },
        },
        linkTool: {
          class: LinkTool,
          config: {
            endpoint: environment.USER_POST_SERVICE + 'post/get/meta',
          },
        },
        code: CodeTool,
        table: {
          class: Table,
          inlineToolbar: true,
          config: {
            rows: 2,
            cols: 3,
          },
        },
      },
    });
    this.showEditor = true;
  }
}

```

Screenshots:
![image](https://user-images.githubusercontent.com/33107251/97604677-0c1ca400-1a0e-11eb-8ca0-a871d12db9f6.png)

Editor.js version: "^2.17.0"

Plugins you use with their versions:
"@editorjs/code": "^2.4.1",
 "@editorjs/embed": "^2.2.1",
 "@editorjs/header": "^2.4.1",
 "@editorjs/image": "^2.3.3",
 "@editorjs/link": "^2.1.3",
 "@editorjs/list": "^1.4.0",
 "@editorjs/paragraph": "^2.6.1",
  "@editorjs/table": "^1.2.2",

**Comment by neSpecc** [comment]
Looks like this is a problem with SSR. Follow this issue https://github.com/codex-team/editor.js/issues/1036

**Comment by anhtuank7c** [comment]
If anyone still wonder how to make it work in SvelteKit. You need to disable SSR for that page or use dynamic import.

```
// src/routes/+layout.js
export const ssr = false;
```

**Comment by alexmnv** [comment]
> If anyone still wonder how to make it work in SvelteKit. You need to disable SSR for that page or use dynamic import.

:+1: 
Or you can use `svelte-editorjs` adapter: https://github.com/pablo-abc/svelte-editorjs/blob/main/src/index.ts

**Comment by anhtuank7c** [comment]
I write my own Markdown Editor in SvelteKit instead of use an existing editor at the end :)

https://github.com/codex-team/editor.js/assets/3163410/8a693c64-a937-4d9c-92ec-543a3166e335

**Comment by digitaldrreamer** [comment]
If you're looking for Svelte
This works for me (ignore the svelte 5 syntax if you need for Svelte 4):
```svelte
<script>
    import { onMount } from "svelte";

    /**
     * @type {EditorJS | null}
     */
    let editor = $state(null);

    /** @type {HTMLElement | null} */
    let editorEl = null;
    onMount(async () => {
        try {
            const { default: EditorJS } = await import('@editorjs/editorjs');
            editor = new EditorJS({
                holder: editorEl
            });
        } catch (error) {
            console.error("Failed to load EditorJS:", error);
        }
    });

    let props = $props()



</script>

<div bind:this={editorEl} class="w-full h-full {props.class}"></div>

```
Source: https://dev.to/digitaldrreamer/make-editorjs-work-in-sveltekit-ssr-34ho
