### ISSUE TITLE
[Bug]Double versioning in dist/editor.js.LICENSE.txt

### ISSUE THREAD

**Issue by sosie-js** [codex-team/editor.js#1409]
I wanted to grab the version of the editor, as it is no more in the bundle in production, we have to look as suggested to
 dist/editor.js.LICENSE.txt then I reallize there is a double promotion of editor.js

The first one good:

/*!
 * Editor.js
 * 
 * @version 2.19.0
 * 
 * @licence Apache-2.0
 * @author CodeX <https://codex.so>
 * 
 * @uses html-janitor
 * @licence Apache-2.0 (https://github.com/guardian/html-janitor/blob/master/LICENSE)
 */

the second one not as still pointing to the previous version

/**
   * Editor.js
   *
   * Short Description (눈_눈;)
   *
   * @version 2.18.0
   *
   * @license Apache-2.0
   * @author CodeX-Team <https://ifmo.su>
   */

I expected just the first so my [script loader](https://github.com/sosie-js/script-loader) will be happy during versioning coherency checks

**Comment by neSpecc** [comment]
Seems outdated. If it is still actual, I'll reopen

**Comment by neSpecc** [comment]
P.S. Your project looks interesting, nice work
