### ISSUE TITLE
[Bug] Trying to merge two blocks that don't have a `merge` method

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#1415]
In [2.18](https://github.com/codex-team/editor.js/pull/1181/files#diff-3a2e107229dbebf0e0b7e00160e7faec0cf71e6baf51872078e031789692c8b5R352-R354) release there was a mistake with adding a `public` access modifier to the `block.mergeable` getter.

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/3684889/98250749-e6048000-1f88-11eb-855b-8ce49eabcf19.png">

And now, it is a public method instead of a getter. As a result, trying to press `Backspace` between two same blocks (that don't have a `merge` method) occurs an error: 

```
Unhandled Promise Rejection: TypeError: this.tool.merge is not a function. (In 'this.tool.merge(data)', 'this.tool.merge' is undefined)
```

Steps to reproduce:
1. Go to example.html
2. Make to List blocks
3. Place the caret at the beginning of the second List
4. Press `Backspace`
5. You'll see an error

Expected behavior:

Error is not thrown.

Editor.js version:

2.19

**Comment by robonetphy** [comment]
@neSpecc 
I replace public with get it working perfectly fine on the paragraph plugin but not for list but there is no error on the console.
is that correct result?

**Comment by neSpecc** [comment]
> @neSpecc
> I replace public with get it working perfectly fine on the paragraph plugin but not for list but there is no error on the console.
> is that correct result?

open a draft pr please, and attach it
