### ISSUE TITLE
How do I refresh the data with new content?

### ISSUE THREAD

**Issue by impactvelocity** [codex-team/editor.js#1418]
Hello!

I have an editorjs instance, and I am getting new updates from the server with real time collaboration. 

When those updates come in, I want to set the editorjs instance with that new content.

I have seen people point to the render function in the block: https://editorjs.io/blocks#render

But I don't understand how I can make use that.

I would like something like editor.set(newContent) ?

Thanks!

**Comment by neSpecc** [comment]
What a problem with `blocks.render()`?

**Comment by impactvelocity** [comment]
Thanks for the reply, neSpecc!

Maybe I need a code example of how blocks.render works outside of a custom block?

let editor = new EditorJS({ ...... setup stuff ... })

-- new content comes in ...

editor.render(newContent)  ? That doesn't seem to work...

:)

**Comment by neSpecc** [comment]
> editor.render(newContent) ? That doesn't seem to work...

```js
editor.blocks.render(newContent)
// ....^^^^^^
```
