### ISSUE TITLE
Unable to save html in data blocks❓

### ISSUE THREAD

**Issue by shreeharsha-factly** [codex-team/editor.js#1425]
**Question**

Unable to save html in data blocks

**Context**

When I try to update data like

```
this.data = {
    html: "<div><p>TESTING</p></div>"
}
```
Block is updated as

```
{
 html: "TESTING"
}
```
It doesn't update whole html.

**Comment by 0xdud** [comment]
check the sanitizer tutorial

**Comment by shreeharsha-factly** [comment]
@0xdud  thanks for the reply. By setting sanitizer it worked.
