### ISSUE TITLE
Uncaught SyntaxError: Identifier 'editor' has already been declared

### ISSUE THREAD

**Issue by Aayushpatil77** [codex-team/editor.js#1429]
Editor.js is declaring variables twice 

Steps to reproduce:
1. `let editor = new EditorJS({
   onReady: () => {
      console.log('Editor.js is ready to work!')
   }
});`
2. Click on submit button

Expected behavior:
Should not declare the varibale twice

Device, Browser, OS: Windows 7

Editor.js version: latest

**Comment by neSpecc** [comment]
This is not related to Editor.js. Looks like a problem in your code.

**Comment by jabcreations** [comment]
I'm the lead developer of the JAB Creations web platform and someone came to one of the sites I manage and this error was triggered. I already have a global "editor" variable for my own internal purposes. I don't know how or why (most likely your) editor was implemented though if you're writing something third party you need to use VERY distinct variable names.
