### ISSUE TITLE
Window doesn't scroll when block selection💡

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1447]
1. Describe a problem.
Window doesn't scroll when block selection. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/7702653/100407133-f05afb00-30aa-11eb-9ecf-3141b1239d28.gif)

2. Describe the solution you'd like. Mockups are welcome.
Window scroll when block selection

**Comment by ranemihir** [comment]
I don't think such an issue exists. The window is scrolling perfectly fine.

**Comment by hata6502** [comment]
@ranemihir 
It seems this issue occurs in block selection with keyboard UP or DOWN key.

**Comment by ranemihir** [comment]
@hata6502 Then its quite expected since the editor takes control of the arrow keys and TAB button once focused.
