### ISSUE TITLE
[Bug] Tooltip Position Broken

### ISSUE THREAD

**Issue by vincenzocasu** [codex-team/editor.js#1449]
Hi, i'm using Editorjs in a Bootstrap 4 Project, my editorjs container is inserted into a bootstrap card.
So on hovering the toolbar tooltips position was not correct. Checkout the attached screen...
Is there a simple way to fix this issue?

Expected behavior: tooltip positioned correctly

Screenshots: 
![Schermata 2020-11-28 alle 12 56 41](https://user-images.githubusercontent.com/11066229/100515212-94f83e00-317a-11eb-9d94-1fb9c5a93ded.png)

Device, Browser, OS: MacOS

Editor.js version: latest

Plugins you use with their versions: 

<script src="https://cdn.jsdelivr.net/npm/@editorjs/header@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/simple-image@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/delimiter@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/list@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/checklist@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/quote@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/code@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/embed@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/table@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/link@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/warning@latest"></script>

<script src="https://cdn.jsdelivr.net/npm/@editorjs/marker@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/inline-code@latest"></script>

<script src="https://cdn.jsdelivr.net/npm/@editorjs/image@2.3.0"></script>

<script src="https://cdn.jsdelivr.net/npm/editorjs-undo@0.1.4/dist/bundle.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.0/dist/editor.min.js"></script>

**Comment by vincenzocasu** [comment]
Is there anyone who can help me fix the positioning of the tooltips?

**Comment by neSpecc** [comment]
Can you provide a demo page?

**Comment by vincenzocasu** [comment]
At moment i'm developing in my local environment... if you want we can make a remote desktop session :)

**Comment by slaveofcode** [comment]
I also got that problem, is there any way to fix it via configuration overrides? or CSS styling

**Comment by slaveofcode** [comment]
Turns out this is because my root `<HTML>` element, has default padding on CSS styles, so removing it will fix the bug. so you may check your root HTML or BODY tag if has any CSS padding (or margin) setup @vincenzocasu

**Comment by neSpecc** [comment]
Seems outdated
