### ISSUE TITLE
[Bug] onChange stop firing on 2.19.1

### ISSUE THREAD

**Issue by dimitrov-adrian** [codex-team/editor.js#1467]
After upgrade to 2.19.1 onChange event stop firing. Reverting to 2.19.0 fix event.

Editor.js version: 2.19.1

**Comment by neSpecc** [comment]
Please, provide steps to reproduce or the demo page.

**Comment by Kellaro** [comment]
Didn't happen in my case, onChange works as expected.

**Comment by dimitrov-adrian** [comment]
Don't have online demo, but this is the code how init the editor

https://github.com/dimitrov-adrian/directus-extension-editorjs-interface/blob/67a22b358f6d4828e613bd38ce4e64082cfc90ba/src/interface.vue#L87

**Comment by climba03003** [comment]
> 
> 
> Don't have online demo, but this is the code how init the editor
> 
> https://github.com/dimitrov-adrian/directus-extension-editorjs-interface/blob/67a22b358f6d4828e613bd38ce4e64082cfc90ba/src/interface.vue#L87
> 
> Edit:
> 
> It seems that the problem is in my end, the onChange doesn't works with promises anymore

You saved my time on research why my handler is not fired. I am the same as you register the `onChange` event as `Promise` and it didn't fired.
