### ISSUE TITLE
[Bug] Loaded data is not shown in editor

### ISSUE THREAD

**Issue by simpleauthority** [codex-team/editor.js#1495]
I am using EditorJS in lieu of [github.com/strapi/strapi/](strapi)'s built-in editor. This is the render function of my container component:

```javascript
render() {
    const { onChange, name, value } = this.props;
    console.log('got value in render')
    console.log(JSON.parse(value))
    
    return <EditorJS
            instanceRef={instance => this.editorInstance = instance}
            tools={EDITOR_JS_TOOLS}
            data={JSON.parse(value)}
            onChange={async () => {
                try {
                    const data = await this.editorInstance.save();
                    console.log('will save data:')
                    console.log(data)
                    onChange({ 
                        target: {
                            name,
                            value: JSON.stringify(data)
                        }
                    })
                } catch (error) {
                    console.error("Failed to save the new data")
                }
            }} 
        />;
}
```
    
Loading data works:

```json
{
  "time": 1609555019753,
  "blocks": [
    {
      "type": "paragraph",
      "data": {
        "text": "abcd"
      }
    }
  ],
  "version": "2.19.0"
}
```

Saving also works:

```json
{
  "time": 1609556122994,
  "blocks": [
    {
      "type": "paragraph",
      "data": {
        "text": "abcdefg"
      }
    }
  ],
  "version": "2.19.1"
}
```

After it's loaded, it's successfully in the `EditorJsContainer` component:
![it's alive](https://owo.whats-th.is/661Nbna.png)

But in the editor itself, I have a whole lot of nothing:
![he's dead, jim](https://owo.whats-th.is/7X8HGoc.png)

This is what's in my dev console:
![im a developer not a farmer damn it](https://owo.whats-th.is/nUFvJFF.png)

Looks like the editor first renders with no data, and then gets the data when the prop is updated. This is probably due to Strapi. If it's the issue, then I will take this upstream.

Ignore the timeout error, that is Strapi.

As for the warning about stretchBlock, I think that's a tool or something but not sure.

Steps to reproduce:
I don't really know how to repro this, but I **do** have the repository for the project here: https://github.com/simpleauthority/cms/

I call the EditorJS component here: https://github.com/simpleauthority/cms/blob/master/extensions/content-manager/admin/src/components/EditorJS/index.js#L21

If you want to try and repro in real time, I can give a **project member** access to my prod instance to see it happening. Or you can run my local repo. You need an env file and a mariadb database, which I can help you setup if it helps.

Expected behavior:
I expect the content to show.

Screenshots:
Included above.

Device, Browser, OS:
Arch Linux, Firefox 84.0.1
Editor.js version: 2.19.1 (also occurs on 2.19.0).

Plugins you use with their versions:
```
    "@editorjs/checklist": "^1.3.0",
    "@editorjs/code": "^2.6.0",
    "@editorjs/delimiter": "^1.2.0",
    "@editorjs/editorjs": "^2.19.1",
    "@editorjs/embed": "^2.4.0",
    "@editorjs/header": "^2.6.1",
    "@editorjs/image": "^2.6.0",
    "@editorjs/inline-code": "^1.3.1",
    "@editorjs/link": "^2.3.1",
    "@editorjs/list": "^1.6.1",
    "@editorjs/marker": "^1.2.2",
    "@editorjs/paragraph": "^2.8.0",
    "@editorjs/quote": "^2.4.0",
    "@editorjs/raw": "^2.3.0",
    "@editorjs/simple-image": "^1.4.0",
    "@editorjs/table": "https://github.com/alexiej/table.git",
    "@editorjs/warning": "^1.2.0",
```

Please let me know how I can start fixing this as my site is currently unusable :'(

**Comment by simpleauthority** [comment]
Ok, it's definitely something to do with the fact that for the first few hundred ms the `value` is null. This _could_ be strapi's fault but can't verify for sure. I would think it wouldn't matter and editor.js would just show the data as it does get it a few ms later, right?

I am working around this temporarily with a delayed render, when the prop is definitely there:

```javascript
componentDidMount() {
    console.log("mounted component, scheduling a delayed render...")
    setTimeout(() => {
        console.log("now rendering data in editor")

        const { value } = this.props
        
        let parsed
        try {
            parsed = JSON.parse(value)
        } catch {
            parsed = null
        }

        this.editorInstance.render(parsed)
    }, 1000)
}
```
    
This works but I'm not jazzed about it. Let me know if this can be fixed in editorjs or if I should file a report with strapi?

**Comment by sis-dk** [comment]
Hi, its because you missed an option in https://github.com/Jungwoo-An/react-editor-js

Pass enableReInitialize={true} to <EditorJS>. Its false by default and ignores props updates. This will also re-init editorjs if any other prop apart from data updates. So beware of it.

**Comment by simpleauthority** [comment]
Thanks. Seems like a strapi bug then probably. I will try to report it upstream.
