### ISSUE TITLE
MarkdownBlock: add Markdown Block support

### ISSUE THREAD

**Issue by taurenshaman** [codex-team/editor.js#1500]
[editorjs-markdown-parser in awesome-editorjs](https://github.com/stejul/editorjs-markdown-parser) is not suitable for me, so I created another one: [markdown-block](https://github.com/tunaltd/blocks-editor/tree/main/src/components/markdown-block)

demo:  
![image](https://user-images.githubusercontent.com/1308706/104009629-55dff280-51e6-11eb-9090-4801e3d32a09.png)

https://user-images.githubusercontent.com/1308706/104009770-7dcf5600-51e6-11eb-9a4b-61d760aa6623.mp4

[youtube](https://www.youtube.com/watch?v=Bsvm65tP4Bs)

**Comment by neSpecc** [comment]
There is no question, so I'll close this issue.

**Comment by HalleyGao** [comment]
https://hexx.vercel.app/
