### ISSUE TITLE
editorjs.io site not working❓

### ISSUE THREAD

**Issue by DurhamSmith** [codex-team/editor.js#1530]
Hi all,

I see that editorjs.io has been down for a few days. Any idea when it will be available again?

Will editorjs see ongoing development?

**Comment by neSpecc** [comment]
It's working fine. Can you trace the request?

**Comment by hata6502** [comment]
I experienced the server error, but it works now.

**Comment by DurhamSmith** [comment]
> It's working fine. Can you trace the request?

When trying in firefox I get:

> Hmm. We’re having trouble finding that site.
> 
> We can’t connect to the server at editorjs.io.
> 
> If that address is correct, here are three other things you can try:
> 
>     Try again later.
>     Check your network connection.
>     If you are connected but behind a firewall, check that Firefox has permission to access the Web.

When trying to ping it I get:

```
$ ping editorjs.io
 Temporary failure in name resolution
$ ping www.editorjs.io
ping: www.editorjs.io: Temporary failure in name resolution
```

**Comment by DurhamSmith** [comment]
Seems to be an issue with isp blocking the site (or vice versa). VPN solved this for me.

**Comment by neSpecc** [comment]
Ok, I'll close the issue. If someone will have problems with accessing the site, let us know.
