### ISSUE TITLE
Problem with accessing editorjs.io

### ISSUE THREAD

**Issue by CavalcanteLeo** [codex-team/editor.js#1535]
<img width="1439" alt="Captura de Tela 2021-02-13 às 03 14 18" src="https://user-images.githubusercontent.com/1735944/107843421-9b757980-6da9-11eb-8690-ff9a2e1833ec.png">

**Comment by neSpecc** [comment]
Looks like we have a problem with DNS resolving for some places. Will find a solution.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/3684889/107844669-98e54500-6de6-11eb-820a-dae6668ef4a8.png">

**Comment by kabachook** [comment]
@CavalcanteLeo For now it seems that Google DNS (`8.8.8.8`) and Cloudflare DNS (`1.1.1.1`) are working fine with our DNS provider

**Comment by romdim** [comment]
![Screen Shot 2021-02-14 at 1 25 56 PM](https://user-images.githubusercontent.com/2739250/107876763-349ab200-6ec8-11eb-99b7-a20f4a117ffa.png)

Server down for the Netherlands

**Comment by kabachook** [comment]
@romdim Can you please tell which DNS server you are using? You can do that by running `dig editorjs.io`, the server IP will be at the bottom, or `nslookup editorjs.io`.
For the fix I suggest setting your DNS server to `1.1.1.1` or `8.8.8.8`, while we troubleshoot the problem

**Comment by romdim** [comment]
![Screen Shot 2021-02-14 at 4 12 32 PM](https://user-images.githubusercontent.com/2739250/107880518-77b44f80-6edf-11eb-80cf-8558acd82192.png)

**Comment by kabachook** [comment]
Can you run the commands in my comment? This output is not relevant since this website is using Google DNS, not your system one

**Comment by romdim** [comment]
![Screen Shot 2021-02-14 at 4 24 07 PM](https://user-images.githubusercontent.com/2739250/107880742-1a210280-6ee1-11eb-9373-1d6fafeff50c.png)

**Comment by CavalcanteLeo** [comment]
In Brazil (São Paulo)

; <<>> DiG 9.10.6 <<>> editorjs.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 20388
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;editorjs.io.			IN	A

;; Query time: 5866 msec
;; SERVER: 192.168.15.1#53(192.168.15.1)
;; WHEN: Sun Feb 14 18:58:24 -03 2021
;; MSG SIZE  rcvd: 40

**Comment by romdim** [comment]
I just tried again and it works for me.

**Comment by CavalcanteLeo** [comment]
still down here

**Comment by CavalcanteLeo** [comment]
Are anywhere else the docs available?

**Comment by kabachook** [comment]
@CavalcanteLeo you can set `/etc/hosts` record to `95.213.200.245 editorjs.io` for now, while we investigate the DNS problem

**Comment by kabachook** [comment]
@CavalcanteLeo @romdim  We have changed our DNS servers, the changes will be propagated within 24 hours. Please check the site availability after 24 hours. Thanks for your help troubleshooting the issue.

**Comment by CavalcanteLeo** [comment]
My pleasure to help, I'll try later

**Comment by CavalcanteLeo** [comment]
It's live again

**Comment by neSpecc** [comment]
Resolved. Let us know if you will have troubles in the future.
