### ISSUE TITLE
[Bug] Block selection excepts the first block

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1549]
Block selection excepts the first block

Expected behavior:
All block should be selected. 

Screenshots:

https://user-images.githubusercontent.com/7702653/108519542-104a3580-730d-11eb-8650-8549ca2af740.mp4

Editor.js version: `next` branch

**Comment by talyguryn** [comment]
Cannot reproduce on 2.19.1 on Safari 14.0.3 and Chrome 88.0.4324.192

**Comment by hata6502** [comment]
@talyguryn Yes, it occurs in `next` branch.

**Comment by talyguryn** [comment]
oh, sorry. yea. 

![image](https://user-images.githubusercontent.com/15259299/109276674-5af51180-7827-11eb-8f02-63be7e1374c0.png)
