### ISSUE TITLE
[Bug] can't import LogLevels 

### ISSUE THREAD

**Issue by dudif91** [codex-team/editor.js#1576]
Hi,
I'm trying to import LogLevels like:
import EditorJS, { LogLevels } from "@editorjs/editorjs";

           editor: new EditorJS({
                holder: this.id,
                placeholder: this.placeholder,
                logLevel: LogLevels.ERROR,
                tools: {
                    header: {
                        class: Header,
                        config: {
                            placeholder: "Enter a header",
                        },
                    },
                    list: List,
                    checklist: Checklist,
                    marker: Marker,
                    image: SimpleImage,
                },
                data: this.data,
            }),

but in runtime i'm getting this error:
[Vue warn]: Error in data(): "TypeError: _editorjs_editorjs__WEBPACK_IMPORTED_MODULE_3__.LogLevels is undefined"

**Comment by GabrielGil** [comment]
Hey @dudif91, how did you solve this? I am still getting undefined when importing `LogLevels` in the latest version.

**Comment by dudif91** [comment]
@GabrielGil hey so i used it like this "logLevel: "ERROR" as LogLevels" instead of "logLevel: LogLevels.ERROR"

**Comment by GabrielGil** [comment]
Yeah, I was afraid of that. I think the issue should remain opened, since the enum is not correctly exported. Using the enum value should be valid. 

Thanks for your answer! :)

**Comment by guirip** [comment]
This bug is still live 🐛

**Comment by Getmrahul** [comment]
Faced the same issue, for now I'm re-creating the enum in my component or file and using it instead of import.

**Comment by gohanbg** [comment]
Probably not a great solution, but I'm using 
```
        editor: new EditorJS({
            holder: this.id,
            placeholder: this.placeholder,
            logLevel: "ERROR" as any,
            tools: {
                header: {
                    class: Header,
                    config: {
                        placeholder: "Enter a header",
                    },
                },
                list: List,
                checklist: Checklist,
                marker: Marker,
                image: SimpleImage,
            },
            data: this.data,
        }),```

**Comment by Chaxwell** [comment]
I'm still getting the error, I don't really understand why to be frank.
```
export 'LogLevels' (imported as 'LogLevels') was not found in '@editorjs/editorjs' (possible exports: default)
```

I've tried multiple ways of importing but to no avail.
```Javascript
import { default as EditorJS, LogLevels } from '@editorjs/editorjs'
```

**Comment by duyl328** [comment]
I tried to use it in Vue3, the version information is as follows：

``vue``: ``^3.4.29``;

``vite``: ``^5.3.1``;

``@editorjs/editorjs``: ``^2.30.5``;

``@editorjs/header``: ``^2.8.7``;

``@editorjs/list``: ``^1.10.0``;

``node``: ``>=20.14.0 <=18.8.2``;

``npm``: ``>=10.7.0 <=9.8.1``

I tried all three of these citation methods, but none of them worked.

```js
import { LogLevels } from '@editorjs/editorjs/types/configs/log-levels.js'
import { LogLevels } from '@editorjs/editorjs/types/index'
import EditorJS, { LogLevels } from '@editorjs/editorjs'
```

The error messages are：
> Failed to resolve import "@editorjs/editorjs/types/configs/log-levels.js" from "src/views/dev/vue/EditorjsDemo.vue".
> Does the file exist?


> Failed to resolve import "@editorjs/editorjs/types/index" from "src/views/dev/vue/EditorjsDemo.vue". Does the file
> exist?

> [Vue Router warn]: Unexpected error when starting the router: SyntaxError: The requested module '
> /node_modules/.vite/deps/@editorjs_editorjs.js?v=36a4c3e8' does not provide an export named 'LogLevels'

Is there something wrong with my approach?
