### ISSUE TITLE
[Bug] Clicking the bottom padding of editor is not creating empty paragraph block in Version 2.19.2

### ISSUE THREAD

**Issue by hyun-park** [codex-team/editor.js#1603]
## Describe a bug:

-  Clicking the bottom padding of editor is not creating empty paragraph block in Version 2.19.2

## Steps to reproduce:
1. Migrate Editor.js higher than `2.19.2`
2. Create a non-paragraph block end of the editor.
3. Click below the last block.
4. Does not create empty paragraph block end of the editor.

## Screenshots:
![editorjs_bug_empty_paragraph_block](https://user-images.githubusercontent.com/28282249/111728947-4bf70180-88b1-11eb-96ce-3f6a96d11fd2.gif)

## Expected behavior:
- Should create empty paragraph block end of the editor.

**Editor.js version: `2.19.2`**

**Comment by benjaminbouwyn** [comment]
Same issue  as #1588

**Comment by deepmagar** [comment]
Any update on this issue .clicking on bottom padding editor js not adding empty paragraph in latest version
