### ISSUE TITLE
💡Urgent need for real-time collaboration solutions

### ISSUE THREAD

**Issue by milu2003** [codex-team/editor.js#1612]
There is an urgent need for a real-time collaboration solution. Didn't this editor think of this problem at the beginning of its design?

Basically, all mainstream editors have good real-time collaboration solutions

https://github.com/yjs/yjs-demos

**Comment by Will-Bill** [comment]
Urgent need? From a group of open source developers? 

Maybe you should contribute.

**Comment by milu2003** [comment]
Because editorjs has no collaborative function, I reconstructed the project with prosemirror, and the experience is very good. I hope editorjs can achieve this effect as soon as possible


https://user-images.githubusercontent.com/15957433/113650278-8985c800-96c2-11eb-8b3c-2bac22c7e25a.mov

**Comment by wmonecke** [comment]
@milu2003 could you share with us how you achieved this?

**Comment by milu2003** [comment]
@wmonecke like that
