### ISSUE TITLE
editor.js is not working with angular 11 universal (SSR).it is giving error "Reference Error: window not define".IS Editor.js has a angular ssr support...?

### ISSUE THREAD

**Issue by gurdeepsinghiet** [codex-team/editor.js#1616]
Hi Codex-team,

I am using editorjs with angular Universal SSR.But,editor.js is not working with angular 11 universal (SSR).it is giving error "Reference Error: window not define".IS Editor.js has a angualr ssr support...?

it is giving following error:
ReferenceError: window is not defined
    at Object.<anonymous> (C:\Users\10059648\Desktop\ELEARNINGWEBPACKDIG\node_modules\@editorjs\header\dist\bundle.js:1:194)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)

Following is the detail of Editod.js usee in the project.
Device, Browser, OS:Window 7

Editor.js version:  "@editorjs/editorjs": "^2.19.3",

Plugins you use with their versions:
"@editorjs/embed": "^2.4.0",
    "@editorjs/header": "^2.6.1",
    "@editorjs/image": "^2.6.0",
    "@editorjs/inline-code": "^1.3.1",
    "@editorjs/link": "^2.3.1",
    "@editorjs/list": "^1.6.2",
    "@editorjs/paragraph": "^2.8.0",
    "@editorjs/quote": "^2.4.0",
    "@editorjs/simple-image": "^1.4.1",
    "@editorjs/warning": "^1.2.0",

Kindly help me to resolve the issue.

Regards,
GS

**Comment by gohabereg** [comment]
Hi @gurdeepsinghiet 
There is a third-party library for angular support: @tinynodes/ngx-editorjs
However, Editor.js is a client library so it won't work on the server side

**Comment by ronaldohoch** [comment]
Maybe this can help.
https://github.com/angular/universal/blob/master/docs/gotchas.md

**Comment by neSpecc** [comment]
Duplicate https://github.com/codex-team/editor.js/issues/1036
