### ISSUE TITLE
[Bug] v2.20.0 sanitises by default

### ISSUE THREAD

**Issue by dave5** [codex-team/editor.js#1631]
The output of v2.20.0 has html tags removed by default. This does not happen with 2.19.3.

Steps to reproduce:

1. Use `example.html` and set script for editor to `<script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>`

2. Format some of text using basic HTML:

![html 2 20 0](https://user-images.githubusercontent.com/903936/113761351-7418a880-976b-11eb-811d-807ff510fecc.png)

3. click 'editor.save()' button to generate JSON:

![json 2 20 0](https://user-images.githubusercontent.com/903936/113761496-a2968380-976b-11eb-9ca1-8a78923cd8ae.png)

4. revert script for editor to  `<script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.19.3"></script>`

5. Format some of text using basic HTML:

![html 2 19 3](https://user-images.githubusercontent.com/903936/113761627-c954ba00-976b-11eb-8b8f-396fd50ad4ac.png)

6. click 'editor.save()' button to generate JSON:

![json 2 19 3](https://user-images.githubusercontent.com/903936/113761664-d40f4f00-976b-11eb-811b-c5fd07897b30.png)

**Comment by m-sergiy26** [comment]
The same problem.

**Comment by fabian1896** [comment]
The same problem.

**Comment by gohabereg** [comment]
Will be fixed by #1574

**Comment by tuantmtb** [comment]
:'(

**Comment by kaaaaaaaaaaai** [comment]
The same problem. :::::(

**Comment by gohabereg** [comment]
Fixed in v2.20.1

**Comment by adriangzz** [comment]
This should be open again, happening on 2.22.3
