### ISSUE TITLE
[Bug] [Documentation?/dist] dist/editor.js file not located in master branch 

### ISSUE THREAD

**Issue by a2800276** [codex-team/editor.js#1643]
The Getting Started documentation section "manually load file in your project" links to a non-existent location for the editor.js file.

Steps to reproduce:
1. Go to: https://editorjs.io/getting-started#manually-load-file-to-your-project
2. Click on `editor.js`
3. -> 404

The assembled javascript files are available in the 'release/...' branches. I can't judge whether this is the intended behavior, i.e. whether the link is incorrect or whether the `dist` directory is missing in the master branch.

Newer releases don't have branches anymore and are tagged instead. The `dist` directory is there until v.2.19.1 and missing since ... I couldn't find any discussion concerning releases/branch names/dist directory  (though I didn't try toooooo hard) so I'm not sure what the intended behavior is.

**Comment by neSpecc** [comment]
Fixed, thanks.
