### ISSUE TITLE
[Bug] Unable to remove an image block

### ISSUE THREAD

**Issue by wutsi** [codex-team/editor.js#1654]
The action menu of the image is broken

Steps to reproduce:
1. Add an image to your text
2. Click on the image menu
3. Several option have disapeared from menu: UP/DOWN/Delete

Expected behavior:

Screenshots:

<img width="740" alt="Screen Shot 2021-04-14 at 8 05 35 AM" src="https://user-images.githubusercontent.com/39621277/114707817-a771af00-9cf8-11eb-8e35-c55de64da161.png">

**Comment by susana-bit** [comment]
Same happens with some other plugins with the editorjs v.2.20.1.
Version v.2.20.0 works fine.

**Comment by wutsi** [comment]
is there any plan to fix this issue?

**Comment by gohabereg** [comment]
Fixed in v2.20.2
