### ISSUE TITLE
[Bug] i18n for default tunes not working

### ISSUE THREAD

**Issue by NogaMan** [codex-team/editor.js#1661]
Describe a bug.

Steps to reproduce:
1. Follow [your tutorial on 18n](https://editorjs.io/internationalization) to translate block tunes
2. Realize it does not work

Other translations from the tutorial work well

the version I use is `2.20.2`

```
...
      blockTunes: {
        "delete": {
          "Delete": "Удалить"
        },
        "moveUp": {
          "Move up": "Переместить вверх"
        },
        "moveDown": {
          "Move down": "Переместить вниз"
        }
      },
...
```

Expected behavior: it works

Screenshots:

![Снимок экрана 2021-04-16 в 20 09 57](https://user-images.githubusercontent.com/10100542/115059826-c2f2da80-9eef-11eb-99c9-31470f455152.png)

![Снимок экрана 2021-04-16 в 20 12 47](https://user-images.githubusercontent.com/10100542/115060100-211fbd80-9ef0-11eb-9d8c-f8f8a10630c5.png)

Device, Browser, OS: macos chrome

Editor.js version: `2.20.2`

Plugins you use with their versions:

paragraph 2.8.0
header 2.6.1
image 2.6.0

**Comment by ghost** [comment]
Also image, hyperlink plugins.

**Comment by rety14** [comment]
In version 2.20.* use **deleteTune**, **moveUpTune** and **moveDownTune**.

### Example
`      blockTunes: {
        "deleteTune": {
          "Delete": "Удалить"
        },
        "moveUpTune": {
          "Move up": "Переместить вверх"
        },
        "moveDownTune": {
          "Move down": "Переместить вниз"
        }
      },`

**Comment by christoph-kluge** [comment]
@rety14 thank you - blockTunes are now translated again 👍 

Besides that it seems that all plugin translations are not working anymore.

**Comment by Broutard** [comment]
i18n API seems broken since v2.20.0.
All my translation didn't appear since the release (tested with 2.19.3 and works fine).

**Comment by stephannv** [comment]
I'm using v.2.21.0 and followed docs example (https://editorjs.io/internationalization#example) and didn't work `blockTunes`, `stub`, `Add a link`.
