### ISSUE TITLE
❓ What setup editor.js so hard?

### ISSUE THREAD

**Issue by IRediTOTO** [codex-team/editor.js#1675]
**Question**
Just found editor.js but why it so hard to use?
**Context**
I like the way editor.js work. But I just want to setup like demo on homepage of editor.js. But it not work as expect :|
Aleast give users a fast and usefull start to use.

**Comment by IRediTOTO** [comment]
With tiny ECM I just need do some steps and get basic tool avalable... 
![image](https://user-images.githubusercontent.com/15695252/116810180-70125780-ab6c-11eb-8833-f5a4f3ee8587.png)

**Comment by neSpecc** [comment]
What exactly is hard?

**Comment by neSpecc** [comment]
Closed due to inactivity
