### ISSUE TITLE
onChange shouldn't be fired when programmatically setting the editor's content

### ISSUE THREAD

**Issue by cleverplatypus** [codex-team/editor.js#1682]
**Question**

Is there a way to prevent `onChange` when programmatically set the editor's content?

**Context**

The editor emits `onChange` event when calling `editor.blocks.render(content)` which, short of setting the config's `data` property, seems to be the only way to set the editor's content after initialization. 

The problem is that if the `onChange` is used to detect whether a document needs to be saved, asynchronously loading data and using `editor.blocks.render(content)` will falsely inform the app that the content was changed.

Furthermore, even setting a previously saved content object will mutate the `time` value, making even relying on that value to assess whether the doc really changed non-viable. 

`onChange` events are generally emitted upon user interaction with a widget, as opposed to programmatic content change.

Furthermore:
-  the number of times `onChange` is called is inconsistent, so, even using the "just ignore the first time it's called" strategy doesn't work
- `onChange` is (sometimes) called even when just using the `config.data` property at creation time

Only way I found to make it work is as follows, which is not very elegant:

```js
//...
onChange: () => {
          (async () => {
            const content = await editorJS.save();
            if (JSON.stringify(content.blocks) !== JSON.stringify(model.content.blocks)) {
              model.content = content;
            }
          })();
        },
//...

**Comment by BulavinaNk** [comment]
I have the same problem, using  JSON.stringify is the worse solution, it will taken a lot of time

**Comment by jggc** [comment]
Same problem for us, there should be an option when inserting or updating a block where we can specify whether the onChange callback will be executed.

Another option would be to configure our onChange callback when we register it to specify which type of change we want to listen to.

**Comment by russelshane** [comment]
Spent hours trying to make editorjs collaborative and add auto save feature. In part of that, onChange event shouldn't be fired everytime the editor instance changes, best (but not good) solution I ever had was to artificially slow down the editorjs component.
