### ISSUE TITLE
Any support for React-Typescript projects?

### ISSUE THREAD

**Issue by aquibbaig** [codex-team/editor.js#1691]
I was wondering if there are any guides/API references for how to get started with using EditorJS for react-typescript projects? I have been facing a lot of issues with importing types(for toolbar components such as Header, List, etc.)

**Comment by spadgeaki** [comment]
Hello, I was researching the same issue for few days and these are some useful finds:
- https://github.com/hata6502/editorjs-examples
- https://github.com/Walkthroughs/editorjs-with-react
- https://github.com/Walkthroughs/editorjs-react-tool

**Comment by aquibbaig** [comment]
@spadgeaki Thanks for the references!
