### ISSUE TITLE
Accessing Paste Event at Editor Level

### ISSUE THREAD

**Issue by mhmttosun** [codex-team/editor.js#1700]
Hi,
i want to clean copied MS Word paragraf before Paste event.
Is there a beforePaste event?
how can i access paste event on editor api like onReady, onChange or editor.save()

Thanks

**Comment by danlynkew** [comment]
Also running into several issues with recent EditorJS versions which I feel I might solve by accessing the `paste` event at the Editor level. +1

**Comment by benlammers** [comment]
+1 having an issue with copy and pasting from Notion into editor and editor sanitizes the data before the block onPaste method and takes out important markdown, would like to be able to preprocess this by getting access to this onPaste event

**Comment by yankaled** [comment]
+1
