### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by chsdwyl** [codex-team/editor.js#1701]
ReferenceError: window is not defined
    at Object.<anonymous> (D:\project\editor.js\node_modules\?[4me?[24m\node_modules\?[4m@editorjs?[24m\editorjs\dist\editor.js:2:198)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1068:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:933:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:774:14)?[39m
?[90m    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)?[39m
?[90m    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)?[39m
?[90m    at async Loader.import (internal/modules/esm/loader.js:177:24)?[39m
?[90m    at async Object.loadESM (internal/process/esm_loader.js:68:5)?[39m

**Comment by chisomgbata** [comment]
Are you using nuxt js?

**Comment by pankajcomorade** [comment]
Hi @chisomgbata ,
I am using it with angular 10.0.0. When I create my SSR build(Angular Universal).It gives **Window is not defined** 

**Error Copy from console. Please see:**
**ReferenceError: window is not defined
    at Object../node_modules/@editorjs/editorjs/dist/editor.js** 
    
![image](https://user-images.githubusercontent.com/7919559/123528066-7b17dd00-d702-11eb-8aff-70f096739cfb.png)

**Comment by chisomgbata** [comment]
I have not used angular before but the concept of server side rendering is same, to fix the issue make sure you are importing editorjs to only client side, so do some research on how to render some elements or component or script in only client side

**Comment by neSpecc** [comment]
Duplicate https://github.com/codex-team/editor.js/issues/1036
