### ISSUE TITLE
[Bug] On mobile, a combination of delete / enter duplicates some text

### ISSUE THREAD

**Issue by svengau** [codex-team/editor.js#1704]
On mobile, a combination of delete / enter duplicates some text

Steps to reproduce:
1. Go to https://editorjs.io from an mobile (tested on Android).
2. delete a space
3. press enter, 
4. delete the return carriage, 
5. press enter again

Expected behavior: text should not be duplicated

Video: https://www.youtube.com/watch?v=pqdHnzmnU2w

Device, Browser, OS: Oneplus 5T, Brave, Android 10

Editor.js version: the one on the official website

**Comment by neSpecc** [comment]
Seems outdated
