### ISSUE TITLE
[Bug] Ctrl-Z doesn't work after deleting the whole content

### ISSUE THREAD

**Issue by svengau** [codex-team/editor.js#1706]
Ctrl -Z doesn't work after deleting the whole content

Steps to reproduce:

1. Go to https://editorjs.io
2. Select all content, by typing ctrl A + ctrl A, and delete it
4. Try to cancel the deletion by type ctrl Z. Nothing happens

Device, Browser, OS: Macbook Pro, Chrome 91, Catalina

Editor.js version: the one on the official website

**Comment by neSpecc** [comment]
Duplicate https://github.com/codex-team/editor.js/issues/518
