### ISSUE TITLE
[Bug] Ctrl-Z doesn't work after pressing Enter

### ISSUE THREAD

**Issue by svengau** [codex-team/editor.js#1707]
Ctrl -Z doesn't work after pressing Enter.

Steps to reproduce:

1. Go to https://editorjs.io
2. Anywhere in the code, press Enter
4. Press Ctrl + Z. Nothing happens. I would expect the Enter char to be cancelled.

Device, Browser, OS: Macbook Pro, Chrome 91, Catalina

Editor.js version: the one on the official website

**Comment by neSpecc** [comment]
Duplicate https://github.com/codex-team/editor.js/issues/518
