### ISSUE TITLE
💡Add a new member to output JSON ===>  ["status" = "changed/unchanged/deleted"]

### ISSUE THREAD

**Issue by bmknaidu555** [codex-team/editor.js#1713]
Hi,

Thanks for making such an useful editor.

Is it possible to add a new member to the output JSON of each block. Let say I am writing an article and it has an 100 blocks of data.
Now, if the content in any of the block gets changed, I would like to add new member to the output JSON i.e. "status=changed/unchanged/deleted". 

Example:
=====

{
   "time":1620998181753,
   "blocks":[
      {
         "id":"KgdqCNgbL2",
         "type":"paragraph",
         "data":{
            "text":"sldjf sldkfj sdflkjsdf sdlkf"
         },
     "status" = "changed"
      },
      {
         "id":"MRVZDdb21t",
         "type":"paragraph",
         "data":{
            "text":"sdflksdf sldfjs dflksjdf sdf"
         },
         "status" = "unchanged"
      },
      {
         "id":"s-Hk7_ZO7s",
         "type":"paragraph",
         "data":{
            "text":"sdfksdf slkfjsldf"
         },
         "status" = "unchanged"
      },
      {
         "id":"yUpUO3fR-A",
         "type":"paragraph",
         "data":{
            "text":"sdlkfsd flksdjflsdjfs dfds"
         },
        "status" = "changed"
       }
  ] 
}

Based on the changed status in output JSON I can only send the changed blocks to server instead of new block. This will really help to reduce some bandwidth.

Please let me know your suggestions.

Thanks,
Murali Krishna

**Comment by neSpecc** [comment]
Since the 2.22.0 version, the `onChange` callback accepts changed Block. You can use it for your purposes.

Also, in the same release the [blocks.update(id, data)](https://editorjs.io/blocks#update) method have been introduced.

**Comment by smostafad** [comment]
Hello , I want to change the json file dynamically, that is, the user fills in the information on the site and downloads the new json file. Can you help me?
