### ISSUE TITLE
[Bug] I18n api tools not working

### ISSUE THREAD

**Issue by ghost** [codex-team/editor.js#1715]
Steps to reproduce:
1. insert 
` tools: {
    image: {
      class: ImageTool
}
},
i18n: {
    messages: {
      tools: {
        image: {
          'Test': '123'
        }
      }
    }
}`
2. Call method in any tool. For example Image
`this.api.i18n.t('Test');`
3. Always return 'Test'

**Comment by talyguryn** [comment]
works for me on 2.22.1

config
![image](https://user-images.githubusercontent.com/15259299/123638114-76007e00-d827-11eb-8cc2-2d46cae922cb.png)

usage
![image](https://user-images.githubusercontent.com/15259299/123638152-80bb1300-d827-11eb-92f7-decea5094767.png)

console
![image](https://user-images.githubusercontent.com/15259299/123638173-89abe480-d827-11eb-994f-4e52e289ae7a.png)

**Comment by ghost** [comment]
> works for me on 2.22.1
> 
> config
> ![image](https://user-images.githubusercontent.com/15259299/123638114-76007e00-d827-11eb-8cc2-2d46cae922cb.png)
> 
> usage
> ![image](https://user-images.githubusercontent.com/15259299/123638152-80bb1300-d827-11eb-92f7-decea5094767.png)
> 
> console
> ![image](https://user-images.githubusercontent.com/15259299/123638173-89abe480-d827-11eb-994f-4e52e289ae7a.png)

Thanks, i changed version 2.22.0 to 2.22.1 and works
