### ISSUE TITLE
[Bug] TypeError Cannot read property 'didMutated' of null

### ISSUE THREAD

**Issue by RickGove** [codex-team/editor.js#1751]
Describe a bug.
WIll throw error ```TypeError Cannot read property 'didMutated' of null``` at times

Steps to reproduce:
1. Leave a page using Editor.js
2. See the error
3. (Also happens at other, random times)

Expected behavior:
If there is nothing to check didMutated on, return instead of throwing an error

Screenshots:
![image](https://user-images.githubusercontent.com/63856101/130012306-a2ef9197-e656-42fa-a04f-bd247aa59c92.png)

Device, Browser, OS:
Ubuntu (Happens on mac as well), Electron

Editor.js version:
^2.22.1

Plugins you use with their versions:
Embed
header
paragraph
simple-image

**Comment by samchan0221** [comment]
I was also seeing this message on 2.22.1
2.22.2 seems to have fixed it

**Comment by RickGove** [comment]
> I was also seeing this message on 2.22.1
> 2.22.2 seems to have fixed it

Thank you, this fixed it!!!

**Comment by neSpecc** [comment]
Looks resolved
