### ISSUE TITLE
How to disable default paragraph tool

### ISSUE THREAD

**Issue by ThemeMetro** [codex-team/editor.js#1763]
The question.

How to disable default paragraph tool?

**Comment by woren951** [comment]
You can specify default Tool.
 
From [types/configs/editor-config.d.ts](https://github.com/codex-team/editor.js/blob/65b86c92038694a80e6311377b510be439806863/types/configs/editor-config.d.ts#L28)

```
  /**
   * This Tool will be used as default
   * Name should be equal to one of Tool`s keys of passed tools
   * If not specified, Paragraph Tool will be used
   */
  defaultBlock?: string;
```

**Comment by ThemeMetro** [comment]
> You can specify default Tool.
> 
> From [types/configs/editor-config.d.ts](https://github.com/codex-team/editor.js/blob/65b86c92038694a80e6311377b510be439806863/types/configs/editor-config.d.ts#L28)
> 
> ```
>   /**
>    * This Tool will be used as default
>    * Name should be equal to one of Tool`s keys of passed tools
>    * If not specified, Paragraph Tool will be used
>    */
>   defaultBlock?: string;
> ```

but after this the toolbar option is not available to select another tool/block, that's why want disable this permanently.
