### ISSUE TITLE
Whether the toolbar displayed when the plus icon is clicked can be customized as a drop-down list

### ISSUE THREAD

**Issue by lishaoxin123** [codex-team/editor.js#1769]
Hello, can you only add plugins to the toolbar, can you click the plus icon or the focus icon to display a drop-down menu and put all the plugins in this drop-down menu

**Comment by neSpecc** [comment]
The toolbox will become a vertical list soon. 

<img width="444" alt="image" src="https://user-images.githubusercontent.com/3684889/160130410-75e5ce5a-1d53-4c59-adb4-7965bbb1fa2b.png">

Anyway, it will be good if users would have the ability to customize the UI as they want. This feature is planned for the 3.0 version.

**Comment by neSpecc** [comment]
Closed as solved
