### ISSUE TITLE
[Bug] I can't multi line selection via iPhone safari

### ISSUE THREAD

**Issue by dancinlife** [codex-team/editor.js#1772]
Describe a bug.

I can't multi line selection via iPhone safari

Device, Browser, OS: iOS

Editor.js version: editorjs@latest

**Comment by kaaaaaaaaaaai** [comment]
i have same ploblems

**Comment by MonkZL** [comment]
How did you fix this problem

**Comment by VityaSchel** [comment]
Why is this issue closed?
