### ISSUE TITLE
Fixed Toolbar, Sticky Toolbar

### ISSUE THREAD

**Issue by saurav2799** [codex-team/editor.js#1776]
1. Describe a problem.
We are looking to have option of fixed toolbar. This is particularly useful for less internet savvy users, so they can identify the toolbar and format options. so far our team was unable to find this option in the docs / demos (env: reactjs setup)

bonus: if toolbar can stick at top of the content box/div, so users can scroll comfortably on long documents.

2. Describe the solution you'd like. Mockups are welcome.
for example, we have in this submission: 
![image](https://user-images.githubusercontent.com/52714019/132300466-3527c735-6232-4189-aeff-5a19d880032f.png)

3. Are there any alternatives?
for other alternatives, we might have to consider alternate editor - we have looked at tiny, draftjs and now evaluating slatejs.

**Comment by 11ume** [comment]
I am also really interested in this feature, any news?, is it possible to achieve this currently?

**Comment by WowItsDoge** [comment]
This would be a realy nice feature.

**Comment by sabigara** [comment]
I love the writing experience of Editor.js with large display and keyboard, but not very good on mobile...

This option would be the best solution.
