### ISSUE TITLE
Is there a min-width for the editor when the panel comes down❓

### ISSUE THREAD

**Issue by MightyPhoenix** [codex-team/editor.js#1777]
**Question**

On small width the editor options (block options panel) drops down, it there a way to prevent that from happening?

**Context**

We are working on a chrome extension and and the width of the window is very small and the panel comes below, but it's a bad User experience, we want the original minimalistic design that editor js offer (the plus sign on the left and options on the right of the clock)

![image](https://user-images.githubusercontent.com/31657266/132308461-519628f2-b18b-4494-a41e-4dd4de01b3b7.png)

**Comment by Srinjana** [comment]
yes i agree
