### ISSUE TITLE
[Bug] So, how do I insert AND link an image?

### ISSUE THREAD

**Issue by rk** [codex-team/editor.js#1788]
You cannot add a link to an image. Why does it look like this needs a plugin? Isn't this HTML editor 101?

Steps to reproduce:
1. Go to [https://editorjs.io](https://editorjs.io)
2. Click on the editor
3. Try to add a link to the CODEX image.
4. Try to add an image within a link.
5. Try to add a linked image, without resorting to using raw HTML code...

Expected behavior:

- I kinda expect to be able to link an image w/o adding raw HTML.
- Either a link option should show in the "Tune" panel, or the "inline link" should be possible.

Screenshots: non really needed for this.

Device, Browser, OS: any

Editor.js version: 2.18, including latest

Plugins you use with their versions:

```
       "@editorjs/checklist": "^1.1.0",
        "@editorjs/code": "^2.4.1",
        "@editorjs/delimiter": "^1.1.0",
        "@editorjs/editorjs": "^2.15.1",
        "@editorjs/embed": "^2.2.1",
        "@editorjs/header": "^2.3.1",
        "@editorjs/image": "^2.3.3",
        "@editorjs/inline-code": "^1.3.0",
        "@editorjs/link": "^2.1.3",
        "@editorjs/list": "^1.4.0",
        "@editorjs/marker": "^1.2.1",
        "@editorjs/paragraph": "^2.6.0",
        "@editorjs/raw": "^2.1.1",
        "@editorjs/table": "^1.2.0",
```

Also the versions in use on the home page.

**Comment by neSpecc** [comment]
I'm closing it due to inactivity
