### ISSUE TITLE
[Bug] : Not rendering properly on mobile devices

### ISSUE THREAD

**Issue by anuragvohraec** [codex-team/editor.js#1828]
Describe a bug.
1. No **more-options** button is shown on mobile devices : 
![image](https://user-images.githubusercontent.com/53807480/144687309-7f5df05e-a724-48cf-b0ce-09c76f74c16e.png)

2. When clicking on **+** button the tool set are going beyond toolbar
![image](https://user-images.githubusercontent.com/53807480/144687426-19dcb406-c04d-48c0-8b47-3771f75fcb51.png)

Steps to reproduce:
1. Open [https://editorjs.io/](https://editorjs.io/) on mobile device with resolution (360x640).

Expected behavior:
1. More options buttons must be visible.
2. Toolbar should be within 

Screenshots:
Attached

Device, Browser, OS:
Android browser, or desktop chrome browser in inspect/mobile view (360x640)
Editor.js version:
Current.

Plugins you use with their versions:

**Comment by kaungsithar** [comment]
#1811 Vertical Toolbox will fix this.

**Comment by anuragvohraec** [comment]
> #1811 Vertical Toolbox will fix this.

As for now only adding a single css property will solve the issue:

![image](https://user-images.githubusercontent.com/53807480/159679309-184f38e4-a1e1-479b-a420-382c0eb7f54b.png)

**Comment by itsdiptabiswas** [comment]
I guess the issue is fixed and it should be closed. Now in the mobile view the UI is looking like this - 


<img width="583" alt="image" src="https://github.com/codex-team/editor.js/assets/46165735/c53b1dc0-7c0d-49d3-9a2c-c71d59a65f7c">
