### ISSUE TITLE
💡Prevent delete block on backspace（custom-webcomponent with shadow root will remove the hole block）

### ISSUE THREAD

**Issue by conanliuhuan** [codex-team/editor.js#1840]
1. Describe a problem.
If i defined a custom-webcomponent with shadow-root,and render it in a plugin, backspace in that input will remove all the block

**Comment by conanliuhuan** [comment]
I found another way to do the same thing

**Comment by artyomxyz** [comment]
Could you please share how you did it?

**Comment by conanliuhuan** [comment]
> Could you please share how you did it?

Do not use web component will solve this problem.
I create a plugin with VueJS, just mount a new vue app in plugin element will do the same thing.
