### ISSUE TITLE
[Bug] Typo in Base concepts documentation

### ISSUE THREAD

**Issue by meghrathod** [codex-team/editor.js#1855]
Describe a bug.

Steps to reproduce:
1. Go to … 

    - https://editorjs.io/base-concepts

2. Click on … 

    - In the description of What is clean data, 'r' should be in the strong html tag, forming the word popular
    - Currently is  `<strong class="markup--strong markup--p-strong">one of popula</strong>r`

3. Expected behavior: 

    - Should look somewhat like this
    - `<strong class="markup--strong markup--p-strong">one of popular</strong>`

Screenshots:
![image](https://user-images.githubusercontent.com/23073422/147871801-91effeaa-18df-4e27-8f18-97916ada0eb1.png)

Device, Browser, OS: Chrome on Windows 11

**Comment by neSpecc** [comment]
Fixed
