### ISSUE TITLE
[Bug] Error pasting HTML with Block «...» skipped because saved data is invalid

### ISSUE THREAD

**Issue by cgvictor** [codex-team/editor.js#1865]
Hi. Encountered a bug behavior on paste from clipboard with HTML contents. Chrome latest, FF latest. Reproduced even on your project title page (the demo editor), so probably it's not my config.

Steps to reproduce:
1. Go to editorjs.io. The demo editor with sample content is displayed. Open developer console / console page, to better track what's going on inside.
2. Copy (Ctrl+C) any suitable part of HTML from any page. For instance we have _'Codex: Club of web-development....'_ chunk at the bottom footer on same page: select it, and copy to clipboard (Ctrl+C).
3. Place cursor at the new block '+' marker, and paste the clipboard contents (Ctrl+V). The editor will depict the pasted blocks, but take a precise look at the console log:  
```
[Editor.js saving]:
Header editor.bundle.js:3:3681
Block «header» skipped because saved data is invalid
```
**4. Saving editor contents now, for these pasted blocks will fail. You will lose the pasted content completely when trying to save, or update the page (assuming the autosave is set up).**
5. More to come: pasted blocks are still visible in the editor, so place the cursor into a visible block you have just paste'd in, and type any irrelevant symbol to it, for instance a single whitespace at the end. Now take a look at the console output: [Editor.js saving] reports **everything is now saved well** for block list, including the blocks you have not touched at all.

Expected behavior:
When pasted HTML from clipboard, everything is rendered in the editor is being saved. Or at least, fires an error if there are really any troubles with HTML. Right now, it makes the user think that content is pasted and rendered successfully, being it's not.

Device, Browser, OS: Desktop, Chrome 97.0.4692.71 + Firefox 96.0.1

Editor.js version: **2.22.2**

As far as i can see, issue is applicable to all block types available (header, paragraph, images & so on).

**Comment by cgvictor** [comment]
Version 2.22.3 same behavior. 
I mentioned 2.22.2 because it's still used on editorjs.io title page, but on a latest release = behaves same as well.

**Comment by Dellord** [comment]
Have same issue. Version 2.22.3.

Editor saving data before onPaste call (render -> save -> paste -> validate) and has no reaction for paste changes. So data for validation is not actual and block skipped.

Chrome 97.0.4692.99, Firefox 96.0.3

**Comment by cgvictor** [comment]
Seems to be fixed in `2.24.3`. Thanks a lot! Closing the issue

**Comment by kanejamison** [comment]
I'm still seeing a version of this issue occurring on editorjs.io. It appears to be related to the issue in #2065 where final item in a paste gets left out of the JSON shown in the data preview.

Editorjs homepage is running on "version" : "2.24.3". Pretty sure we're seeing some similar bugs in our app on 2.25.0.

![image](https://user-images.githubusercontent.com/918780/200044333-cb7190fa-9277-420d-8807-6f130f48f453.png)

**Comment by tam315** [comment]
I also faced this issue today and it was caused by the DeepL chrome extension.
In my case, disabling it is not enough and I need to uninstall it completely💀

**Comment by trongld21** [comment]
I have the same problem although I have updated the version to 2.26.5. I don't know how to fix it, please help me!

**Comment by meiyasan** [comment]
Same here. I had a look inside the html page. Failing blocks are identical to the correct one. Unless there are some invisible chars.

To reproduce, I have input a raw html containing a h1 block and a p tag and I get issue with the header block.

Please advice ! @cgvictor

**Comment by ram-kumar-shrestha** [comment]
In my case the problem was caused due to React.StrictMode which causes the component to rerender twice.
To prevent that I used extra ref
`  const initEditorCalled = useRef(false);`
  
  and only intialize the editor only iff it has not been initialized before
 ```
   // Call initEditor only if it hasn't been called before
    if (!initEditorCalled.current) {
      initEditor();
    }
```

**Comment by Vandal-William** [comment]
I confirm that it is React.StrictMode that is causing the error: 'Block "header" skipped because saved data is invalid.' After disabling it, everything works fine and I no longer have any errors.

**Comment by HarshitAnchan** [comment]
"use client";
import React, { useEffect, useRef, useState } from "react";
import EditorJS from "@editorjs/editorjs";
import Header from "@editorjs/header";
import Delimiter from "@editorjs/delimiter";
import Alert from "editorjs-alert";
import List from "@editorjs/list";
// import NestedList from '@editorjs/nested-list';
import Checklist from "@editorjs/checklist";
// import Embed from '@editorjs/embed';
import SimpleImage from "@editorjs/simple-image";
import Table from "@editorjs/table";
import CodeTool from "@editorjs/code";
// import { TextVariantTune } from '@editorjs/text-variant-tune';
// import { doc, onSnapshot, updateDoc } from 'firebase/firestore';
// import { db } from '@/config/firebaseConfig';
// import { useUser } from '@clerk/nextjs';
import Paragraph from "@editorjs/paragraph";
import { doc, onSnapshot, updateDoc } from "firebase/firestore";
import { db } from "@/config/firebaseConfig";
import { useUser } from "@clerk/nextjs";
// import GenerateAITemplate from './GenerateAITemplate';
function RichDocumentEditor({ params }) {
  const ref = useRef();
  let editor;
  const { user } = useUser();
  const [documentOutput, setDocumentOutput] = useState();
  let isFetched = false;
  useEffect(() => {
    user && InitEditor();
  }, [user]);

  // useEffect(() => {
  //   params && GetDocumentOutput();
  // }, [params]);

  // Used to save document
  const SaveDocument = () => {
    ref.current.save().then(async (outputData) => {
      // console.log(outputData);
      const docRef = doc(db, "documentOutput", params?.documentid);
      await updateDoc(docRef, {
        output: outputData,
        editedBy: user?.primaryEmailAddress?.emailAddress,
      });
    });
  };

  const GetDocumentOutput = () => {
    const unsubscribe = onSnapshot(
      doc(db, "documentOutput", params?.documentid),

      (doc) => {
        if (
          isFetched == false ||
          doc.data()?.editedBy != user?.primaryEmailAddress?.emailAddress
        )
          // console.log(doc.data());
          // setDocumentOutput(doc.data()?.output);
          doc.data()?.output && editor.render(doc.data()?.output);
        isFetched = true;
      }
    );
  };

  const InitEditor = () => {
    if (!editor?.current) {
      editor = new EditorJS({
        onChange: (ap, event) => {
          SaveDocument();
        },
        onReady: () => {
          GetDocumentOutput();
        },
        //  Id of Element that should contain Editor instance

        holder: "editorjs",
        tools: {
          header: Header,
          delimiter: Delimiter,
          paragraph: Paragraph,
          alert: {
            class: Alert,
            inlineToolbar: true,
            shortcut: "CMD+SHIFT+A",
            config: {
              alertTypes: [
                "primary",
                "secondary",
                "info",
                "success",
                "warning",
                "danger",
                "light",
                "dark",
              ],
              defaultType: "primary",
              messagePlaceholder: "Enter something",
            },
          },
          image: SimpleImage,

          table: Table,
          list: {
            class: List,
            inlineToolbar: true,
            shortcut: "CMD+SHIFT+L",
            config: {
              defaultStyle: "unordered",
            },
          },
          checklist: {
            class: Checklist,
            shortcut: "CMD+SHIFT+C",
            inlineToolbar: true,
          },
          code: {
            class: CodeTool,
            shortcut: "CMD+SHIFT+P",
          },
          //   textVariant: TextVariantTune
        },
      });
      ref.current = editor;
    }
  };
  return (
    <div className="lg:-ml-20 text-black ">
      <div id="editorjs"></div>
    </div>
  );
}

export default RichDocumentEditor;

i have set React.StrictMode to false then too its not working my version is version
"2.30.4"

**Comment by Pankajk001** [comment]
> "use client"; import React, { useEffect, useRef, useState } from "react"; import EditorJS from "@editorjs/editorjs"; import Header from "@editorjs/header"; import Delimiter from "@editorjs/delimiter"; import Alert from "editorjs-alert"; import List from "@editorjs/list"; // import NestedList from '@editorjs/nested-list'; import Checklist from "@editorjs/checklist"; // import Embed from '@editorjs/embed'; import SimpleImage from "@editorjs/simple-image"; import Table from "@editorjs/table"; import CodeTool from "@editorjs/code"; // import { TextVariantTune } from '@editorjs/text-variant-tune'; // import { doc, onSnapshot, updateDoc } from 'firebase/firestore'; // import { db } from '@/config/firebaseConfig'; // import { useUser } from '@clerk/nextjs'; import Paragraph from "@editorjs/paragraph"; import { doc, onSnapshot, updateDoc } from "firebase/firestore"; import { db } from "@/config/firebaseConfig"; import { useUser } from "@clerk/nextjs"; // import GenerateAITemplate from './GenerateAITemplate'; function RichDocumentEditor({ params }) { const ref = useRef(); let editor; const { user } = useUser(); const [documentOutput, setDocumentOutput] = useState(); let isFetched = false; useEffect(() => { user && InitEditor(); }, [user]);
> 
> // useEffect(() => { // params && GetDocumentOutput(); // }, [params]);
> 
> // Used to save document const SaveDocument = () => { ref.current.save().then(async (outputData) => { // console.log(outputData); const docRef = doc(db, "documentOutput", params?.documentid); await updateDoc(docRef, { output: outputData, editedBy: user?.primaryEmailAddress?.emailAddress, }); }); };
> 
> const GetDocumentOutput = () => { const unsubscribe = onSnapshot( doc(db, "documentOutput", params?.documentid),
> 
> ```
>   (doc) => {
>     if (
>       isFetched == false ||
>       doc.data()?.editedBy != user?.primaryEmailAddress?.emailAddress
>     )
>       // console.log(doc.data());
>       // setDocumentOutput(doc.data()?.output);
>       doc.data()?.output && editor.render(doc.data()?.output);
>     isFetched = true;
>   }
> );
> ```
> 
> };
> 
> const InitEditor = () => { if (!editor?.current) { editor = new EditorJS({ onChange: (ap, event) => { SaveDocument(); }, onReady: () => { GetDocumentOutput(); }, // Id of Element that should contain Editor instance
> 
> ```
>     holder: "editorjs",
>     tools: {
>       header: Header,
>       delimiter: Delimiter,
>       paragraph: Paragraph,
>       alert: {
>         class: Alert,
>         inlineToolbar: true,
>         shortcut: "CMD+SHIFT+A",
>         config: {
>           alertTypes: [
>             "primary",
>             "secondary",
>             "info",
>             "success",
>             "warning",
>             "danger",
>             "light",
>             "dark",
>           ],
>           defaultType: "primary",
>           messagePlaceholder: "Enter something",
>         },
>       },
>       image: SimpleImage,
> 
>       table: Table,
>       list: {
>         class: List,
>         inlineToolbar: true,
>         shortcut: "CMD+SHIFT+L",
>         config: {
>           defaultStyle: "unordered",
>         },
>       },
>       checklist: {
>         class: Checklist,
>         shortcut: "CMD+SHIFT+C",
>         inlineToolbar: true,
>       },
>       code: {
>         class: CodeTool,
>         shortcut: "CMD+SHIFT+P",
>       },
>       //   textVariant: TextVariantTune
>     },
>   });
>   ref.current = editor;
> }
> ```
> 
> }; return (
> 
> 
> 
> 
> );
> }
> export default RichDocumentEditor;
> 
> i have set React.StrictMode to false then too its not working my version is version "2.30.4"

Bro , have you solved this problem ? I am also making this project from techGuruji. and facing same problem. please help
