### ISSUE TITLE
💡EditorJS Tab Navigation Friendly

### ISSUE THREAD

**Issue by ewalpole** [codex-team/editor.js#1953]
1. Describe a problem. 
Currently trying to use EditorJS as an input for a form with other simpler inputs. It seems like it's assumed that users are only mouse users and that EditorJS is the only item on the page right now. It's very difficult to use `tab` and `shift+ tab` (accessibility key combos) to move from EditorJS to the other form inputs because EditorJS traps the focus and these common key combos. Right now my solution is to put EditorJS into a containing div, detect keydowns of shortcut key to destroy EditorJS (ctrl+n/p) and move back and forth from simple inputs to EditorJS, and then once the focus is in the containing div again, I re-initialize EditorJS and set focus manually (not very straightforward). Maybe there's a better way I don't see.

2. Describe the solution you'd like. Mockups are welcome.
EditorJS should consider having an option for Exit, Back/Forward for accessibility/page flow reasons that the users can `tab` or `shift+tab` to inside the Editor (at the very least).

Scenario:
Using EditorJS, adding text etc.
User wants to go to next form input (ex. address/tags), tabs over to "Next" within the Editor.
Focus shifts to the next tabbable item in the page.
^ Same for going back

3. Are there any alternatives?
Unsure.

**Comment by neSpecc** [comment]
Duplicate https://github.com/codex-team/editor.js/issues/927
