### ISSUE TITLE
[Bug] v2.23.1 readOnly: true crashes the editor

### ISSUE THREAD

**Issue by hlynurstef** [codex-team/editor.js#1968]
On version 2.23.1 when we create a new EditorJs instance with `readOnly: true` the editor crashes with the following error:

```
Cannot read properties of undefined (reading 'destroy')
```

This crash does not happen on v2.23.0

Steps to reproduce:
1. Make sure you are on version 2.23.1 of `@editorjs/editorjs`
2. Create an EditorJs instance with readOnly: true
3. Observe the crash

I've created a reproducable example in codesandbox where you can toggle between readOnly true/false:
https://codesandbox.io/s/editorjs-readonly-crash-myw3o?file=/src/App.js

When readOnly is toggled to true you can observe the crash.

NOTE: This crash does not happen on v2.23.0

Expected behavior:
Not crashing

Screenshots:
![image](https://user-images.githubusercontent.com/15615089/153242258-721b05f3-2b70-4635-b520-ec37aae3f4bc.png)

Device, Browser, OS:
Chrome Version 98.0.4758.80 (Official Build) (arm64)

Editor.js version:
2.23.1

Plugins you use with their versions:
None

**Comment by neSpecc** [comment]
Sorry. Fix was shipped with 2.23.2

**Comment by jimmycrequer** [comment]
@neSpecc Hello, I have the same error on `2.23.0-rc.2`, it seems the fix wasn't applied on that branch can you please check?
