### ISSUE TITLE
[Bug] can't paste links on mobile

### ISSUE THREAD

**Issue by orbachar** [codex-team/editor.js#1970]
Paste link doesn't work on mobile, on desktop it works as expected.
See attached video

Device, Browser, OS: chrome on Android

Editor.js version: 2.23.2

# #

https://user-images.githubusercontent.com/57751360/153760931-3c751348-28e4-43ba-bfd6-9b83b94a6f09.mp4

**Comment by robonetphy** [comment]
Hi @orbachar, I am unable to reproduce the problem as shown in the video below:
# #

https://user-images.githubusercontent.com/23169768/157361849-1e1c9c9e-4368-4cf3-8d02-5b7f79b8f03f.mp4

If it still occurs on your phone then pls provide us with the chrome version.
Happy editing...

**Comment by orbachar** [comment]
cant reproduce either, thanks!
