### ISSUE TITLE
Can I use editor.js with react or next along with typescript?

### ISSUE THREAD

**Issue by pythonhubdev** [codex-team/editor.js#1986]
I am trying to build an editor based website for learning react and nextjs.

I am using typescript along with next.js so I would like to know wether I can use editor.js with typescript and next.

**Comment by BaronSlayer** [comment]
you would need to import it dynamically with { ssr: false } or use react-editor-js package

**Comment by AlbinoGeek** [comment]
The answer is "sort of" -- there are lots of gotchas.

It feels like hundreds of gotchas once you try to use TypeScript.

Biggest one: NONE of the default plugins expose typings for whatever reason.

**Comment by berkaygurbuz** [comment]
@pythonhubdev any update? I am trying to start to use editorjs in nextjs typescript it gives lots of errors can you handle it? Should I continue to use it?

**Comment by pythonhubdev** [comment]
I didn't use it as of now i moved to some other editor while I asked this doubt may be I should give a try again.

**Comment by AlbinoGeek** [comment]
It's a real shame that this rapper won't support it properly, but what you
can do, is downgrade your next by like three major versions, then it works.

Specifically, you need to downgrade react to 17, and then pick the next
version that still works with 17.

**Comment by obfusticatedcode** [comment]
> I didn't use it as of now i moved to some other editor while I asked this doubt may be I should give a try again.

Curious, which other Editor did you decide to use and does it have the same features?

**Comment by davidsonaguiar** [comment]
> > Não usei até agora, mudei para outro editor enquanto fazia essa dúvida, talvez eu deva tentar novamente.
> 
> Curioso, qual outro Editor você decidiu usar e ele possui as mesmas funcionalidades?

I would also like to know if there is another one like it, that works with react + typescript

**Comment by teknology** [comment]
2024 and yet here we are.. still..

**Comment by Tilakraj0308** [comment]
> 2024 and yet here we are.. still..

It's 2025 now and yet here we are...

**Comment by bekogeko** [comment]
It's 2026 now and yet we are still here...

**Comment by AlbinoGeek** [comment]
To be fair, this "just works" as a Client component in NextJS v16 -- even Turbopack etc.
Just treat it like any other 5* year old legacy package, use transpilePackages directive.
