### ISSUE TITLE
onChange event not called when adding new block

### ISSUE THREAD

**Issue by MrMooky** [codex-team/editor.js#1997]
When I create a new element, e.g. a delimiter, and instantly store my content, the new element is not stored because the `onChange` event is not triggered. But when creating a new element and changing content (active keyup), the element gets stored because the `onChange` is triggered.

Expected behavior: `onChange` should be called after adding a new element.

Screenshots: https://www.loom.com/share/5bba14a6eb844bfdae677b47ee5e2553

Device, Browser, OS: macOS Safari

Editor.js version: 2.23.2

**Comment by robonetphy** [comment]
@MrMooky, Thanks for reporting the bug. 
But can you share some more details like 
`what is your editorjs configuration?`
`what method you are using to store the content instantly?`
