### ISSUE TITLE
[Bug] Jerky motion during mouse movement after scrolling

### ISSUE THREAD

**Issue by pix666** [codex-team/editor.js#2036]
This behavior started with version 2.24.0.

Steps to reproduce:
1. Click on any block
2. Scroll the page with the mouse wheel
3. Move your mouse

Video:

https://user-images.githubusercontent.com/6928240/165931619-71e755a7-3305-415c-b645-729c21e20929.mp4

**Comment by marcoaureliorp** [comment]
Same bug here @pix666!

**Comment by Dilyarbuzan** [comment]
Same here. Is there any solution for this? Please advice

**Comment by NathanLandsX** [comment]
Same here on Windows 10 on Edge. Hoping this is fixed soon, was planning on using this on a significant project in 2 weeks.

**Comment by moomoo-dev** [comment]
Was this ever fixed?
