### ISSUE TITLE
[Bug] Keyboard selection by word doesn't work when selecting from right to left

### ISSUE THREAD

**Issue by gohabereg** [codex-team/editor.js#2045]
Describe a bug.

Steps to reproduce:
1. Go to https://editorjs.io
2. Click in the middle of any paragraph 
3. Try to select several words via keyboard from right to left (on MacOS Opt + Shift + Arrow left)

Expected behaviour:
Words should be selected

Actual behaviour:
After selecting the second word selection is lost and cursor jumps to the beginning of the paragraph

Device, Browser, OS:
Chrome, MacOS

Editor.js version:
2.24.2

**Comment by yswang0927** [comment]
Yes, I also found this problem.

**Comment by mrinmays** [comment]
+1

**Comment by rzvtig** [comment]
+1
