### ISSUE TITLE
Columns, one note style canvas

### ISSUE THREAD

**Issue by whathappenedman** [codex-team/editor.js#2047]
Hi. It doesn't seem like there is built in support for columns or a wide page with multiple blocks positioned on an xy coordinate somewhat like Microsoft onenote. Is that correct?

Further, just looking at the plugin sample code it seems open to implement, with the only issue being logic to handle the positioning. Any obvious gotchas before I give it a go? For example can I make the custom plugin the parent of all other blocks?

**Comment by neSpecc** [comment]
See this discussion: https://github.com/codex-team/editor.js/discussions/1872
