### ISSUE TITLE
inlineToolbar add new items

### ISSUE THREAD

**Issue by bar-boss** [codex-team/editor.js#2071]
Hello.
How I can add to inlineToolbar new items: undeline, line-through ?
Something like that:
` inlineToolbar: ['link', 'italic', 'underline', 'line-through']`

**Comment by neSpecc** [comment]
You need to connect your Underline, Line Through, and other tools under the `tools` property of Editor Config.

See also: 
[Inline Toolbar Order](https://editorjs.io/configuration#inline-toolbar-order)
