### ISSUE TITLE
Is there a way to change block setting orientation/direction?

### ISSUE THREAD

**Issue by Nico-L** [codex-team/editor.js#2082]
Hello,

I am using editorjs with Svelte.

For large screen sizes, the settings windows opens toward the bottom : 
![image](https://user-images.githubusercontent.com/11961129/174077906-b1fec390-dafd-4e36-9c51-73e031e4f625.png)

But for the smaller screen (when the buttons move for side to below the block), the settings window open in the up direction:
![image](https://user-images.githubusercontent.com/11961129/174078342-0fae6b50-299d-455f-9374-ffc2e1280d04.png)

I have an issue for the first few blocks with the settings windows outside of the editor not visible:
![image](https://user-images.githubusercontent.com/11961129/174078907-c7e8a04d-ba8b-4c01-9bee-17cfaac3dbcc.png)

I tried to play with the z-index of different elements with no success.

Is there a mean to change the direction the settings window opens to?

Thanks

**Comment by DevrG03** [comment]
Hii @neSpecc , I am new to open source. Can any one please tell me where can I find the code for this menu, I would like to give it a try.

**Comment by neSpecc** [comment]
> Hii @neSpecc , I am new to open source. Can any one please tell me where can I find the code for this menu, I would like to give it a try.

Hi, we're currently working on making the Block Tunes panel vertical just like the Toolbox. So this issue will be resolved in the next update. 

Please, consider choosing an another issue from the "good first issue" label. We'll be glad to help.

**Comment by neSpecc** [comment]
For now on mobile devices the popover will sticked to the bottom of the screen.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/3684889/219498818-aad65a5c-96d2-4e50-b1bd-4a575ba5ab2b.png">
