### ISSUE TITLE
[Bug] Keyboard shortcuts for creating new blocks no longer work, as of 2.19.0

### ISSUE THREAD

**Issue by julianpeterson1** [codex-team/editor.js#2089]
Describe a bug.

Steps to reproduce:
1. Go to https://editorjs.io/
2. Try to create a new block in the demo editor (Code seems to work there with CMD+SHIFT+D, but none of the other ones do)

Expected behavior: Shortcuts defined should appear in the block menu, and should create a new block of that type when pressed.

Thanks!

Screenshots:

Before: While on version 2.18 this is what we saw:

https://user-images.githubusercontent.com/10519464/175384602-f8cb798d-ad9b-4b1e-9eb5-742025a6d2b6.mov

The keyboard shortcuts worked as expected.

After updating to 2.25 (went back to 2.19 and the issue was still there, so I assume it was introduced on 2.19): 

https://user-images.githubusercontent.com/10519464/175384667-4cdf7f1b-3159-4a66-9630-c6f2aad8f73c.mov

Device, Browser, OS: Macbook Pro, Chrome, OS X 12.4
>2.19.0

Plugins you use with their versions:

Custom Paragraph
Custom Heading 1
Custom Heading 2
Custom Heading 3
Custom Title

**Comment by khanakia** [comment]
I am having the same issue. Shortcuts are not working e.g. `CMD+SHIFT+H` to create new headings.
