### ISSUE TITLE
[Bug] - Shortcuts are not working e.g. CMD+SHIFT+H not creating new header block

### ISSUE THREAD

**Issue by khanakia** [codex-team/editor.js#2112]
Describe a bug.

Steps to reproduce:
1. Go to https://github.com/codex-team/editor.js/blob/next/example/example.html
2. Press command `CMD+SHIFT+H`

Expected behavior:
It should insert the header but nothing happens

Device, Browser, OS: Chrome, Opera OSX

Editor.js version: 2.25.0

Plugins you use with their versions: Header, Text

**Comment by Akash187** [comment]
Yes, I would like to confirm that this issue exists. Also, the shortcut will not show in the toolbar.
