### ISSUE TITLE
support translations💡

### ISSUE THREAD

**Issue by yzn-h** [codex-team/editor.js#2118]
1. Describe a problem.

it will be nice if people can go [here](https://hosted.weblate.org/projects/bytemd/) and translate things like "Image" and "Heading" to their language without plugins

2. Describe the solution you'd like. Mockups are welcome.
this site [https://hosted.weblate.org/projects/bytemd/](https://hosted.weblate.org/projects/bytemd/)

3. Are there any alternatives?
have the ability to remove the base blocks to add them in my lang

**Comment by neSpecc** [comment]
We have the [Internationalization API](https://editorjs.io/i18n) allowing to translate all the UI texts without plugins.
