### ISSUE TITLE
[Bug] Quote aligment is not working

### ISSUE THREAD

**Issue by samandar-boymurodov** [codex-team/editor.js#2130]
Describe a bug.

Steps to reproduce:
1. Connect quote plugin(https://www.npmjs.com/package/@editorjs/quote) to EditorJs
2. Create quote element
3. Press the "tab" key in quote input (not in the caption)
4. Choose one of the alignment options: left or center
5. Nothing happens

Expected behavior:
Text in quote is aligned according to the selected alignment option

If it is not possible to achieve the expected behavior, would it be possible to completely remove alignment options when the tab is clicked? Instead, focus is moved to caption element as in https://tjournal.ru/

Screenshots:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/65066111/187073247-cc413496-85bf-4022-8c94-21542cd684b6.png">

Device, Browser, OS:
Chrome browser

Editor.js version:
2.25.0

Plugins you use with their versions:
Quote - 2.4.0

**Comment by neSpecc** [comment]
The issue is not related to the Editor.js core repo. Better open it in the [Quote Tool](http://github.com/editor-js/quote) repo.
