### ISSUE TITLE
EditorJS always renders two editors how to stop it from doing that in nextjs

### ISSUE THREAD

**Issue by vikram2009** [codex-team/editor.js#2154]
EditorJS always renders two editors how to stop it from doing that in nextjs

I'm using Nextjs with Editor.js 
how to stop editorjs from rendering 2 editors
the image below shows the problem im facing 
my code and image :- 
```jsx
useEffect(() => {
    let editor = { isReady: false };
    const Editorjs = require('@editorjs/editorjs')
    const Header = require('@editorjs/header');
    const SimpleImage = require('@editorjs/simple-image');
    const Embed = require('@editorjs/embed');
    const Quote = require('@editorjs/quote');
    if(!editor.isReady) {

    editor =   new Editorjs({
      holder: 'editorjs',
 placeholder: "Start typing",
      tools: {
        header: {
          class: Header,
          shortcut: 'ALT+SHIFT+H',
          inlineToolbar: ['link' , 'bold'],
        },
        image: {
class: SimpleImage,
        },
        embed: {
          class: Embed,
          inlineToolbar: true,
          config: {
            services: {
              youtube: true,
              coub: true,
              codepen: {
                regex: /https?:\/\/codepen.io\/([^\/\?\&]*)\/pen\/([^\/\?\&]*)/,
                embedUrl: 'https://codepen.io/<%= remote_id %>?height=300&theme-id=0&default-tab=css,result&embed-version=2',
                html: "<iframe height='300' scrolling='no' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%;'></iframe>",
                height: 300,
                width: 600,
                
              }
            }
          }
        },
      },
    }
      
    )
      
      
  }
}, [])

```
![image](https://user-images.githubusercontent.com/73585468/197724265-39116681-a982-4b73-8c53-f0e94e3c0039.png)

**Comment by santiagoalcazarch** [comment]
@vikram2009 You just have to disable the StrictMode on your app's root. 
``` jsx
  // <React.StrictMode>
    <App />
  // </React.StrictMode>
```

**Comment by vikram2009** [comment]
I dont have React.Strictmode enabled

**Comment by vikram2009** [comment]
my _app.jsx
```jsx
import "../style.css";
import "../App.css";
import { Ldb } from './loadingbar';
// This default export is required in a new `pages/_app.js` file.
export default function MyApp({ Component, pageProps }) {
  
  return (<>
  <>
    <>
  <Ldb />
    </>
  <Component {...pageProps} />;
  </>
  </>)
}

```

**Comment by vikram2009** [comment]
Thank you for ur solutions,
but i fixed this problem myself @santiagoalcazarch

**Comment by volagold** [comment]
@vikram2009 how did you fix the problem? I'm running into the same issue and I'd like to know your solution, thank you!

**Comment by volagold** [comment]
ok never mind, I got it. We just need to disable Strict Mode in `next.config.js`:

```javascript
// next.config.js
module.exports = {
  reactStrictMode: false,
}
```

**Comment by Jeff909Dev** [comment]
> ok never mind, I got it. We just need to disable Strict Mode in `next.config.js`:
> 
> ```js
> // next.config.js
> module.exports = {
>   reactStrictMode: false,
> }
> ```

Instead of disable strict mode, that can be useful for a lot of situations I prefer using a ref to control if Editor has been loaded:

```js
export const TextEditor = () => {
  const isReady = useRef(false);

  useEffect(() => {
    if (!isReady.current) {
      new Editor(config);
      isReady.current = true;
    }
  }, []);

  return <div id="editorjs" />;
};
```

Hope it helps 😄

**Comment by keremnymn** [comment]
> > ok never mind, I got it. We just need to disable Strict Mode in `next.config.js`:
> > ```js
> > // next.config.js
> > module.exports = {
> >   reactStrictMode: false,
> > }
> > ```
> 
> Instead of disable strict mode, that can be useful for a lot of situations I prefer using a ref to control if Editor has been loaded:
> 
> ```js
> export const TextEditor = () => {
>   const isReady = useRef(false);
> 
>   useEffect(() => {
>     if (!isReady.current) {
>       new Editor(config);
>       isReady.current = true;
>     }
>   }, []);
> 
>   return <div id="editorjs" />;
> };
> ```
> 
> Hope it helps 😄

Great solution, thank you!

**Comment by polyglotSE** [comment]
I don't think there is a need to use useRef. It's a React behavior in development mode to mount components twice to ensure our cleanup logic is written correctly. Just add the cleanup logic and you'll be good to go without any hacky solutions. Here is a short example:

```
useEffect(() => {
    const editor = new EditorJS({
        holder: ENTER_YOUR_HOLDER_ID
    });

    return () => {
        editor.destroy();
    };
}, []);
```

**Comment by gwebtechology** [comment]
Define your editor outside the `useEffect` and check if `editor?.isReady` before rendering a new EditorJS

```javascript copy
import EditorJS from "@editorjs/editorjs";

export const EditorJSMode: React.FC = (...) => {

  let editor: EditorJS | null = null;

  useEffect(() => {
    const initEditor = async () => {

        if (editor?.isReady) {
          return;
        }

        editor = new EditorJS({
              ....
        })
   ...
   }
}
```
