### ISSUE TITLE
If the content is presented in read-only mode, how should I solve the SEO problem?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [codex-team/editor.js#2165]
If the content is presented in read-only mode, how should I solve the SEO problem?

**Comment by neSpecc** [comment]
Which kind of a problem?

**Comment by Yakumo-Yukari** [comment]
> Which kind of a problem?

Search engine inclusion issues

**Comment by neSpecc** [comment]
Which kind of issues? Please, provide more details about your issues and how they are related to the Editor.js

**Comment by Yakumo-Yukari** [comment]
> Which kind of issues? Please, provide more details about your issues and how they are related to the Editor.js

Sorry, maybe it's my front-end rendering.

**Comment by ehsan-soleimanian** [comment]
This is how Google sees the content with readOnly mode.
![image](https://github.com/codex-team/editor.js/assets/59331480/21818a68-2306-4afb-8426-260be69bbc6f)
@Yakumo-Yukari
