### ISSUE TITLE
Paste list formatting issues

### ISSUE THREAD

**Issue by 297468765** [codex-team/editor.js#2172]
Describe a bug.
Paste list formatting issues
Steps to reproduce:

https://cliff-christmas-94e.notion.site/ffff-978f4c6bb8be4b88a8d98f183ddcc50b
    
Copy the text in the link above and paste it into the editor
Screenshots:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/81843623/203754197-30eafa1a-d13e-4982-b601-ec5d5b872d41.png">

**Comment by neSpecc** [comment]
This issue is related to the [Nested List](https://github.com/editor-js/nested-list) tool, not Editor core, so I'll close it.
