### ISSUE TITLE
[Bug] Can not delete nested list first item

### ISSUE THREAD

**Issue by Rue-pro** [codex-team/editor.js#2175]
Can not delete nested list first item

Steps to reproduce:
1. Create nested list
2. Try to delete first item of the nested list

Expected behavior:
First element of the nested list is deleted

Demo:
![Alt Text](https://media.giphy.com/media/pxrg8JalGk6J0qn0jM/giphy.gif)

Device, Browser, OS:
PC, Chrome, Linux

Editor.js version:
2.26

Plugins you use with their versions:
@editorjs/nested-list 1.0.2

**Comment by Rue-pro** [comment]
Would like to fix this bug

**Comment by neSpecc** [comment]
It is related to the https://github.com/editor-js/nested-list so please open an issue in there
