### ISSUE TITLE
Readonly mode does not fully reflect plugin-created blocks

### ISSUE THREAD

**Issue by intaek-h** [codex-team/editor.js#2185]
I'm using editorjs/table plugin. It has column/row resizing feature but when I toggle readonly mode, which is offered by editorjs, the cells are shown without resized width and height.
At first, I tried to look for codes that style readonly mode in editorjs/table repository, but found out that they were in editorjs code base.
![스크린샷 2022-11-26 오후 8 19 10](https://user-images.githubusercontent.com/108341074/204086086-52dba727-caf8-446a-a86e-83aad6debb18.png)
![스크린샷 2022-11-26 오후 8 19 14](https://user-images.githubusercontent.com/108341074/204086091-3eadb683-0931-41a5-8cbd-b94955960bc4.png)

My question is, is there a way for a third-party plugin to modify readonly-mode code? If not, which method in editorjs should I look up and change?

**Comment by neSpecc** [comment]
The Read-only Mode style is a part of the Tool's logic. Editor core does not know about the tool's internal structure and styles.

Looks like you're using the 3rd party Table tool. So this issue is related to that tool.
