### ISSUE TITLE
[Bug] UI Issue

### ISSUE THREAD

**Issue by imransilvake** [codex-team/editor.js#2193]
Describe a bug.
The newest ver 2.26.0 is having UI problems with the Custom tooltip actions and some fonts looks bigger than the others like heading, list etc (`H`).

Steps to reproduce:
1. Install v2.26.0
2. Check the icons

Expected behavior:
UI should work like it works in v.2.25.0
<img width="218" alt="Screenshot 2022-11-29 at 20 56 58" src="https://user-images.githubusercontent.com/13087225/204635189-ae7b4bd6-8895-4052-8449-1ebf10c62107.png">
<img width="355" alt="Screenshot 2022-11-29 at 20 57 29" src="https://user-images.githubusercontent.com/13087225/204635194-bbf5b676-f25a-4a78-8aae-1d104f8f2dbf.png">

Screenshots:
<img width="381" alt="Screenshot 2022-11-29 at 20 48 10" src="https://user-images.githubusercontent.com/13087225/204634253-f0f53831-84de-4603-99c7-75751217960d.png">
<img width="290" alt="Screenshot 2022-11-29 at 20 48 15" src="https://user-images.githubusercontent.com/13087225/204634256-3c0f2aaa-af7e-4176-8285-3ab20e2894c4.png">

Device, Browser, OS:
Mac OS (Chrome)

Editor.js version:

Plugins you use with their versions:

**Comment by medzhidov** [comment]
Have the same problem with fresh installation
![CleanShot 2022-11-30 at 18 35 23@2x](https://user-images.githubusercontent.com/11080873/204797845-6baf4bf1-03bd-4b00-b17a-f3b4abf13739.png)
![CleanShot 2022-11-30 at 18 35 57@2x](https://user-images.githubusercontent.com/11080873/204797906-b92e135e-fdea-4cbb-a6fb-358d2113d8ae.png)

**Comment by neSpecc** [comment]
Update all the tools to the latest version. We've updated all the icons. Now it's recommended to have a 24x24 container for SVG icons. 

If you have self-made tools, you can use the icons from the new [CodeX Icons](https://github.com/codex-team/icons) pack.

**Comment by medzhidov** [comment]
@neSpecc I updated all plugins but table and underline at least have this bug

**Comment by medzhidov** [comment]
<img width="552" alt="CleanShot 2022-12-01 at 15 54 14@2x" src="https://user-images.githubusercontent.com/11080873/205022528-2711b506-2fdd-481f-9539-512001e0064d.png">

![CleanShot 2022-12-01 at 15 54 47@2x](https://user-images.githubusercontent.com/11080873/205022698-73cd6d5d-bed8-4cb1-ac77-344ffe309df0.png)

**Comment by medzhidov** [comment]
Also all icons inside table actions buggy

<img width="950" alt="CleanShot 2022-12-01 at 16 14 13@2x" src="https://user-images.githubusercontent.com/11080873/205026818-74f24acd-2867-42e4-92ed-acc6cb7947d7.png">

**Comment by medzhidov** [comment]
Only marker's icon fixed

**Comment by neSpecc** [comment]
> Also all icons inside table actions buggy

do you have svg stroke/fill styles on your side?

**Comment by medzhidov** [comment]
@neSpecc no, i just install table and activate it as a plugin

<img width="580" alt="CleanShot 2022-12-01 at 16 18 45@2x" src="https://user-images.githubusercontent.com/11080873/205027519-8f935fe6-d6a8-4360-972c-db9ad5909ae5.png">

<img width="571" alt="CleanShot 2022-12-01 at 16 18 57@2x" src="https://user-images.githubusercontent.com/11080873/205027561-55e3c5c0-1df3-4cce-ba45-b79bf34fdc9b.png">

**Comment by neSpecc** [comment]
Table and Underline icons fixed, update to the last version please.

What about your screenshot, I can't reproduce it. Check your CSS overrides, probably you have some SVG styles somewhere

**Comment by medzhidov** [comment]
@neSpecc all icons fixed now, thank you a lot!

**Comment by mqtik** [comment]
Can @editor-js allow the customization of icons? As in, allow developers to just change the icon.
Design is a big deal, and the editor must fit the design of the website, otherwise it looks out of place

**Comment by neSpecc** [comment]
> Can @editor-js allow the customization of icons? As in, allow developers to just change the icon.
> Design is a big deal, and the editor must fit the design of the website, otherwise it looks out of place

You can [specify](https://editorjs.io/getting-started/#available-tools-options) `toolbox` property with `icon` and `title` overrides
