### ISSUE TITLE
[2.26.1] MenuConfig: Is it possible to change order/priority of BlockTunes? 

### ISSUE THREAD

**Issue by christoph-kluge** [codex-team/editor.js#2200]
Is it possible to change the order of additional custom tunes?

<img width="447" alt="Screenshot 2022-12-03 at 11 27 43" src="https://user-images.githubusercontent.com/1446269/205436525-00b6c0c9-c62d-4ad0-ba97-0e975529ca50.png">

**Comment by TatianaFomina** [comment]
Installed tunes were supposed to appear above the internal tools, though this behavior was broken in [v2.26.0](https://github.com/codex-team/editor.js/releases/tag/v2.26.0). The bug is fixed in [v2.26.2](https://github.com/codex-team/editor.js/releases/tag/v2.26.2)
