### ISSUE TITLE
[Bug] Images not pasting correctly while pasting from another website

### ISSUE THREAD

**Issue by medzhidov** [codex-team/editor.js#2206]
When you copy/paste images with content from another website or the same but from another tab it has empty `event.detail.data.src`. I tried this on various websites and articles/images, but everywhere the same behavior

Steps to reproduce:
1. Copy
<img width="913" alt="CleanShot 2022-12-05 at 12 10 34@2x" src="https://user-images.githubusercontent.com/11080873/205561866-4c87025e-4a1b-4b6c-a961-46dac19850e3.png">

2. Paste
<img width="887" alt="CleanShot 2022-12-05 at 12 11 12@2x" src="https://user-images.githubusercontent.com/11080873/205561951-7258c939-e4c4-4fe8-b570-ccc1fdc28660.png">

3. 
![CleanShot 2022-12-05 at 12 12 04@2x](https://user-images.githubusercontent.com/11080873/205562085-55f495a2-83d3-4344-ae12-32ef4ac75693.png)

Expected behavior: event.detail.data.src should has the src attribute because it has it in original

Device, Browser, OS: any browser, MacOS

Editor.js version: 2.26.1

Plugins you use with their versions: any plugin, problem in core paste.ts script

**Comment by medzhidov** [comment]
Uff, after several hours in sources i found that you should pass all attributes in pasteConfig:

```javascript
static get pasteConfig() {
        return {
            /**
             * Paste HTML into Editor
             */
            tags: [
                {
                    img: {
                        src: true,
                        alt: true
                    }
                }
            ],
        }
   }
```

Hope this helps somebody

**Comment by buranovite** [comment]
This should be in the documentation, thanks a lot

**Comment by akash1201** [comment]
when I try to copy paste from another blog, the image is being pasted twice. Rest content is fine.

editorjs/image V2.8.1
