### ISSUE TITLE
[Bug] Pasted HTML lists are empty

### ISSUE THREAD

**Issue by ollietreend** [codex-team/editor.js#2208]
Whenever I copy a HTML list (either a `<ul>` or `<ol>`) from the web, and paste it into an Editor.js instance, an empty list gets created. The list items are not populated.

This only seems to happen when pasting formatted text from an external application – i.e. where the clipboard data is in `text/html` format. Copying within or between Editor.js instances works as expected – presumably this is due to the clipboard data having the [custom mime type](https://github.com/codex-team/editor.js/blob/811a41366bbf8201105c12ef92f8c8abb907f028/src/components/modules/paste.ts#L115-L116) `application/x-editor-js` and therefore being processed differently.

### Steps to reproduce

1. Open the demo editor at [editorjs.io](https://editorjs.io/).
2. Copy this list directly from the GitHub issue.
3. Paste it into the editor. It will render as an empty ordered list.

### Expected behavior

I expect the `<li>` list items to be populated within the list block's `data.items` attribute. Instead, the `items` array is empty.

### Screenshots

https://user-images.githubusercontent.com/7735945/206200924-e4a22bd3-f797-4cce-8f7a-1b77f998ce25.mov

### Device, Browser, OS

I'm using macOS Monterey. I've been able to recreate the bug in Chrome, Brave, Firefox and Safari.

### Editor.js version

In local development, I've had issues with the current release, version 2.26.1. Presumably this is also what's running on the [Editor.js homepage demo](https://editorjs.io/).

### Plugins you use with their versions

I can recreate the issue in an Editor.js instance with only the default header, paragraph and list tools enabled.

**Comment by ollietreend** [comment]
### Investigation done so far

I've wrapped the `@editorjs/list` tool to inspect the element that gets passed into the [pasteHandler method](https://github.com/editor-js/list/blob/f0e9f0110983cd973a1345f2885b18db4fd54636/src/index.js#L433-L468).

```js
import List from '@editorjs/list';

class DebuggedList extends List {
  pasteHandler(element) {
    console.log(element);
    super.pasteHandler(element);
  }
}

export default DebuggedList;
```

When I paste using this DebuggedList tool, I get the following in the JS console:

<img width="1058" alt="JavaScript console" src="https://user-images.githubusercontent.com/7735945/206202623-79ab2a8b-8934-44de-9e4e-4276435bc3e6.png">

This strikes me as odd. I would have expected to see an `<ol>` containing `<li>` elements – since this is what I pasted. Instead, the `<li>`s seem to have been stripped, and the `<ol>` now only contains a single text node.

I've also noticed that the `<a>` link in the first item of the **Steps to reproduce** list has been stripped. Only the link text remains.

Has something replaced the child elements by setting `element.textContent`? 🤔 

### Test coverage

I can't see any obvious signs that this particular 'journey' has been tested. So I wonder if this could be a regression?

In the main [codex-team/editor.js](https://github.com/codex-team/editor.js) repo, the [Copy pasting from Editor](https://github.com/codex-team/editor.js/blob/next/test/cypress/tests/copy-paste.spec.ts) spec doesn't cover HTML lists. And I can't see any tests in the [editor-js/list](https://github.com/editor-js/list) repo.

**Comment by ollietreend** [comment]
### Regression in 2.26.0

It looks like this is a regression introduced in the recent version 2.26.0.

When I run the previous version (2.25.0) in a local dev environment, HTML lists paste correctly as expected.

**Comment by ollietreend** [comment]
I've done some more digging, and it looks like there's an easy workaround.

The [pasteConfig for List](https://github.com/editor-js/list/blob/f0e9f0110983cd973a1345f2885b18db4fd54636/src/index.js#L230-L234) contains uppercase tag names. Changing them to lowercase fixes the issue.

```diff
static get pasteConfig() {
  return {
-    tags: ['OL', 'UL', 'LI'],
+    tags: ['ol', 'ul', 'li'],
  };
}
```

It looks like the sanitizer config is now case sensitive, where it was previously case insensitive.

I think the regression was introduced by #2100, released in [v2.26.0-rc.1](https://github.com/codex-team/editor.js/compare/v2.26.0-rc.0...v2.26.0-rc.1). Ideally there would be a unit test to ensure that tag names are case insensitive.

**Comment by imransilvake** [comment]
same issue on v2.26.0.

**Comment by imransilvake** [comment]
I downgraded to v.2.25.0 until there is a fix for this issue. I would say this is a high-priority bug that is causing a lot of problems for the users pasting content.
