### ISSUE TITLE
[Bug] Typescript compiler errors when importing editorjs in SvelteKit project (preserveValueImports)

### ISSUE THREAD

**Issue by rajwilkhu** [codex-team/editor.js#2209]
Describe a bug.

Steps to reproduce:
1. Create a sveltekit project
2. install editorjs as an npm depenency
3. import editorjs as 
```typescript
import type EditorJS from '@editorjs/editorjs';
```
5. run linter with default rules and you get the following linter error
```
Error: 'BlockToolData' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.
       import {BlockToolData} from '../tools';
```

Expected behavior:
Typescript compiler should be compile project without errors

Screenshots:

Device, Browser, OS:

Editor.js version: 2.26.2

Plugins you use with their versions: None yet

**Comment by paolopiaggio** [comment]
+1 👍 
same error here, could be related to #1432
