### ISSUE TITLE
[Bug] Serious Issue Tab on Input opens the Menu after Update to v2.26.4

### ISSUE THREAD

**Issue by khanakia** [codex-team/editor.js#2228]
Describe a bug.

Steps to reproduce:
1. Go to https://editorjs.io/
2. Click on Caption Input on Image
3. Press Tab it is opening the Menu

Expected behavior: It should not open the menu

Screenshots:

https://user-images.githubusercontent.com/2174170/209351479-aad24e35-1007-41ca-8b33-897d395d2221.mov

Device, Browser, OS: Chrome

Editor.js version: [v2.26.4](https://github.com/codex-team/editor.js/releases/tag/v2.26.4)

Plugins you use with their versions:

**Comment by khanakia** [comment]
@neSpecc It will affect production for many users. 

We should patch it on a priority basis.

I hope you can understand.

**Comment by gkovats** [comment]
Is this a bug? It seems like tab has always navigated to the tune / toolbar. Maybe missing previous behavior.

**Comment by khanakia** [comment]
Not sure but I fixed it by adding custom keydown code and also there seem to be lots of bug with editor.js already.
```
  rootNode.addEventListener('keydown', (event) => {
      switch (event.code) {
        case 'Tab':
          this.tabHandler(event);
          break;
      }
    });
```
PS: If you just started using editor.js I would prefer to consider using https://lexical.dev/ that seems promising and also have active community support

**Comment by gkovats** [comment]
Thanks for the recommendation, sir.
