### ISSUE TITLE
[Bug]  DeepL Translate not allowing to save paragraph

### ISSUE THREAD

**Issue by gjorgiev** [codex-team/editor.js#2235]
There is a problem if you have  **DeepL Translate extension** installed in your browser. If you try to save the content you will get: **Block «paragraph» skipped because saved data is invalid**, even if you have text written in the paragraphs.

![chrome_0pBuMpbruN](https://user-images.githubusercontent.com/3934745/211557146-4a0067ad-4d23-430e-a34d-9d431692fb13.gif)

**Comment by rogepi** [comment]
eh...... Nevertheless, I'm very grateful that you found this bug, I just figured out why this is happening

**Comment by AlexRMU** [comment]
+1
Maybe the problem is in the extension and not in the editor.
In any case, it would be nice to see the stability of the editor with various extensions that affect the page in a certain way.

**Comment by sgbai78** [comment]
I'm having the same problem. I think it shouldn't be affected by any particular extension. There is no problem other than the paragraph, so I think it can be modified.

**Comment by MuhammadAhmedev** [comment]
> +1
> Maybe the problem is in the extension and not in the editor.
> In any case, it would be nice to see the stability of the editor with various extensions that affect the page in a certain way

I am facing same issue how to fix it ?
