### ISSUE TITLE
How to catch block focus, blur event?

### ISSUE THREAD

**Issue by intaek-h** [codex-team/editor.js#2236]
**Question**
I need to show a button only when the block is focused, but I can't find where to catch that event.

I found that the block elements, `<div class="ce-block"></div>` get a `ce-block--focused` class when they're focused. Any way to receive that state in the block?

<img width="419" alt="스크린샷 2023-01-11 오전 11 40 13" src="https://user-images.githubusercontent.com/108341074/211705378-6554e516-1129-45b3-95c5-2d2baf3a2694.png">
<img width="427" alt="스크린샷 2023-01-11 오전 11 40 18" src="https://user-images.githubusercontent.com/108341074/211705398-c288ee28-8104-48d3-a6e2-0b5764ca1218.png">

**Comment by PanicaCC** [comment]
Hi, I'm also interested

**Comment by lijie1129** [comment]
Maybe we can use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)

```javascript
// The editorjs is the holder of EditorJS
const holder = document.getElementById("editorjs");
const config = { attributes: true, childList: true, subtree: true, attributeOldValue: true };
const callback = (mutationList, observer) => {
  for (const mutation of mutationList) {
    if (mutation.type !== 'attributes' || mutation.attributeName !== 'class') {
      return;
    }

    const target = mutation.target;
    const classList = Array.from(target.classList || []);

    if (!classList.includes('ce-block')) return;

    const oldValue = mutation.oldValue.split(' ');

    if (classList.includes('ce-block--focused') && !oldValue.includes('ce-block--focused')) {
      console.log('--- the block focused ---', target);
    }
  }
};
const observer = new MutationObserver(callback);

observer.observe(holder, config);

// remember release observer
// observer.disconnect();
```

**Comment by intaek-h** [comment]
Update: Using `document.activeElement` could be more efficient in certain situations.

**Comment by intaek-h** [comment]
I ended up using the Mutation Observer. Below is the logic to find out the `focusedBlock`. However, it is not perfect. For example, if you see the `if (isNewBlockAdded)` condition block, I am setting the `focusedBlock` as the last `.ce-block` block even if a new block is actually added in between the blocks. It is because I didn't need to chase the actuall added block. So you will have to build more from here.
```javascript
initObserver() {
  const callback = (mutationList, observer) => {
    let focusedBlock = null

    mutationList.forEach(mutation => {
      if (mutation.type === 'attributes') {
        const previouslyUnfocused =
          !mutation.oldValue?.includes('ce-block--focused')
        const currentlyFocused =
          mutation.target.classList.contains('ce-block--focused')

        if (previouslyUnfocused && currentlyFocused) {
          focusedBlock = mutation.target
        }
      }

      if (mutation.type === 'childList') {
        const isNewBlockAdded =
          mutation.addedNodes.length === 1 &&
          mutation.target.classList.contains('codex-editor__redactor')
        const isBlockRemoved =
          mutation.removedNodes.length === 1 &&
          mutation.removedNodes[0] instanceof HTMLElement &&
          mutation.removedNodes[0].classList.contains('ce-block')

        if (isNewBlockAdded) {
          const editor = this.$refs.editorjs
          const blocksWrapper = editor.querySelector(
            '.codex-editor__redactor',
          )

          focusedBlock = blocksWrapper.lastChild
        }

        if (isBlockRemoved) {
          const hasUpperBlock = !!mutation.previousSibling

          if (hasUpperBlock) {
            focusedBlock = mutation.previousSibling
          }
        }
      }
    })

    if (focusedBlock && this.focusedBlock !== focusedBlock) {
      this.focusedBlock = focusedBlock
    }

    this.focusedBlock && this.repositionToolbar(this.focusedBlock)
  }

  this.observer = new MutationObserver(callback)
},
```

**Comment by intaek-h** [comment]
It's a shame that the EditorJS has very limited APIs for developers to use. If you are trying to build an editor out of EditorJS, remember that you have to use it as is. Don't try to customize it to your necessities. You will face many many obstacles that are very hard to overcome. 

If you want a customizable editor core, I suggest using Prosemirror or Quill. They are both serializable, and have much bigger communities.
