### ISSUE TITLE
Does Editorjs have the function of disabling editing?

### ISSUE THREAD

**Issue by LCattle** [codex-team/editor.js#2242]
When setting default data for, users are not allowed to operate, but can only see and click the link.
But it seems that the document does not have this function

**Comment by reregaga** [comment]
Maybe this link will be helpful
https://editorjs.io/configuration#read-only-mode
```js
editor.readOnly.toggle();
```

**Comment by neSpecc** [comment]
@reregaga thanks for the correct answer

**Comment by LCattle** [comment]
@reregaga thanks!
