### ISSUE TITLE
Is it possible to change the selection highlight color?

### ISSUE THREAD

**Issue by Saturnine-Softworks** [codex-team/editor.js#2243]
I'm working on incorporating EditorJS into an app I develop as a replacement for the (objectively worse) HTML WYSIWYG editor which I had made. The app has several color themes on the dark and light side, and I've been working on sifting through the CSS for EditorJS tools to figure out what I need to override. I've gotten most of the way there. 

One of the things I _can't_ seem to figure out is what setting needs to be changed to override the text selection color. Is this possible, or is it hardcoded into the JS side somewhere?

Thanks in advance.

**Comment by neSpecc** [comment]
Try to override this: 

https://github.com/codex-team/editor.js/blob/next/src/styles/ui.css#L115-L117

**Comment by Saturnine-Softworks** [comment]
> Try to override this:
> 
> https://github.com/codex-team/editor.js/blob/next/src/styles/ui.css#L115-L117

Thanks! I'm not sure how I overlooked this. Worked like a charm.
