### ISSUE TITLE
How to add ID to html blocks

### ISSUE THREAD

**Issue by SirMetathyst** [codex-team/editor.js#2246]
Hello, how can I go about adding the block Id from source json data to the html blocks in Id attribute. I want to use this in an anchor tag. 

I see there was a previous issue about this but it was closed without a solution. Is there a configuration option to enable such behaviour?

**Comment by williamsbs** [comment]
Hi,
I have found a solution to this issue, and it is quite easy to implement. Here are the steps to follow:

- Identify the HTML elements you want to add an ID to (in this example, I have used the class `ce-block`)
- Retrieve the blocks of data from your JSON source
- Iterate through each block and take its ID, then assign it to the corresponding HTML element

Here is an example of how to do this in code (note that this is just an example and will need to be adapted to your specific implementation):

```
const elements = document.getElementsByClassName("ce-block");

let content = this.pageContent // This is the pageContent from my editorJS source data

// Alternatively, you could retrieve the saved data like this:
editor.save().then((savedData: OutputData) => {
    content = savedData;
});

for (let i = 0; i < content.blocks.length; i++) {
    const blockId = content.blocks[i].id;
    elements[i].setAttribute("id", blockId);
}
```

And there you have it! Each div with the class of ce-block will now have the ID of its corresponding data block.

**Comment by SirMetathyst** [comment]
Thank you @williamsbs that is certainly one way of doing it. If I don’t find a built in way to do it I will use your solution. To be honest, it doesn’t make sense to me that each ce-block doesn’t have an id by default that matches the json data.
