### ISSUE TITLE
vickfredworth@gmail.com

### ISSUE THREAD

**Issue by fathers-love** [codex-team/editor.js#2260]
### Discussed in https://github.com/codex-team/editor.js/discussions/2259

<div type='discussions-op-text'>

<sup>Originally posted by **fathers-love** February  1, 2023</sup>
Project in mind. Need a volunteer programmer, can such one mail the subject mail address ....
such one should mail subject mail address asap.
Thanks.</div>

**Comment by neSpecc** [comment]
closed as spam
