### ISSUE TITLE
Scroll to top when popover_overlay clicked on iPhone Safari

### ISSUE THREAD

**Issue by intaek-h** [codex-team/editor.js#2261]
1. The browser scrolls to the top and scrolls back to where I was whenever I touch popover_overlay to close the popover.
2. Touching `+` button to add another block does not set caret to the newly created block.

First bug:
1. On my iphone 14 pro, I visited https://editorjs.io/
3. I clicked **Play With Demo** to try the editor on mobile.
4. typed some texts and touched **Block Tunes** button.
5. The popover showed up, and I touched the overlay to close the popover.
6. The browser scrolled to the top and scrolled back to where I was

Second bug:
1. write some text
2. touch `+` button and choose **Heading**
3. check if the caret is showing on a new block.
4. I had to touch the new block **twice** in order to get focus.

Expected behavior:

Screenshots:

https://user-images.githubusercontent.com/108341074/216000617-9fba71de-ee9b-4e83-b276-f642820e5c71.MP4

Device, Browser, OS: iPhone 14 Pro, Safari

Editor.js version: I faced this issue on 2023/02/01 GMT. So the version should be `2.26.5`?

Plugins you use with their versions:

**Comment by julianplop** [comment]
Same here.

**Comment by intaek-h** [comment]
Adding: I guess the problem is caused by the Safari's re-focusing algorithm. It scrolls the browser to where the caret is activated.

**Comment by korytovaf** [comment]
Has it been decided yet?
