### ISSUE TITLE
Toolbar gets cut off

### ISSUE THREAD

**Issue by alxppp** [codex-team/editor.js#2268]
When highlighting a text that's on the right end of the editor, the toolbar gets cut off:

![image](https://user-images.githubusercontent.com/4237216/217559148-9cae3d3a-4dd3-4c1c-8d14-5519e4af0ef8.png)

Do you have any pointer where to fix this?

**Comment by neSpecc** [comment]
Thanks for the report. The Inline Toolbar will be updated soon, so we'll try to include a fix for that as well.

**Comment by alxppp** [comment]
Thank you for the quick reply! Did the implementation already start? Is there something I can help out with?

**Comment by Clouds101** [comment]
Have you ever issued an update related to this issue?

**Comment by neSpecc** [comment]
Resolved by #2550
