### ISSUE TITLE
Cannot read properties of undefined error

### ISSUE THREAD

**Issue by tempcoderr** [codex-team/editor.js#2275]
I have written a editorjs code for nextjs and if I try to add inline toolbar, the code starts giving `Saving failed due to the Error TypeError: Cannot read properties of undefined (reading 'sanitizeConfig')` error and when I add some text to the editor, it throws `TypeError: Cannot read properties of undefined (reading 'create')` error.

Code:
```js
import React, { useState, useEffect, useRef } from "react";
import EditorJS from "@editorjs/editorjs";

const Editor2 = ({ holder }) => {
  const [editorData, setEditorData] = useState("");
  const ref = useRef();

  const initializeEditor = () => {
    const editor = new EditorJS({
      holder: holder,
      data: editorData,
      onReady: () => {
        ref.current = editor;
      },
      async onChange(api, event) {
          const data = await api.saver.save();
          onChange(data);
       },
      inlineToolbar: true,
      inlineToolbar: ["bold", "italic", "underline"],
    });
  };
  useEffect(() => {
    if (!ref.current) {
      initializeEditor();
    }
    return () => {
      if (ref.current && ref.current.destroy) {
        ref.current.destroy();
      }
    };
  }, []);
  return <div id={holder} />;
};
export default Editor2;
```

Screenshots:
![Error1](https://user-images.githubusercontent.com/117140065/219040637-bc39bcea-b6e1-499d-a20c-dca50138f098.png)
![Error2](https://user-images.githubusercontent.com/117140065/219040649-9991463f-242f-4503-8b21-e2aacd92b98a.png)

Editor.js version:
2.26.4

Plugins you use with their versions:
None

**Comment by neSpecc** [comment]
We don't have `underline` tool internally, and you haven't connected your own implementation of it, so remove it from the `inlineToolbar` config

```diff
- inlineToolbar: true,
- inlineToolbar: ["bold", "italic", "underline"],
+ inlineToolbar: ["bold", "italic"],
```
