### ISSUE TITLE
Attached files don't show in read mode, only in edit mode.

### ISSUE THREAD

**Issue by minhluudinh** [codex-team/editor.js#2309]
Attached files don't show in read mode

Steps to reproduce:
1. Go to https://docs.codex.so/getting-started
2. Follows the steps to set up the project
3. Install @editorjs/attaches, run "npm start" & add files.

Expected behavior: attached files are shown in read mode

Screenshots:

![Screenshot_20221118_154205](https://user-images.githubusercontent.com/63277221/225693293-f1113983-85c2-4b07-bfaf-cca7fec4622b.png)

![2](https://user-images.githubusercontent.com/63277221/225692570-b571b508-3b94-411a-a038-1fb22a2d9a6a.png)
b7.png)
![3](https://user-images.githubusercontent.com/63277221/225692591-e19e420d-fdd4-48b5-93f5-551cf3102de1.png)

Device, Browser, OS: Chrome (Windows 11)

Editor.js version: "@editorjs/editorjs": "^2.25.0"

Plugins you use with their versions:  "@editorjs/attaches": "^1.3.0"

**Comment by neSpecc** [comment]
Duplicates https://github.com/editor-js/attaches/issues/72
