### ISSUE TITLE
Add an extra setting to all block types

### ISSUE THREAD

**Issue by tregismoreira** [codex-team/editor.js#2323]
I started playing with Editor.js a few days ago, and I gotta say it's been fun!

One thing that came up is the need for adding an extra "Add border" option in the block tune options. This should apply to all block types, from both core and custom plugins.

I know I could extend the original class and add my customizations, 

```
import Header from "@editorjs/header";

class MyHeader extends Header {
  // customizations here
}

export default MyHeader
```

But it would require me to do it for each plugin. Besides, I'd need to replicate some code to prevent the default settings to be overwritten.

That's why I wanted to find a way to write once and apply to all block types.

Is that possible? I could not find anything in the documentation :(

Thank you in advance.

**Comment by gohabereg** [comment]
Hi @tregismoreira 
It seems you can make use of Block Tunes API — https://editorjs.io/block-tunes-api/
