### ISSUE TITLE
Pasting header is broken

### ISSUE THREAD

**Issue by ssowonny** [codex-team/editor.js#2325]
After updating the version from 2.27.0-rc.3 to 2.27.0-rc.4, pasting header is not working correctly. Not like other blocks, "text" field in the header gets an empty string when `save(toolsContent)` of the Header plugin is called.

Steps to reproduce:
1. Copy text, including headers. (I attached the example below.)
2. Paste it to EditorJS.
3. Save the content and check if the headers are still there.

Example copy text:

#### header example

paragraph example.

Expected behavior:
The header should be saved.

Screenshots:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/412544/229079947-d1a743e7-1032-4f6b-a339-192b8f39b4bc.png">
<img width="419" alt="image" src="https://user-images.githubusercontent.com/412544/229079879-9bdbf89f-971a-4e97-a6cf-1143034a6765.png">

Device, Browser, OS: Macbook Air M2, Chrome, OSX

Editor.js version: 2.27.0-rc.4

Plugins you use with their versions:

Header, Paragraph

**Comment by ssowonny** [comment]
https://github.com/editor-js/header/blob/master/src/index.js#L253
I guess it's because the header block replaces the element.

**Comment by neSpecc** [comment]
I can confirm the problem, and yes, it's related to my recent change. I'll fix it soon.

**Comment by manusanchev** [comment]
Still happening, any updates?

**Comment by neSpecc** [comment]
I'm working on that
