### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by meiyasan** [codex-team/editor.js#2336]
I was using a WYSIWIG engine and Editor JS looks great..
I would like to switch but I have to check some features.

Is there some way for this JSON output to be converted into HTML... server-side ? 
I have some parsing and post-processing done with PHP. 
So if the block are rendered at runtime this would make some of my current implementation unusable

I saw some snippet, but I am really not sure this is complete feature
https://devsheet.com/code-snippet/editorjs-blocks-json-to-html-javascript/

**Comment by neSpecc** [comment]
All you need to do is to iterate through the blocks and pass each of them to a separate template using regular switch-case. Just like in your example

**Comment by meiyasan** [comment]
Sorry I forgot to close earlier, that eventually what I ended up doing :)
Many thanks for the reply!

**Comment by pachecotatih** [comment]
how to make html to blocks editorjs?
