### ISSUE TITLE
Heading Tags are not working in React^18.2.0

### ISSUE THREAD

**Issue by pinak3748** [codex-team/editor.js#2344]
Describe a bug:
The header tag is not working in the EditorJS library in the React project. When using the code as mentioned above, the header tag is not being rendered properly.

Steps to reproduce:
- Import the EditorJS library in a React project using the code mentioned above.
- Use the "header" tool to create a header.
- Check if the header is being rendered properly.

 Expected behavior:
The header tag should be rendered properly and displayed on the webpage.

Screenshots:
N/A

Device, Browser, OS:
Device: Desktop/Laptop
Browser: Chrome (64-bit)
OS: Windows 10 Home

Editor.js version:
"@editorjs/editorjs": "^2.26.5"

**Comment by neSpecc** [comment]
> is not being rendered properly

Please, provide more details.
