### ISSUE TITLE
Ability to extend LinkInlineTool

### ISSUE THREAD

**Issue by CharlRitterDev** [codex-team/editor.js#2352]
Is there a way to extend the LinkInlineTool class? 

We are trying to extend the LinkInlineTool [here](https://github.com/codex-team/editor.js/blob/next/src/components/inline-tools/inline-tool-link.ts#L35) to allow us to pass our own property on the a tag, without it being filtered out.

However, there's no way to import and extend this class. Is there a workaround?

**Comment by sergio-itru** [comment]
https://github.com/trinhtam/editorjs-hyperlink something like this? or you can create your own plugin, check docs https://editorjs.io/the-first-plugin/
