### ISSUE TITLE
Delete block not working correctly

### ISSUE THREAD

**Issue by htoann** [codex-team/editor.js#2386]
Describe a bug.
When I select the entire text of the block (eg paragraph) and press the backspace button the event doesn't detect the change and doesn't fire any event.

Steps to reproduce:
1. Go to …
2. Click on …
3. …

Expected behavior: Editor onchange emits "block-changed" event

Screenshots:

Device, Browser, OS:

Editor.js version:

Plugins you use with their versions:

**Comment by tunngtv** [comment]
I am also experiencing a similar issue where, when I select the entire text in a block and delete it using the delete button, no event is triggered. The selected text block appears to be deleted, but the original data remains unchanged.

https://github.com/codex-team/editor.js/assets/43735484/09a485db-f574-4294-8149-45093d998054
