### ISSUE TITLE
Getting unexpected error on selcting the paragraph and heading blocks,

### ISSUE THREAD

**Issue by cptiwari20** [codex-team/editor.js#2389]
When I try to select the Text in the editorjs it is throwing erros.

I am using blockTunes for text alignment and anchor, and I tested after removing that, still have same issue.
I thought it may be something related to checklist block, i have also removed it, issue still persisit.
I have no idea what is happening?
Please help me out.

Error is - 
`this.popover.addEventListener is not a function
TypeError: this.popover.addEventListener is not a function
    at c.connectedCallback (http://localhost:3000/static/js/vendors-node_modules_editorjs_checklist_dist_bundle_js-node_modules_editorjs_delimiter_dist_b-d79937.chunk.js:35273:30)
    at o.value (http://localhost:3000/static/js/vendors-node_modules_editorjs_checklist_dist_bundle_js-node_modules_editorjs_delimiter_dist_b-d79937.chunk.js:10968:63)
    at http://localhost:3000/static/js/vendors-node_modules_editorjs_checklist_dist_bundle_js-node_modules_editorjs_delimiter_dist_b-d79937.chunk.js:10958:17
    at Array.forEach (<anonymous>)`

Screenshots:
**
![image](https://github.com/codex-team/editor.js/assets/33618258/d2575b2a-3bff-4b0e-8113-27cb396834a4)
**

Device, Browser, OS: Mac/Win/Linux, Chrome, MS Edge

Editor.js version: ^2.26.2
Plugins you use with their versions:  "@editorjs/checklist": "^1.4.0",
    "@editorjs/delimiter": "^1.3.0",
    "@editorjs/editorjs": "^2.26.2",
    "@editorjs/embed": "^2.5.3",
    "@editorjs/header": "^2.7.0",
    "@editorjs/image": "^2.8.1",
    "@editorjs/inline-code": "^1.4.0",
    "@editorjs/link": "^2.5.0",
    "@editorjs/marker": "^1.3.0",
    "@editorjs/nested-list": "^1.3.0",
    "@editorjs/paragraph": "^2.9.0",
    "@editorjs/quote": "^2.5.0",
    "@editorjs/raw": "^2.4.0",
    "@editorjs/table": "^2.1.2",
    "@editorjs/warning": "^1.3.0",
 "editorjs-drag-drop": "^1.1.13",
    "editorjs-hyperlink": "^1.0.6",
    "editorjs-inline-spoiler-tool": "^1.0.1",
    "editorjs-parser": "^1.5.3",
    "editorjs-text-alignment-blocktune": "^1.0.3",
    "editorjs-text-color-plugin": "^2.0.2",
    "editorjs-undo": "^2.0.21",

**Comment by neSpecc** [comment]
We don't have `this.popover.addEventListener` code in the Editor.js core. And in the Checklist tool as well. So this problem is not related to this repo.

Try to find that code in your bundle and get the exact module.
