### ISSUE TITLE
Removes Id prop after save() for every second block  

### ISSUE THREAD

**Issue by TihomirGG** [codex-team/editor.js#2403]
Hello guys. I really enjoy the flexibility of the editor but I think I found a problem. When the editor saves the blocks, every second object is without the id prop

This is the data https://pastebin.com/zwKWt0jq which I pass to the editor when I am initializing it and this is what I receive when I call ` editor.save() `  https://pastebin.com/4g49ccuQ

I am using Google Chrome

Editor.js version: 2.27.0

Using: nestedCheckList, Underline, Striketrough

This is a screenshot of how I initialise the editor .
![image](https://github.com/codex-team/editor.js/assets/50490954/704ef702-a43c-4fef-b906-8f3cc34f97d4)

**Comment by neSpecc** [comment]
Can't reproduce. Looks like a problem is on your side. 

Try passing saved data using `data` property as mentioned in docs:
https://editorjs.io/configuration/#passing-saved-data

**Comment by TihomirGG** [comment]
I added ` time ` and ` version ` prop in the ` data ` object but still have the same problem. However thanks for the fast response

**Comment by TihomirGG** [comment]
Today I saw that every new block dont have id after saving

**Comment by neSpecc** [comment]
Ids in your example looks customised, so check your logic again. The problem is most likely on your side. Or provide a reproducible demo and I'll reopen an issue.

**Comment by TihomirGG** [comment]
Those are mongos ObjectIds.  Are we sure that these Ids from the editor will always be unique?

**Comment by TihomirGG** [comment]
and yeah when I stop working with them everything is alright. Thanks for the guidance
