### ISSUE TITLE
save

### ISSUE THREAD

**Issue by QiaoJC-ac** [codex-team/editor.js#2428]
hi，save seems to get only blocks with non-empty content. Is there any way to get all blocks (including blocks with non-empty content)?

**Comment by QiaoJC-ac** [comment]
So far I've found that I can only change the validate method in each tool and when it returns true even if it's empty, the save method will get the block
  validate() {
    return true
    // return blockData.text.trim() !== ''
  }

**Comment by aacoelho** [comment]
I was looking for something similar just for the paragraph and found that the [editorjs/paragraph](https://github.com/editor-js/paragraph) has the `preserveBlank` config parameter. If you define it as `true` it will save empty paragraphs.
I didn't check every other block, but at least for the paragraph it's possible without having to change the source code of the block.
