### ISSUE TITLE
Deleting Characters in New Blocks

### ISSUE THREAD

**Issue by chative-phuc** [codex-team/editor.js#2429]
Description:
I'm not sure if anyone has raised this bug before, so I wanted to report it. When creating a new block and adding a few spaces before a word, if the cursor is positioned at the start of the word and I press the Delete button (or <- Back button), the entire block is deleted instead of just one character.

Steps to Reproduce:
(I used your demo website to reproduce the bug, so you should be able to replicate it)

1.Go to your demo website: https://editorjs.io/
2.Enter some random text.
3.Place your cursor at the center of the text or somewhere else and press Enter (to create a new block).
4.Add some spaces before that word and click the Delete button (or <- Back button), and you will see the bug occur.
Expected Behavior:
Only one character should be deleted, not the entire block.

Browser:
Chrome, OS: Windows 11
Editor.js version: None

**Comment by chative-phuc** [comment]
Link video reprod bug
https://drive.google.com/file/d/1boiA0ShwTpaeaPGNFHkF3tsOCdWRwSCm/view?usp=sharing

**Comment by chative-phuc** [comment]
![image](https://github.com/codex-team/editor.js/assets/128776850/8463d05d-ce57-4ed9-9b9d-ba06f9b6f9f2)

I have identified the issue here. It look like the issue with the logic in the 'Caret.isAtStart' condition is that it doesn't cover the situations where there's a space before the caret. Hope this can assist you in resolving the problem

**Comment by dewly-tra** [comment]
![Screenshot 2023-08-11 at 14 47 11](https://github.com/codex-team/editor.js/assets/72931531/90a508eb-3c0a-417a-bac2-caeff8a7b283)
I believe this is the root cause of the issue:
let firstLetterPosition = focusNode.textContent.search(/\S/);`

**Comment by dewly-tra** [comment]
The firstLetterPosition always equals 0 when there is a space before the caret.

**Comment by dewly-tra** [comment]
I think it should be replaced with:
```
let match = focusNode.textContent.match(/^\s*(\S)/);
let firstLetterPosition = match ? match.index + match[0].length : 0;
```
