### ISSUE TITLE
Embed tool not appearing on the front-end

### ISSUE THREAD

**Issue by oyatek** [codex-team/editor.js#2435]
Describe a bug.

Steps to reproduce:
1. Add @editorjs/embed tool
2. See the front-end

Expected behavior: get embed tools in the editor

Screenshots: 

![image](https://github.com/codex-team/editor.js/assets/1853136/ac813ce0-a4e0-4663-a410-25f8bbef4e5a)

![image](https://github.com/codex-team/editor.js/assets/1853136/7386c9a5-270c-4d9d-9bec-fe7392660cf7)

Device, Browser, OS: Chrome, OSX

Editor.js version: latest

**Comment by neSpecc** [comment]
Wrong repo

**Comment by oyatek** [comment]
Yes I know but it looks like the "@editor-js/embed" repo is abandoned and issues are never replied there - so I decided to ask here.
