### ISSUE TITLE
EditorJS doesn't render in PROD after vite build

### ISSUE THREAD

**Issue by fitterfizzle** [codex-team/editor.js#2451]
When starting the dev environment of our app with `vite` the editorJS renders just fine:

<img width="560" alt="image" src="https://github.com/codex-team/editor.js/assets/96863959/6dd2314d-99e8-46d8-bace-99841218c983">

However after building the app for production with `vite build`, the same container doesn't render the editor itself:

<img width="372" alt="image" src="https://github.com/codex-team/editor.js/assets/96863959/d7911d4a-4b2e-4a6f-8b8f-ec9048cbb658">

There are no error messages in the console.

In `package.json`, type is already set to `module`.

Are we missing anything special to make it work in production mode?

**Comment by neSpecc** [comment]
It depends on your implementation. How do you initialize the editor?

**Comment by fitterfizzle** [comment]
```js
const GenericEditorJS = forwardRef(
  (
    { readOnly, data, onChange, onReady, autofocus, holder, minHeight = 20 },
    ref,
  ) => {
    const { t } = useTranslation();
    const ejInstance = useRef();

    const holderId = useMemo(() => {
      return holder ?? "editorjs";
    }, []);

    const initEditor = () => {
      const editor = new EditorJS({
        holder: holderId,
        onReady: () => {
          ejInstance.current = editor;
          if (ref) ref.current = editor;
          !!onReady && onReady();
        },
        autofocus,
        placeholder: t("editorjs-placeholder"),

        data,
        onChange,
        tools: EDITOR_JS_TOOLS,
        minHeight,
        readOnly,
      });
    };

    useEffect(() => {
      if (ejInstance.current === null) {
        initEditor();
      }

      return () => {
        ejInstance?.current?.destroy();
        ejInstance.current = null;
        if (ref) ref.current = null;
      };
    }, []);

    return <div id={holderId} />;
  },
);
```

**Comment by fitterfizzle** [comment]
Thank you for supporting, and importing like this:

```js
import EditorJS from "@editorjs/editorjs";
```

**Comment by fitterfizzle** [comment]
> ```js
> const ejInstance = useRef();
> ```

I think we found the issue, this has to be initialized to `null` so that the check in `useEffect` against `null` works.
