### ISSUE TITLE
"v-show" led to add the class ''codex-editor--narrow'' incorrectly

### ISSUE THREAD

**Issue by chf-gh** [codex-team/editor.js#2457]
I use "v-show" control the editor show or hidden, But when the editor show the "+" button and "option" button come to the right, I found the editor add the class "codex-editor--narrow" automatically . It makes the layout wrong.

Has that happened to anyone?

Here is my code:
```html
<div id="editorjs" v-show="flag"></div>
```
This is the result:

![image](https://github.com/codex-team/editor.js/assets/20312535/e3b05d61-19fc-47e7-b198-c6c596a925d1)

**Comment by neSpecc** [comment]
Narrow mode depends on holder width. It is enabled when the width is not enough.

**Comment by chf-gh** [comment]
> Narrow mode depends on holder width. It is enabled when the width is not enough.

The width of the component is definitely long enough , If "v-show" is not used, it will be displayed normally on the left,Whether the "v-show" affects the length determination within the component ?

**Comment by neSpecc** [comment]
You're probably initializing the editor even when `v-show=false`. Try to initialize it only when an element is shown.

P. S. I think, the Narrow-mode will be removed in one of the next releases. We will find a better solution for thin containers.

**Comment by chf-gh** [comment]
> You're probably initializing the editor even when `v-show=false`. Try to initialize it only when an element is shown.即使 `v-show=false` ，您也可能正在初始化编辑器。尝试仅在显示元素时对其进行初始化。
> 
> P. S. I think, the Narrow-mode will be removed in one of the next releases. We will find a better solution for thin containers.P.S. 我认为窄模式将在下一个版本中被删除。我们将为薄型容器找到更好的解决方案。

Thank you for your answer, I have used a absolute element cover it up instead of use "v-if" controle it.
