### ISSUE TITLE
Some blocks skipped on saving after pasting as HTML

### ISSUE THREAD

**Issue by kaaaaaaaaaaai** [codex-team/editor.js#2481]
Steps to reproduce:

https://codesandbox.io/embed/busy-sky-rv7z97?fontsize=14&hidenavigation=1&theme=dark

1. go to editorjs document, and copy text contains Header text
2. access codesandbox, paste text and save button.
3. skip header text, `Block «header» skipped because saved data is invalid ` output  in console

Expected behavior:

save header text,

Screenshots:
<img width="519" alt="スクリーンショット 2023-09-15 10 50 00" src="https://github.com/codex-team/editor.js/assets/2194021/1664f246-5883-4f49-b845-4e3d36584205">

Device, Browser, OS:
maybe all.
mac M1, Chrome

Editor.js version:

Plugins you use with their versions:
    "@editorjs/editorjs": "2.28.*",
    "@editorjs/header": "2.7",

**Comment by kaaaaaaaaaaai** [comment]
@neSpecc @gohabereg 
However, headers written directly in the editor are saved.

**Comment by neSpecc** [comment]
I've managed to reproduce it in Firefox. I'll check, thanks

**Comment by neSpecc** [comment]
The fix is available at `2.28.1` and `2.29.0-rc.2`
