### ISSUE TITLE
Typescript Types

### ISSUE THREAD

**Issue by ainsleyclark** [codex-team/editor.js#2500]
Hey

Is there anyway to import just `/types` for an external project? On `DefinitelyTyped` I believe there is only the individual components.

I'm also wondering if there's a collection of types with each component?

**Comment by CHE1RON** [comment]
Bumping this. I cannot find Typescript types anywhere 😭 Have you found a way to deal with this, @ainsleyclark? 🙏

**Comment by sebmeister2077** [comment]
What version are you using @ainsleyclark ?

**Comment by neSpecc** [comment]
You can access editor js types right from the package

```ts
import Editor, { type OutputData, type API } from '@editorjs/editorjs';
```
