### ISSUE TITLE
2.28.1 spams to console didMutated & etc

### ISSUE THREAD

**Issue by morskoyzmey** [codex-team/editor.js#2512]
I've updated to this version (I like manually choose version number instead of @latest) and got fixed copy-paste-header-not-saving-bug (thanks!), but now my console is spamed with 

mutationBelongsToBlock false [MutationRecord] editorjs@2.28.1?_=1697399672600:16 
mutationBelongsToBlock false [MutationRecord] editorjs@2.28.1?_=1697399672600:16
...

when I edit blocks.

The issue is here (at least):

![image](https://github.com/codex-team/editor.js/assets/2198173/390ad74e-026f-49b6-99b6-ea05c2807e53)
![image](https://github.com/codex-team/editor.js/assets/2198173/ac10ee15-f672-46cc-9ff8-bc77f0143327)

**Comment by neSpecc** [comment]
Fixed in `2.28.2`
