### ISSUE TITLE
Could add "id" in the ce-block?

### ISSUE THREAD

**Issue by CharlieCho2017** [codex-team/editor.js#2529]
Could also add "id" in the ce-block when adding " data-id"? I want to use id in an anchor tag. 
![image](https://github.com/codex-team/editor.js/assets/28870006/2a5a14e8-66ca-40ea-aa6d-34f6981e8f73)

**Comment by milu2003** [comment]
How did you solve it in the end?

**Comment by neSpecc** [comment]
You can do it manually after editor is loaded. Or you can scroll a page by js to a particular `[data-id]` element
