### ISSUE TITLE
Header elements aren't aligned with the toolbar actions

### ISSUE THREAD

**Issue by andyjessop** [codex-team/editor.js#2536]
<img width="234" alt="Screenshot 2023-11-13 at 22 07 13" src="https://github.com/codex-team/editor.js/assets/1304307/6149479b-1f15-4fe5-8471-07a6d7f81e89">

When the header is larger than level 4, the alignment is off.

Expected behavior:
I would expect the toolbar to line-up with the centre of the header.

Editor.js version: ^2.28.2

Plugins you use with their versions: Heading and Paragraph

**Comment by BasicallyPolaris** [comment]
Has anyone found a solution to this issue? I am unsure how to fix it as the styling for the positioning of the menu is applied inline, thus I assume editorjs itself manages the positioning of the menu depending on the row you are on (maybe by getting the wrapping div height and then adding a fixed offset ?) 

Would love to know if anyone managed to fix it :)
