### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by farazalidev** [codex-team/editor.js#2537]
Describe a bug.

When i start writting something, it throws an error "TypeError: Cannot read properties of undefined (reading 'length')"

Steps to reproduce:
1. Go to …
2. Click on …
3. …

Expected behavior:

Screenshots:
![Screenshot from 2023-11-15 15-55-20](https://github.com/codex-team/editor.js/assets/115402976/68fe660c-3037-4fcd-ac17-07d89d804db4)

Device: HP pavilion 500 PC series,
Browser:Chrome Version 119.0.6045.123,
 OS:Ubuntu 23.04

Editor.js version:2.28.2

Plugins you use with their versions:
 "@editorjs/header": "^2.7.0",
    "@editorjs/list": "^1.8.0",
    "@editorjs/table": "^2.2.2",
    "editorjs-html": "^3.4.3",
    "editorjs-inline-tool": "^0.4.0",
    "editorjs-paragraph-with-alignment": "^3.0.0",
    "editorjs-text-alignment-blocktune": "^1.0.3",
   "@editorjs/image": "^2.8.2",
   "editorjs-change-case": "^0.0.3",
   "editorjs-undo": "^1.0.1",

editorJs File: [File](https://gist.github.com/farazalidev/1840f894ba1c08828bdb402b6d1a73dd
)

**Comment by neSpecc** [comment]
Would you provide a full stack trace?
