### ISSUE TITLE
TypeError: Spread syntac requires ...iterable[Symbol.iterator] to be a function

### ISSUE THREAD

**Issue by dtdetwiller** [codex-team/editor.js#2567]
I am looking for guidance on how to fix this error I am getting. I have an app using Cordova. EditorJS works on the Web version, but not on iOS. Here is the error:

![Screenshot 2023-12-19 at 10 37 23 AM](https://github.com/codex-team/editor.js/assets/47906927/cef55383-a537-4225-ba97-244e1b32ad14)

If this is not the right place to ask this question, please let me know where to ask this. Thanks!

**Comment by neSpecc** [comment]
Seems like this issue is not related to Editor.js. It's better to ask it at the Cordova community.
