### ISSUE TITLE
ReferenceError: Element is not defined | Remix js

### ISSUE THREAD

**Issue by fzsf163** [codex-team/editor.js#2590]
Describe a bug.
I am using Remix js. 
versions:
`"@remix-run/css-bundle": "^2.4.1",
    "@remix-run/express": "^2.4.1",
    "@remix-run/node": "^2.4.1",
    "@remix-run/react": "^2.4.1",`

I wanted to try editor js, I installed, called instance then ran the app. And this error showed up.

Steps to reproduce:
1. install as doc says `npm i @editorjs/editorjs --save`
2. npm run dev
3. error should show up [it did in my case]

Expected behavior: To run editor js on remix

Screenshots:
error :
![Screenshot 2024-01-19 184603](https://github.com/codex-team/editor.js/assets/86884235/65a53e38-e0ad-4563-909b-7aa14f55a91f)

Editor JS declare :
![Screenshot 2024-01-19 184817](https://github.com/codex-team/editor.js/assets/86884235/ef528bac-d3f8-48e6-9180-e98de440e582)

Call Editor JS:
![Screenshot 2024-01-19 184832](https://github.com/codex-team/editor.js/assets/86884235/2297f98c-ee14-4940-9ab2-5d852d8aea14)

Device, Browser, OS: 64-bit operating system, x64-based processor , AMD Ryzen 5 5600 6-Core Processor  ,Windows 11 version 22621.3007 , Chrome Version 120.0.6099.225 (Official Build) (64-bit)

Editor.js version:   "@editorjs/editorjs": "^2.28.2",

Plugins you use with their versions: none

**Comment by gohabereg** [comment]
Hi,
According to the log, the code is running in the NodeJS environment where `Element` is not defined as well as other browser APIs.
EditorJS is a client library, so you need to set up your project to not run EditorJS code on the server.

Closing the issue as it is not an EditorJS bug

**Comment by fzsf163** [comment]
> Hi, According to the log, the code is running in the NodeJS environment where `Element` is not defined as well as other browser APIs. EditorJS is a client library, so you need to set up your project to not run EditorJS code on the server.
> 
> Closing the issue as it is not an EditorJS bug

thank you sir, I will look into it.

**Comment by fzsf163** [comment]
I fixed it. Now it renders.

**Comment by jsgv** [comment]
@fzsf163 Could you share your solution?

**Comment by fzsf163** [comment]
> @fzsf163 Could you share your solution?

yes sure.
the components that require to be rendered on client must be inside `<ClientOnly/>`, And if you have say a file named `Component.tsx` that has imports (like say editor js) that needs to be rendered on client, you simply name it `Component.client.tsx`, this `*.client.tsx` forces remix to render that components entirely on client side. To make it render only server side just change the `*.client.tsx` to `*.server.tsx`. Then when you call that component on any file and put that inside `<ClientOnly>{ ()=> (<Component/>) }<ClientOnly/>`. Install remix-utls to get client-only component.

Example :

Editor.client.tsx
```
import EditorJS from "@editorjs/editorjs";

export default function Editor() {
  const editor = new EditorJS({
    /**
     * Id of Element that should contain the Editor
     */
    holder: "editorjs",

    /**
     * Available Tools list.
     * Pass Tool's class or Settings object for each Tool you want to use
     */
  });
  return <div id="editorjs"></div>;
}

```
then I `<Editor/>` inside `Blog-Page.tsx` route
```
import { ClientOnly } from "remix-utils/client-only";
import Editor from "~/components/EditorJS.client"

  <ClientOnly fallback={<p>Loading Editor Please Wait...</p>}>
          {() => (
              <Editor></Editor> 
          )}
   </ClientOnly>
```
