### ISSUE TITLE
Cannot find module 'codex-notifier' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ilirbeqirii** [codex-team/editor.js#2591]
Describe a bug.

Cannot find module 'codex-tooltip' or its corresponding type declarations.
Cannot find module 'codex-notifier' or its corresponding type declarations.

Expected behavior:

Screenshots:

Device, Browser, OS:

Editor.js version: 2.28.2

Plugins you use with their versions: Initial ones

**Comment by sandrooco** [comment]
See also #2390 - did you find out anything regarding this?

**Comment by ilirbeqirii** [comment]
> See also #2390 - did you find out anything regarding this?

nah man, needed to install these two deps for this issue to go away. Surprisingly none of the maintainers are responding back.

**Comment by Sozialarchiv** [comment]
Here another duplicate: #2462

**Comment by Sozialarchiv** [comment]
Both packages are in the devDependcies:

https://github.com/codex-team/editor.js/blob/next/package.json#L53

I think both packages should be in dependencies. The imports are not only types:

https://github.com/codex-team/editor.js/blob/eb7ffcba3c1387404a61046bb9360ae1cd926efc/src/components/utils/notifier.ts#L7
https://github.com/codex-team/editor.js/blob/eb7ffcba3c1387404a61046bb9360ae1cd926efc/src/components/utils/tooltip.ts#L5
