### ISSUE TITLE
Slash doesn't open toolbox

### ISSUE THREAD

**Issue by fitterfizzle** [codex-team/editor.js#2597]
With v2.29.0 Tab doesn't open the Toolbox anymore since it was changed to slash.

However, when typing a "/" in an empty line, the toolbox doesn't appear, only the slash gets typed.

**Comment by neSpecc** [comment]
We need more information on how this problem could be reproduced.

Do you have any tools connected?

**Comment by fitterfizzle** [comment]
We are using following tools:

```js
{
  header: Header,
  table: Table,
  list: NestedList,
  checklist: CheckList,
  warning: Warning,
  code: Code,
  embed: Embed,
  raw: Raw,
  quote: Quote,
  delimiter: Delimiter,
  underline: Underline,
  marker: Marker,
  inlineCode: InlineCode,
  simpleImage: SimpleImage,
}
```

Tried also disabling all tools but still no toolbox shows up when typing the "/"

**Comment by fitterfizzle** [comment]
As an additional information, editor.js is being used in a react environment.

**Comment by neSpecc** [comment]
Try demo on editorjs.io. Does it work for you?

**Comment by fitterfizzle** [comment]
Just tried on the homepage, it also doesn't work there:

<img width="1138" alt="SCR-20240126-kkpb" src="https://github.com/codex-team/editor.js/assets/96863959/eddb95a8-d83c-46e3-ad45-baac73dd5992">

Just one additional piece of information, have been testing this on a Mac.

**Comment by ilyamore88** [comment]
Reproducible with Spanish layout in Chrome on MacOS.

Hi @fitterfizzle. Could you please also provide the information about your keyboard layout and browser?

**Comment by fitterfizzle** [comment]
CH layout and Chrome. However just tested it with Safari and there it works.

**Comment by ilyamore88** [comment]
Same for Spanish layout. I believe Chrome has different key codes for the Slash button in some layouts.

**Comment by neSpecc** [comment]
@fitterfizzle would you test it in `2.29.1`?

**Comment by fitterfizzle** [comment]
Testing with `2.29.1` and it appears to be working for my case. Thank you!
