### ISSUE TITLE
Customise Toolbox Icon

### ISSUE THREAD

**Issue by olibooty** [codex-team/editor.js#2615]
Is it possible to customise the Toolbox/ Toolbar/ Tunes icon?

The six dots icon.

> <img width="187" alt="Screenshot 2024-02-13 at 13 01 31" src="https://github.com/codex-team/editor.js/assets/27422045/fc7a9b6a-da3e-4e7f-8dbf-63f7e6394bf4">

If it is already possible, I can't find it in the documentation. It would be useful to have it better documented if that's the case

Apologies if I am using the wrong nomenclature, I couldn't figure out which is the correct terminology to use

**Comment by neSpecc** [comment]
You can use CSS overrides as a workaround. 

P.S. Could you share, what icon do you prefer?

**Comment by olibooty** [comment]
Thanks @neSpecc. Am currently using font awesome in a next app. So the standard import probably won't work
