### ISSUE TITLE
Do not understand documanetation

### ISSUE THREAD

**Issue by fzsf163** [codex-team/editor.js#2617]
The question.
How to use types for tools?
Why and how the question has come up.
If you use TypeScript you need to explicitly specify that typeof Tool implements BlockToolConstructable or InlineToolConstructable

How and where ?

```
import EditorJS, {
  BlockToolConstructable,
  InlineToolConstructable,
} from "@editorjs/editorjs";
import Header from "@editorjs/header";
import List from "@editorjs/list";
export default function Editor() {
  const editor = new EditorJS({
    holder: "editorjs",
    tools: {
      header: {
        class: Header,
      },
    },
  });
  return <div id="editorjs"></div>;
}

where do you add it? 
```

**Comment by neSpecc** [comment]
Maybe this example will help https://github.com/codex-team/editor.js/blob/next/test/cypress/fixtures/tools/ToolMock.ts

**Comment by fzsf163** [comment]
> Maybe this example will help https://github.com/codex-team/editor.js/blob/next/test/cypress/fixtures/tools/ToolMock.ts

no sir it does not, i will just use `//@ts-ignore`

**Comment by neSpecc** [comment]
See https://github.com/codex-team/editor.js/issues/2143
