### ISSUE TITLE
Are you aware of that method .on doesn't work properly?

### ISSUE THREAD

**Issue by KamGor** [codex-team/editor.js#2620]
Method .on doesn't register listener on events. More of it you don't added anywhere events list.

Expected behavior: Change of model should fire change event or something else but it doesn't work.

Editor.js version: 2.29.0

**Comment by keremnymn** [comment]
Same issue, editor won't register any event:
```
        instance.isReady.then(() => {
            setEditorInstance(instance);
            instance.on("click", (e) => {
                console.log(e) // never triggered
            })
        });
```

**Comment by neSpecc** [comment]
Editor is not an Event Target at the moment. Where did you found such a code like `instance.on()`? Our docs says nothing about it.

But currently we're thinking about exposing our Event Bus to the API. Probably it will be added in 2.30

**Comment by KamGor** [comment]
@neSpecc I think it's not clearly stated as you tell. In documentation there is Core API/Listeners chapter where are misguiding information. I have added PR #2621 where is described proper events names.

**Comment by neSpecc** [comment]
Actually the `Listeners` module is just a utility for binding/clearing events. It's not a public Event Bus and you won't see any editor events in there

**Comment by keremnymn** [comment]
I inferred from [this line](https://github.com/codex-team/editor.js/blob/e9b4c30407d351d3772ff9f809ba02f3fd537422/types/index.d.ts#L169)

**Comment by neSpecc** [comment]
> I have added PR #2621 where is described proper events names.

Now I see. You're talking about Events API, not a Listeners. It's a relatively new api and we have no documentation for it. Would you add that docs to the https://github.com/codex-team/editorjs.io instead of docs/usage.md?

**Comment by KamGor** [comment]
Yes, I will. Thank you!
