### ISSUE TITLE
Error: The Parser function of type "table" is not defined. 

### ISSUE THREAD

**Issue by fzsf163** [codex-team/editor.js#2623]
The question.
The parser can not parse table. How do you parse table? I am using remix js with ts and tailwind css. 
check also https://github.com/editor-js/awesome-editorjs/issues/104
Why and how the question has come up.
https://github.com/editor-js/table using this plugin as mentioned in the Awesome Editor.js readme.md . But now I can not parse it.

this is the code 
```
import { OutputData } from "@editorjs/editorjs";
import editorJsHtml from "editorjs-html";

const EditorJsToHtml = editorJsHtml();

type Props = {
data: OutputData;
};
type ParsedContent = string | JSX.Element;

export default function EJ_Renderer({ data }: Props) {
const html = EditorJsToHtml.parse(data) as ParsedContent[];
console.log("🚀 ~ EJ_Renderer ~ html:", html); // 👈 this is where error comes from

return (

{/* {html.map((item, index) => {
if (typeof item === "string") {
return (
<div dangerouslySetInnerHTML={{ __html: item }} key={index}>

);
}
return item;
})} */} 👈 this code block destroys everything. Sometimes work though.

);
}

```

**Comment by tiagozip** [comment]
Hello, this is NOT related to the editor.js library. Please close this issue and post on `editorjs-html`'s issues on Github. (you need to define a parser for each element. Check their docs and please look around before spamming the issues tab)

**Comment by fzsf163** [comment]
> Hello, this is NOT related to the editor.js library. Please close this issue and post on `editorjs-html`'s issues on Github. (you need to define a parser for each element. Check their docs and please look around before spamming the issues tab)

Okk
