### ISSUE TITLE
Can't pass block data to tune

### ISSUE THREAD

**Issue by smartpage** [codex-team/editor.js#2630]
This is my block tune,

`

export default class MyBlockTune {
    static get isTune() {
        return true;
    }
    constructor({ api, data, config, block }) {
        this.api = api;
        this.data = data;
        this.config = config;
        this.block = block;
        console.log('Constructor called');
        console.log('Constructor data:', data);
        console.log('Constructor block:', block);
        // Set up a listener for when the block data might change
    }

    render() {
        return {
            icon: '<svg>...</svg>', // Place your SVG markup here
            label: 'Generate AI Text',
            onActivate: async () => {
                console.log('Block Data: ', this.block.data);
                console.log('Block ID: ', this.block.id);

                const blockIndex = this.api.blocks.getCurrentBlockIndex();
                console.log('Block Index: ', blockIndex);
                if (blockIndex !== null && blockIndex !== undefined) {
                    const block = this.api.blocks.getBlockByIndex(blockIndex);
                    if (block) {
                        console.log('Block: ', block);
                        const blockID = block.id;
                        console.log('Block ID: ', blockID);
                        if (block.data) {
                            console.log('Block data: ', block.data);
                        } else {
                            console.log('No data found in this block.');
                        }
                    } else {
                        console.log('No block found at this index.');
                    }
                } else {
                    console.log('No block index found.');
                }
                //alert('Triggered!');
                this.changeBlockText(); // Keep this as it was
            },
        };
    }

    changeBlockText() {
        try {
            const blockIndex = this.api.blocks.getCurrentBlockIndex();
            console.log('Block Index: ', blockIndex);
            if (blockIndex === -1) {
                throw new Error('No block is currently selected.');
            }

            // Retrieve block details once and use throughout
            const block = this.api.blocks.getBlockByIndex(blockIndex);
            console.log('Block: ', block);
            const blockId = block.id;

            if (!block || !block.id) {
                throw new Error('No valid ID for the current block.');
            }

            console.log('Block Data: ', block.data);

            const newBlockData = {
                text: 'New Text Here', // Replace 'New Text Here' with the new text you want
            };

            // Updating the block with new data
            this.api.blocks.update(blockId, newBlockData).catch((error) => {
                console.error('Error updating block text:', error);
            });
        } catch (error) {
            console.error(error.message || 'Error updating block text:', error);
        }
    }

    async generateAIText(originalText) {
        // Returns new text if generation is successful, otherwise returns the original text
        try {
            const response = await new Promise((resolve, reject) => {
                chrome.runtime.sendMessage({ action: 'testOpenAi', data: originalText }, (response) => {
                    if (response && response.success) {
                        resolve(response.result); // Resolve with new text
                    } else {
                        reject(new Error('Failed to generate text')); // Reject if unsuccessful
                    }
                });
            });
            return response; // Return the generated text
        } catch (error) {
            console.error(error);
            return originalText; // Return the original text if there is an error
        }
    }
}
`

when constructor is initiated, data is undefined, I don't know why, 

this is my initiation of the editor:

` const articleBlocks = convertReadabilityArticleToEditorJsBlocks(response.article);
                const editor = new EditorJS({
                    holder: 'editorjs',
                    data: {
                        blocks: articleBlocks,
                    },
                    tools: {
                        myBlockTune: {
                            class: MyBlockTune,
                            config: {
                                // Important: Does your tune need specific data to work?
                                // Example
                            },
                        },
                        header: {
                            class: Header,
                        },
                        paragraph: {
                            class: Paragraph,
                            tunes: ['myBlockTune'], // Add the tune to the header tool
                        },
                        list: List,
                        image: Image,

                        // Add more tools as needed
                    },
                });`

All the blocks have data when being created, example:

` elements.forEach((element) => {
            if (element.tagName === 'P') {
                blocks.push({
                    type: 'paragraph',
                    data: {
                        text: element.textContent,
                    },
                });`

I can clearly see the content of the paragraph, and yet I can't read it inside the tune. 

What am I missing? Please assist

**Comment by neSpecc** [comment]
It's hard to read your code, please format it well

**Comment by neSpecc** [comment]
Resolved in Telegram channel by calling `this.block.save()`

**Comment by smartpage** [comment]
> It's hard to read your code, please format it well

You're right, my apologies, I don't seem to be able to do so with the ''
