### ISSUE TITLE
Latest version (v2.29.1) not published under `latest` tag on npm registry

### ISSUE THREAD

**Issue by paescuj** [codex-team/editor.js#2648]
Heya 👋 

I've noticed the latest version ([v2.29.1](https://github.com/codex-team/editor.js/releases/tag/v2.29.1)) doesn't have the `latest` tag on the npm registry: https://www.npmjs.com/package/@editorjs/editorjs?activeTab=versions

You might be able to tag it retroactively:
```shell
npm dist-tag add @editorjs/editorjs@2.29.1 latest
```

Thank you!

**Comment by neSpecc** [comment]
Done, thanks.
