### ISSUE TITLE
Implementing Inline Tool Opening on Text Hover in Editor.js

### ISSUE THREAD

**Issue by mitee163** [codex-team/editor.js#2669]
### Discussed in https://github.com/codex-team/editor.js/discussions/2668

<div type='discussions-op-text'>

<sup>Originally posted by **mitee163** March 26, 2024</sup>
I'm exploring the usage of Editor.js and I'm interested in implementing a feature where inline tools open on hovering over text within the editor. I would like to know if anyone has experience or has implemented this functionality before.

Specifically, I want the inline tool to be triggered when a user hovers over text within the editor, providing the option to access my custom inline tool to editing options or actions related to that text. If anyone has successfully achieved this or has any insights on how to approach it within the Editor.js framework, I would greatly appreciate any guidance or pointers.

Thank you in advance for your help!</div>

**Comment by reindert-vetter** [comment]
I don't think that is easily possible. How is the script supposed to know what is selected?

I do expect that the inline tool would be visible when I place my cursor. Then I expect an inline tool that allows me to type future letters in bold, for example.
