### ISSUE TITLE
Chrome error when EditorJs is loaded in an iframe

### ISSUE THREAD

**Issue by bettysteger** [codex-team/editor.js#2675]
We have the rare case where we embed EditorJs in another site's iframe for one of our customers, then the EditorJs is initialized successfully, but the plus button is not showing up. In Safari it works, in Chrome I am getting this JS error message in the browser console:

```
DOMException: getLayoutMap() must be called from a top-level browsing context or allowed by the permission policy.
```

I think it is possible that this errors occurs since the `/` [The Slash](https://codex.so/editor-js-2-29) update.

Screenshots: 
![image](https://github.com/codex-team/editor.js/assets/244475/b0c4daab-f69f-4679-9dc1-99b201a90ce0)

Device, Browser, OS: MacBook Air, Chrome v123, MacOS

Editor.js version: 2.29.1

**Comment by neSpecc** [comment]
It is used in a single place. Probably, we can handle that case somehow

**Comment by bettysteger** [comment]
@neSpecc our customer added this to the allow attribute and it works now, we can close the issue.  

```
<iframe allow="fullscreen *; keyboard-map *">...</iframe>
```

**Comment by ozanmuyes** [comment]
So [this comment](https://github.com/WICG/keyboard-map/issues/38#issuecomment-876813768) says the same thing it is sometimes in an iframe which we cannot control (e.g. Stackblitz). Any advises in this case?

**Comment by damacisaac** [comment]
Same issue. @neSpecc we should reopen this, as it's often the case that you can't control the parent iframe.
