### ISSUE TITLE
URL is not being treated as a url

### ISSUE THREAD

**Issue by WebDevSachin** [codex-team/editor.js#2700]
Describe a bug.

Steps to reproduce:
1. Paste this link on the editor https://jobs.asu.edu.om

Expected behavior:
https://jobs.asu.edu.om this link should be of type a and clickable as normal link.

Screenshots:
![image](https://github.com/codex-team/editor.js/assets/62601272/854a8c31-eaba-4c48-8fd3-0c05d698bcd1)
![image](https://github.com/codex-team/editor.js/assets/62601272/aab7bcea-af6f-435d-aec3-84ef186b6827)

Device, Browser, OS:
Mac os , Chrome 

Editor.js version:
2.29.1

Plugins you use with their versions:
My hyperlink config:-
    hyperlink: {
        class: Hyperlink,
        config: {
            shortcut: 'CMD+L',
            target: '_blank',
            rel: 'nofollow',
            availableTargets: ['_blank', '_self'],
            availableRels: ['author', 'noreferrer'],
            validate: false,
        }
    },

**Comment by WebDevSachin** [comment]
![image](https://github.com/codex-team/editor.js/assets/62601272/4345846d-b462-42f0-88fe-becf71de4dab)
![image](https://github.com/codex-team/editor.js/assets/62601272/7f67219a-bf29-4d4f-a839-aa0758952c31)
I am pasting a link it is taking as the text. It should be saved as the url. I am doing any configuration wrong. Can anybody please help. I want this to understand the link and save as link . I don't want to do this manually. Thanks.

**Comment by neSpecc** [comment]
Duplicates #2081
