### ISSUE TITLE
Tools not working ? new way to import in React ?

### ISSUE THREAD

**Issue by chuckdu21** [codex-team/editor.js#2753]
Hi, i just started a new react project with EditorJS.

I'm facing two issues:
- I got two editors on my page. I saw one post saying to remove StrictMode from React but not working.
- Header tools not appears in the editor toolbar. Tried to do like the example from this git: `import Header from '@editorjs/header'` but it says there is no module header... Btw i had to type `as unknown as ToolConstructable` to avoid typing error (i'm using tsx)

Here is my code:

```
import EditorJS from '@editorjs/editorjs'
import type { ToolConstructable } from '@editorjs/editorjs'
import Header from '@editorjs/editorjs'
import './App.css'

function App() {

  const editeur = new EditorJS({
    holder: 'editorjs',
    tools: {
      header:  Header as unknown as ToolConstructable
    }
  })
  return (
    <div className='App'>
      <div id='editorjs' className='editor' />
    </div>
  )
}
export default App;
```
What am i doing wrong ?

**Comment by SebastianMuszynski** [comment]
Hey @chuckdu21,
make sure to install `@editorjs/header` package first.

Then import it using the following code:
```
import Header from '@editorjs/header'
```

**Comment by idebenone** [comment]
Hi @chuckdu21,

[Here](https://codesandbox.io/p/sandbox/q8p987) is the basic implementation of Editor.js with React + TypeScript.
If you have any additional doubts, please feel free to ask.
