### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by patelaryan0914** [codex-team/editor.js#2759]
![image](https://github.com/codex-team/editor.js/assets/110459548/1dca4d7b-0d8c-489f-8b03-f2e35ff3774f)
it was working yesterday today it just broke..

**Comment by samavati** [comment]
@Aryanop0914 I also have the same issue
could you please let me know how you fixed it?

**Comment by patelaryan0914** [comment]
@samavati switch to version 2.8.1 of @editor/header

**Comment by neSpecc** [comment]
We'll ship a fix today
