### ISSUE TITLE
Latest editorjs bold button click triggers form submit

### ISSUE THREAD

**Issue by max-frai** [codex-team/editor.js#2769]
Describe a bug.

Steps to reproduce:
Double click any word, inline toolbar will appear. Click on "B" to make it bold. It makes word bold but also triggers form submit..

Expected behavior:
It shouldn't trigger form submit. Should only make word bold.

Device, Browser, OS:
Macos, Windows Chrome

Editor.js version: 2.30.1

**Comment by afonsosantos** [comment]
~~Also happening here, using 2.30.0.~~

@max-frai This is fixed in version 2.30.2, as seen here: https://github.com/codex-team/editor.js/releases/tag/v2.30.2

**Comment by neSpecc** [comment]
Resolved in 2.30.2
