### ISSUE TITLE
Action on paste: prevent from creating new blocks

### ISSUE THREAD

**Issue by Malimalo** [codex-team/editor.js#2782]
Hello,
While creating a custom tool with multiple text fields in it, it appears that when I paste some formatted text or some multi-line text, it does not paste the text in the editable div of my tool. It creates new paragraph blocks below instead.

I can't find the right configuration of pasteConfig and onPaste methods to prevent the EditorJS to create new blocks when I paste a text in it.

```
  static get pasteConfig() {
    return {
      tags: ['*'], // Handle all HTML tags
      patterns: {
        text: /[\s\S]+/ // Pattern to match any text
      }
    };
  }

  onPaste(event) {
    const data = event.detail.data;
    const target = window.getSelection().anchorNode;

    if (target) {
      this.insertHTMLAtCursor(data);
    } else {
      console.warn('Cannot paste data: no valid target found');
    }
  }
```

**Comment by neSpecc** [comment]
Agree, that is annoying. We're gonna improve our paste module soon.

Duplicates #2142
