### ISSUE TITLE
Allow async render in Block Tool Plugin

### ISSUE THREAD

**Issue by cadamsdev** [codex-team/editor.js#2787]
Currently the `render` function only allows synchronous operations. However, I would like to call an async function inside the render function and wait for that to complete before returning the html element.

For my use case I would like to create a new block "CodeBlock" that has syntax highlighting using [Shiki syntax highlighter](https://shiki.style/) however all the methods to highlight the code are asynchronous. I would like to get the value from the async function before the render function is called to prevent visual issues.

See here
https://github.com/cadamsdev/notes/blob/cadamsdev/editorjs-issue/apps/web-app/src/lib/editorjs/plugins/CodeBlock/index.ts#L130

Proposed
Allow us to render data async
```ts
async render() {

}
```

or provide a new hook we can use to call async functions before render is called

**Comment by paul-cofnod** [comment]
I'd love this to be a feature too. I'm trying to load a c# cshtml component via fetch / ajax and await the returned html before returning the component.

**Comment by sielay** [comment]
@cadamsdev can you explain why it's not planned? It's fine if you don't intend to support it, but as some of us will have a case for it, we'd like to gain an understanding of the pros and cons.

In my case, the pain point is the focus management. Sometimes I need to perform an async render, and I can already do that by reusing the element; however, the focus is being lost.
