### ISSUE TITLE
Chrome error when EditorJs is loaded in an iframe

### ISSUE THREAD

**Issue by damacisaac** [codex-team/editor.js#2789]
See https://github.com/codex-team/editor.js/issues/2675.

This issue is preventing use of the library when inside of an iframe that is out of our control.

**Comment by neSpecc** [comment]
Please, add more details. How to reproduce the problem? 
I've tested this code and the editor is working fine in there

```html
<iframe src="https://editorjs.io" frameborder="0" width="100%" height="700px"></iframe>
```

**Comment by damacisaac** [comment]
@neSpecc  It works almost fine, but the `[ + ]` button does not appear beside blocks. I tried just now with your example in a random `http://localhost:8000` site and was able to see the error in the console logs and the button does not appear.

**Comment by welcomeapp** [comment]
Is there any information on how to fix this bug? There is no access to the iframe settings and `[+]` is not displayed and the error 
![image](https://github.com/user-attachments/assets/15925a4e-1398-4137-b11e-524c97583ee0)

**Comment by damacisaac** [comment]
the fix is to merge this PR: https://github.com/codex-team/editor.js/pull/2790

**Comment by damacisaac** [comment]
@neSpecc can we get that PR merged?
