### ISSUE TITLE
Cannot find compiled file

### ISSUE THREAD

**Issue by PuzzlingGGG** [codex-team/editor.js#2797]
I try to create anything yet it always says Cannot find compiled file C:\Users\puzzling\Desktop\je-remake\src\_codux\boards\app\app.board.tsx but its there.. trying to open or create components or boards keeps results in this error. I used Vite with SCSS and CSS Modules

Steps to reproduce:
1. click on new component or new board, or try to open any.

Expected behavior:
open the editor

Screenshots:
![image](https://github.com/user-attachments/assets/5cc9ad44-4909-4ce3-90f0-c01cc7093955)
![image](https://github.com/user-attachments/assets/c3754c62-33ab-4ff8-bcd3-108edf9d7563)
![image](https://github.com/user-attachments/assets/47e8b74e-c4a1-4f8f-b210-086cbed145ea)

Device, Browser, OS: 
Windows 10 PC

Editor.js version:
newest version on https://www.codux.com/download

Plugins you use with their versions:
I don't think I have any plugins, as I just installed it

**Comment by neSpecc** [comment]
Not related to the Editor.js
