### ISSUE TITLE
Angular 18 context (second menu - please see video attached) collapsed

### ISSUE THREAD

**Issue by miff** [codex-team/editor.js#2801]
The question.
When you try to open the context menu, it collapses immediately...

Why and how the question has come up.
Using angular 18
https://github.com/user-attachments/assets/723355dc-d165-402f-b6f8-0ecc47694858

**Comment by miff** [comment]
This is related to the Ng-Zorro

**Comment by shyam-infraon** [comment]
Hey @miff , can you point me towards a working example of a clean integration of editor js with the latest version of angular.
