### ISSUE TITLE
Issue with NestedList and List types for EditorJS

### ISSUE THREAD

**Issue by VladMesesan** [codex-team/editor.js#2812]
Trying to add a List or a NestedList to the editorJS tools results in errors related to the new Tool and BlockTool Constructables.

![image](https://github.com/user-attachments/assets/24428c9c-6ca2-4bfd-8f15-a8e2e4450cb9)

![image](https://github.com/user-attachments/assets/20712b14-4b10-4d45-b1cb-33107e6534d6)

As of right now, downgrading the @editorJs/List package to 1.9.0 solves the issue. Not sure about the nestedList package though.
Will provide any other info required.
Thanks!

**Comment by neSpecc** [comment]
Thanks for the report, we'll take a look soon

**Comment by andreea-meetgeek** [comment]
Hi! Any update on this issue? Experiencing the same problem on Nested Lists (1.4.3) Downgrading does not seem to solve the problem.
I tried defining my own types, as suggested in [this thread](https://github.com/editor-js/header/issues/23) but it breaks Nested List functionality.

**Comment by idebenone** [comment]
Hi @andreea-meetgeek,

Please try the latest version of [List](https://github.com/editor-js/list) tool. If you are still facing any issues or have any additonal questions, do let us know.

**Comment by xXNickznXx** [comment]
@idebenone @neSpecc
The issue persists, even on the latest List Version (2.0.2)
![image](https://github.com/user-attachments/assets/163ce5cc-43c5-443f-aed1-3be14f20e90b)

**Comment by e11sy** [comment]
hey @xXNickznXx @andreea-meetgeek, `list` plugin (since 2.0.0 version) uses Improvement of `editor.js` which is available since `2.31.0-rc.2` which we haven't released yet, you can try using this version of editor to solve types issue, also let us know if this would not help
