### ISSUE TITLE
ISSUE: When selecting a tool from dropdown in Tool Menu using enter key, the tool block gets displayed with a new line break 

### ISSUE THREAD

**Issue by DimitrijeJ** [codex-team/editor.js#2835]
This is annoying regarding lists, here are images for this purpose:

![Screenshot from 2024-09-25 10-19-23](https://github.com/user-attachments/assets/af44d4ad-c20f-4b86-81f0-90e92fb4b5de)

So, when I press enter key on this tool the following gets displayed (you can obviously notice the issue with the new line displaying):

![Screenshot from 2024-09-25 10-22-59](https://github.com/user-attachments/assets/180434e3-cc53-466d-9e8e-0cb894dd74c1)

**Comment by idebenone** [comment]
Hi @DimitrijeJ,
Please update the List Plugin to the latest version. Your issue will be resolved.
If you face any additional issues, let us know. We will look into it.

https://github.com/editor-js/list
