### ISSUE TITLE
Inline anchors sometimes don't save

### ISSUE THREAD

**Issue by samvandamme** [codex-team/editor.js#2844]
Steps to reproduce:
![ScreenRecording2024-10-13at22 00 09-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/eab62f46-a36f-4811-b00a-3ccbbc7a96f4)
As you can see, when a link is at the beginning of a block it saved, but somewhere in the middle of the block it doesnt. I paste in the URL and press Enter. If I type the URL, the same happens.

Expected behavior:
To save the links every time

Device, Browser, OS:
Mac, Safari

Editor.js version:
2.30.6

**Comment by neSpecc** [comment]
It is a Safari-related bug. I'll do the fix.

**Comment by neSpecc** [comment]
Resolved by #2864, available in 2.30.7
