### ISSUE TITLE
Getting multiple instance of Editor.js

### ISSUE THREAD

**Issue by Varun-Chakraborty** [codex-team/editor.js#2858]
I just got introduced to editor.js from the internet and tried setting it up in my react app and got multiple instances there

code setting up editor.js:
```ts
import EditorJS from '@editorjs/editorjs';
import Header from '@editorjs/header';

export function Editor() {
  const editor = new EditorJS({
    holder: 'editorjs',
    tools: {
      header: Header
    },
    data: {
      time: 0,
      blocks: [
        {
          type: 'header',
          data: {
            text: 'Hello Editor.js!',
            level: 2
          }
        }
      ]
    }
  });

  return <div id="editorjs" className="w-[800px] h-[500px] border overflow-scroll rounded-lg" />;
}
```

As you can see in the image attached below, there are multiple "Hello Editor.js" instead of one, which is definitely not what we want and as I mentioned above I just tried it so it might be that I am doing something wrong.

Steps to reproduce:
1. Install `@editorjs/editorjs` in react based environment
2. Set it up in any component
3. Check the results

Expected behavior:
There should have been only one of its instance

Screenshots:
![image](https://github.com/user-attachments/assets/cbf88802-7e31-4533-8ff5-5712ad3cb86a)

Device, Browser, OS:
Laptop, Firefox, Ubuntu

Editor.js version:
2.30.6

Plugins you use with their versions:
Header: 2.8.8

**Comment by neSpecc** [comment]
Seems like your function called several times. Each time you call `new EditorJS()`, it will insert the new instance to passed element. Check your component lifecycle.
