### ISSUE TITLE
How do you implement inline blocks

### ISSUE THREAD

**Issue by chf-gh** [codex-team/editor.js#2882]
I want to use `/` list my inline block list, for example an emoji inline block, select an emoji and insert it into the cursor position, does anyone know how to do that?
Here's how it looks:
![Snipaste_2024-12-02_11-02-21](https://github.com/user-attachments/assets/57905f4d-dca8-461b-ad44-e4b3dbefe4a8)

**Comment by neSpecc** [comment]
You can create an Inline Tool for that. Use `renderActions()` method for creating an emoji list 
https://editorjs.io/inline-tools-api-1/
