### ISSUE TITLE
Nested inline <code> elements

### ISSUE THREAD

**Issue by ii888ii** [codex-team/editor.js#2888]
1. Type "A B C D E X a b c d e" in a paragraph.
2. Select "X" and click on InlineCode button (with "<>" icon)
3. Select "E X a" and click on InlineCode button
4. Select "D E X a b" and click on InlineCode button

And so on...

Expected behavior:

One `<code>` element instead of nested `<code>` elements

Screenshots:

<img width="206" src="https://github.com/user-attachments/assets/298c9018-a046-4042-87d2-20087b5bba2e">

Device, Browser, OS: Firefox and Chrome on Windows

Editor.js version: 2.30.7

**Comment by neSpecc** [comment]
Please, reopen it at the [Inline Code](https://github.com/editor-js/inline-code) repo
