### ISSUE TITLE
Docs: How to use

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#311]
Usage basics:

1. Toolbox
2. Inline Toolbar
3. Block Settings
4. Shortcuts

**Comment by blaqdog** [comment]
Подскажите, как можно получить json заполненных полей? 
```
editor.saver.save()
	  .then((savedData) => {
		console.log(savedData);
	  });
```
возвращает ошибку в консоли: "editor.saver.save is not a function"
Также пробовал codex.editor.saver.save()

**Comment by neSpecc** [comment]
Привет, @blaqdog. Мы выпустили версию 2.0-beta. Readme должен ответить на все вопросы:

https://github.com/codex-team/codex.editor

**Comment by Butonix** [comment]
Здравствуйте. Подскажите, как сохранить данные Json заполненных блоков на react?
Подключил все по инструкции, редактор работает!
при сохранении контента нет
`onSubmit = e => {
    e.preventDefault();
    this.setState(
      {
        data: {
          ...this.state.data,
          content: JSON.stringify(this.state.data)
        }
      },
      this.props.submit(this.state.data);
    );
  };`

**Comment by neSpecc** [comment]
Outdated
