### ISSUE TITLE
[EPIC] API Documentation

### ISSUE THREAD

**Issue by gohabereg** [codex-team/editor.js#510]
Check and update API docs
- [x] Usage
- [x] Configuration
- [x] Block Tools
- [x] Block Tunes
- [x] Inline Tools
- [x] Blocks API
- [x] Caret API
- [x] Events API
- [x] Listeners API 
- [x] Notifier API
- [x] Sanitizer API
- [x] Saver API
- [x] Selection API
- [x]  Styles API
- [x] Toolbar API

**Comment by neSpecc** [comment]
Done
