### ISSUE TITLE
List: allow to create linebreak by shift+enter

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#515]

**Comment by khaydarov** [comment]
Воспроизводится только в Сафари

**Comment by marvinside** [comment]
Works on https://editorjs.io/
Seems resolved.

**Comment by martinjnilsen** [comment]
Found this thread while looking for an answer. I can't seem to get the shift + enter to work with the list tool, and it seems to be a problem also in this [sandbox I found](https://codesandbox.io/s/editor-js-react-9ckxv). Is there a way to fix this?
