### ISSUE TITLE
Close Toolbar after Link insertion

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#600]
1. Select fragment of text
2. Click on Link Tool at the Inline Toolbar (or press CMD+K)
3. Enter or paste a link and press Enter
4. Link will be inserted, but Inline Toolbar still opened

We need to close the Inline Toolbar after link insertion

**Comment by tanmayv** [comment]
Regarding this issue, on pressing enter we want the inline-toolbar to close?

**Comment by neSpecc** [comment]
@tanmayv yes

**Comment by tanmayv** [comment]
I was thinking of closing the `inlineToolbar` whenever we call `Toolbar.close()` or we can expose `InlineToolbar` to API as well and the close it manually as well from the `inline-tools`. What would you suggest?

**Comment by neSpecc** [comment]
You can directly call `this.Editor.InlineToolbar.close();` at the specific moment

**Comment by neSpecc** [comment]
Sorry, you are right, it’s better to use an API, because it is a logic of the inline link tool, not an editor core module

**Comment by neSpecc** [comment]
@tanmayv

**Comment by neSpecc** [comment]
@tanmayv Inline Toolbar API now available at the `release/2.13` branch, so create a branch based on it. And PR should be opened to that branch.
