### ISSUE TITLE
Add placeholder

### ISSUE THREAD

**Issue by gohabereg** [codex-team/editor.js#606]

**Comment by dimensi** [comment]
Сейчас прокидывание placeholder в конфиг класса EditorJS не дает никакой реакции, ишью посвященно этому багу?

**Comment by neSpecc** [comment]
@gohabereg describe issue please

**Comment by gohabereg** [comment]
Now placeholder could be set by providing `config` object for Paragraph Tool.

```
new EditorJS({
  tools: {
    paragraph: {
      config: {
        placeholder: 'Tell your story...'
      }
    }
  }
})
```

I'm closing the issue

**Comment by parallaxpro** [comment]
Not working
![image](https://user-images.githubusercontent.com/64248086/84050862-bf392200-a9c7-11ea-9bbd-b0069d3bf36d.png)
![image](https://user-images.githubusercontent.com/64248086/84050892-c9f3b700-a9c7-11ea-98c2-fef0922e00c2.png)

**Comment by yahyatoumi** [comment]
> Not working ![image](https://user-images.githubusercontent.com/64248086/84050862-bf392200-a9c7-11ea-9bbd-b0069d3bf36d.png) ![image](https://user-images.githubusercontent.com/64248086/84050892-c9f3b700-a9c7-11ea-98c2-fef0922e00c2.png)

same problem the placeholder of a paragraph cant be displayed if befor of it there is a header element or any other element
