### ISSUE TITLE
"Plus" button is not centered

### ISSUE THREAD

**Issue by talyguryn** [codex-team/editor.js#608]
Firefox 65, macOS 10.13.6 / Win 7

![image](https://user-images.githubusercontent.com/15259299/52538838-7f890880-2d88-11e9-9cdc-91fc5cc842d9.png)

**Comment by akash-mitra** [comment]
Just some additional info -

The button is centered in chrome. But not centered in Firefox. 

The translate values in `ce-toolbar__plus` is different between chrome (`transform: translate3d(0px, calc(-50% + 10px), 0px)`) and firefox (`transform: translate3d(0px, calc(-50% + 22px), 0px)`)

In chrome, the  block has a height of 24px - which I believe is coming from `line-height: 1.7` - but in firefox the block height is `zero` unless you start writing something. 

**Below is a screenshot from chrome** Notice 45px (24px + 21px padding) content height (light blue color) 
<img width="779" alt="image" src="https://user-images.githubusercontent.com/3336242/68525805-71184f00-0310-11ea-8b66-0d409ee4728f.png">

**Below is a screenshot from Firefox**, the content height is zero (only 21px from padding).
<img width="698" alt="image" src="https://user-images.githubusercontent.com/3336242/68525920-71651a00-0311-11ea-8919-b1f04f10bd07.png">

**Comment by neSpecc** [comment]
Resolved in 2.16.1
