### ISSUE TITLE
Caret does not centred on windows

### ISSUE THREAD

**Issue by khaydarov** [codex-team/editor.js#621]
### Windows

**Firefox**

Caret inside List
![image](https://user-images.githubusercontent.com/6507765/53346253-b7b34e00-3927-11e9-9110-600efc579939.png)

Plus button not centered:
![image](https://user-images.githubusercontent.com/6507765/53346314-d285c280-3927-11e9-8add-9d09ba882e59.png)

**Edge 18+**
![image](https://user-images.githubusercontent.com/6507765/53346704-969f2d00-3928-11e9-8f74-cc778e2b471e.png)

![image](https://user-images.githubusercontent.com/6507765/53346744-b6ceec00-3928-11e9-9a95-391e91debe8e.png)

**Comment by akash-mitra** [comment]
Believe this issue is related to #608

**Comment by neSpecc** [comment]
Resolved
