### ISSUE TITLE
Сохранение пустого редактора

### ISSUE THREAD

**Issue by markmoskalenko** [codex-team/editor.js#636]
— Сохраняем json редактора без ввода данных. Пустой параграф.
— Повторно открываем форму редактирования с загрузкой json из шага 1
Итог: в редакторе нет вообще блоков. Нельзя начать что-то вводить так как нет поля ввода. В консоли ошибок нет.

**Comment by gohabereg** [comment]
Not reproducible.

There are an if statement for that case.
https://github.com/codex-team/editor.js/blob/master/src/components/core.ts#L171
