### ISSUE TITLE
Cannot add Link Tool with toolname "link" 

### ISSUE THREAD

**Issue by talyguryn** [codex-team/editor.js#637]
Why I should avoid using "link" name? "linkTool" name works correctly. 

![image](https://user-images.githubusercontent.com/15259299/53700881-15540880-3e08-11e9-8d9f-eeb06097b74f.png)

**Comment by neSpecc** [comment]
Суть в том, что в самом редакторе зашиты некоторые Тулы, например плагины инлайнового тулбара `link`, `bold`, `italic` или встроенный `paragraph`. Поэтому если подключить снаружи через `config.tools` другие плагины с такими же названиями, они не будут работать.

Надо сделать названия внутренних плагинов более уникальными.

link -> inline-link
bold -> inline-bold
italic -> inline-italic
