### ISSUE TITLE
В версии 2.11.9 сломалась адаптивная верстка (для мобильных устройств) редактора

### ISSUE THREAD

**Issue by bondarev** [codex-team/editor.js#647]
В версии **2.11.9** тулбар не принимает вид версии для устройств с небольшим размером экрана. 

В **2.11.8** все в порядке. 

![image](https://user-images.githubusercontent.com/616126/54375328-e48a9380-4691-11e9-9ed6-84f0dc9fedf4.png)

**Comment by talyguryn** [comment]
resolved in #650
