### ISSUE TITLE
Remove global placeholder styles and move them to plugins

### ISSUE THREAD

**Issue by gohabereg** [codex-team/editor.js#652]
Plugins:
- [ ] Header

**Comment by bentron2000** [comment]
Hey There, 

Is this issue about providing styles in a config object?

I'm considering your great editor for our project - but we'd want to heavily modify the styling, and also use different styles depending on where we use it.

If so. +100 for doing that :)

**Comment by neSpecc** [comment]
@bentron2000 We will think about it. At the moment, you can override the default styles by adding more specific selectors.

**Comment by neSpecc** [comment]
outdated
