### ISSUE TITLE
Add RTL support

### ISSUE THREAD

**Issue by eyy** [codex-team/editor.js#670]
https://en.wikipedia.org/wiki/Bi-directional_text

Thanks.

**Comment by amitassaraf** [comment]
+1

**Comment by abublihi** [comment]
Hi, I have examine Editor.js and it is mostly support RTL,

you can find the what i have done on this codepin [https://codepen.io/anon/pen/zQqeeM](https://codepen.io/anon/pen/zQqeeM)

**Comment by IssaMokdad** [comment]
The rtl feature is broken, I am setting the direction to rtl in i18n config, but it doesn't work. any idea regarding the issue?

**Comment by ShahriarKh** [comment]
Is this implemented? If so, can somebody please explain how to use it?

RTL/LTR buttons in Word:
![image](https://user-images.githubusercontent.com/31452340/136075128-93a251d9-ed4d-4dc3-9cf4-202069c79588.png)
