### ISSUE TITLE
Getting started typo

### ISSUE THREAD

**Issue by nfilzi** [codex-team/editor.js#675]
Just lost 20 minutes on this one, trying to setup what looks like an awesome editor 😔
And when I found it, I wanted to punch something 😅

On [this page](https://editorjs.io/getting-started)

```
import EditorJS from '@editorjs/editorjs';

const editor = new EditorJs();
```

`new EditorJs()` 👉 `new EditorJS()`, capital **S** at the end!!

Now I can finally play with it 😁
Cheers!

**Comment by gohabereg** [comment]
Hey!

Thanks a lot for your attentiveness! Fixed now 🙈
