### ISSUE TITLE
Small Grammatical Errors

### ISSUE THREAD

**Issue by co16353sidak** [codex-team/editor.js#677]
I was going through the website and found this paragraph.
<img width="424" alt="Screenshot 2019-04-03 at 10 54 34 PM" src="https://user-images.githubusercontent.com/35738138/55499533-da8dfc00-5663-11e9-92f2-9e366f3d31ca.png">
I feel that there are some grammatical errors that are missing. (these could be intentional but if they aren't)

1.  the heading could be `The API is the feature`
2. `Each block is provided by a plugin`
3. `Dozens have been created`
 I would love to send a PR with the proposed changes.

**Comment by n0str** [comment]
Looks good to me

**Comment by co16353sidak** [comment]
I am unable to find the website files where in I can go and make the changes, can someone help me out by pointing me in the right direction ?
@n0str

**Comment by talyguryn** [comment]
@co16353sidak 😉 

https://github.com/codex-team/codex/blob/master/www/application/views/templates/landings/editor.php#L81-L86
