### ISSUE TITLE
Bug with inline toolbar - wrong «surround» behaviour

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#679]
1. Select fragment
2. Click on Link, then click on Marker
3. Marker wrapper will be inserted right into Inline Toolbar 

<img width="464" alt="image" src="https://user-images.githubusercontent.com/3684889/55544432-bbc74e00-56d3-11e9-8d6d-1a77e66047b2.png">

**Comment by ranemihir** [comment]
What is the method to set focus back to the selected part of the text? Does anyone know? @gohabereg @khaydarov @neSpecc

**Comment by gohabereg** [comment]
Not reproducible in the last version
