### ISSUE TITLE
Throw error on multiply CMD + A

### ISSUE THREAD

**Issue by dimensi** [codex-team/editor.js#684]
```
app.js:formatted:15002 Uncaught TypeError: Cannot read property 'parentNode' of null
    at e.value (app.jst:formatted:15002)
    at HTMLUListElement.<anonymous> (app.js:formatted:14925)
```
![2019-04-05 13-12-34 2019-04-05 13_13_20](https://user-images.githubusercontent.com/11390039/55620844-a2da9d80-57a4-11e9-8e2e-8cc8a3fb795c.gif)
![image](https://user-images.githubusercontent.com/11390039/55620878-b423aa00-57a4-11e9-8758-813bbc671d91.png)

**Comment by dimensi** [comment]
Ошибка происходит только когда в среди блоков есть список.

**Comment by khaydarov** [comment]
Got it. Will be fixed in the release2.14
