### ISSUE TITLE
Add title property for tool's settings

### ISSUE THREAD

**Issue by dimensi** [codex-team/editor.js#686]
Now the buttons in the toolbox have hints that show the name of the tool thanks to this issue #498 .
![image](https://user-images.githubusercontent.com/11390039/55629295-872ec180-57bb-11e9-91a2-67fff26d4fde.png)
Can you add the same tips for settings?
![image](https://user-images.githubusercontent.com/11390039/55629405-cd842080-57bb-11e9-8bef-82e0aed7e6e5.png)

**Comment by neSpecc** [comment]
Resolved
