### ISSUE TITLE
how to turn an existing row into a heading <h1>, <h2>, <h3> etc?

### ISSUE THREAD

**Issue by rolfo85** [codex-team/editor.js#687]
Hi,

getting familiar with this awesome editor. 

I'm just trying to figure out how I can turn  an existing row into a heading `<h1>, <h2>, <h3>` without creating a new line > click on the plus icon > select "H" and then paste the row?

Is there a way to have the H on the toolbar or some other ways?

Thanks

**Comment by gohabereg** [comment]
Hi @rolfo85 

There is no option for that now, will come with the next releases

**Comment by rolfo85** [comment]
sounds good

**Comment by neSpecc** [comment]
Released with version 2.15
