### ISSUE TITLE
mathjax or kaTeX for mathematics 

### ISSUE THREAD

**Issue by vladp** [codex-team/editor.js#688]
this is a feature request, probably also related in complexity (and perhaps some implementation detail) to https://github.com/codex-team/editor.js/issues/671
Would be great to have Editor.JS to support math symbols. Makes the utility of the library much greater.

Thank you for making this avialable

**Comment by taurenshaman** [comment]
I have implemented a basic KaTeX:
https://github.com/tunaltd/codex-editor-modules/tree/master/single/katex
Demo: https://taurenshaman.github.io/demo/editor@codexteam+katex.html
![image](https://user-images.githubusercontent.com/1308706/84991287-e686b080-b178-11ea-97b1-9d43da5413b8.png)

**Comment by neSpecc** [comment]
[Awesome Editor.js](https://github.com/editor-js/awesome-editorjs) contains such tools.
