### ISSUE TITLE
Backspace fires "history back" after cmd+a in Firefox

### ISSUE THREAD

**Issue by talyguryn** [codex-team/editor.js#691]
1. cmd+a on any block
2. backspace

firefox 65.0, macOS 10.13.6

**Comment by LachlanGrant** [comment]
Same issue except just clicking below all blocks and dragging upwards to select all blocks. I don't think it's related to cmd+a (unless @talyguryn 's issue is different)

**Comment by FredHasselot** [comment]
Same here.

**Comment by carakas** [comment]
same here
