### ISSUE TITLE
Close inlineToolbar by escape

### ISSUE THREAD

**Issue by khaydarov** [codex-team/editor.js#692]

**Comment by Shazer2** [comment]
I want to work on this :)

**Comment by neSpecc** [comment]
@Shazer2 great! Feel free to ask a questions, if you'll have

**Comment by Shazer2** [comment]
@neSpecc I'm new to the codebase, however it looks like [https://github.com/codex-team/editor.js/blob/master/src/components/modules/blockEvents.ts#L118](this) is causing the inline toolbar to close immediately after the escape key is released.

Is there any reason this line of code is necessary? It appears the logic to close the inline toolbar is already implemented but this line keeps it from staying closed!

**Comment by khaydarov** [comment]
closed with #932
