### ISSUE TITLE
Should have ability to align the Content inside the Block...

### ISSUE THREAD

**Issue by prashant1k99** [codex-team/editor.js#693]
It would be best if the **Alignment of the Content** can be done... Then would be easy to align content  like images, headings, etc.. and I was unable to insert heading in the example of the Editor...

**Comment by gohabereg** [comment]
Hi @prashant1k99 !

Thank you for the idea!

At the moment you can switch content type only for empty blocks. So if you need heading just press enter to create empty paragraph and then choose Header with plus button or tab key

**Comment by Antonio-Laguna** [comment]
@gohabereg I'm not sure if possible or your thoughts but I'd be willing to make a module/pr for this. I think most blocks could benefit from alignment pretty much as HX appears when you click on the three dots we should get left, center, right and justified. 

Does that sound OK to you? Would you be interested in such a feature?

**Comment by gohabereg** [comment]
Hi @Antonio-Laguna 

Sure, it would be great feature!
We are planning to add API for settings section (we call it Tunes) and it should help us to implement any Tunes we want (as alignment for example).

Actually, there are [PR](https://github.com/codex-team/editor.js/pull/585) but we decided to freeze it for the next releases.

If you have time and really want to help us you can implement alignment tunes the same way as current default settings [implemented](https://github.com/codex-team/editor.js/tree/master/src/components/block-tunes).

**Comment by Antonio-Laguna** [comment]
Sure, I'd like to follow up on this. Will get moving on that! Thanks for pointing me in the right direction.

**Comment by Antonio-Laguna** [comment]
Hey @gohabereg ! Got started on this today and actually wondering how you guys develop. I've seen there's no npm script to actually startup webpack or anything alike. Tried to run `npx webpack` which seems to generate something but going to `http://127.0.0.1:8081/example/example-dev.html` does not seem to work as it throws an exception so I'm clearly not doing something right.

**Comment by gohabereg** [comment]
Hey @Antonio-Laguna 

Please check out the code development guide — https://editorjs.io/core-development

Also you can join our [Telegram](https://t.me/editorjsdev) or [Gitter](https://gitter.im/codex-team/editor.js) channels to keep in touch

**Comment by semoal** [comment]
I've implemented it guys, @gohabereg @Antonio-Laguna  @prashant1k99 https://github.com/codex-team/editor.js/pull/12

Let's review it, if it can be released on the next release!
