### ISSUE TITLE
Can't get the image rendered as HTML

### ISSUE THREAD

**Issue by rolfo85** [codex-team/editor.js#694]
Hi,

I'm using the "image" plugin. I configured all the server side that is storing the image properly.
I'm sending back the response using the JSON template as shown in the plugin guide.

The format I obtain is correct and the  URL works great. However, EditorJS doesn't build the <img> with the URL I'm passing in the response. It's just preloading it.

Is there something I should do?

**Comment by gohabereg** [comment]
Hi @rolfo85!

Is there any errors in the debugger?

**Comment by rolfo85** [comment]
I fixed it.

I was using  a wrong template for the json response.

I was using this:
`
    return response()->json([
        "file" => "http://localhost:8000/storage/rte-images/" . $cleanedFilenameWithExtension
    ]);

`
And this is the right one:

`
    return response()->json([
        "file" => [
                "url" => "http://localhost:8000/storage/rte-images/" . $cleanedFilenameWithExtension
            ],
    ]);

`

**Comment by adamhowell** [comment]
Hi guys,

I'm also having some issues with getting the editor to display the image after successful upload and when I'm returning the proper JSON.

This is my JSON response:

```
{
  "success" : 1,
  "file" : {
    "url":"https://groupy-co.s3.amazonaws.com/uploads/photo/path/98/untitled-1938.jpg"
  }
}
```

And this is the error I'm seeing in the debugger:

![Screen Shot 2019-04-08 at 6 01 23 PM](https://user-images.githubusercontent.com/26133/55759817-5acbad00-5a28-11e9-8313-9452cea8e4c0.png)

Any help would be appreciated. And great job so far on the editor! Exactly what I've been looking for.

**Comment by neSpecc** [comment]
The issue is under discussion here: https://github.com/editor-js/image/issues/22
