### ISSUE TITLE
Add es version of bundle

### ISSUE THREAD

**Issue by dimensi** [codex-team/editor.js#697]
Today webpack and rollup prefer work with es modules than umd or commojs. With es modules webpack/rollup can's use tree shaking and bundles have smaller size because in es module bundle dropped weird wrappers.

**Comment by PaulKinlan** [comment]
I'm currently facing a similar issue. I'm not targeting any browser that can't already support modules, so having to Babel my build is hugely inconvenient when all I really need is for a complementary output of an esm file.
