### ISSUE TITLE
Remove rows in table

### ISSUE THREAD

**Issue by oknoorap** [codex-team/editor.js#698]
I accidentally added new row, is it possible to remove unwanted rows or columns?

![image](https://user-images.githubusercontent.com/247018/55704768-37443a80-5a07-11e9-9632-f35dfb1d82c7.png)

**Comment by neSpecc** [comment]
Currently the UI does not have such tools. The Table block is currently in beta, it has minimal functionality, so you are free to improve it and send a Pull Request, or wait until we or someone implements it. 

But this is a very important feature, so it should come soon. Along with bug fixes and stability improvements.

The original repo an issuse: https://github.com/editor-js/table/issues/30

**Comment by DavitPetrosyan** [comment]
Hi @neSpecc. 

Does this functionality already implemented? I dave downloaded the 1.2.2 version of editorjs/table, but can't find ability to remove rows/cols from UI.

Thank you. 
Davit

**Comment by christoph-kluge** [comment]
@khaydarov why this issue got closed? Can you provide some information so people can understand your decisions?

Is it a duplicate? Is there a new version coming? Are you dropping support?

**Comment by neSpecc** [comment]
> @khaydarov why this issue got closed? Can you provide some information so people can understand your decisions?
> 
> Is it a duplicate? Is there a new version coming? Are you dropping support?

This is the issue for Table Tool. It is not related to editor.js core. Follow https://github.com/editor-js/table/issues/30
