### ISSUE TITLE
Cross block selection from text

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#703]
Need to provide an ability to select several blocks with keyboard and by mouse from center of block.

### By mouse

- [x] By mouse moving from block's text and over next block, select these two blocks
- [x] By mouse moving from block's text and over previous block, select these two blocks

### By keyboard selection

- [x] By `SHIFT+DOWN` at last line, select current and next blocks.
- [x] By `SHIFT+UP` at the first line, select current and previous block
- [ ] By second `СMD+SHIFT+DOWN` in any line, select current and next blocks.
- [ ] By second `СMD+SHIFT+UP` in any line, select current and previous blocks.

### Select more blocks 

- [ ] If one or more blocks are selected, by `SHIFT+DOWN`, select one more block below
- [x] If one or more blocks are selected, by `SHIFT+UP`, select one more block above

### Deselect blocks 

- [x] If 1+ blocks was selected by shift+up, by next `SHIFT+DOWN` deselect one upper block
- [x] If 1+ blocks was selected by shift+down, by next `SHIFT+UP` deselect one lowest block

Related issues 
#702 
#672

**Comment by gohabereg** [comment]
Resolved by #826

**Comment by matthiasg** [comment]
Is this visible somewhere online ? The main page does not yet show this right ?

**Comment by aniruddha-mithya** [comment]
Is there an api to access the currently selected blocks?
