### ISSUE TITLE
Blocks converter

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#704]
Need to provide ability of convertation one block into another.

- [x] Add new Tools API (static?) getter `convertationConfig` that will specify 2 properties: `export` and `import`.

`export` — value of what field should be used to covert this tool to other
`import` — in which field of tool's `data` we should put a content exported from original block.

```
class Header {
  constructor(){
    this.data = {
       text: '',
       level: 2
    }
  }

  get convertationConfig(){
    return {
       export: 'text'
       import: 'text',
    }
  }
}
```

- [x] Some tools may have complex data structure, for example `List`, so maybe `export` and `import` can be a function, in addition to string tokens. In this case, the function accepts saved data and return a string-value to export.

- [x] If current block's Tool has an `export` value, add the converter dropdown to the inline toolbar

- [x] At the converter dropdown, place all tools that specified `import` value

- [x] By clicking on converter tool, save original block, extract an `export` field and switch this block with the new one passing extracted value through the `import` field

**Comment by rtpHarry** [comment]
im new here so not sure if convertation is a quirky concept or a mistranslation. 

I would expect it to be "conversion".

**Comment by neSpecc** [comment]
UI is ready.

![](https://capella.pics/6c1f708b-a30c-4ffd-a427-5b59a1a472e0.jpg)

## Mechanics

There is no dropdowns at the Inline Toolbar (unlike Notion). Also, there is no Block tools at the Inline Toolbar (like Medium and Paper) because they affects the whole Block, not a selected fragment.

- Need to create the new Block Converter Toolbar that looks like Toolbox but without Plus Button and with background/border etc like Inline Toolbar.
- Block Converter Toolbar should be shown when user selects the whole Block by CMD+A
- Block Converter Toolbar should be shown when user selects more that 95% of blocks content.
- Current Block's type is highlighted
- Paragraph tool should be added to the Toolbar (icon required)

**Comment by neSpecc** [comment]
Related #687

**Comment by aponski** [comment]
Hi, any estimates on 2.15 release dates? Waiting for conversion tool :)

**Comment by neSpecc** [comment]
@aponski will be released next week.

**Comment by gohabereg** [comment]
Resolved by #826

**Comment by alexey13** [comment]
Here is the use case when we have problems with 95%: only one line in a paragraph with marker  inline component for example. Its impossible to implement because if we select that line we will see only block tools but we want to make a one-line marker in a paragraph. Why we need a paragraph? Its perfect for aligning content left-center-right-justify.

**Comment by neSpecc** [comment]
@alexey13 can you create an issue based on this case? We will thinking about it.
