### ISSUE TITLE
Cannot find module 'codex-notifier'

### ISSUE THREAD

**Issue by bkdiehl** [codex-team/editor.js#713]
When I install @editorjs/editorjs version 2.12.4 through npm it gives me this error when I import EditorJS.  TS2307: Cannot find module 'codex-notifier'.

**Comment by iGeek0** [comment]
i have the same problema, the first time work great, but the next day show the same...

**Comment by iGeek0** [comment]
i found a solution just need no execute this comand 
`npm instal codex-notifier --save`
nex you need to edit node_modules > codex-notifier > index.d.ts

and this to the top of code 
`import * as notifier from "codex-notifier";`
its work for me!

**Comment by gohabereg** [comment]
Hi @iGeek0 

Thank you! We will update types definitions with the out of the box solution of this problem

**Comment by Tonvdpol** [comment]
When I apply this solution I get a new error:

`[ ERROR ]  TypeScript: node_modules/codex-notifier/index.d.ts:1:7
           Circular definition of import alias 'notifier'.
`

I have EditorJS version 2.12.4 installed.

**Comment by bkdiehl** [comment]
I noticed that this problem only comes up if I use an import statement. After implementing the workaround by @iGeek0, I was getting errors from server side rendering in my react app (ReferenceError: window is not defined). Changing the import statement to "require" in my componentDidMount method seems to have solved the problem, though now it's only rendered client side.

**Comment by gohabereg** [comment]
Resolved by #719
