### ISSUE TITLE
Problem with the start placeholder "Tell your story"

### ISSUE THREAD

**Issue by Aleksst95** [codex-team/editor.js#714]
After rendering editor the start placeholder appear just when I make new empty paragraph or enter a text and clear it.

**Comment by delroh** [comment]
Also, tools are added, the add block menu gets mixed with the placeholder text. See attached image: 
![image](https://user-images.githubusercontent.com/3700414/57504308-f0758900-72c1-11e9-8b0b-7468a011f8ee.png)

**Comment by nynevi** [comment]
I can confirm that I experience the same two issues above

**Comment by nynevi** [comment]
root div (class `codex-editor`) has no `codex-editor--empty` class on init. probably because we have an initialBlock inside the editor that counts as not empty

**Comment by mostafa6765** [comment]
you can try with paragraph placeholde `.` @Aleksst95 

```js
paragraph: {
    class: Paragraph,
    inlineToolbar: true,
     config: {
        placeholder: '.'
      }
 },
```
