### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by webpreneur** [codex-team/editor.js#716]
Does the library supports **Angular**? Are you planning on supporting it in the future?

**Comment by gohabereg** [comment]
Hi @webpreneur !

You should be able to use Editor.js in Angular without any problem. However we are planning to create package with Angular component soon

**Comment by NiNJAD3vel0per** [comment]
I am also expecting Angular support.!!!

**Comment by tekknikk** [comment]
Would totally love angular support.  That would rock!  Let me know if you need help.

**Comment by MikeLallemont** [comment]
Oh yes, this would be excellent. I am integrating editorjs into an Ionic project. They have a tool called Stencil that allows you to create web components from Javascript. This would allow it to work with any framework and use native dom elements. Maybe something to look into?

**Comment by riscie** [comment]
@gohabereg Thank you for telling us about your plans regarding an angular package. In the meantime I tried to get editor.js running in one of our angular applications. I suppose it's not as easy, as one might think. After importing and constructing the editorjs object I get: ` Editor.js is not ready because of Error: element with ID «editor-js» is missing. Pass correct holder's ID.`. 

The element with the id `editor-js` does exist inside the same component. My guess is, that due to angulars encapsulation, the editorjs library can not access the html element to create the editor.

Can you maybe point me to the right direction? Do you happen to have a sample where editorjs is used with angular?

thanks again for the great work :+1:

**Comment by tanepiper** [comment]
@webpreneur @gohabereg Hi, so I've been working on this anyway so I've released a open-source library for this:

https://github.com/tanepiper/ngx-tinynodes/tree/master/libs/ngx-editorjs

I'll publish it on NPM with [`@tinynodes/ngx-editorjs`](https://www.npmjs.com/package/@tinynodes/ngx-editorjs) - I've published a 0.0.1 version for now as a placeholder until I can write docs, but have a look in the example app how to import and use it.

https://github.com/tanepiper/ngx-tinynodes/tree/master/apps/ngx-tinynodes/src

Since I'm intending to use this myself in a project I'll be releasing new features soon.

**Comment by tanepiper** [comment]
@gohabereg @webpreneur I've released v1.0.0 on `npm`.

There is a working demo here: https://tinynodes-ngx.firebaseapp.com/ngx-editorjs-demo

It look me a little longer to release as I had to fix an AOT issue - there's details in the README on how to import EditorJS tools that supports production compiling: https://github.com/tanepiper/ngx-tinynodes/blob/master/libs/ngx-editorjs/README.md

**Comment by MikeLallemont** [comment]
I installed this package and it required peer dependencies of @editorjs/editorjs, @editorjs/header, @editorjs/list and @editorjs/paragraph. Then the module NgxEditorJSModule is not located at @tinynodes/ngx-editorjs but at @tinynodes/ngx-editorjs/src. 

Maybe fix that or update documentation? 

But thanks so much for making this! Looking forward to using it. 

Mike

**Comment by tanepiper** [comment]
Hi @MikeLallemont 

Thanks for the feedback - I've released `1.2.0` today and now have full docs here: https://tanepiper.github.io/ngx-tinynodes/

In regards to the peer dependencies, this is because Angular AOT requires these dependencies to be at the root of the project, adding them as hard dependencies won't work.  I've added added a quick notes [here](https://github.com/tanepiper/ngx-tinynodes/tree/master/libs/ngx-editorjs-plugins) in the plugin docs.

I've also removed default plugins from the core package, you now need to pass them manually within the config for `header`, `paragraph` and `list`.  This is mostly due to a `@nrwl/nx` issue with monorepos, allowing me to release.

If you have any more feedback feel free to leave issues on my [main repo](https://github.com/tanepiper/ngx-tinynodes/issues)

**Comment by MikeLallemont** [comment]
Tane,

Great work and I appreciate so much. But a few of those links are 404s and it would be super helpful if you had some documentation of what the Angular template should look like or have the source to the demo available. I found some code for he nav-bar, side-menu, etc. but nowhere could I find the main editor demo code. When I load the demo page it does not show the editor anymore either. Maybe something got deleted? 

Anyway, I’m looking forward to using it when it all comes together and I’ll add bugs or feature requests as I come across. Are you planning on making the component work as an Angular form control? If so that would be ideal. 

Thanks again for the hard work!

Mike

**Comment by tanepiper** [comment]
@MikeLallemont Thanks for the feedback - aware of a few 404's due to the way Compodoc works, I'll look to resolve that soon.

If you look in the docs for the module and demo module:

https://tanepiper.github.io/ngx-tinynodes/modules/NgxEditorJSModule.html
https://tanepiper.github.io/ngx-tinynodes/components/NgxEditorJSComponent.html

These have example uses.  I'm working on 1.3 just now, but this will mostly be unit tests I'm working on - I'll also possibly have a pre-build form component for reactive and template driven forms, it's on my feature list but I had some issues with the first version I wrote so I need to re-think it slightly.

**Comment by tanepiper** [comment]
@MikeLallemont Hello again, I've since released 1.3

Have a look at the demo on https://tinynodes-ngx.firebaseapp.com/ngx-editorjs-demo/pages

In regards to using it, have a look at https://tanepiper.github.io/ngx-tinynodes/components/PageContainerComponent.html#info

This version is mostly internal changes, I didn't get time to do the Form component - but now it should be easier, this version was mostly making the EditorJS more accessible in Angular and work with more observable values.

**Comment by tanepiper** [comment]
Hello again issue subscribers!  I've just released 2.0.0 and it's quite a big change internally, also now the component works with Angular Forms out the box.  Not only that, there is a native Material component to use (see [demo](https://tinynodes-ngx.firebaseapp.com/ngx-editorjs-demo/angular-form)).

Docs have been updated quite a bit and again the demo in the repo show's example usage with auto save support

**Comment by leorolland** [comment]
How to use EditorJs with Angular 9 using ViewChild :

component.html
```html
<div #editorJs></div>
```

component.ts
```ts
import { Component, Input, ViewChild, ElementRef, AfterViewInit } from '@angular/core';
import EditorJS from '@editorjs/editorjs';
import Header from '@editorjs/header'; 
import List from '@editorjs/list'; 

@Component({
  selector: 'app-component',
  templateUrl: './.component.html',
  styleUrls: ['./component.scss']
})
export class Component implements AfterViewInit {
  @ViewChild('editorJs') el:ElementRef;

  constructor() { }

  ngAfterViewInit() {
    console.log(this.rd); 
    const editor = new EditorJS({
      holder: this.el.nativeElement,
      tools: { 
        header: Header, 
        list: List,
      }, 
      
    });
  }

}

```

**Comment by Pietrox** [comment]
Somehow this code throws me that element is undefined. Did you use some timeout on the original code?

**Comment by markCornejo** [comment]
When compiling. In Angular 9 gives me the following error. 

> ERROR in node_modules/@editorjs/editorjs/types/api/block.d.ts:2:25 - error TS2307: Cannot find module '../../src/types-internal/block-data'.

**Comment by dottodot** [comment]
> How to use EditorJs with Angular 9 using ViewChild :
> 
> component.html
> 
> ```
> <div #editorJs></div>
> ```
> 
> component.ts
> 
> ```ts
> import { Component, Input, ViewChild, ElementRef, AfterViewInit } from '@angular/core';
> import EditorJS from '@editorjs/editorjs';
> import Header from '@editorjs/header'; 
> import List from '@editorjs/list'; 
> 
> @Component({
>   selector: 'app-component',
>   templateUrl: './.component.html',
>   styleUrls: ['./component.scss']
> })
> export class Component implements AfterViewInit {
>   @ViewChild('editorJs') el:ElementRef;
> 
>   constructor() { }
> 
>   ngAfterViewInit() {
>     const editor = new EditorJS({
>       holder: this.el.nativeElement,
>       tools: { 
>         header: Header, 
>         list: List,
>       }, 
>       
>     });
>   }
> 
> }
> ```

I'm trying to use editorjs using this method in Angular but when I try to add a block by clicking or by using a shortcut I get the following error, apart from the paragraph block which works ok.

```
error-handler.service.ts:12 TypeError: Cannot read property 't' of undefined
    at new t (bundle.js:formatted:1)
    at e.value (bundle.js:formatted:1)
    at e.value (bundle.js:formatted:1)
    at e.value (bundle.js:formatted:1)
    at e.value (bundle.js:formatted:1)
    at e.value (bundle.js:formatted:1)
    at HTMLLIElement.<anonymous> (bundle.js:formatted:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (bundle.js:formatted:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
```

My current config is 

```
 const editor = new EditorJS({
      holder: this.el.nativeElement,
      placeholder: 'Write blog here!',
      tools: {
        header: {
          class: Header,
          shortcut: 'CMD+SHIFT+H',
        },
        list: {
          class: List,
          inlineToolbar: true,
        },
        paragraph: {
          class: Paragraph,
          inlineToolbar: true,
        },
      },
    });
```

**Comment by susana-bit** [comment]
> When compiling. In Angular 9 gives me the following error.
> 
> `ERROR in node_modules/@editorjs/editorjs/types/api/block.d.ts:2:25 - error TS2307: Cannot find module '../../src/types-internal/block-data'.`

Same issue here in Angular 8

**Comment by khan9920** [comment]
I am trying to use Editor.js in one of my Angular apps and when I try to configure heading, lists and other blocks, it gives me the following error:

```
ERROR TypeError: Cannot read property 't' of undefined
    at e.value (bundle.js:10)
    at new e (bundle.js:10)
    at e.value (editor.js:2)
    at e.value (editor.js:2)
    at e.value (editor.js:2)
    at e.value (editor.js:2)
    at e.value (editor.js:2)
    at HTMLLIElement.<anonymous> (editor.js:2)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
```


This is the code snippet of my component. 


```
import { Component, OnInit } from '@angular/core';
import EditorJS from '@editorjs/editorjs';
import Header from '@editorjs/header';
import List from '@editorjs/list';

@Component({
  selector: 'app-editorjs',
  templateUrl: './editorjs.component.html',
  styleUrls: ['./editorjs.component.css']
})
export class EditorjsComponent implements OnInit {

  editor;

  constructor() { }

  ngOnInit() {
    this.editor = new EditorJS({
      holder: 'editor-js',
      tools: {
        header: {
          class: Header,
          shortcut: 'CMD+SHIFT+H',
        },
        list: {
          class: List,
          inlineToolbar: true,
        },
      }
    });
  }

  onSave() {
    this.editor.save().then((outputData) => {
      console.log('Article data: ', outputData)
    }).catch((error) => {
      console.log('Saving failed: ', error)
    });
  }
}
```

Anybody knows how to fix this? :(

**Comment by dottodot** [comment]
@khan9920 I had this problem too. It seems to be resolve in the latest version but you will get a type error when trying to build using it. So I use patch-package to resolve the type error.

**Comment by khan9920** [comment]
@dottodot I updated it to the latest version, but then started getting this error.

`ERROR in node_modules/@editorjs/editorjs/types/api/block.d.ts(2,25): error TS2307: Cannot find module '../../src/types-internal/block-data'.`

I opened that file from @editorjs/editorjs/types/api/block.d.ts and commented out the line that has errors. It works fine now. I know this not the best practice and may cause unwanted issues, but it does what I want it to do 😅 

Thanks for suggesting patch-package, I will give it a shot too. 😎

**Comment by renanredel** [comment]
> @dottodot I updated it to the latest version, but then started getting this error.
> 
> `ERROR in node_modules/@editorjs/editorjs/types/api/block.d.ts(2,25): error TS2307: Cannot find module '../../src/types-internal/block-data'.`
> 
> I opened that file from @editorjs/editorjs/types/api/block.d.ts and commented out the line that has errors. It works fine now. I know this not the best practice and may cause unwanted issues, but it does what I want it to do 
> 
> Thanks for suggesting patch-package, I will give it a shot too.

For me, only works after I commented theses lines.
Has any way to get around that error?

**Comment by BondarenkoMaks** [comment]
the same issue: 
`_node_modules/@editorjs/editorjs/types/api/block.d.ts(2,25): error TS2307: Cannot find module '../../src/types-internal/block-data'.`_

**Comment by REPTILEHAUS** [comment]
+1 for Angular Support

**Comment by tanepiper** [comment]
@REPTILEHAUS and others - I still get notification for this thread it seems.

I wrote a Angular component that supports EditorJS, also works with Material - the demo is here https://tinynodes-ngx.firebaseapp.com/ngx-editorjs-demo with links to the docs

**Comment by REPTILEHAUS** [comment]
@tanepiper thanks, I would really like if the official team released something though

**Comment by Sh3nl0ng** [comment]
@tanepiper thanks a lot for all of your hard work on this package. I've spent the past few nights familiarizing myself with editor.js and your packages.

I'm very interested in using Angular components to create custom Editor.js content blocks. Do you have any experience accomplishing this?

For those running into the `ERROR in node_modules/@editorjs/editorjs/types/api/block.d.ts(2,25): error TS2307: Cannot find module '../../src/types-internal/block-data'.` please see: https://github.com/codex-team/editor.js/issues/1183#issuecomment-651464641

**Comment by susana-bit** [comment]
> When compiling. In Angular 9 gives me the following error.
> 
> `ERROR in node_modules/@editorjs/editorjs/types/api/block.d.ts:2:25 - error TS2307: Cannot find module '../../src/types-internal/block-data'.`

**Comment by ratkorle** [comment]
Hi, I am trying to implement EditorJs in my Angular Project.
as above the implementation is with ViewChild:

` <div id="post-editor" #editorJs></div>
`
```
ngAfterViewInit() {
    this.SetEditor();
  }
```

```
SetEditor(): void {
    this.editor = new EditorJS({
      holder: this.el.nativeElement,
      tools: {
        header: {
          class: Header,
          config: {..............
```

When I run it with **ng serve** works good. but when It is **built** and served. I get the following error:
```
ReferenceError: Element is not defined
    at Object.apply (/Users/xxxx/xxxx/client/xxxx/dist/server/webpack:/node_modules/@editorjs/editorjs/dist/editor.js:2:230487)
    at Object.call (/Users/xxxxx/xxxxx/client/xxxxx/dist/server/webpack:/node_modules/@editorjs/editorjs/dist/editor.js:2:231357)


```
Any help please ?

**Comment by susana-bit** [comment]
> > When compiling. In Angular 9 gives me the following error.
> > `ERROR in node_modules/@editorjs/editorjs/types/api/block.d.ts:2:25 - error TS2307: Cannot find module '../../src/types-internal/block-data'.`
> 
> Same issue here in Angular 8

This bug is solved in editor v 2.19

**Comment by kinng007** [comment]
> Edit - I've found the answer was using @angular/elements to create web components that play nice with the natural flow of editorjs. 
@Sh3nl0ng - I am trying to achieve the same. Can you refer me to a sample code?

**Comment by ankitkanaujia** [comment]
Hi there,
I am using  Editor.js in my angular project.
Angular CLI: 10.0.8
Node: 12.13.0
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@nguniversal/builders             10.1.0
@nguniversal/common               10.0.2
@nguniversal/express-engine       10.0.2
@schematics/angular               9.1.0
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

I run npm run build:ssr it bbuilds my project fine 
but as soon as I run npm run serve:ssr 
it gives me the error 
!function(e,a){for(var i in a)e[i]=a[i]}(exports,function(modules){var installedModules={};function __webpack_require__(moduleId){if(installedModules[moduleId])return installedModules[moduleId].exports;var module=installedModules[moduleId]={i:moduleId,l:!1,exports:{}};return modules[moduleId].call(module.exports,module,module.exports,__webpack_require__),module.l=!0,module.exports}return __webpack_require__.m=modules,__webpack_require__.c=installedModules,__webpack_require__.d=function(exports,name,getter){__webpack_require__.o(exports,name)||Object.defineProperty(exports,name,{enumerable:!0,get:getter})},__webpack_require__.r=function(exports){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(exports,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(exports,"__esModule",{value:!0})},__webpack_require__.t=function(value,mode){if(1&mode&&(value=__webpack_require__(value)),8&mode)return v

ReferenceError: window is not defined
    at Object.kzam (C:\Users\Ankit\Desktop\PoliticsKiPathshala\dist\PoliticsKiPathshala-frontend\server\main.js:1:2392099)
    at __webpack_require__ (C:\Users\Ankit\Desktop\PoliticsKiPathshala\dist\PoliticsKiPathshala-frontend\server\main.js:1:295)
    at Object.86gh (C:\Users\Ankit\Desktop\PoliticsKiPathshala\dist\PoliticsKiPathshala-frontend\server\main.js:1:1038947)
    at __webpack_require__ (C:\Users\Ankit\Desktop\PoliticsKiPathshala\dist\PoliticsKiPathshala-frontend\server\main.js:1:295)
    at Object.hFx2 (C:\Users\Ankit\Desktop\PoliticsKiPathshala\dist\PoliticsKiPathshala-frontend\server\main.js:1:2333631)
    at __webpack_require__ (C:\Users\Ankit\Desktop\PoliticsKiPathshala\dist\PoliticsKiPathshala-frontend\server\main.js:1:295)
    at __webpack_require__ (C:\Users\Ankit\Desktop\PoliticsKiPathshala\dist\PoliticsKiPathshala-frontend\server\main.js:1:295)
    at Object.ZAI4 (C:\Users\Ankit\Desktop\PoliticsKiPathshala\dist\PoliticsKiPathshala-frontend\server\main.js:1:1618632)
    at __webpack_require__ (C:\Users\Ankit\Desktop\PoliticsKiPathshala\dist\PoliticsKiPathshala-frontend\server\main.js:1:295)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! politics-ki-pathshala-frontend@0.0.0 serve:ssr: `node dist/PoliticsKiPathshala-frontend/server/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the politics-ki-pathshala-frontend@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ankit\AppData\Roaming\npm-cache\_logs\2020-12-06T12_25_21_249Z-debug.log

Any idea why that might be? or how can I resolve this issue?

**Comment by AppsusUK** [comment]
> > Edit - I've found the answer was using @angular/elements to create web components that play nice with the natural flow of editorjs.
> 
> @Sh3nl0ng - I am trying to achieve the same. Can you refer me to a sample code?

Hi were you able to get custom components as blocks in editorjs?

**Comment by thekhegay** [comment]
`Cannot read property 'updateCurrentInput' of undefined`

Anyone handle same error?

**Comment by neSpecc** [comment]
Angular supported. For SSR issues follow this thread https://github.com/codex-team/editor.js/issues/1036
