### ISSUE TITLE
Editor height by default has too much empty space

### ISSUE THREAD

**Issue by dheerajsarwaiya** [codex-team/editor.js#724]
Editor height is calculated as sum of block heights + 300px of bottomZone. This extra bottomZone of 300 px is huge for use cases such as comment section, or asking users to write small notes or paragraph.

It would be great if we have option to decrease the bottomZone height. 
![Screenshot from 2019-04-13 10-38-33](https://user-images.githubusercontent.com/18539875/56083538-23b81b80-5ddb-11e9-951e-a9ff0178ce32.png)

**Comment by neSpecc** [comment]
Resolved by #719

**Comment by ponnex** [comment]
We still experience the issue with padding-bottom having 300px. v2.15.1 of editorjs.

**Comment by arturcesarmelo** [comment]
Wasn't solved, as far as i can see.

![image](https://user-images.githubusercontent.com/18191910/69498452-fbdb7b00-0ec6-11ea-97c3-3c305f751339.png)

Even if you reduce the codex-editor content height, an 300px padding-bottom overflows the editor content.

How can i fix this?

**Comment by hata6502** [comment]
I see, miHeight option can't set to 0px. 
Please fix

```
this.config.minHeight = this.config.minHeight || 300;
```

to

```
this.config.minHeight = this.config.minHeight!==undefined ? this.config.minHeight || 300;
```

https://github.com/codex-team/editor.js/pull/719/files#diff-e3bf20e89f6b22c16beb3e17fb3c8a60R154

**Comment by neSpecc** [comment]
@hata6502 you are welcome to fix it and send a PR

**Comment by Dectom** [comment]
Not fixed, still a problem!

![image](https://user-images.githubusercontent.com/14962862/102064492-45a74400-3def-11eb-9243-8b9d547978b7.png)

minHeight set to 30 however it still creates a 300px padding-bottom, this is really annoying. Please resolve

![image](https://user-images.githubusercontent.com/14962862/102064606-6bcce400-3def-11eb-861d-088db617cf0f.png)

**Comment by khan9920** [comment]
How do I use `config` in my code? I couldn't find any examples anywhere. Please help!

![image](https://user-images.githubusercontent.com/29376547/103152324-f24cd280-47ac-11eb-8ce3-eccb742cd9cb.png)

**Comment by yuya-pascolo** [comment]
@khan9920 
```
this.editor = new EditorJS(
  holder: 'editor-js',
  ...,
  minHeight : 0
);
```

**Comment by andreykorolev** [comment]
When I set minHeight to 0 it creates block with 300 height and then reduces it to 0 after a second.

**Comment by roland83** [comment]
@andreykorolev 
> When I set minHeight to 0 it creates block with 300 height and then reduces it to 0 after a second.

I noticed this too. There's a "codex-editor__loader" class with height: 30vh, you'll need to override that

`.codex-editor__loader { height: 38px !important; }`

This eliminated the resize for me. May need to tweak the value for your use case.

**Comment by bellcoTech** [comment]
I added both of these and it now works

.codex-editor__loader { height: 38px !important; }
.codex-editor__redactor { height: 38px !important; }

**Comment by nagarjuna-gangadhari** [comment]
.ce-block__content, .ce-toolbar__content { max-width: calc(100% - 100px) !important; } .cdx-block { max-width: 100% !important; }
.codex-editor__loader { height: 38px !important; }
.codex-editor__redactor { padding-bottom: 38px !important; }

**Comment by mu7ammad1** [comment]
> .ce-block__content, .ce-toolbar__content { max-width: calc(100% - 100px) !important; } .cdx-block { max-width: 100% !important; } .codex-editor__loader { height: 38px !important; } .codex-editor__redactor { padding-bottom: 38px !important; }

this is true code in style css or global styles in the page
