### ISSUE TITLE
Documentation error: editor.js installed as dev-dependency

### ISSUE THREAD

**Issue by davidsneighbour** [codex-team/editor.js#730]
The documentation at [docs/installation](https://github.com/codex-team/editor.js/blob/master/docs/installation.md) states to install editor.js via npm by 

```
npm i @editorjs/editorjs --save-dev
```

This would install it as dev-dependency and if someone really OCD uses this it can lead to the editor.js files not being available in production environments. Right? It should be installed as default dependency, not dev?

**Comment by delroh** [comment]
Shouldn't this change also be reflected on https://editorjs.io/getting-started ?

**Comment by davidsneighbour** [comment]
It probably will be once the site is updated. If you check in docs/installation.md it is already changed.

**Comment by Haraldson** [comment]
This is still wrong in Getting started, almost a year later?
