### ISSUE TITLE
Editor Nesting

### ISSUE THREAD

**Issue by TheCrether** [codex-team/editor.js#732]
I want to make structure charts and found editor.js
And if I wanted to make a if, I wanted to make a editor for the right and one for the left, or is there an better possibility? 
Maybe that column support which i saw before while scrolling through the issues

**Comment by neSpecc** [comment]
@TheCrether need more detailed explanation, maybe you have a mockup?

**Comment by TheCrether** [comment]
here a screen shot what kind of represent what i want to do
![grafik](https://user-images.githubusercontent.com/18720938/56273668-79533780-60fd-11e9-8d1c-207840ff7d8e.png)

not really styled but thats kind of what i want to do

**Comment by TheCrether** [comment]
any update for nested editors?

**Comment by neSpecc** [comment]
Looks like you just need to initialise two independent Editor instances and show one of them. Or make a single instance and replace it with another after condition will be changed.
