### ISSUE TITLE
Error when leaving page before form with Editor.js is fully loaded

### ISSUE THREAD

**Issue by guillaumepn** [codex-team/editor.js#733]
I added Editor.js in my React app (via [this wrapper](https://github.com/stfy/react-editor.js))

When I go to the page with a form containing the Editor.js react component, and leave the page before Editor.js was fully loaded (I notice there is a little delay during which a loader is spinning in the textarea), it "breaks" my app, showing only a blank page with the following error in browser's console :

`TypeError: Cannot read property "'disconnect'" of undefined`

The error doesn't seem to be related to the React wrapper, as it is not modifying the MutationObserver's disconnect function ; I'd like to know if people using Editor.js directly also face this issue

Don't know if this would fix the issue, but I can do a PR checking if `this.observer` is defined/not null before disconnecting here :  
```js
public destroy() {
    this.mutationDebouncer = null;
    this.observer.disconnect();
    this.observer = null;
  }
```

**Comment by neSpecc** [comment]
Thanks for the report. Please, feel free to send a PR, we will test it and add to the next release.

**Comment by easychen** [comment]
i meet this problem too , but also in react app .

**Comment by guillaumepn** [comment]
Couldn't reproduce the issue with Editor.js on a simple app (No React or whatever)

I'll have to do some more tests in React env before submitting a PR

**Comment by brandontle** [comment]
It seems to be an issue with the react-editor.js wrapper. [I opened an issue on this topic over there](https://github.com/stfy/react-editor.js/issues/1).
