### ISSUE TITLE
Can't get current block index via editor instance

### ISSUE THREAD

**Issue by easychen** [codex-team/editor.js#741]
I use `react-edtior-js` to build a block editing experience, this component expose a editor instance for operation. 

But when i use blocks.getCurrentBlockIndex, it always returns -1 .  Is this method OK
 for instance calling or just work in api ?

```
this.editorInstance.blocks.getCurrentBlockIndex()
```

**Comment by easychen** [comment]
I found the problem. If your call this method after blur , it will return -1.

**Comment by ratneshmurugesan** [comment]
> I found the problem. If your call this method after blur , it will return -1.

And, so, When an element is focused, save the index in state or storage, before blur out.
