### ISSUE TITLE
Need some API

### ISSUE THREAD

**Issue by CITGuru** [codex-team/editor.js#743]
Hello,

I am currently using this in a react blog as our writing tool and there are some methods I can't find thats suppose to be there.

Is there a method like `onChange` or `change` that tells us whenever a change occurs. I looked through the source code and I saw it there. But I think its not in use and not documented.

I also notice that the toolbar plus button is not at the right place. Like as it is in the demo on editorjs.io

**Comment by gohabereg** [comment]
Hi @CITGuru 

There are an option for initial configuration that you can pass to handle changes https://editorjs.io/configuration#editor-modifications-callback

Plus button appears at the other place (inside of the editor zone) in the narrow wrappers, making the wrapper wider might solve the problem.

**Comment by CITGuru** [comment]
@gohabereg Thanks for your response.

I tried increasing the wrapper width and the plus button still the same. 

in the `onChange` method, can we get the data apart from using the .`save` method

**Comment by gohabereg** [comment]
@CITGuru 

Could you please provide a screenshot with the button?

You need to call `save` method manually, we don't provide saved data to the `onChange` callback for performance purposes

**Comment by CITGuru** [comment]
![Screenshot from 2019-04-25 16-01-55](https://user-images.githubusercontent.com/16475846/56746175-94fcb480-6773-11e9-8145-890168ae8c2b.png)

**Comment by CITGuru** [comment]
I also notice that pressing the backspace button clears the content of a block

**Comment by gohabereg** [comment]
Well, could you open new issue for the button bug and provide there your environment (os, browser etc). I'm closing this one
