### ISSUE TITLE
input type="number" Uncaught DOMException Error

### ISSUE THREAD

**Issue by onuralp4** [codex-team/editor.js#754]
Hello !

When i am using input for my plugin with type="number", following error is threw by editorjs :

`editorjs@latest:16 
Uncaught DOMException: Failed to set the 'selectionEnd' property on 'HTMLInputElement': The input element's type ('number') does not support selection.
    at e.value (https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest:16:100567)
    at https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest:16:99795
    at https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest:16:12402`

It does not effect any core functionality like saving or rendering as i tested out. I am not sure if it is major issue or not. Should we do something about this error ?

Onur

**Comment by khaydarov** [comment]
@onuralp4 Hi!
Can you describe in more detail the case of usage input with type number? When error is thrown? After you insert rendered Block or when you're trying to set caret via keyboard...
I think we could take the issue in the next release

**Comment by neSpecc** [comment]
Looks like it is not actual
