### ISSUE TITLE
Save not triggered on toolbar change

### ISSUE THREAD

**Issue by dellow** [codex-team/editor.js#757]
The editors save method does not trigger when you use a toolbar action.

For example, on the quote module, if I were to change the alignment, I would have to edit some text before the save method is triggered.

**Comment by khaydarov** [comment]
Fixed in [v2.19](https://github.com/codex-team/editor.js/releases/tag/v2.19.0)

**Comment by vaal-** [comment]
2.19.3 the problem still exists
