### ISSUE TITLE
[Docs] Broken link at Configuration page

### ISSUE THREAD

**Issue by delroh** [codex-team/editor.js#762]
In the configuration page, at the [Change the default Block](https://editorjs.io/configuration#change-the-default-block) section, the [paste patterns](https://editorjs.io/process-paste-patterns)  link is returning this JSON:
```
{
    "success": false,
    "error": "Entity with given alias does not exist"
}
```

**Comment by gohabereg** [comment]
Thanks @delroh 

Fixed 👍
