### ISSUE TITLE
save() method to allow html?

### ISSUE THREAD

**Issue by butaminas** [codex-team/editor.js#763]
I have html content with attributes loaded into paragraph blocks on load and it works great but whenever I click save, I only get the text and not the full HTML of the paragraph.

Anyway to allow saving full HTML rather than text only?

**Comment by butaminas** [comment]
Figured out myself, though please let me know if there is a better way.

What I did was I created a custom tool based on Paragraph tool and allowed 'span' attribute in sanitizer and then made my customParagraph as a default paragraph by using "initialBlock: 'customParagraph'" setting.

Is there something else I need to do to completely disable the default paragraph tool?

**Comment by khaydarov** [comment]
@butaminas I think it is a better way for now is to use "customParagraph" and change Class properties inside it. We'll think about "built-in paragraph" configuration and will include in the nearest releases.
Thanks!
