### ISSUE TITLE
setToPreviousBlock offset doesn't work

### ISSUE THREAD

**Issue by butaminas** [codex-team/editor.js#764]
I don't fully understand the idea of this option but the way I think it should work is the offset should place the marker in the block after X characters (X - being the offset number).

Right now, when I use the offset, no matter what number I put in, the marker is either at the beginning or at the end (based on the first option being 'start' or 'end').

Am I understanding this 'offset' option wrong? Is there anyway to actually define markers position?

**Comment by khaydarov** [comment]
Hi @butaminas 
No, the `offset` is not wrong option. In most cases Editor's core needs to set caret at 'start or 'end'.  The `this.positions.START` or 'this.positions.END' constants sets the `offset` the length or 0.

To use default offset, pass 'this.positions.DEFAULT'
