### ISSUE TITLE
Add support for IntelliSense 

### ISSUE THREAD

**Issue by RogerLiNing** [codex-team/editor.js#766]
Hi There

Is it possible to add intellisense like this editor?
https://microsoft.github.io/monaco-editor/
![image](https://user-images.githubusercontent.com/18111035/57602557-06b96880-7592-11e9-8ec4-0f8fdc34353c.png)

**Comment by ZiQiLN** [comment]
Editor.js isn't solution for code editing, it's an solution for building content which can be perfectly used in CMS. You should take attention to embed content and use ex. https://codesandbox.io/

**Comment by RogerLiNing** [comment]
Thanks a lot @ZiQiLN. 
Actually, I'm not looking for a solution for code editing, I just want to save time when I'm writing. It'll be a huge benefit if there are hints when I'm writing. 

I finally found an alternative for this case https://summernote.org/examples/#hint, this is exactly what I wanted. So, it's ok to close this issue, and thank you so much for your suggestion!
