### ISSUE TITLE
How to work with JSX in editor.js

### ISSUE THREAD

**Issue by roman-kosiuh** [codex-team/editor.js#769]
I use React, how can i pass jsx into the editor ? For example
```
class EditPage extends React.Component {
   componentDidMount() {
      const editor = new EditorJS({
      holderId: 'codex-editor',
      autofocus: true,
      tools: {
        header: {
          class: Header,
          inlineToolbar: true,
          shortcut: 'CMD+SHIFT+H'
        },
     },
      data: {
        "time": 1550476186479,
        "blocks": [
           {
              "type": "paragraph",
              "data": {
                "text": <div onClick={this.someFunc} className="hello">Hello World</div>
              }
           }
        ]
      },
      onReady: () => {
        console.log('Editor.js is ready to work!');
      }
    })
   }
  someFunc = () => console.log('Hello world');
  render() {
      return (
       <><div id="codex-editor" /></>
      )
  }
}
```

**Comment by nynevi** [comment]
You will probably have to use low-level APIs of React for this. You can probably have a JSON representing your element and it's state in it's data object in the block then React.createElement or something like that while adding it but then again you would probably have to create block plugins with your HelloWorldComponent to use it in the editorjs

**Comment by neSpecc** [comment]
@roman-kosiuh in your example, you store some kind of plugin's UI in the `data.text` property, that is incorrect behavior. the `data` should store only exported text-values of your Tool. The UI should rendered by the `render()` method of it. You can use React there.
