### ISSUE TITLE
Update data in existing editor.

### ISSUE THREAD

**Issue by mrmurphy** [codex-team/editor.js#776]
In order to prevent editing conflicts when two users may be interacting with the same document, I'd like to fetch changes from the server regularly, and update the content of the editor with anything that may have changed.

I can't find an API to set the blocks that the editor has in it after the initial configuration, though.

Would I just call `.clear` on the editor, and then call `insertBlock` on each of my newly fetched blocks? I'd also save and restore the cursor position then, I suppose?

**Comment by neSpecc** [comment]
You can use [clear](https://editorjs.io/blocks#clear) and [render](https://editorjs.io/blocks#render) methods. For working with caret, use [Caret API](https://editorjs.io/caret).

What methods you would also like to see?

**Comment by mrmurphy** [comment]
Okay, that makes sense. I was thinking of an API where I could pass in an array of blocks, like I can do on init, and the editor would replace the existing content with the new content while preserving the cursor position. But as you said, that can be done by hand.
