### ISSUE TITLE
!!! conflict  grammarly !!!

### ISSUE THREAD

**Issue by mostafa6765** [codex-team/editor.js#779]
editorjs is nice block styled editor. but when grammerly extension is enabled that time editorjs is `valueless`  output is grammerly error html. 

resolve this conflict with grammarly.

# approximate solve 

```js
componentDidMount() {
    const { editor } = this.refs
    const draftEditor = editor.refs.editor
    draftEditor.setAttribute('data-gramm', 'false')
  }
```

reference 
* [draft-js issue 616](https://github.com/facebook/draft-js/issues/616#issuecomment-260666477)

**Comment by hotthemes** [comment]
I had the same issue.

**Comment by RomainLapeyre** [comment]
Same issue too

**Comment by Sutarodo** [comment]
Grammarly have refused to support Draft until they figure out how to play nicely.

**Comment by khpatel4991** [comment]
Look at [Perfect Tense](https://www.perfecttense.com/). Shameless plug as I'm one of the developers of it. We have umd script that can be injected in you website that will enable grammar checking on any sort of content editable **without touching/modifying user's dom**.

**Comment by LearnedVector** [comment]
Anybody figure this out? I can't seem to get Grammarly disabled.

**Comment by khaydarov** [comment]
@mostafa6765 @LearnedVector @Sutarodo @hotthemes @RomainLapeyre it works for me fine! 
![image](https://user-images.githubusercontent.com/6507765/69494498-8c1cbe80-0ecd-11ea-938d-c1a8dce10f2e.png)

Can you write your browser and editor version, please?

**Comment by mostafa6765** [comment]
what about output? My issue was output. @khaydarov

**Comment by khaydarov** [comment]
@mostafa6765 yeah, i see. Fix is comming, i opened pull request

**Comment by darpandalal2013** [comment]
@khpatel4991 we want to make a similar chrome plugin 
we have developed a product called as www.manuscripts.ai 

can you help ?
