### ISSUE TITLE
Overwrite paragraph plugin

### ISSUE THREAD

**Issue by vincent-herlemont** [codex-team/editor.js#780]
Hello,

Is it possible to overwrite default `Paragraph` plugin ?
I try something like that with cloning src directory of [@editorjs/paragraph](https://github.com/editor-js/paragraph) to `./paragraph` directory.
```Javascript
        import Paragraph from './paragraph';
        const editor = new EditorJS({
            autofocus: true,
            tools: {
                paragraph: {
                    class: Paragraph,
                },
            }
        });
```
I update `Paragraphe.DEFAULT_PLACEHOLDER` but nothing append.

Thanks for your help.

**Comment by gohabereg** [comment]
Hi @vincent-herlemont 

You will be able to do it in 2.14 version (will be published soon).

**Comment by glauberm** [comment]
@gohabereg Was it implemented? Couldn't find a guide for it.
