### ISSUE TITLE
How to update the data property of Editorjs options

### ISSUE THREAD

**Issue by vsvanshi** [codex-team/editor.js#781]
Hi, 
I am not able to find any api or function in the docs which can be used to update the data.
Suppose I have updated data, and want to update the editorjs instance, I suppose something like this should be present.
`editorJsInstance.setData(newData);
`
Can you please help in the same?

Glad to give more insight if required

**Comment by gohabereg** [comment]
Hi @vsvanshi 

You can use `render()` and `clear()` methods to manipulate the data

Docs: https://editorjs.io/blocks

**Comment by kevtiq** [comment]
@gohabereg 
I call the `render()` with a very simple new set of data.

```
[{"type":"header","data":{"text":"Register now!","level":2}}]
```

I get the following error:

```
Unhandled Rejection (TypeError): Cannot read property 'map' of undefined
```

The `clear()' does empty the entire content. But iterating over the array of new data, and using the `insert()` gives a different error message. 

```
Unhandled Rejection (TypeError): Cannot read property 'config' of undefined
```

**Comment by neSpecc** [comment]
Resolved

**Comment by itsMarydan** [comment]
I sent my editor.js data to MongoDB but when I get it back I am not able to pass it into the editor. I retrieve it using await

**Comment by elnur-elnur** [comment]
how can i create Multiple image with editor js ?

**Comment by gauravsaluja2006** [comment]
For me, editor was getting reset after calling the render method, must be specific to my code.

calling the render method with new data inside a setTimeout helped here.
