### ISSUE TITLE
Don't disable TAB behaviour on non-initial blocks

### ISSUE THREAD

**Issue by bkroeker** [codex-team/editor.js#791]
Currently, all tab presses are suppressed, except on new blocks in which case it opens the toolbar and cycles through it.  This is non-intuitive for block types with many fields (such as a custom one I am building), in which case a user would expect a tab press to jump the cursor to the next form field.  IMO, the more intuitive tab behaviour would be for ALL non-initial blocks to behave as default, rather than simply be suppressed.

**Comment by PentaHelix** [comment]
Any updates on this? I also need this functionality for tools with multiple fields

**Comment by neSpecc** [comment]
For now, the Tab is used for opening Block Tunes panel in non-empty blocks. To navigate through the inputs you can use the keyboard arrows.

**Comment by christoph-kluge** [comment]
@bkroeker @PentaHelix I had the same issue. You can get the relevant changes from here https://github.com/christoph-kluge/editor.js/commit/405cd85b68736041c6a8c412555a142059587c4d . This will give you the relevant TAB functionality which you need. I needed this on my custom modules with inputs as well. Now I'm quite happy and it finally feels pretty good to TAB back and forth.

I think that https://github.com/codex-team/editor.js/issues/927 is perhaps the right place to discuss about it.

**Comment by hata6502** [comment]
I think this is very important issue for accessibility!
Please see: https://www.w3.org/TR/WCAG21/#no-keyboard-trap

**Comment by neSpecc** [comment]
Duplicate https://github.com/codex-team/editor.js/issues/927
