### ISSUE TITLE
How can i extract JSON (Output data) cleaned data using editor.js editor.

### ISSUE THREAD

**Issue by karunakar2smart** [codex-team/editor.js#797]
I created all the essential imports and started using all the features of the editor.js editor. It was really awesome though.
I was wondering that, how can I copy all the JSON formatted text i.e output data created on saving at the editor.js editor, to use for my website purposes?

**Comment by neSpecc** [comment]
Call `save()` method. More information see at the Docs, [Saving Data](https://editorjs.io/saving-data)
