### ISSUE TITLE
The functionality to undo the processing of inserts in the EditorJS plugin

### ISSUE THREAD

**Issue by milanP96** [codex-team/editor.js#801]
While creating the Editor.js plugin, which is a wrapper for the tiptap rich editor of the text editor, the following incorrect behavior was found:
When inserting text into the Editor.js tiptap plugin, the insertion of the text takes place and a paragraph object is created with the given text. That is, the text is duplicated.

It was discussed that this behavior can be corrected by entering an additional parameter that allows you to disable insert processing for the Editor.js plugin.
It is required to implement this parameter.

**Comment by gohabereg** [comment]
Resolved by #826
