### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by ludec** [codex-team/editor.js#808]
Is not possible to add mailto to link in plain text.
Example:
`some <a href="mailto:example@mail.com">link</a> in text`

We are not able to define **rel** and **target** in links.

We find out problems with entities:
- Is not possible to make single non-break space in plain text 
Example:
`some plain&nbsp;text`
- Note for you: When you add for example entity `&copy;` than you can see in html structure automaticly transformed symbol `©`. Shouldn't the html entity be rendered instead of symbol?

Just FYI: Is not possible to add or edit image atributies (e.g. width, height) and adjust their position (e.g. align center or right).

**Comment by neSpecc** [comment]
You can add `mailto` links by the same way as regular links: with Inline Toolbar.

`rel` and `target` is the site-related logic, that would better implement on backend side. 

What about html entities, it looks strange. We will check that.

Images size and position can be specified on your own render-side. There are many devices you usualy need to support, so hardcoding `width` or `height` on the Editor-side is not a good idea.

**Comment by ludec** [comment]
Thank you for your answer.

We will appreciate solution about entities.

Thank you.

Best regards,
Luděk Komoň

Pilot - design studio
studio@pilot.cz
+420 541 245 778
www.pilot.cz
