### ISSUE TITLE
Bug Inline toolbar link

### ISSUE THREAD

**Issue by mira-kovar** [codex-team/editor.js#809]
Hi,
when I use inline toolbar and add link or (CMD+K) and fill `mailto:some@email.addr`. Editor will create source code `.... <a href="http://mailto:some@email.addr">....`. It is obviously error.

Thank for your feedback.

**Comment by neSpecc** [comment]
Thanks, will be fixed soon

**Comment by gohabereg** [comment]
Resolved by #826
