### ISSUE TITLE
Backspace Deleting Whole Block

### ISSUE THREAD

**Issue by CITGuru** [codex-team/editor.js#810]
Backspace is deleting the whole block. I notice while typing with it. Whenever I pressed backspace it deletes the whole block

**Comment by khaydarov** [comment]
@CITGuru Hi! Will be fixed in the next release

**Comment by blockchain-expert** [comment]
Is there any solution for this? I have this issue.

**Comment by neSpecc** [comment]
@blockchain-expert @CITGuru we need more details: detailed steps to reproduce, editor.js version you use.

**Comment by md-haroon** [comment]
HI 

> Backspace is deleting the whole block. I notice while typing with it. Whenever I pressed backspace it deletes the whole block

@CITGuru  how to solve this problem ,, i'm also facing the same problem

**Comment by neSpecc** [comment]
Still no steps to reproduce. If someone will face that, please provide steps or a reproducible demo page. In that case, we will reopen this issue.

**Comment by terryureche** [comment]
Hi,

I have the same issue.

Browser: Chrome.Version 85.0.4183.121 (Official Build) (64-bit)
Operating system: Mac OS Catalina 10.15.6 / Windows 10 64-bit

Steps to reproduce the issue:

1.Install Sapling plugin for Chrome
2.Any blocks will be cut when the backspace is pressed.

There seems to be a conflict with Sapling plugin for chrome extensions.

**Comment by neerajhbhat** [comment]
Hi, Any update on this?
