### ISSUE TITLE
Scrollable toolbar on mobile

### ISSUE THREAD

**Issue by radiocity** [codex-team/editor.js#820]
![S90627-205233](https://user-images.githubusercontent.com/2347073/60288950-f7159980-991d-11e9-9734-b07e9e0da412.jpg)
Browser: Google Chrome 75.0
Platform: Android 7.0 (Flyme 6.3.1.0RU)

**Comment by gohabereg** [comment]
Hi @radiocity ! 
Thank you for feedback, mobile UX is improved in version 2.15 which will be published soon

**Comment by neSpecc** [comment]
Outdated
