### ISSUE TITLE
Improve Block Settings toggler

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#835]
- [x] Remove current block highlighting
- [x] Update style and position of Block Settings Toggler
- [x] Show Block Settings Toggler by hover on Block 
- [x] When Block Settings are opened, highlight Block.
- [ ] Click on Block Settings Toggler should open settings. Drag should drag block (See Drag'n'drop issue)
- [x] Show Tooltip with helper (Tab, click, drag description) by hover on Block Settings Toggler

**Comment by carakas** [comment]
It would help if this was made in such a way that you can use the editor without using a mouse

**Comment by neSpecc** [comment]
@carakas Editor.js supports keyboard-only manipulations. See #672

**Comment by christoph-kluge** [comment]
> - [ ] Show Block Settings Toggler by hover on Block



@neSpecc I have added this feature with a custom `onReady` handler. If this is still relevant I could move/implement it nativeley into editorjs. Just give me a quick heads up.

**Comment by MakarovCode** [comment]
@christoph-kluge could you share your custom onReady handler for toggling on hover?

**Comment by christoph-kluge** [comment]
@MakarovCode there you go: https://gist.github.com/christoph-kluge/c367f987935bc4381e52183f73696cc4

**Comment by MakarovCode** [comment]
@christoph-kluge nice!, this is just what I needed! Thanks!

**Comment by neSpecc** [comment]
Done
