### ISSUE TITLE
Block Tunes API

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#841]
Provide API that allows to build Block Tunes plugins

**Comment by rishighan** [comment]
Hello @neSpecc, Thanks for your work on editor.js
I have a few questions about Block Tunes: 
1. Why does selecting 90% of the text in a block give me a block tunes menu? From the user's perspective it is 90% of the text, not 100%. Shouldn't the user see an inline tools menu unless they select 100% of the text? (at which point they have selected the content of the entire block)
2. The conversion menu is another point of contention. Given the fuzziness around what constitutes a block vs. what constitutes not-a-block, the paradigm of block and inline menus starts to get confusing. Should editor.js offer a static toolbar with both block and inline options? The menu tools can be enabled or disabled based on whether the user is navigation a block or just the contents of a block. Just wanted to get your perspective on this.

**Comment by fdev** [comment]
Any progress on this? I would love to be able to add custom Block Tunes that apply to all block types.

**Comment by neSpecc** [comment]
@fdev we have a PR implementing this feature, but is currently in a freezed state. Upcoming version 2.16 won't contain that, but 2.17 — maybe.

**Comment by carakas** [comment]
Looking forward to this one

**Comment by nsobolev** [comment]
Привет, когда релиз? Нужно реализовать эту фичу - https://github.com/codex-team/editor.js/issues/980

**Comment by mikekoro** [comment]
> @fdev we have a [PR](https://github.com/codex-team/editor.js/pull/585/files) implementing this feature, but it is currently in a freezed state. Upcoming version 2.16 won't contain that, but 2.17 — maybe.

Currently at 2.17. Seems like it didnt make it did?

**Comment by mguenther** [comment]
Any news on this?

**Comment by gohabereg** [comment]
Hi @mguenther 

There are two related PRs opened #1075 #1078.

#1078 includes Block Tunes API, but it's only on the concept stage. There are still some things to do. Will be merged after it's tested and approved

**Comment by neSpecc** [comment]
Released in 2.20
