### ISSUE TITLE
Problem with onChange callback

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#843]
Sometimes event is not triggered.

https://t.me/editorjsdev/1266

**Comment by atilkan** [comment]
Also it doesn't provide changed data.

**Comment by gohabereg** [comment]
Hi @atilkan
It is expected behaviour

**Comment by atilkan** [comment]
@gohabereg While i got someone, can you tell me how do you get changed data?

**Comment by gohabereg** [comment]
Just call `save` method in `onChange` callback. No way to get diff at the moment, will come with the next releases

**Comment by atilkan** [comment]
@gohabereg Thanks. That was my current solution. It did not feel right though.

**Comment by hagemann** [comment]
Any chance this could be looked into? 🙏It’s a critical bug that changes are not tracked and it affects several plugins (e.g. Code or Raw HTML).

**Comment by gohabereg** [comment]
Hi @hagemann 
Will take a look tomorrow

**Comment by VitaliyDemchuk** [comment]
> Hi @hagemann
> Will take a look tomorrow

Is there any result?

**Comment by gohabereg** [comment]
Hi @VitaliyDemchuk 
Sorry, I forgot about this one as it on the bottom of the backlog. Will investigate asap

**Comment by VitaliyDemchuk** [comment]
@gohabereg Thanks!

**Comment by Darkinsideus** [comment]
Hello! How are you doing with the fix?

**Comment by robonetphy** [comment]
Hi There,
How Should I reproduce this issue?

**Comment by Katrienvh** [comment]
Can anyone confirm the fix works? I have updated to v2.19 but still got the problem. The issue appears in https://github.com/editor-js/quote. 

Someone who can help? Do I miss something?

**Comment by Katrienvh** [comment]
Anyone?

**Comment by quantruong-2518** [comment]
How can i get only the lastest value with onchange. When i upload image, the callback emit empty object first @.@
