### ISSUE TITLE
Cannot read property 'parentNode' of null on mouseover

### ISSUE THREAD

**Issue by dimensi** [codex-team/editor.js#846]
```
app.js:133 Uncaught TypeError: Cannot read property 'parentNode' of null
    at e.value (app.js:133)
    at HTMLDocument.t.onMouseOver (app.js:133)
```
![image](https://user-images.githubusercontent.com/11390039/60975552-d6ddd580-a334-11e9-9f2c-6ec78ef8e181.png)

**Comment by khaydarov** [comment]
@dimensi can you describe steps to reproduce?

**Comment by dimensi** [comment]
I can't remember. Issue too old. I'm going to close it.
