### ISSUE TITLE
Using JSX tools render method

### ISSUE THREAD

**Issue by vpetrushenko** [codex-team/editor.js#849]
Hi! I would like to understand if it is possible for tools `render` method to return JSX? 

For example, I want each paragraph of editor to be my own (already written) React component, which is basically `<div>` with `contenteditable` attribute, but also with a lots of logic inside. Ideally I would love something like this:

```javascript
class CustomParagraph {
  // other methods here

  render() {
    return <EditableDiv/>; // where EditableDiv is a big component
  }
}

export class NewEditableDiv extends React.Component {
  render() {
    return <EditorJS
      tools={{
        paragraph: CustomParagraph
      }}
    />;
  }
}
```

**Comment by gohabereg** [comment]
Hi @vpetrushenko 
No, it is not possible to return JSX from `render` method. If you want to use JSX you can try some render tools for it (eg. [preact](https://preactjs.com/) or just call `ReactDOM.render` with tool wrapper)

**Comment by vpetrushenko** [comment]
> Hi @vpetrushenko
> No, it is not possible to return JSX from `render` method. If you want to use JSX you can try some render tools for it (eg. [preact](https://preactjs.com/) or just call `ReactDOM.render` with tool wrapper)

Thank you for your decent answer.

**Comment by natterstefan** [comment]
Hi @gohabereg, would you mind sharing a short example? Thank you!

**Comment by natterstefan** [comment]
Hi @gohabereg, would you mind sharing a short example? Thank you!

Or could you share your final solution with me @vpetrushenko, please?

**Comment by gohabereg** [comment]
Hi @natterstefan !
Sure, it should be something like this:
```
render () {
  const jsx = <Component />;
  const container = document.createElement('div');

  ReactDOM.render(jsx, container);

  return container;
}
```

**Comment by natterstefan** [comment]
@gohabereg, thank you! Will test it. (you're fast ^^)

**Comment by natterstefan** [comment]
Hello @gohabereg, it's me again. Looks like I can render a React component, _but_ for some reason eg. `onClick` is not working. It's a simple custom plugin with a Button.

When I add it with React the `onClick` does not work, but when adding it with `createElement('button')` and adding the `onclick` there it does. Any clue/hint for me?

Here's an example: https://codesandbox.io/s/solitary-night-96hzk?fontsize=14.

**Comment by gohabereg** [comment]
Hey @natterstefan, it seems, some of inner Editor.js handlers stops event propagation. Definitely we should look into this.

If I select button's content it works ok:
![Screen-Recording-2019-11-12-at-12 55 59](https://user-images.githubusercontent.com/23050529/68661580-3dc20400-054c-11ea-9645-1bddbfdd7541.gif)

**Comment by natterstefan** [comment]
Hi @gohabereg, mhm, looks like. Is this something easy or complicated to fix? Haven't looked into the editorjs codebase (yet) by myself to be honest. :/

I have updated the example and added both a react and plain-js example, so it can be easily compared: https://codesandbox.io/s/solitary-night-96hzk.

**Comment by natterstefan** [comment]
I created a new issue for this topic: https://github.com/codex-team/editor.js/issues/946.

**Comment by gohabereg** [comment]
Thanks @natterstefan !
It requires some investigation, should be complicated.

**Comment by hata6502** [comment]
https://github.com/codex-team/editor.js/issues/849#issuecomment-552815971

I also encounted this onClick problem!
I'll research it.

**Comment by natterstefan** [comment]
Hi @hata6502, you can find a solution ("workaround") here already: https://github.com/codex-team/editor.js/issues/946#issuecomment-555760936.

**Comment by nicomsz** [comment]
> Hi @natterstefan ! Sure, it should be something like this:
> 
> ```
> render () {
>   const jsx = <Component />;
>   const container = document.createElement('div');
> 
>   ReactDOM.render(jsx, container);
> 
>   return container;
> }
> ```
I cant render the component on "jsx", it returns me that error: Teste' refers to a value, but is being used as a type here. Did you mean 'typeof Teste'?ts(2749)
