### ISSUE TITLE
The inline tool has a strange behavior when selecting the entire content of a block

### ISSUE THREAD

**Issue by Paul-maire** [codex-team/editor.js#853]
Hello, when selecting the entire content of a block I would like to have my custom inline tool that I developed. How can I access it in this case?

![issue](https://user-images.githubusercontent.com/17704166/61776922-47d4c100-adfc-11e9-91b8-0b1029284488.gif)

**Comment by MalyshevDmitry** [comment]
Any news?

**Comment by neSpecc** [comment]
When you select the entire block, you will see the [Conversion Toolbar](https://editorjs.io/tools-api#conversionconfig) instead of Inline Toolbar. There are only Block tools to convert selected Blocks.

We are planning to check for a lines count and do not show Conversion Toolbar for small single-line paragraphs like you show on gif. Will be added in next releases.

**Comment by MalyshevDmitry** [comment]
@neSpecc Peter, this is really strange behavior in a case when user wants to apply italic style for all current paragraph.

Can you give a temporary workaround solution? Thanks.

**Comment by neSpecc** [comment]
I'm thinking that it's a bad practice to make entire paragraph italic or bold or link. You can use specific blocks for that reasons. 

We will include a solution in next minor version.

**Comment by MalyshevDmitry** [comment]
@neSpecc Can you say the date of the next minor version? Thanks

**Comment by enes-sahin** [comment]
> I'm thinking that it's a bad practice to make entire paragraph italic or bold or link. You can use specific blocks for that reasons.
> 
> We will include a solution in next minor version.

@neSpecc 
I think any user can need to apply inline styles (italic/bold etc.) for all block. Instead of %95 of selection, i prefer to see **both inline toolbar and conversion toolbar together in one line when a user selects all block.** Otherwise only inline toolbar can be displayed.

**Comment by Idji** [comment]
+1 for Topic Starter. For exapmle, i have title block, and can't make it bold/italic/whatever on already worked project(

**Comment by rishighan** [comment]
> I'm thinking that it's a bad practice to make entire paragraph italic or bold or link. You can use specific blocks for that reasons.

Not to sound disrespectful, but why exactly is it a bad practice?

**Comment by gkshi** [comment]
> We are planning to check for a lines count and do not show Conversion Toolbar for small single-line paragraphs like you show on gif

It can be helpful for this issue. Strange behavior of toolbar appears not only in single-line blocks. I've tried to select a part of text and get inline tool.

There is a simple text block on gif:
![sc](https://user-images.githubusercontent.com/13585582/66716421-3638ff00-edd6-11e9-854c-7240c8062a89.gif)

**Comment by neSpecc** [comment]
Resolved in 2.16 #966
