### ISSUE TITLE
Show block settings [...] on new block

### ISSUE THREAD

**Issue by danbars** [codex-team/editor.js#877]
When creating new block either by using the `+` button or just a paragraph block, the block settings disappears. 

I'm not sure if this is on purpose or a bug, but I found it inconvenient that I have to click on the currently active block in order to show the block settings (`...` button).

I think that it is common case that I'd like to configure the block that I'm currently working on, therefore the block settings is useful at this point.

I thought about showing it programatically, but couldn't find a way - 
* `editor.toolbar.show()` - shows also the plus sign 
* in the code I saw 2 params that could be passed - `withBlockActions` and `needToCloseToolbox` - but I didn't see any effect when passing them + I don't think that they are what I need 
* also in the code I saw internal object that has the method `editor.toolbar.blockActions.show()` - but that object is not exposed to the external api 

So 2 questions: 
1. do you think that current behavior is correct and should stay like this 
2. can you expose `blockActions` object to the api? 

Thanks

**Comment by robonetphy** [comment]
Hey @danbars, Thanks for the issue. I am closing this issue since this changes included in new UI version 2.25.0.
