### ISSUE TITLE
no BR tag in block tool text

### ISSUE THREAD

**Issue by gkshi** [codex-team/editor.js#891]
![image](https://user-images.githubusercontent.com/13585582/64603582-4de12a00-d3c9-11e9-9cd7-33577749fdd5.png)

Hello. It seems line breaks are not adding into text.
In latest Chrome and Safari I can't add line break in block tool with `enableLineBreaks: true` property (such as **Quote** and other custom tools).
You can get this case when just typing a text and press Enter, not paste.

**Comment by hata6502** [comment]
It may be resolved with sanitize settings. 

https://github.com/editor-js/paragraph/blob/master/src/index.js

```
  static get sanitize() {
    return {
      text: {
        br: true,
      }
    };
  }
```

**Comment by gkshi** [comment]
I use original [Quote](https://github.com/editor-js/quote) plugin, it includes sanitize method with br option by default. But it's not working correctly.

There is a gif from editorjs website. No br tag in text.
![image](https://user-images.githubusercontent.com/13585582/70996172-437aae80-20e3-11ea-910c-241c9648b1d8.png)

**Comment by Stanko** [comment]
Try adding `div` to the sanitize settings. It worked for us as a fix for Safari. Safari adds `<div><br></div>` instead of `<br>` and then divs get sanitized and removed.

```js
  /**
   * Sanitizer rules
   */
  static get sanitize() {
    return {
      text: {
        br: true,
        div: true,
      },
    };
  }
```

**Comment by gkshi** [comment]
Thanks everybody, guys, I'll close the issue, it's no more actual for me.

**Comment by mirkomaty** [comment]
@gkshi: How did  you solve the problem? I have similar issues.

**Comment by gkshi** [comment]
@mirkomaty Hi, I've not solved the problem finally. I think it's a quite important bug. You can reopen the issue then.

**Comment by itmysm** [comment]
Here’s a custom plugin to add a `<br>` tag as a block tool in EditorJS. Simply import it into your EditorJS component and add it to the `tools` configuration:

![Image](https://github.com/user-attachments/assets/8dcc7227-e59d-4cf9-a3ff-f50c4518bed0)

```typescript
import type { BlockTool, BlockToolData } from "@editorjs/editorjs";

export default class BrTool implements BlockTool {
  static get toolbox() {
    return {
      title: "Line Break",
      icon: '<svg width="17" height="10" viewBox="0 0 17 10" xmlns="http://www.w3.org/2000/svg"><path d="M16.5 1.5L10 8 3.5 1.5" stroke="currentColor" stroke-width="2" fill="none" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round"/></svg>',
    };
  }

  render(): HTMLElement {
    return document.createElement("br");
  }

  save(blockContent: HTMLElement): BlockToolData {
    return {};
  }
}
```

To use it, import and add it to your `tools` object like this:

```javascript
import BrTool from "./path/to/BrTool";

tools: {
  br: { class: BrTool },
  // ... other tools
}
```
