### ISSUE TITLE
Problem with second CMD+A after selection clearing still continues

### ISSUE THREAD

**Issue by enes-sahin** [codex-team/editor.js#892]
The bug in https://github.com/codex-team/editor.js/issues/827 still continues in **Release/2.15.1** and **Release/2.16**. 
( Tested in : Ubuntu 18.04, Chrome 76.0)

As @neSpecc points out : 
> 1. Select one block by CMD+A.
> 2. Clear selection
> 3. Select one block by CMD+A again
> 4. All blocks will be selected instead of one block.

**Comment by neSpecc** [comment]
Resolved by #966
