### ISSUE TITLE
【I'm in a hurry.】Block's save method does not save Html fragments

### ISSUE THREAD

**Issue by isnl** [codex-team/editor.js#893]
This is my custom tools.
I want the save method of blocks to get an HTML fragment
![image](https://user-images.githubusercontent.com/35526117/65038446-9036d800-d982-11e9-94fb-8ec0b01e61d0.png)

But when you call the save method of the editor instance, you get this.
![image](https://user-images.githubusercontent.com/35526117/65038485-a349a800-d982-11e9-883d-958f7d1ce63b.png)

**Comment by christoph-kluge** [comment]
Is this maybe corelated to https://github.com/editor-js/table/issues/36#issue-497848037 ? It's also a custom module I was puzzled why italic, bold and some other inline tools are working but not newlines.

Could you verify if you are able to use italic or bold elements in your html?

**Comment by neSpecc** [comment]
See https://editorjs.io/sanitize-saved-data
