### ISSUE TITLE
Popup bar overlaps text on mobile

### ISSUE THREAD

**Issue by tiotdev** [codex-team/editor.js#894]
When adding a paragraph on mobile, the popup bar is displayed on a fixed position below the first row of text and doesn't move when adding more rows, therefore overlapping the text written.

![Screenshot_20190916-010045 (1)](https://user-images.githubusercontent.com/18411522/65066700-2ff56580-d985-11e9-8440-91599f5f47c9.png)

**Comment by LydiaF** [comment]
Hey @tiotdev, 

Did you find a solution to this? Would appreciate if you would share if you did! Thanks :)

**Comment by tiotdev** [comment]
No solution unfortunately

**Comment by LydiaF** [comment]
Okay, thanks. Will post if we sort it out :)


Lydia Flynn
CEO Lesson Prep
+353 (0)89 205 2817
Trinity Enterprise Tower,
Pearse St., Dublin 2

**Comment by robonetphy** [comment]
Hey @tiotdev, Thanks for the issue. I am closing this issue since it is not reproducible in version 2.25.0.
