### ISSUE TITLE
Write Plugin in Typescript

### ISSUE THREAD

**Issue by step4** [codex-team/editor.js#900]
I try to create a new block and inline tool for displaying mathemtical formulas.
Therefore I started with the tutorial 'The first plugin'.
I have wondered if you could write this plugin in typescript and found the types in your repo.

Is there a tutorial for writing plugins in typescript?

**Comment by ulshv** [comment]
@step4 this is how I use it with TypeScript/React/mobx:

```typescript
import React from 'react'
import ReactDOM from 'react-dom';
import EditorJS, { API, ToolSettings, BaseTool } from '@editorjs/editorjs';
import { observable } from 'mobx';

type SimpleImageData = {
  url?: string
}

type SimpleImageConstructorParams = {
  api: API
  config?: ToolSettings
  data: SimpleImageData
}

class SimpleImage implements BaseTool {
  @observable data: SimpleImageData;

  constructor({ data }: SimpleImageConstructorParams) {
    this.data = data;
  }

  render() {
    const container = document.createElement('div');
    const toolView = <SimpleImageView data={this.data} tool={this} />
    ReactDOM.render(toolView, container);
    return container;
  }
}

// somewhere in the code

const editor = new EditorJS({
  holderId: 'editor-root',
  tools: {
    image: SimpleImage
  }
});
```

**Comment by step4** [comment]
Thank you!

I did a more deep dive into the types and use not only the BaseTool type but rather the BlockTool type.

**Comment by neSpecc** [comment]
@step4 cool. Can you show us a result when you will done with it?

If there are still problems with TS?

**Comment by ponnex** [comment]
Hi have a problem using BaseTool

```
Argument of type '{ holderId: string; tools: { header: any; link: any; list: any; marker: any; reference: typeof SimpleImage; }; data: OutputData; }' is not assignable to parameter of type 'string | EditorConfig | undefined'.
  Type '{ holderId: string; tools: { header: any; link: any; list: any; marker: any; reference: typeof SimpleImage; }; data: OutputData; }' is not assignable to type 'EditorConfig'.
    Types of property 'tools' are incompatible.
      Type '{ header: any; link: any; list: any; marker: any; reference: typeof SimpleImage; }' is not assignable to type '{ [toolName: string]: ToolSettings | BaseToolConstructable | BlockToolConstructable | InlineToolConstructable; }'.
        Property 'reference' is incompatible with index signature.
          Type 'typeof SimpleImage' is not assignable to type 'ToolSettings | BaseToolConstructable | BlockToolConstructable | InlineToolConstructable'.
            Type 'typeof SimpleImage' is not assignable to type 'BaseToolConstructable'.
              Types of parameters '__0' and 'config' are incompatible.
                Property 'data' is missing in type '{ api: API; config?: ToolSettings | undefined; }' but required in type 'SimpleImageConstructorParams'.Vetur(2345)
```

Any help for writing plugin in typescript?

**Comment by step4** [comment]
This is the first prototype just put everything together to get it to work.
So it is mostly not pretty but it works.

```js
import {
  BlockTool,
  BlockToolConstructable,
  API,
  ToolConfig,
  BlockToolData,
  PasteConfig,
  PasteEvent,
  PatternPasteEventDetail
} from '@editorjs/editorjs'

import katex from 'katex'
import {
  ConversionConfig,
  SanitizerConfig
} from '@editorjs/editorjs/types/configs'

import { LatexIcon } from './icons'
//styles imports in angular.json
interface LatexToolData extends BlockToolData {
  latexString: string
}

export default class LatexBlock implements BlockTool {
  latexString: string
  static latexSearchPattern = /.*\$\$.*\$\$.*/
  wrapperDiv: HTMLDivElement = document.createElement('div')
  latexDiv: HTMLDivElement = document.createElement('div')
  editTextfield: HTMLSpanElement = document.createElement('span')
  api: API

  static get toolbox(): { icon: string; title?: string } {
    return {
      icon: LatexIcon,
      title: 'Latex'
    }
  }

  static get pasteConfig(): PasteConfig {
    return {
      patterns: {
        doubleDollars: this.latexSearchPattern
      }
    }
  }
  conversionConfig?: ConversionConfig
  isInline?: boolean

  constructor({
    api,
    config,
    data
  }: {
    api: API
    config?: ToolConfig
    data?: LatexToolData
  }) {
    this.api = api

    if (data.hasOwnProperty('latexString')) {
      this.latexString = (data as LatexToolData).latexString
    } else if (typeof data === 'string') {
      this.latexString = data
    } else {
      this.latexString = '\\text{Doppelklick hier...}'
    }

    this.editTextfield.classList.add('latex-editfield')
    this.editTextfield.style.display = 'none'
    this.editTextfield.style.justifyContent = 'center'
    this.editTextfield.style.alignItems = 'center'

    const delimeterSpan = document.createElement('SPAN')
    delimeterSpan.innerHTML = ' $$ '
    delimeterSpan.contentEditable = 'false'
    delimeterSpan.style.margin = '0 10px'

    const latexSpan = document.createElement('SPAN')
    latexSpan.contentEditable = 'true'
    latexSpan.tabIndex = 0
    latexSpan.innerHTML = this.latexString

    this.editTextfield.contentEditable = 'false'

    this.editTextfield.appendChild(delimeterSpan)
    this.editTextfield.appendChild(latexSpan)
    this.editTextfield.appendChild(delimeterSpan.cloneNode(true))

    this.editTextfield.addEventListener('focusout', event => {
      this.latexString = latexSpan.textContent.replace(/\$nbsp;/g, '')
      this.editTextfield.style.display = 'none'
      this.renderLatex()
      this.latexDiv.style.display = 'initial'
    })

    this.wrapperDiv.classList.add('latex-wrapper')

    this.wrapperDiv.ondblclick = event => {
      this.latexDiv.style.display = 'none'
      this.editTextfield.style.display = 'flex'
      latexSpan.focus()
    }

    this.latexDiv.classList.add('latex-render')
  }

  static get enableLineBreaks() {
    return true
  }
  static get shortcut() {
    return 'CTRL+SHIFT+L'
  }

  static get conversionConfig() {
    return {
      export: text => text,
      import: text => text
    }
  }

  static get sanitize() {
    return {
      latexString: false // disallow HTML
    }
  }

  sanitize?: SanitizerConfig

  save(block: HTMLDivElement) {
    // console.log(block)
    // ;(window as any).x = block

    return {
      latexString: (block.firstElementChild as HTMLElement).dataset.latexString
    }
  }
  renderSettings(): HTMLElement {
    return document.createElement('div')
  }
  validate(blockData): boolean {
    if (!blockData.latexString.trim()) {
      return false
    }

    return true
  }
  onPaste(event: PasteEvent): void {
    let blockReplaced = false
    let offset = 1

    if (event.type === 'pattern') {
      let array = (event.detail as PatternPasteEventDetail).data.split(
        /(\$\$[^\$\$]*\$\$)/
      )
      array = array.filter(entry => entry != '')
      if (array.length === 1) {
        this.latexString = array[0].replace(/\$\$/g, '')
        this.renderLatex()
      } else {
        array.reverse().forEach(part => {
          const isLatex = /^\$\$.*\$\$$/.test(part)
          if (isLatex) {
            this.latexString = part.replace(/\$\$/g, '')
            if (!blockReplaced) {
              this.renderLatex()
              blockReplaced = true
              offset = 0
            } else {
              this.api.blocks.insert(
                'latexBlock',
                { latexString: this.latexString },
                {},
                this.api.blocks.getCurrentBlockIndex() + offset,
                false
              )
            }
          } else {
            this.api.blocks.insert(
              'paragraph',
              { text: part },
              {},
              this.api.blocks.getCurrentBlockIndex() + offset,
              false
            )
          }
        })
      }
    }
  }

  render(): HTMLElement {
    this.wrapperDiv.innerHTML = ''
    this.latexDiv.innerHTML = ''
    this.renderLatex()
    this.wrapperDiv.append(this.latexDiv)
    this.wrapperDiv.append(this.editTextfield)

    return this.wrapperDiv
  }

  renderLatex() {
    this.latexDiv.dataset.latexString = this.latexString
    katex.render(this.latexString, this.latexDiv, {
      throwOnError: false,
      output: 'html',
      displayMode: true
    })
  }
}

```

@ponnex without any code I can not see whats missing

**Comment by ponnex** [comment]
Yes thank you I can work on from the sample code you've given thaaanks a lot!

**Comment by christopher-caldwell** [comment]
I found this thread by looking for how to type pre-existing plugins that do not provide types. 

In case anyone else has issues **just getting TS to chill when using other people's plugins**
This works on v `2.22.2`

```ts
// Somewhere, make a .d.ts file

declare module '@editorjs/list' {
  import { BlockTool } from '@editorjs/editorjs'

  export default class List implements BlockTool {
    save(block: HTMLDivElement)
    render(): HTMLElement
  }
}
```

Then the error goes away when using them

```ts
const editorOptions: EditorConfig = {
  ...,
  tools: {
    header: {
      class: Header 
    }
  }
}
```

**Comment by Kirynn** [comment]
I'm having an issue creating a tool.

```
Type 'typeof JobBlock' is not assignable to type 'ToolConstructable | ToolSettings<any>'.
  Type 'typeof JobBlock' is not assignable to type 'BlockToolConstructable'.
    Types of parameters '__0' and 'config' are incompatible.
      Type '{ api: API; config?: any; }' is missing the following properties from type 'JobBlockToolConstructorOptions': data, readOnly
```
I'm following what @step4 did with a couple of small modifications

```typescript
interface JobBlockToolData extends BlockToolData {

    content: string
    section: string
    title: string
}

interface JobBlockToolConstructorOptions extends BlockToolConstructorOptions {
    api: API
    data: JobBlockToolData
    config?: ToolConfig
}

export default class JobBlock implements BlockTool {

    api: API;
    config: ToolConfig | undefined;
    data: JobBlockToolData;
    sanitize?: SanitizerConfig | undefined;

    constructor({ api, data, config }: JobBlockToolConstructorOptions) {

        this.api = api;
        this.data = data;
        this.config = config;
    }

    save(block: HTMLElement) {
        throw new Error("Method not implemented.");
    }

    render(): HTMLElement {
        throw new Error("Method not implemented.");
    }

    drawView(): HTMLDivElement {

        throw new Error("Method not implemented.");
     }
}
```

I have also tried having `JobBlock` implement `BlockToolConstructable` but that doesn't seem it help.
One thing to note is that I am using typescript in strict mode.

Any help would be very much appreciated 😄

**Comment by Kirynn** [comment]
Nevermind, it stopped throwing an error when I added the `static get toolbox` function.
Perhaps this is something that should be defined in `BlockTool`? Or am I just dumb 😋

**Comment by milban** [comment]
> I'm having an issue creating a tool.
> 
> ```
> Type 'typeof JobBlock' is not assignable to type 'ToolConstructable | ToolSettings<any>'.
>   Type 'typeof JobBlock' is not assignable to type 'BlockToolConstructable'.
>     Types of parameters '__0' and 'config' are incompatible.
>       Type '{ api: API; config?: any; }' is missing the following properties from type 'JobBlockToolConstructorOptions': data, readOnly
> ```
> 
> I'm following what @step4 did with a couple of small modifications
> 
> ```ts
> interface JobBlockToolData extends BlockToolData {
> 
>     content: string
>     section: string
>     title: string
> }
> 
> interface JobBlockToolConstructorOptions extends BlockToolConstructorOptions {
>     api: API
>     data: JobBlockToolData
>     config?: ToolConfig
> }
> 
> export default class JobBlock implements BlockTool {
> 
>     api: API;
>     config: ToolConfig | undefined;
>     data: JobBlockToolData;
>     sanitize?: SanitizerConfig | undefined;
> 
>     constructor({ api, data, config }: JobBlockToolConstructorOptions) {
> 
>         this.api = api;
>         this.data = data;
>         this.config = config;
>     }
> 
>     save(block: HTMLElement) {
>         throw new Error("Method not implemented.");
>     }
> 
>     render(): HTMLElement {
>         throw new Error("Method not implemented.");
>     }
> 
>     drawView(): HTMLDivElement {
> 
>         throw new Error("Method not implemented.");
>      }
> }
> ```
> 
> I have also tried having `JobBlock` implement `BlockToolConstructable` but that doesn't seem it help. One thing to note is that I am using typescript in strict mode.
> 
> Any help would be very much appreciated 😄

Same here. version 2.25.0

**Comment by Kirynn** [comment]
I solved this by adding a method will the following signature:

```typescript
static get toolbox(): { title: string, icon: string | FunctionalComponent<SVGAttributes> 
```

**Comment by BensenHsu** [comment]
> This is the first prototype just put everything together to get it to work. So it is mostly not pretty but it works.
> 
> ```js
> import {
>   BlockTool,
>   BlockToolConstructable,
>   API,
>   ToolConfig,
>   BlockToolData,
>   PasteConfig,
>   PasteEvent,
>   PatternPasteEventDetail
> } from '@editorjs/editorjs'
> 
> import katex from 'katex'
> import {
>   ConversionConfig,
>   SanitizerConfig
> } from '@editorjs/editorjs/types/configs'
> 
> import { LatexIcon } from './icons'
> //styles imports in angular.json
> interface LatexToolData extends BlockToolData {
>   latexString: string
> }
> 
> export default class LatexBlock implements BlockTool {
>   latexString: string
>   static latexSearchPattern = /.*\$\$.*\$\$.*/
>   wrapperDiv: HTMLDivElement = document.createElement('div')
>   latexDiv: HTMLDivElement = document.createElement('div')
>   editTextfield: HTMLSpanElement = document.createElement('span')
>   api: API
> 
>   static get toolbox(): { icon: string; title?: string } {
>     return {
>       icon: LatexIcon,
>       title: 'Latex'
>     }
>   }
> 
>   static get pasteConfig(): PasteConfig {
>     return {
>       patterns: {
>         doubleDollars: this.latexSearchPattern
>       }
>     }
>   }
>   conversionConfig?: ConversionConfig
>   isInline?: boolean
> 
>   constructor({
>     api,
>     config,
>     data
>   }: {
>     api: API
>     config?: ToolConfig
>     data?: LatexToolData
>   }) {
>     this.api = api
> 
>     if (data.hasOwnProperty('latexString')) {
>       this.latexString = (data as LatexToolData).latexString
>     } else if (typeof data === 'string') {
>       this.latexString = data
>     } else {
>       this.latexString = '\\text{Doppelklick hier...}'
>     }
> 
>     this.editTextfield.classList.add('latex-editfield')
>     this.editTextfield.style.display = 'none'
>     this.editTextfield.style.justifyContent = 'center'
>     this.editTextfield.style.alignItems = 'center'
> 
>     const delimeterSpan = document.createElement('SPAN')
>     delimeterSpan.innerHTML = ' $$ '
>     delimeterSpan.contentEditable = 'false'
>     delimeterSpan.style.margin = '0 10px'
> 
>     const latexSpan = document.createElement('SPAN')
>     latexSpan.contentEditable = 'true'
>     latexSpan.tabIndex = 0
>     latexSpan.innerHTML = this.latexString
> 
>     this.editTextfield.contentEditable = 'false'
> 
>     this.editTextfield.appendChild(delimeterSpan)
>     this.editTextfield.appendChild(latexSpan)
>     this.editTextfield.appendChild(delimeterSpan.cloneNode(true))
> 
>     this.editTextfield.addEventListener('focusout', event => {
>       this.latexString = latexSpan.textContent.replace(/\$nbsp;/g, '')
>       this.editTextfield.style.display = 'none'
>       this.renderLatex()
>       this.latexDiv.style.display = 'initial'
>     })
> 
>     this.wrapperDiv.classList.add('latex-wrapper')
> 
>     this.wrapperDiv.ondblclick = event => {
>       this.latexDiv.style.display = 'none'
>       this.editTextfield.style.display = 'flex'
>       latexSpan.focus()
>     }
> 
>     this.latexDiv.classList.add('latex-render')
>   }
> 
>   static get enableLineBreaks() {
>     return true
>   }
>   static get shortcut() {
>     return 'CTRL+SHIFT+L'
>   }
> 
>   static get conversionConfig() {
>     return {
>       export: text => text,
>       import: text => text
>     }
>   }
> 
>   static get sanitize() {
>     return {
>       latexString: false // disallow HTML
>     }
>   }
> 
>   sanitize?: SanitizerConfig
> 
>   save(block: HTMLDivElement) {
>     // console.log(block)
>     // ;(window as any).x = block
> 
>     return {
>       latexString: (block.firstElementChild as HTMLElement).dataset.latexString
>     }
>   }
>   renderSettings(): HTMLElement {
>     return document.createElement('div')
>   }
>   validate(blockData): boolean {
>     if (!blockData.latexString.trim()) {
>       return false
>     }
> 
>     return true
>   }
>   onPaste(event: PasteEvent): void {
>     let blockReplaced = false
>     let offset = 1
> 
>     if (event.type === 'pattern') {
>       let array = (event.detail as PatternPasteEventDetail).data.split(
>         /(\$\$[^\$\$]*\$\$)/
>       )
>       array = array.filter(entry => entry != '')
>       if (array.length === 1) {
>         this.latexString = array[0].replace(/\$\$/g, '')
>         this.renderLatex()
>       } else {
>         array.reverse().forEach(part => {
>           const isLatex = /^\$\$.*\$\$$/.test(part)
>           if (isLatex) {
>             this.latexString = part.replace(/\$\$/g, '')
>             if (!blockReplaced) {
>               this.renderLatex()
>               blockReplaced = true
>               offset = 0
>             } else {
>               this.api.blocks.insert(
>                 'latexBlock',
>                 { latexString: this.latexString },
>                 {},
>                 this.api.blocks.getCurrentBlockIndex() + offset,
>                 false
>               )
>             }
>           } else {
>             this.api.blocks.insert(
>               'paragraph',
>               { text: part },
>               {},
>               this.api.blocks.getCurrentBlockIndex() + offset,
>               false
>             )
>           }
>         })
>       }
>     }
>   }
> 
>   render(): HTMLElement {
>     this.wrapperDiv.innerHTML = ''
>     this.latexDiv.innerHTML = ''
>     this.renderLatex()
>     this.wrapperDiv.append(this.latexDiv)
>     this.wrapperDiv.append(this.editTextfield)
> 
>     return this.wrapperDiv
>   }
> 
>   renderLatex() {
>     this.latexDiv.dataset.latexString = this.latexString
>     katex.render(this.latexString, this.latexDiv, {
>       throwOnError: false,
>       output: 'html',
>       displayMode: true
>     })
>   }
> }
> ```
> 
> @ponnex without any code I can not see whats missing

Hi @step4, Thank you for creating this tool, I tried but don't know how to use it in my React-Typescript project. Could you please elaborate more on how to use this tool? Much appreciated! Is this just creating a `latex.ts` file and importing it into the working file `xxx.tsx`? Or I have to create a `bundle.js` file to make it work?

**Comment by BensenHsu** [comment]
> This is the first prototype just put everything together to get it to work. So it is mostly not pretty but it works.
> 
> ```js
> import {
>   BlockTool,
>   BlockToolConstructable,
>   API,
>   ToolConfig,
>   BlockToolData,
>   PasteConfig,
>   PasteEvent,
>   PatternPasteEventDetail
> } from '@editorjs/editorjs'
> 
> import katex from 'katex'
> import {
>   ConversionConfig,
>   SanitizerConfig
> } from '@editorjs/editorjs/types/configs'
> 
> import { LatexIcon } from './icons'
> //styles imports in angular.json
> interface LatexToolData extends BlockToolData {
>   latexString: string
> }
> 
> export default class LatexBlock implements BlockTool {
>   latexString: string
>   static latexSearchPattern = /.*\$\$.*\$\$.*/
>   wrapperDiv: HTMLDivElement = document.createElement('div')
>   latexDiv: HTMLDivElement = document.createElement('div')
>   editTextfield: HTMLSpanElement = document.createElement('span')
>   api: API
> 
>   static get toolbox(): { icon: string; title?: string } {
>     return {
>       icon: LatexIcon,
>       title: 'Latex'
>     }
>   }
> 
>   static get pasteConfig(): PasteConfig {
>     return {
>       patterns: {
>         doubleDollars: this.latexSearchPattern
>       }
>     }
>   }
>   conversionConfig?: ConversionConfig
>   isInline?: boolean
> 
>   constructor({
>     api,
>     config,
>     data
>   }: {
>     api: API
>     config?: ToolConfig
>     data?: LatexToolData
>   }) {
>     this.api = api
> 
>     if (data.hasOwnProperty('latexString')) {
>       this.latexString = (data as LatexToolData).latexString
>     } else if (typeof data === 'string') {
>       this.latexString = data
>     } else {
>       this.latexString = '\\text{Doppelklick hier...}'
>     }
> 
>     this.editTextfield.classList.add('latex-editfield')
>     this.editTextfield.style.display = 'none'
>     this.editTextfield.style.justifyContent = 'center'
>     this.editTextfield.style.alignItems = 'center'
> 
>     const delimeterSpan = document.createElement('SPAN')
>     delimeterSpan.innerHTML = ' $$ '
>     delimeterSpan.contentEditable = 'false'
>     delimeterSpan.style.margin = '0 10px'
> 
>     const latexSpan = document.createElement('SPAN')
>     latexSpan.contentEditable = 'true'
>     latexSpan.tabIndex = 0
>     latexSpan.innerHTML = this.latexString
> 
>     this.editTextfield.contentEditable = 'false'
> 
>     this.editTextfield.appendChild(delimeterSpan)
>     this.editTextfield.appendChild(latexSpan)
>     this.editTextfield.appendChild(delimeterSpan.cloneNode(true))
> 
>     this.editTextfield.addEventListener('focusout', event => {
>       this.latexString = latexSpan.textContent.replace(/\$nbsp;/g, '')
>       this.editTextfield.style.display = 'none'
>       this.renderLatex()
>       this.latexDiv.style.display = 'initial'
>     })
> 
>     this.wrapperDiv.classList.add('latex-wrapper')
> 
>     this.wrapperDiv.ondblclick = event => {
>       this.latexDiv.style.display = 'none'
>       this.editTextfield.style.display = 'flex'
>       latexSpan.focus()
>     }
> 
>     this.latexDiv.classList.add('latex-render')
>   }
> 
>   static get enableLineBreaks() {
>     return true
>   }
>   static get shortcut() {
>     return 'CTRL+SHIFT+L'
>   }
> 
>   static get conversionConfig() {
>     return {
>       export: text => text,
>       import: text => text
>     }
>   }
> 
>   static get sanitize() {
>     return {
>       latexString: false // disallow HTML
>     }
>   }
> 
>   sanitize?: SanitizerConfig
> 
>   save(block: HTMLDivElement) {
>     // console.log(block)
>     // ;(window as any).x = block
> 
>     return {
>       latexString: (block.firstElementChild as HTMLElement).dataset.latexString
>     }
>   }
>   renderSettings(): HTMLElement {
>     return document.createElement('div')
>   }
>   validate(blockData): boolean {
>     if (!blockData.latexString.trim()) {
>       return false
>     }
> 
>     return true
>   }
>   onPaste(event: PasteEvent): void {
>     let blockReplaced = false
>     let offset = 1
> 
>     if (event.type === 'pattern') {
>       let array = (event.detail as PatternPasteEventDetail).data.split(
>         /(\$\$[^\$\$]*\$\$)/
>       )
>       array = array.filter(entry => entry != '')
>       if (array.length === 1) {
>         this.latexString = array[0].replace(/\$\$/g, '')
>         this.renderLatex()
>       } else {
>         array.reverse().forEach(part => {
>           const isLatex = /^\$\$.*\$\$$/.test(part)
>           if (isLatex) {
>             this.latexString = part.replace(/\$\$/g, '')
>             if (!blockReplaced) {
>               this.renderLatex()
>               blockReplaced = true
>               offset = 0
>             } else {
>               this.api.blocks.insert(
>                 'latexBlock',
>                 { latexString: this.latexString },
>                 {},
>                 this.api.blocks.getCurrentBlockIndex() + offset,
>                 false
>               )
>             }
>           } else {
>             this.api.blocks.insert(
>               'paragraph',
>               { text: part },
>               {},
>               this.api.blocks.getCurrentBlockIndex() + offset,
>               false
>             )
>           }
>         })
>       }
>     }
>   }
> 
>   render(): HTMLElement {
>     this.wrapperDiv.innerHTML = ''
>     this.latexDiv.innerHTML = ''
>     this.renderLatex()
>     this.wrapperDiv.append(this.latexDiv)
>     this.wrapperDiv.append(this.editTextfield)
> 
>     return this.wrapperDiv
>   }
> 
>   renderLatex() {
>     this.latexDiv.dataset.latexString = this.latexString
>     katex.render(this.latexString, this.latexDiv, {
>       throwOnError: false,
>       output: 'html',
>       displayMode: true
>     })
>   }
> }
> ```
> 
> @ponnex without any code I can not see whats missing

Hi @step4 , Thank you for creating this tool! Could you please also share the code for the Latex inline tool? Much appreciated!!!

**Comment by step4** [comment]
This code is atleast 2 years old. So not sure how many modifications are needed. 
 I am not working with editor.js anymore, so I can't help unfortunately.

```typescript
import { InlineTool, API } from '@editorjs/editorjs'
import { LatexIcon } from './icons'

import katex from 'katex'

export default class LatexInline implements InlineTool {
  static get isInline() {
    return true
  }

  static get enableLineBreaks() {
    return true
  }

  static get sanitize() {
    return {
      span: true,
    }
  }

  public get shortcut(): string {
    return 'CMD+M'
  }

  button: HTMLButtonElement
  _state: boolean
  api: API

  static latexClass = 'latex-span'

  get state() {
    return this._state
  }

  set state(state) {
    this._state = state

    this.button.classList.toggle(this.api.styles.inlineToolButtonActive, state)
  }

  constructor({ api }) {
    this.api = api
    this.button = null
    this._state = false
  }

  oldRange: Range

  surround(range: Range): void {
    if (this.state) {
      // If highlights is already applied, do nothing for now
      this.unwrap(range)
      return
    }
    this.wrap(range)
  }

  wrap(range: Range) {
    const selectedText = range.extractContents()
    const span = document.createElement('span')
    span.classList.add(LatexInline.latexClass)
    span.contentEditable = 'false'
    let sanitizedString = this.api.sanitizer.clean(
      selectedText.textContent.replace(/\$/g, ''),
      {}
    )
    sanitizedString = sanitizedString.replace(/[&]nbsp[;]/gi, '')

    this.renderLatex(sanitizedString, span)
    // span.ondblclick = event => {
    //   const range = new Range();
    //   range.setStartBefore(span);
    //   range.setEndAfter(span);
    //   this.edit(range);
    // };
    range.insertNode(span)
    this.api.selection.expandToTag(span)
  }

  unwrap(range: Range) {
    const latex = this.api.selection.findParentTag(
      'SPAN',
      LatexInline.latexClass
    )
    const latexString = latex.dataset.latexString
    const latexNode = document.createTextNode(latexString)
    latex.remove()
    range.insertNode(latexNode)
  }

  edit(range: Range) {
    this.oldRange = range

    const latex = range
      .extractContents()
      .querySelector(`.${LatexInline.latexClass}`) as HTMLElement
    const latexString = latex.dataset.latexString
    const editSpan = document.createElement('SPAN')
    const delimeterSpan = document.createElement('SPAN')
    const latexSpan = document.createElement('SPAN')
    delimeterSpan.innerHTML = ' $ '
    delimeterSpan.contentEditable = 'false'
    delimeterSpan.style.margin = '0 5px'

    editSpan.contentEditable = 'false'
    latexSpan.contentEditable = 'true'
    latexSpan.tabIndex = 0
    latexSpan.innerHTML = latexString

    editSpan.appendChild(delimeterSpan)
    editSpan.appendChild(latexSpan)
    editSpan.appendChild(delimeterSpan.cloneNode(true))

    const focusOutEventhandler = (event) => {
      editSpan.removeEventListener('focusout', focusOutEventhandler)
      editSpan.remove()

      this.oldRange.insertNode(document.createTextNode(latexSpan.textContent))
      this.wrap(this.oldRange)
      window.getSelection().removeAllRanges()
    }

    latexSpan.addEventListener('keydown', (ev) => {
      console.log(latexSpan.querySelector('br'))

      if (ev.keyCode === 13) {
        ev.preventDefault()
        ev.stopImmediatePropagation()
        ev.stopPropagation()
        editSpan.blur()
      }
    })

    editSpan.addEventListener('focusout', focusOutEventhandler)

    latex.remove()
    range.insertNode(editSpan)
    this.api.inlineToolbar.close()
    latexSpan.focus()
  }

  renderLatex(latexString: string, inlineElement: HTMLElement) {
    inlineElement.dataset.latexString = latexString
    katex.render(latexString, inlineElement, {
      throwOnError: false,
      output: 'html',
      displayMode: false,
      strict: false,
    })
  }

  checkState(selection: Selection): boolean {
    let latex = this.api.selection.findParentTag('SPAN', LatexInline.latexClass)

    this.state = !!latex

    if (!this.state) {
      const selectionText = selection.anchorNode.nodeValue.substring(
        selection.focusOffset,
        selection.anchorOffset
      )
      if (/(^[^\$]*\$[^\$]*\$[^\$]*$)/.test(selectionText)) {
        this.surround(selection.getRangeAt(0))
        return
      }
    }

    if (this.state) {
      const range = new Range()

      range.setStartBefore(latex)
      range.setEndAfter(latex)
      this.edit(range)
    }

    return this.state
  }

  renderActions(): HTMLElement {
    const latexUrl = document.createElement('input')
    latexUrl.style.display = 'none'
    return latexUrl
  }
  clear(): void {}

  render(): HTMLElement {
    this.button = document.createElement('button')
    this.button.type = 'button'
    this.button.innerHTML = LatexIcon
    this.button.classList.add(this.api.styles.inlineToolButton)

    return this.button
  }
}
```
