### ISSUE TITLE
How do I "view" the actual document being saved by the editor?

### ISSUE THREAD

**Issue by sam26880** [codex-team/editor.js#914]
First of all, thanks for a great tool :)

Is there a "view" mode vs "edit" mode? I'm able to edit the document just fine. I'm able to save the data as well. But now, I'd like to DISPLAY the saved data to the user WITHOUT actually showing the editing capability. Is there a built in way to do this? Am I missing anything?

Thanks in advance!

**Comment by utkarshrai003** [comment]
@sam26880 Did you find anything for this? Plugins like slate have view mode, but I could not find anything on editor js documentation though.

**Comment by sam26880** [comment]
No I haven't found anything. The issue that I have is that when links are added, they are not clickable in the "default" mode which makes sense because default mode is the "EDIT" mode. So what I'm looking for is "VIEW" mode where the content is NOT editable AND the links are actually clickable.

**Comment by utkarshrai003** [comment]
Looks like we need to render the HTML ourselves with the clean data, which editor js provides. I am also looking to solve this and found this thread while researching. Maybe, this would be helpful to you as well.

https://github.com/codex-team/editor.js/issues/676

**Comment by sam26880** [comment]
Got you. Yea seems like there are others looking for the same solution. I'll try some of their suggestions and see how it goes. Thanks for bringing that up.

**Comment by avdkishore** [comment]
There is this [open issue](https://github.com/codex-team/editor.js/issues/837) which suggests that `readOnly` flag similar to what `SlateJS` provides is in their roadmap.

**Comment by sumitvekariya** [comment]
https://medium.com/@sumitvekariya7/editor-js-read-only-mode-in-angular-4f73192ed860

**Comment by sam26880** [comment]
@sumitvekariya interesting. Thanks for that solution. I'm not using Angular. Any VueJS implementation would be helpful. Thanks again.

**Comment by khaydarov** [comment]
read-only mode is published with [v2.19](https://github.com/codex-team/editor.js/releases/tag/v2.19.0)
