### ISSUE TITLE
Tab lock

### ISSUE THREAD

**Issue by carakas** [codex-team/editor.js#927]
Mouse is not required, you can do all manipulations from the keyboard only.

Enter — to create a new block.
Shift+Arrows — to select fragment
Tab — to open Toolbox at empty block
Tab — to open Block Settings at non-empty block
Tab (and Shift+Tab) — to switch focused button at the Toolbox, Inline Toolbar or Block Settings panels

and so on.

If we are missed something that you can not do without mouse, please create a separate Issue describing a problem.

_Originally posted by @neSpecc in https://github.com/codex-team/editor.js/issues/672#issuecomment-545424112_

All of this works, but I can't figure out how I can get out of the editor and to the next element in my form. I tried the arrows in the last element and tabbing. Both on an empty block and a block with content

**Comment by neSpecc** [comment]
I've understood. 

A possible solution for us is to add an option defining the key that will be used to open Toolbox and leaf tools so you can override Tab with any button.

**Comment by carakas** [comment]
that would be amazing

**Comment by christoph-kluge** [comment]
How does Tabbing in general work? I got a custom block which contains multiple input-elements.

```
<input1> <input2>
<input3> <input4>
```

1. As soon as I tab in any of the fields. I get the toolboxed opened. 
2. As soon as I hit "backspace" and the previous input's are empty it's jumping to the above block

Is there any description/faq which describes how I can prevent this behavior?

**Comment by adhanji8** [comment]
I really need to keep the tab key reserved for different functionality. Can anyone point me into how I would be able to override this?

**Comment by Simon-Renault** [comment]
+1 I was searching how to change the toolbar trigger key, would love to have it pop when tou type "/" in the editor.

**Comment by vmc08** [comment]
Any updates on this one? Would like to use "/" instead of Tab key for some reasons.

**Comment by christoph-kluge** [comment]
According to my comment above I've updated the functionality for my usecase (https://github.com/christoph-kluge/editor.js/commit/405cd85b68736041c6a8c412555a142059587c4d)

* Add `CTRL + 7` as Toolbar toggle
* Remove `TAB` as Toolbar toggle
* `TAB` + `SHIFT + TAB` does jump forward and backword between block input's and blocks (when no toolbar is open)
* `TAB` + `SHIFT + TAB` does jump forward and backword between items inside toolbars (inline, toolbar, toolbar - as soon as it's open)

To me this still feels pretty natural.

**Comment by bencohendev** [comment]
+1 on this. Would really love to be able to change the default toggle, especially to "/" instead of Tab

**Comment by joakimnordlund** [comment]
+1 on this.

**Comment by christoph-kluge** [comment]
Just because this thread got bumped. 

Related to my previous message above. If someone needs a workaround for `<input/>`, `<textarea/>` and `<select/>`. Then you could simply stop propagation on those elements. This one keeps tabbing to the next input and stops opening the toolbar.

```
const inputElement = this.formBuilder.make('input').

// avoid TAB key to bubble up into editorjs default behavior
el.onkeydown = function (event) {
    if (event.key === "Tab") {
        event.stopPropagation()
    }
}
```

**Comment by sarashino** [comment]
+1 on this.

**Comment by shreyvijayvargiya** [comment]
@christoph-kluge How can I add new command to open toolbar like "/", exactly we have in Notion?

**Comment by martinjnilsen** [comment]
+1 Would love to use "/" as in Notion!

**Comment by saiftheboss7** [comment]
Would love it!

**Comment by thinkdj** [comment]
Please prioritize this request. Editor.js is undeniably one of the best editors available out there from a _very_ long time, a front-runner in many respects. It should not lag behind now. 
Most fluid editors out there like Notion, Microsoft Loop etc. follow the convention of bringing up the menu on "/" and it is becoming increasingly popular. 
"Tab" on the other hand is quite non-intuitive for a pop-out menu trigger, and an option to configure the trigger key is required.

**Comment by joon610** [comment]
i wanna it.... "/"

**Comment by gooooooooney** [comment]
+1

**Comment by hff399** [comment]
+1

**Comment by aacoelho** [comment]
+1

**Comment by ozergul** [comment]
Who needs to "/" shortcut, here are the workaround, include the editorjs/paragraph plugin to your codebase and modify it like that:


```js
  // new method
  onBackslash(e) {
    const isEmpty = !this.data.text.trim?.() || this._data.text === '&nbsp;'

    if (e.shiftKey && e.key === '/' && isEmpty) {
      // Actually, Editorjs has a method
      // this.api.toolbar.open()
      // But this method doesn't work

      const toolbar = document.querySelector('.ce-toolbar')
      const toolbarPlus = document.querySelector('.ce-toolbar__plus')
      const toolbarActions = document.querySelector('.ce-toolbar__actions')

      if (!toolbarPlus) {
        return
      }

      toolbarPlus.click()
      toolbarActions.classList.add('ce-toolbar__actions--opened')
      toolbar.classList.add('ce-toolbar--opened')

      e.preventDefault()
    }
  }
  // end new method

  /**
   * Create Tool's view
   * @return {HTMLElement}
   * @private
   */
  drawView() {
    const div = document.createElement('DIV')

    div.classList.add(this._CSS.wrapper, this._CSS.block, this._CSS.alignment[this.data.alignment])
    div.contentEditable = !this.readOnly
    div.dataset.placeholder = this.api.i18n.t(this._placeholder)
    div.innerHTML = this.data.text
    div.dir = 'auto'

    div.addEventListener('keyup', this.onKeyUp)
    div.addEventListener('keydown', this.onBackslash) // <---------- added this lime

    return div
  }
```

**Comment by neSpecc** [comment]
I'm working on it. Join our [Telegram channel](https://t.me/codex_editor) to be informed when the Release Candidate will be ready for testing. My estimate is this month.
