### ISSUE TITLE
TypeScript definitions for existing plugins?

### ISSUE THREAD

**Issue by toddATavail** [codex-team/editor.js#935]
I have been trying (and failing) to create TypeScript definition (.t.ds) files for the core EditorJs plugins (Embed, Table, List, CheckList, Paragraph, etc.). It appears that these are available neither at DefinitelyTyped nor here.

* Has anyone had any luck doing this manually?
  * If so, could someone share the results of this work with me?
* If this is considered unnecessary for some reason, then perhaps someone could point me toward the correct way of using these plugins from TypeScript?
* If it matters, I am also using React.

I have been away from TypeScript for a few years, so my apologies in advance if these questions have obvious (but not to me!) answers. Thanks in advance.

**Comment by toddATavail** [comment]
Has anyone investigated this yet? I have been working on something else while still hoping for an answer, but I need to get back to this task soon. Thanks in advance for any help you can provide!

**Comment by toddATavail** [comment]
Okay, I finally figured out a solution that will work for me. I can post if anyone is interested.

**Comment by bbugh** [comment]
@toddATavail Usually if you figure out a solution, someone will need it and it's worth just posting. 🤪 What did you come up with?

**Comment by BluebambooSRL** [comment]
Nice @toddATavail, could you share the solution pls?. Thanks in advance, Federico

**Comment by toddATavail** [comment]
I'm sorry, but I'm extremely sick right now, and have been for about a week. I'll try to clean up my work and share it once I am feeling better and unburied from my usual job. I'm afraid that this isn't a priority for me, but I will keep it on my to-do list and get to it when I can. Thanks.

**Comment by VanishMax** [comment]
@toddATavail did get well after the illness? What about posting the typings?

**Comment by cjmling** [comment]
Not an ideal solution but if you just want things to start working.

https://stackoverflow.com/a/50516783/507203

**Comment by viczem** [comment]
React applications started by Create React App with TypeScript has the file `src/react-app-env.d.ts`. This file references TypeScript types declarations that are specific to the project.

To avoid  errors `TS7016: Could not find a declaration file ...` at import of any `@editorjs/pluginName` add custom declarations to the `src/react-app-env.d.ts`.

**Example:**
```ts
declare module "@editorjs/header" {
  import Header from "@editorjs/header";
  export = Header;
}

declare module "@editorjs/list" {
  import List from "@editorjs/list";
  export = List;
}

declare module "@editorjs/table" {
  import Table from "@editorjs/table";
  export = Table;
}
```

This is not a universal solution, but maybe help in finding an answer in another case.

**Comment by berkaygurbuz** [comment]
> React applications started by Create React App with TypeScript has the file `src/react-app-env.d.ts`. This file references TypeScript types declarations that are specific to the project.
> 
> To avoid errors `TS7016: Could not find a declaration file ...` at import of any `@editorjs/pluginName` add custom declarations to the `src/react-app-env.d.ts`.
> 
> **Example:**
> 
> ```ts
> declare module "@editorjs/header" {
>   import Header from "@editorjs/header";
>   export = Header;
> }
> 
> declare module "@editorjs/list" {
>   import List from "@editorjs/list";
>   export = List;
> }
> 
> declare module "@editorjs/table" {
>   import Table from "@editorjs/table";
>   export = Table;
> }
> ```
> 
> This is not a universal solution, but maybe help in finding an answer in another case.

It works for me. Thank you

**Comment by Chukwuamaka** [comment]
> React applications started by Create React App with TypeScript has the file `src/react-app-env.d.ts`. This file references TypeScript types declarations that are specific to the project.
> 
> To avoid errors `TS7016: Could not find a declaration file ...` at import of any `@editorjs/pluginName` add custom declarations to the `src/react-app-env.d.ts`.
> 
> **Example:**
> 
> ```ts
> declare module "@editorjs/header" {
>   import Header from "@editorjs/header";
>   export = Header;
> }
> 
> declare module "@editorjs/list" {
>   import List from "@editorjs/list";
>   export = List;
> }
> 
> declare module "@editorjs/table" {
>   import Table from "@editorjs/table";
>   export = Table;
> }
> ```
> 
> This is not a universal solution, but maybe help in finding an answer in another case.

For Next.js applications, you can create a typescript declaration file, e.g. editorjs.d.ts, add the custom declarations in it, and then reference the file in the [include](https://www.typescriptlang.org/tsconfig#include) array in your tsconfig.json.

**Comment by isaacGeorge** [comment]
@toddATavail did figure out a way?
