### ISSUE TITLE
Use image from previous uploads

### ISSUE THREAD

**Issue by LutonDatta** [codex-team/editor.js#937]
EditorJS has two plugin which allows to use images to the editor. But is there any way to use previously uploaded image to the editor? For example if anyone create 5 posts and want to use one image to all of these posts then currently he has to upload same image 5 times. It makes duplicate of same file in the server. So using previously uploaded images is a best option. Is there any way?

**Comment by neSpecc** [comment]
It looks like an issue for [Image Tool](http://github.com/editor-js/image). The editor's core does not know anything about what Tools are doing inside.
