### ISSUE TITLE
Printing Document

### ISSUE THREAD

**Issue by FGCorp** [codex-team/editor.js#940]
how can i print to document i create.i look documentation but i cant see noting about print.thx all good work by the way.

**Comment by mmiszy** [comment]
Press cmd+p (on MacOS) or ctrl+p (on other systems) and you can print any webpage.

**Comment by neSpecc** [comment]
The editorjs is a module of the visual editing of a document. I think you talk about some kind of application for creating documents using editor.js. It is not related to the editor itself, but to the application. 

You need to find such an application or create your own. Or wait till we present our product (we have one in early beta)

**Comment by Aarbel** [comment]
@neSpecc do you have more infos about this external printing tool ?

**Comment by staminna** [comment]
I need this too but with a step ahead. 
1. Ability to save templates and read them back

**Comment by elvisgn** [comment]
> The editorjs is a module of the visual editing of a document. I think you talk about some kind of application for creating documents using editor.js. It is not related to the editor itself, but to the application.
> 
> You need to find such an application or create your own. Or wait till we present our product (we have one in early beta)

Hi, is this available now? Couldn't find a reference in docs.
