### ISSUE TITLE
Не отображается html при выводе если текст копировать с другого сайта

### ISSUE THREAD

**Issue by deefactodev** [codex-team/editor.js#941]
Заметил проблему если вставлять в редактор текст с какого либо сайта , то статья имеет пустой вид , заметил такую вещь , перед отправкой статьи json имеет такой вид 
`{"time":1573038169174,"blocks":[{"type":"paragraph","data":{"text":"В WhatsApp в скором времени появится&nbsp;функция, которая позволит пользователям выбирать, кто из их контактов может добавлять их в группы. Об этом&nbsp;<a href=\"https://thenextweb.com/apps/2019/11/06/whatsapp-now-lets-you-choose-which-contacts-can-add-you-to-groups/?utm_campaign=tweet1\" target=\"_blank\">сообщает</a>&nbsp;The Next Web."}},{"type":"image","data":{"file":{},"caption":"","withBorder":false,"stretched":false,"withBackground":false}},{"type":"paragraph","data":{"text":"Фото: WhatsApp"}},{"type":"paragraph","data":{"text":"Ранее в мессенджере&nbsp;уже&nbsp;<a href=\"https://hi-tech.mail.ru/news/WhatsApp-zapret-na-gruppovie-chati/\" target=\"_blank\">была реализована</a>&nbsp;похожая функция, но она предполагал а выбор сразу большого круга людей — либо кто угодно мог добавить пользователя в чат, либо только знакомый из списка контактов, либо никто."}}],"version":"2.15.1"}`
Где добавляются - " \ " пример - <a href=\"

А когда я публикую статью этих сплешей нет  и текст не отображается вообще 
json имеет вид 

`{"time":1573038169174,"blocks":[{"type":"paragraph","data":{"text":"В WhatsApp в скором времени появится&nbsp;функция, которая позволит пользователям выбирать, кто из их контактов может добавлять их в группы. Об этом&nbsp;<a href="https://thenextweb.com/apps/2019/11/06/whatsapp-now-lets-you-choose-which-contacts-can-add-you-to-groups/?utm_campaign=tweet1" target="_blank">сообщает</a>&nbsp;The Next Web."}},{"type":"image","data":{"file":{},"caption":"","withBorder":false,"stretched":false,"withBackground":false}},{"type":"paragraph","data":{"text":"Фото: WhatsApp"}},{"type":"paragraph","data":{"text":"Ранее в мессенджере&nbsp;уже&nbsp;<a href="https://hi-tech.mail.ru/news/WhatsApp-zapret-na-gruppovie-chati/" target="_blank">была реализована</a>&nbsp;похожая функция, но она предполагал а выбор сразу большого круга людей — либо кто угодно мог добавить пользователя в чат, либо только знакомый из списка контактов, либо никто."}}],"version":"2.15.1"}`
В чем может быть проблема , прошу помочь уже голову сломал ((

**Comment by deefactodev** [comment]
может дело в моей функции? 
`
function Create_Post($registration_data = array()) {
    global $sqlConnect, $wo;
    if ($wo['loggedin'] == false) {
        return false;
    }
    $fields = '`' . implode('`, `', array_keys($registration_data)) . '`';
    $data   = '\'' . implode('\', \'', $registration_data) . '\'';
    $query  = mysqli_query($sqlConnect, "INSERT INTO " . T_POSTS . " ({$fields}) VALUES ({$data})");
    if ($query) {
        return mysqli_insert_id($sqlConnect);
    }
    return false;
}`

**Comment by neSpecc** [comment]
Resolved by author
