### ISSUE TITLE
editor.save() is not a function in React functional component

### ISSUE THREAD

**Issue by ReactorboY** [codex-team/editor.js#945]
Editorjs while imported in React functional component isn't working when calling function to save data.
```
const editor = new EditorJs({
    holder:'editorjs',
    placeholder: 'Let`s write an awesome story!',
    tools: {
        header : {
            class: Header,
            inlineToolbar:true,
            shortcut:"CTRL+SHIFT+H",
            config: {
                placeholder:'Enter Your text'
            }
        }
    },
    data:{}
})

const output = document.getElementById('output')

function Save() {
    editor.save().then(data => {
        output.innerHTML = data
    })
}

export default function Editor() {
    
    return (
        <div>
            <h1>Create Your Post</h1>
            <div id="editorjs" style={{border:'1px solid #ddd', marginBottom:'1rem'}} mx={4}></div>
            <Button variant="contained" color="primary" onClick={Save()}>Save Me</Button>
            <code id="output"></code>
        </div>
    )
}
```

**Comment by mupkoo** [comment]
This React component does not look alright to me. 

- You should initialise the Editor, after rendering your component.
- `onClick={Save()}` is calling `Save` on render, not on click

**Comment by ReactorboY** [comment]
> This React component does not look alright to me.
> 
> * You should initialise the Editor, after rendering your component.
> * `onClick={Save()}` is calling `Save` on render, not on click

it is calling Save function which have saving code.

**Comment by ReactorboY** [comment]
and I also I want to contribute on this project, what should I need to do ?

**Comment by kenyxy** [comment]
I agreed with @mupkoo that  your 'const editor = new EditorJs({holder:'**editorjs**',...' is executed before '<div id="**editorjs**"...' is rendered, so not such element with the id can provide EditorJs's constructor.

**Comment by mupkoo** [comment]
> > This React component does not look alright to me.
> > 
> > * You should initialise the Editor, after rendering your component.
> > * `onClick={Save()}` is calling `Save` on render, not on click
> 
> it is calling Save function which have saving code.

`onClick={Save}` will call `Save` on click, but `onClick={Save()}` is going to call `Save` on render and nothing on on click as `Save` is not returning anything

**Comment by e4coder** [comment]
Something like this should work
```js
export default () => {
  let editor = null;
  React.useEffect(() => {
    editor = new EditorJS()
    return () => {
        // editor.destroy();
    }
  }, [])
  return (
    <div id=editorjs>
    </div>
  )
}
```

**Comment by berkaygurbuz** [comment]
How can you solve this issue ? @ReactorboY
