### ISSUE TITLE
(Firefox) Contenteditable styles

### ISSUE THREAD

**Issue by ralphschindler** [codex-team/editor.js#947]
When loading the editorjs.io homepage in Firefox, it demonstrates issues with lining up the contenteditable [content] with the surrounding div border:

![2019-11-12-15-24-18](https://user-images.githubusercontent.com/76674/68712173-c3e84580-0560-11ea-9810-68d5fa778395.png)

Can you document/export a style that can be used inside tools (as part of the api) to fix this?

Thanks!

**Comment by neSpecc** [comment]
Resolved in 2.16.1
