### ISSUE TITLE
Image plugin

### ISSUE THREAD

**Issue by mrbaobao** [codex-team/editor.js#949]
The feature for Image plugin: Replace the old image uploaded by new one.
_Currently, we cannot replace the image uploaded by new one. We just hack by Removing the old and Upload a new_

**Comment by gohabereg** [comment]
Related to [editor-js/image](https://github.com/editor-js/image)

**Comment by neSpecc** [comment]
@mrbaobao you better to create this issue in the [Image Tool](http://github.com/editor-js/image) repo
