### ISSUE TITLE
With only one word in the editor, select this word raises an exception

### ISSUE THREAD

**Issue by PhilippePerret** [codex-team/editor.js#950]
To reproduce the error:

* initiate an editorjs
* type a word
* select it

=> node_modules/@editorjs/editorjs/dist/editor.js:22 Uncaught TypeError: Cannot read property 'classList' of undefined
    at t.value (node_modules/@editorjs/editorjs/dist/editor.js:22)
    at t.value (node_modules/@editorjs/editorjs/dist/editor.js:22)
    at t.value (node_modules/@editorjs/editorjs/dist/editor.js:12)
    at t.value (node_modules/@editorjs/editorjs/dist/editor.js:12)
    at e.value (node_modules/@editorjs/editorjs/dist/editor.js:22)
    at e.value (node_modules/@editorjs/editorjs/dist/editor.js:22)
    at node_modules/@editorjs/editorjs/dist/editor.js:12
    at node_modules/@editorjs/editorjs/dist/editor.js:12

With NodeJS/Electron

**Comment by khaydarov** [comment]
@PhilippePerret thanks for the report. Could you provide more details? For Chrome browser it is fine

**Comment by NomNes** [comment]
@khaydarov For chrome browser it is NOT fine. And safari too.
The problem is not one word. The error occurs when you try to select ALL the text in the paragraph (triple click, mouse selection, ctrl + A)

**Comment by neSpecc** [comment]
@PhilippePerret @NomNes is the problem still reproduce in 2.16?

**Comment by NomNes** [comment]
this problem is solved, thanks. 
But there was a new one. After initializing the editor, if there are no blocks, the placeholder is not loaded. After clicking on the editor, an error occurs:
```
Uncaught TypeError: Cannot read property 'holder' of undefined
    at e.value (editor.js:12)
    at eval (editor.js:12)
    at eval (editor.js:12)
```
Then the editor works fine

**Comment by neSpecc** [comment]
@NomNes create a separate issue for that, please

**Comment by PhilippePerret** [comment]
I'm not use editor.js any more, sorry.
