### ISSUE TITLE
How to change "Add" label in toolbar?

### ISSUE THREAD

**Issue by PatrickBokhove** [codex-team/editor.js#955]
I know it is possible to change the label of inline toolbar items by giving each tool: 

`toolbox: {
 title: 'whatevertitle'
}`

But how do i change the title of the "Add" tooltip?

![image](https://user-images.githubusercontent.com/7600895/69430422-e2ef9000-0d35-11ea-8c7f-3400c9d9e01b.png)

Kind regards

**Comment by Obzhigalov** [comment]
I have the same issue.

**Comment by lnalex** [comment]
It's hardcoded in the module:  https://github.com/codex-team/editor.js/blob/3382da100076b997946523c1587d26dff7159ea3/src/components/modules/toolbar/index.ts#L127

With the support of i18n (#751) it could be possible to change I think so.

**Comment by neSpecc** [comment]
Yes, it is related to i18n issue #751
