### ISSUE TITLE
How can I call Inline Toolbar for my custom block with text?

### ISSUE THREAD

**Issue by Obzhigalov** [codex-team/editor.js#959]
Inline toolbar appears if I select some range of text in the editorjs default paragraph block. I created custom plugin that allows user to create columns with text - https://prnt.sc/q1qze4. But if I select part of a text in my custom block - inline toolbar doesn't appear. So, how can I solve this issue?
@neSpecc

**Comment by tewang1** [comment]
same question~

**Comment by Obzhigalov** [comment]
I recorded short video about my issue. Do not pay attention to UI, I am testing my custom plugins:)
Video - https://recordit.co/in54iciTf3

**Comment by Obzhigalov** [comment]
Here is thi final DOM structure for editor from video:
![image](https://user-images.githubusercontent.com/49440033/69609545-d66f7e00-103a-11ea-9669-5ec62f2bd0ec.png)

**Comment by neSpecc** [comment]
@Obzhigalov You need to pass `inlineToolbar: true` for your tool in Editor Config. See doc: https://editorjs.io/enable-inline-toolbar

**Comment by Obzhigalov** [comment]
@neSpecc it doesn't help( I tried it before

**Comment by neSpecc** [comment]
@Obzhigalov on the screenshot you've added, there is no `contenteditable` attributes on your Tool. This is the reason, why Inline Toolbar does not appear. 

This restriction was added to prevent showing Inline Toolbar when a user selects any UI texts of the block, for example, labels, buttons, etc.

**Comment by BensenHsu** [comment]
> @Obzhigalov on the screenshot you've added, there is no `contenteditable` attributes on your Tool. This is the reason, why Inline Toolbar does not appear.
> 
> This restriction was added to prevent showing Inline Toolbar when a user selects any UI texts of the block, for example, labels, buttons, etc.

Hi @neSpecc, could you please share more about how to add `contenteditable` attributes on my customized Tool? Since I'm also experiencing the same issue.

**Comment by Parmpreet1** [comment]
You also have to replace inputs to div and then you have to set contenteditable=true, Example 
1. inlineToolbar must true in custom tool.
2.`<div contenteditable=true> test text test text test text</div>`
then inlineToolbar work fine in your custom block.
It's contenteditable not work with inputs or textarea. only work with div
