### ISSUE TITLE
default text is bold. How to make it normal text by config

### ISSUE THREAD

**Issue by deepaksisodiya** [codex-team/editor.js#960]
I have created an editor sandbox for testing. Here is the link https://deepaksisodiya.github.io/editor.js/

By default Its text is bold.
<img width="628" alt="Screenshot 2019-11-25 at 6 05 57 PM" src="https://user-images.githubusercontent.com/3258231/69541055-4257d500-0fae-11ea-85c5-959b3531043f.png">

Is there any configuration for making it normal?

**Comment by gohabereg** [comment]
Hi @deepaksisodiya 
Your example works ok for me

**Comment by neSpecc** [comment]
@deepaksisodiya can't reproduce the problem. Is it still actual?

**Comment by deepaksisodiya** [comment]
@gohabereg @neSpecc Sorry for it. It is working fine on sandbox. My bad, I put the code inside h4 tag thats why it is happening. closing this issue now
