### ISSUE TITLE
rewrite/disable build-in Inline Tools

### ISSUE THREAD

**Issue by kenyxy** [codex-team/editor.js#977]
we know There are three build-in Inline Tools: link, bold, italic. I want to rewrite them as I prefer to use style instead of tag <b>, <i>. 
is there any way to rewrite them or disable them so that I can write my own?

**Comment by neSpecc** [comment]
You can specify Inline Toolbar tools via Editor Config. See a [guide](https://editorjs.io/enable-inline-toolbar#configure-tools-at-inline-toolbar). So you need to connect your own tools via `tools` property and pass them to each Block Tool via the `inlineToolbar` option.

**Comment by kenyxy** [comment]
Thank you very much, Peter! it DOES help to customize which inline tool to be used. 
how about the default/built-in paragraph block? I know I can use "initialBlock" to write my own paragraph block, but the default/built-in paragraph block just works perfect. Can I customize the paragraph block with a class name just like other tools?

**Comment by neSpecc** [comment]
@kenyxy you can specify `inlineToolbar` option for paragraph tool as well:

```js
new EditorJS({
  // other options 

  tools: {
    paragraph: {
      inlineToolbar: ['link']
    },

    // other tools
  }
})
```

**Comment by kenyxy** [comment]
Fantastic! I thought I have to provide a class for it too.

**Comment by tom-yam** [comment]
@neSpecc 
I would like to change the title of build-in inline toolbar. (The reason is that I would like to localize it to Japanese.)
Is there any support for this?
<img width="271" alt="スクリーンショット 2019-12-13 13 50 55" src="https://user-images.githubusercontent.com/49545818/70770185-c59b6800-1daf-11ea-87cc-cb6a9ccdfe30.png">

**Comment by neSpecc** [comment]
@tom-yam for now, the title is hardcoded inside build-in Link tool: https://github.com/codex-team/editor.js/blob/master/src/components/inline-tools/inline-tool-link.ts#L27

We can add an ability to override it with Editor Config. Can you open a separated issue for that?

**Comment by tom-yam** [comment]
OK. 
Created new issue.

**Comment by BensenHsu** [comment]
> Fantastic! I thought I have to provide a class for it too.

Hi @kenyxy , could you please share how you customize/rewrite the style of the inline tool? Much appreciated!
