### ISSUE TITLE
update v.2.16.0 error

### ISSUE THREAD

**Issue by trbear** [codex-team/editor.js#978]
ERROR in node_modules/@editorjs/editorjs/types/api/tooltip.d.ts:4:46 - error TS2307: Cannot find module '../../src/components/external/codex.tooltips'.

4 import {TooltipContent, TooltipOptions} from '../../src/components/external/codex.tooltips';

**Comment by neSpecc** [comment]
You need to init and update submodules.

```
git submodule update --init --recursive
```

**Comment by trbear** [comment]
i'm install package from npm

**Comment by mhfhyh** [comment]
same problem here (installed from npm)

**Comment by neSpecc** [comment]
will be fixed in the upcoming patch

**Comment by natterstefan** [comment]
Thank you @neSpecc!

**Comment by neSpecc** [comment]
Resolved in 2.16.1
