### ISSUE TITLE
Cannot find module '../../src/components/external/codex.tooltips'. in types/tooltip.d.ts

### ISSUE THREAD

**Issue by phamconganh** [codex-team/editor.js#983]
i install latest version Release 2.16 - 3 days ago of editor js then it errors

**Comment by natterstefan** [comment]
Hi @phamconganh, this is a duplicate of https://github.com/codex-team/editor.js/issues/978. Can you close it, please? Thank you.

**Comment by phamconganh** [comment]
Thanks for reply
