### ISSUE TITLE
Unable to hide conversion toolbar item via config

### ISSUE THREAD

**Issue by mpandzo** [codex-team/editor.js#984]
With the introduction of the conversion toolbar action in 2.16.0 no option is provided in config to disable this feature for those of us that do not intend to use it. This is especially important when no addons are used which results in the following display:

![empty](https://user-images.githubusercontent.com/7498710/70246252-ba28bb00-1777-11ea-8b82-9353cc09bd9d.png)

**Comment by neSpecc** [comment]
Resolved in 2.16.1

**Comment by mikekoro** [comment]
> Resolved in 2.16.1

How do you actually disable it? I cant seem to find anything in the docs.
