### ISSUE TITLE
Empty block not being added to blocks[]

### ISSUE THREAD

**Issue by cossssmin** [codex-team/editor.js#985]
When you hit Enter, a new and empty paragraph block is added on page. However, this does not get added to the `blocks[]` array.

The problem with this is that the `getCurrentBlockIndex()` API method queries elements from the DOM, so it's now de-synced from the actual data - you can't use it as a source of truth anymore. In a Vue.js context, where data is your source of truth, this is problematic.

In my case, this happens:

1. I have a paragraph block on page - this would be at index 0 if queried for
2. hit Enter, new paragraph block created on page, at index 1 (but not in data)
3. insert a new block at the end with the API (triggered with click on a button). This block is at index 2 when queried for, but at index 1 in my `blocks[]` data, because nothing was added at step 2...

Any ideas on how to overcome this?

**Comment by gohabereg** [comment]
Hi @cossssmin ,

Empty blocks are not added to saved data because of validation provided by Tools. Default Editor.js paragraph doesn't validate empty strings. You can fork it, change `validate` method, and provide at tools object of configuration.

**Comment by neSpecc** [comment]
Related to #873

**Comment by cossssmin** [comment]
Thanks @gohabereg, but I don’t want to have to maintain a fork - all I’d want is for the `getCurrentBlockIndex()` to work reliably :)

**Comment by neSpecc** [comment]
@cossssmin `getCurrentBlockIndex()` is not designed for identifying the block in saved data, just in Editor UI.

**Comment by cossssmin** [comment]
Yes, that's why I was saying that it's not synced and there isn't a single source of truth. You have something in the data, and the only API method that gets you a block's index shows something else.

If I use the data as a source of truth, I can't reliably get a particular block on page. If I use the API method, same thing. #873 indeed asks for basically the same thing, and I think a UUID like in #727 would be great.

Closing this as duplicate, looking forward to metadata 👍

**Comment by ngmiduc** [comment]
> Hi @cossssmin ,
> 
> Empty blocks are not added to saved data because of validation provided by Tools. Default Editor.js paragraph doesn't validate empty strings. You can fork it, change `validate` method, and provide at tools object of configuration.

Thanks for the solution.
If someone wants to a React Overwrite. I paste it here, if maybe someone looks for that.

```
const NewParagraphTool = (function (original) {
  function Paragraph() {
    original.apply(this, arguments) 
    this.validate = function (savedData) {
      // if (savedData.text.trim() === "" && !this._preserveBlank) {
      //   return false
      // }

      return true
    }
  }
  Paragraph.prototype = original.prototype 
  Paragraph.prototype.constructor = Paragraph 
  return Paragraph
})(Paragraph)
```

**Comment by imransilvake** [comment]
is there an official fix for that? still happening on the current Editor.js version

**Comment by julianplop** [comment]
> is there an official fix for that? still happening on the current Editor.js version

Looking for this too.

**Comment by draobrehtom** [comment]
> > is there an official fix for that? still happening on the current Editor.js version
> 
> Looking for this too.

Same here.

**Comment by imransilvake** [comment]
the solution is to install https://github.com/editor-js/paragraph and use `preserveBlank: true`

<img width="888" alt="Screenshot 2023-01-25 at 14 59 36" src="https://user-images.githubusercontent.com/13087225/214582970-45e522b1-5f37-4490-a7c3-be0a5cfead41.png">

**Comment by julianplop** [comment]
> the solution is to install https://github.com/editor-js/paragraph and use `preserveBlank: true`
> 
> <img alt="Screenshot 2023-01-25 at 14 59 36" width="888" src="https://user-images.githubusercontent.com/13087225/214582970-45e522b1-5f37-4490-a7c3-be0a5cfead41.png">

Did someone implement it successfully? I couldn't. 


``editorMain = new EditorJS({
            holder: loader_id,
            initialBlock: "paragraph",
            defaultBlock:"paragraph",
            readOnly: readMode,
            minHeight : 30,
            tools: {
              paragraph: {
                class: Paragraph,
                inlineToolbar: true,
                preserveBlank: true,
              },
              image: SimpleImage,
              underline: Underline,
              embed: Embed,
              delimiter: Delimiter,
              
              header: {
                class: Header,
                config: {
                  placeholder: "Enter a header",
                  levels: [2, 3],
                  defaultLevel: 3,
                },
              },
              Marker: {
                class: Marker,
                shortcut: 'CMD+SHIFT+M',
              },
              list: {
                class: List,
                inlineToolbar: true,
                config: {
                  defaultStyle: 'unordered'
                }
              },
              checklist: {
                class: Checklist,
                inlineToolbar: true,
              },
              

      
            }
      
        });v

**Comment by yixiann** [comment]
@imransilvake hello! Thank you for your solution! Do you know if there is a similar fix for headers? I cannot seem to find the configuration parameter "preserveBlank" for the headers. 😄
