### ISSUE TITLE
Overwrite inline toolbar title

### ISSUE THREAD

**Issue by tom-yam** [codex-team/editor.js#996]
I would like to change the title of build-in inline toolbar. (The reason is that I would like to localize it to Japanese.)
For now, it is hardcoded inside here. So I hope that we can overwrite title from editor config.
https://github.com/codex-team/editor.js/blob/master/src/components/inline-tools/inline-tool-link.ts#L27

<img width="271" alt="スクリーンショット 2019-12-13 13 50 55" src="https://user-images.githubusercontent.com/49545818/70770185-c59b6800-1daf-11ea-87cc-cb6a9ccdfe30.png">

_Originally posted by @tom-yam in https://github.com/codex-team/editor.js/issues/977#issuecomment-565299729_

**Comment by Farrien** [comment]
+

**Comment by stmegabit** [comment]
+

**Comment by 61Q** [comment]
#### 1. download editorjs/link
https://github.com/editor-js/link    

#### 2. change the file in src/index.js
```static get toolbox() {
    return {
      icon: ToolboxIcon,
      title: 'Link'
    };
  }
```
#### 3. import the edited editor-js/link file from your local directory
3.

**Comment by glauberm** [comment]
Here's how I'm doing it:

```[js]
import BaseParagraph from '@editorjs/paragraph';

export default class Paragraph extends BaseParagraph {
  static get toolbox() {
    return {
      title: 'Texto',
      icon: BaseParagraph.toolbox.icon,
    };
  }
}
```

**Comment by glauberm** [comment]
Now this one I have no idea how to override successfully: https://github.com/codex-team/editor.js/blob/be6f9b78f265c3d553c799c99e59c9916bf29e17/src/components/modules/toolbar/index.ts#L133

**Comment by neSpecc** [comment]
You can use i18n API for that reason:

```js

new EditorJS({
  // ... your config
  i18n: {
    messages: {
      toolNames: {
        Link: 'Custom Title'
      }
    }
  }
})
```
