### ISSUE TITLE
Saving results of inline tool

### ISSUE THREAD

**Issue by VanOvermeire** [codex-team/editor.js#998]
Hi,

I've just written an inline tool for marking text in red, largely based of your example (marker) inline tool.

Works fine, but I am unable to correctly save and reload the result. Sanitize makes sure my <span> with custom class is not erased, but the color that I add as `style` to the span **does** disappear. So after loading text, I am left with a span that does not do anything useful.

This is not an issue with the bold, italic or marker plugins, because those tags themselves already contain all the information you need...

Am I missing an obvious solution, or is this just not possible (yet) for span/div/etc.?

Thanks!

**Comment by gohabereg** [comment]
Hi @VanOvermeire 
Sanitize configuration may contains element attributes:
```
static get sanitize() {
  return {
    style: true,
  };
}
```

**Comment by VanOvermeire** [comment]
Ok, thanks!
